### ISSUE TITLE
more than one thermostat

### ISSUE THREAD

**Issue by davidsean** [espressomd/espresso#1000]
Issuing
`thermostat LD 1.0 1.0`
followed by
`thermostat LB 1.0`
will initialize a system with two thermostats.

Although one can use `thermostat off`to turn off the Langevin thermostat before activating the Lattice-Boltzmann thermostat, the expected behavior should be that the latest call to `thermostat` overrides any previous calls.

Although this cannot be changed for legacy reasons, there could be a warning message displayed when this happens. The documentation could contain a few warnings reminding the user to turn off existing thermostats (for example in the LB section).

If the python interface behaves differently (as I think it does) than an additional warning should be noted in the documentation.

**Comment by hmenke** [comment]
Fixed in #1001.  Why wasn’t this closed already?
