### ISSUE TITLE
create_polymer ignores constraints

### ISSUE THREAD

**Issue by davidsean** [espressomd/espresso#1020]
`polymer.create_polymer(...., constraints=1)` does not seem to avoid constraints.

The behavior is the same whether I include `type_poly_neutral=0, type_poly_charged=0` or not (in this case constraint has type 0).

I add this, because when i do not specify `type_poly_neutral=0` the particles are of type 1 and it could make sense that it ignores the constraint types that it does not interact with.

**Comment by fweik** [comment]
I took a quick look and it was not obvious to me why this does not work. The code is independent of the interactions (which might in itself be a defect), so this is not an issue with the types.
It checks whether the new monomer is on the same side of the constraint (as determined by the sign of the distance), or not.

**Comment by pkreissl** [comment]
@davidsean could you please provide a minimal example script?
I just adapted the `samples/visualization_constraints.py`, namely
 * ~removed~ replaced particle creation by `polymer.create_polymer(..., bond_length=2.0)` with a fene potential
 * removed the LJ[0,1] non-bonded interaction
 * set LJ[0, 0] to be a WCA potential with  `epsilon=1.0` and `sigma=2.0`

I checked for all existing constraints, several polymer lengths (`MPC=...`) and number of polymers (`N_P=...`) up to insane values. Worked perfectly. Also with polymers set up on both sides of the constraint (e.g., sphere constraint with `start_pos` in it's center).
I consistently failed to see this bug, everything worked as expected.

**Comment by pkreissl** [comment]
Offline discussion: seems to work fine. @fweik issue can be closed.
