### ISSUE TITLE
Bonded IAs should not be ifdefed

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1025]
The performance impact of additional bonded IAs is very small if it exists at all, the only effect being that
the Bond_parameters union gets potentially bigger. This is not worth the complexity.

**Comment by jngrad** [comment]
A lot changed since this issue was opened: the `BOND_ANGLE` ifdef was removed in #2546 (7c4f284d), the `TABULATED` ifdef will be removed in #2304 and the `BOND_ANGLEDIST` code was removed in #2338.

**Comment by jngrad** [comment]
We'll be left with only the `UMBRELLA` ifdef (experimental feature) and the `ROTATION` ifdef for bonded IAs.
