### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#1032]
Espresso-3.3.1 fail on Fedora with:
```
make[4]: Entering directory '/home/junghans/rpmbuild/BUILD/espresso-3.3.1/no_mpi/src/core'
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../src/core -I../../src  -I../../../src/core/mpifake   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c -o config-features.lo ../../../src/core/config-features.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../src/core -I../../src -I../../../src/core/mpifake -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c ../../../src/core/config-features.cpp  -fPIC -DPIC -o .libs/config-features.o
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../src/core -I../../src  -I../../../src/core/mpifake   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c -o cells.lo ../../../src/core/cells.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../src/core -I../../src -I../../../src/core/mpifake -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c ../../../src/core/cells.cpp  -fPIC -DPIC -o .libs/cells.o
In file included from ../../../src/core/cells.cpp:30:0:
../../../src/core/utils.hpp:150:16: error: 'std::pmalloc' has not been declared
 #define malloc pmalloc
                ^
../../../src/core/utils.hpp:147:17: error: 'std::prealloc' has not been declared
 #define realloc prealloc
                 ^
Makefile:889: recipe for target 'cells.lo' failed
make[4]: *** [cells.lo] Error 1
```
This is fixed in the master version.  Could you guys tag a new release please?

**Comment by junghans** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1307487

**Comment by junghans** [comment]
Now failing on OpenSuse as well: https://bugzilla.opensuse.org/show_bug.cgi?id=1080642

**Comment by junghans** [comment]
I saw v4.0 is out, but where is the release tag?

**Comment by junghans** [comment]
And https://github.com/espressomd/release/raw/master/espresso-4.0.0.tar.gz has no `espresso-4.0.0` path prefix.

**Comment by KaiSzuttor** [comment]
i readded the tag, but the attached tar.gz file is not usable due to the missing submodule (h5xx).

**Comment by KaiSzuttor** [comment]
@junghans Could you please check if the recently uploaded file for the release meets your requirements?

**Comment by junghans** [comment]
@KaiSzuttor: still no `espresso-4.0.0/` path in `espresso-4.0.0.tar.gz`:
```
tar -tf /usr/portage/distfiles/espresso-4.0.0.tar.gz | head
.clang-format
.codecov.yml
.github/
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
.gitlab-ci.yml
.gitmodules
.travis.yml
AUTHORS
CMakeLists.txt
```

**Comment by KaiSzuttor** [comment]
I'm not familiar with the necessary structure... what you want to have is:
```
tar -tf /usr/portage/distfiles/espresso-4.0.0.tar.gz | head
espresso-4.0.0/.clang-format
espresso-4.0.0/.codecov.yml
espresso-4.0.0/.github/
espresso-4.0.0/.github/PULL_REQUEST_TEMPLATE.md
espresso-4.0.0/.gitignore
espresso-4.0.0/.gitlab-ci.yml
espresso-4.0.0/.gitmodules
espresso-4.0.0/.travis.yml
espresso-4.0.0/AUTHORS
espresso-4.0.0/CMakeLists.txt
``` 
?

**Comment by junghans** [comment]
@KaiSzuttor, that is pretty much the standard for release tarballs!

**Comment by mkuron** [comment]
Back in the Tcl days, there was a script that created our release tarballs. And since @junghans was happy with those, I assume they had a root directory. That script also ran autoconf and automake so the user didn’t need them installed on his machine. I guess we could run cython before creating the tarball so the user doesn’t need it installed.

**Comment by junghans** [comment]
Yes, autotools has `make dist`.

**Comment by junghans** [comment]
Just have a look at the older espresso tarballs to check for the structure.

**Comment by hmenke** [comment]
Why don't you just use `git archive` to generate the tarball?
```bash
git archive --prefix=espresso-4.0.0/ -o /tmp/espresso-bare.tar 4.0.0
git submodule foreach --recursive 'git archive --prefix=espresso-4.0.0/$path/ -o /tmp/espresso-$sha1.tar HEAD'
for archive in /tmp/espresso-*.tar; do
    tar --concatenate -f espresso-4.0.0.tar $archive
done
gzip espresso-4.0.0.tar
```

**Comment by KaiSzuttor** [comment]
the answer is simple: i was not aware of the prefix that is needed

**Comment by KaiSzuttor** [comment]
it's now updated for the tag

**Comment by junghans** [comment]
prefix is correct now, but no `h5xx`?

**Comment by KaiSzuttor** [comment]
fixed

**Comment by junghans** [comment]
I uploaded the tarball to the Gentoo mirror, so please from now on no tarball replacements anymore.

https://github.com/gentoo/gentoo/commit/87ad744e3f351ce03906019a1025fa52454125af

**Comment by junghans** [comment]
And OpenSuse: https://build.opensuse.org/request/show/634398

**Comment by mkuron** [comment]
> OpenSuse

In case you didn't know, Espresso cannot be built with HDF5 support on OpenSUSE 15. The Boost.MPI and HDF5 packages in that release were built against different OpenMPI versions.

**Comment by junghans** [comment]
And Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1625379

**Comment by junghans** [comment]
@mkuron, I think they fixed that in OpenSuse Factory.

**Comment by mkuron** [comment]
I'm not sure about that. Looking at https://build.opensuse.org/public/build/home:cjunghans:branches:devel:languages:python/openSUSE_Tumbleweed/x86_64/python-espressomd/_log, I can see that it installed both openmpi and openmpi2, just like it did on my tests on 15.0 a few weeks ago. While that may build, all tests will fail. Your 42.3 build failed due to some RPM spec syntax issue and The 15.0 build is blocked, whatever that means.

**Comment by junghans** [comment]
@mkuron, so let's disable hdf5 for now and the other issue goes away if make it python3-only.

https://build.opensuse.org/request/show/634468
