### ISSUE TITLE
Decide faith of immersed boundary method

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1038]
This seems very similar to object-in-fluid but contains a lot of code duplication. I tend to remove it. Any objections?

**Comment by fweik** [comment]
Also it lacks tests and docs.

**Comment by rbardak** [comment]
Dito, everything that lacks tests and docs dies. However, I would ask the mailing list and check whether or not someone is using this feature and if they are willing to write some docs/tests.

**Comment by hmenke** [comment]
I'm very much in favour of removing stray features.  Please do this.
