### ISSUE TITLE
Using set_random_state_PRNG leads to stucked script.

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1046]
After using the system.set_random_state_PRNG(), adding an LB fluid does not work.
[lbf.py.zip](https://github.com/espressomd/espresso/files/798676/lbf.py.zip)

 method adding

**Comment by davidsean** [comment]
Seems to only affect the GPU implementation of LBF

**Comment by KaiSzuttor** [comment]
You may be right, I haven't checked, but most people using LB are actually using the GPU implementation.

**Comment by davidsean** [comment]
Yes, of course. I was hoping my observation could help highlight the cause---which seems to be related strictly to the GPU implementation.

**Comment by davidsean** [comment]
Two things worth noting:

1. The problem may be related to an integer overflow. In `set_random_state_PRNG()` changing the line
`states_on_node_i.append(rng.randint(0, sys.maxint))
`
to
`states_on_node_i.append(rng.randint(0, 2**31-1))
`
seems to fix it for me. Perhaps sys.maxint is too big for whatever occurs later in the core.

2. On a perhaps related note (or different bug?), manually setting the states
```
myState = system.set_random_number_generator_state
system.set_random_number_generator_state = myState
``` 
ends up using `mpi_random_set_stat(state)` where `state` is actually smaller than what is sent if called via `set_random_state_PRNG()`. In my test example, the length of the string of numbers sent to  
 `mpi_random_set_stat()` is `625` when used manually, and `626` when used with `set_random_state_PRNG()`. I am not sure which one is correct.

**Comment by davidsean** [comment]
Yet another possibly related issue (or different bug?).

The value the last integer when `system.random_number_generator_state` is called is always the same after being seeded by an arbitrary single value `system.seed=...`
