### ISSUE TITLE
Rare segmentation fault with P3M.

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1057]
In very rare situations (in this case after 2e8 integration loops), I get a segfault.
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: 0xfffffffc032ea7d0
[ 0] /lib64/libpthread.so.0[0x397b40f7e0]
[ 1] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z20p3m_do_assign_chargeILi3EEvdPdi+0x38c)[0x7f63878ceb4c]
[ 2] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z17p3m_charge_assignv+0x1bd)[0x7f63878cdb4d]
[ 3] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z22calc_long_range_forcesv+0x45)[0x7f63879325a5]
[ 4] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z10force_calcv+0xcd)[0x7f6387932c4d]
[ 5] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z12integrate_vvii+0x121)[0x7f638792ce11]
[ 6] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z13mpi_integrateii+0x92)[0x7f63878bc232]
[ 7] /home/kai/git/espresso/build/src/core/libEspressoCore.so.4(_Z16python_integrateibb+0x1b5)[0x7f638792d165]
[ 8] /home/kai/git/espresso/build/src/python/espressomd/integrate.so(+0x56af)[0x7f63679996af]
[ 9] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x88e5)[0x7f63c3d2de15]
[10] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7f63c3d2ea2e]
[11] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7f63c3d2eb42]
[12] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(PyRun_FileExFlags+0xb0)[0x7f63c3d4f050]
[13] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xef)[0x7f63c3d4f22f]
[14] /share/apps/python/2.7.11/bin/../lib/libpython2.7.so.1.0(Py_Main+0xca4)[0x7f63c3d64b74]
[15] /lib64/libc.so.6(__libc_start_main+0xfd)[0x397ac1ed1d]
[16] /share/apps/python/2.7.11/bin/python[0x400649]
*** End of error message ***

**Comment by hmenke** [comment]
Can you provide a stack trace?

**Comment by KaiSzuttor** [comment]
I havent performed 2e8 integrations withe the debugger, sorry.

On 6 Mar 2017, at 16:01, Henri Menke <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you provide a stack trace?

**Comment by fweik** [comment]
Typically this happens when particles are out of the box. The p3m assumes that all particles have valid coordinates, and fails if they are not. Could you rerun with ADDITIONAL_CHECKS, iirc this should catch
this.
