### ISSUE TITLE
Collision detection possibly wrong

### ISSUE THREAD

**Issue by hirschsn** [espressomd/espresso#1077]
The three particle bonding code for cellsystem domain_decomposition in collision.cpp (function three_particle_binding_domain_decomposition) in the inner-most loop looks as follows:
```
if (P->l.ghost) {
  continue;
}
coldet_do_three_particle_bond(P, p1, p2);

if (p1->l.ghost) {
  continue;
}
coldet_do_three_particle_bond(p1, P, p2);

if (p2->l.ghost) {
  continue;
}
coldet_do_three_particle_bond(p2, P, p1);
```
While the first `continue` might make sense, the second and third seem wrong since the formed bonds depend on the ordering of the particles. This code should be reviewed.

**Comment by hirschsn** [comment]
I guess, this might be what was intended:
```
if (!P->l.ghost) {
  coldet_do_three_particle_bond(P, p1, p2);
}

if (!p1->l.ghost) {
  coldet_do_three_particle_bond(p1, P, p2);
}

if (!p2->l.ghost) {
  coldet_do_three_particle_bond(p2, P, p1);
}
```

**Comment by RudolfWeeber** [comment]
The parallelizaiotn probably never was correct (aa2ae). 
Concerning your suggested changes, I think, they are correct. However,, one needs to make sure that the three particle search actually runs on all nodes. Whether that is the case, is not immediately obvious to me.
The collision-angular.tcl testcase only prints out stuff but never fails.
Also, to test a parallel version, the particles wwould have to be placed such that members of a triangle actually land on different nodes

(@Smiljanic)

**Comment by hirschsn** [comment]
Actually, the checks for p1 and p2 might be superfluous because in the very same function it is ensured that `(local_particles[gathered_queue[id].pp1] != NULL) && (local_particles[gathered_queue[id].pp2] != NULL)`. So the question is really: should p1 and p2 be bonded if P is ghost or not.

**Comment by RudolfWeeber** [comment]
Confirmed by the test in testsuite/python/collision_detection.py in 
http://github.com/RudolfWeeber/espresso, py_collision_detection branch.
The test for three particle binding passes on one core and fails for higher numbers of core due to missing bonds.
