### ISSUE TITLE
Publish Sphinx Documentation on Github?

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1078]
What do you think about putting the sphinx Documentation on github?

Technically this is possible, see e.g.:
https://stackoverflow.com/questions/1553800/how-to-upload-html-documentation-generated-from-sphinx-to-github/1622472#1622472

**Comment by hmenke** [comment]
I think this is a good idea.  Actually, I have done this before for Doxygen documentation.

The script to make and publish the docs is here: [`publish_doxygen.sh`](https://github.com/pairinteraction/pairinteraction/blob/master/doc/doxygen/publish_doxygen.sh)

The output can be viewed here: https://pairinteraction.github.io/pairinteraction/

**Comment by helvrud** [comment]
Yes, please, upload it. Let's make it Google searchable!

**Comment by hmenke** [comment]
I now have a tentative version here: https://hmenke.github.io/espresso/

Please tell me if this is what you are after and I will merge it into ESPResSo with permission of the other maintainers.  (I want to merge this myself)

@fweik @rempferg I need access to the [espressomd organization](https://hub.docker.com/r/espressomd/) on DockerHub for this  (My username there is hmenke).

**Comment by mkuron** [comment]
So why do we want to do this? The more sensible place would be www.espressomd.org together with the old-but-still-necessary user's guide. I think we may be spreading our stuff across too many places (we've also got the wiki, the developer guide, the tutorials, ...).

**Comment by hmenke** [comment]
This one is integrated with Travis.

**Comment by jonaslandsgesell** [comment]
Automation is a big point. Also because in the past the userguide pdf was not accessible through the espressomd page. There was constantly some manual work to do in order to be able to view it in the browser. 

I think it is much better to have code documentation in the place where you can also find the code. Therefore I would rather drop content from http://espressomd.org and place it on github instead of doing it the other way around.
An advantage of doing it that way is that you bring people closer to source of espresso. Therefore you could get more contributors.

**Comment by hmenke** [comment]
I agree with @jonaslandsgesell.  My current solution which only builds Sphinx can be augmented to also make the User Guide PDF, the Developers Guide PDF, and Doxygen and put it all on gh-pages.

**Comment by mkuron** [comment]
I don't see how that puts it closer to the code. While it would technically be hosted on Github servers, it would still be at a different URL (http://espressomd.github.io) and there is no extra button that shows up in the top bar of the project page.

**Comment by hmenke** [comment]
Okay, I think this should be discussed in an ESPResSo dev meeting, but here is my suggestion:

* Put Sphinx on GitHub pages.
* Link it to http://espressomd.org
* As a next step put the User Guide PDF and the tutorials on GitHub pages.  (Consider Sphinx-ifying the tutorials?)
* The Developers Guide (hopelessly outdated but could be easily Sphinx-ified) and Doxygen can follow.
* Ultimately move http://espressomd.org to http://espressomd.github.io/
* Get rid of the Wiki.  Nobody uses this.  It lists Coding Day 2015 as current topic.
    - On the [C++ page](http://espressomd.org/wiki/C%2B%2B) it says »We do not use excessive templating in ESPResSo«.
    - The [Developers Guide](http://espressomd.org/wiki/Developer%27s_Guide) is full of Automake and TCL stuff (no CMake, no Python)
    - The [Python Interface page](http://espressomd.org/wiki/Python_Interface) has one pathetic example with syntax that doesn't even work anymore.
* ???
* Profit

**Comment by jonaslandsgesell** [comment]
@mkuron Of course the documentation should be prominently linked in the Readme.

As a off-topic hint: this link from espressomd.org simply does not work inside the browser. http://espressomd.org/jenkins/job/master-doc/lastSuccessfulBuild/artifact/doc/ug/ug.pdf

**Comment by mkuron** [comment]
I agree with all of these points, except for this one:
> Ultimately move http://espressomd.org to http://espressomd.github.io/

Ok, the website is terribly outdated and contains little useful content. But that isn't going to change just by moving it elsewhere.

Automation is also important to keep the documentation in sync between repository and website, but for the tutorials user guide PDF, that was dealt with by Jenkins and that worked too.

The main motivation for going to GitHub pages is if you don't have a domain and web server, but we have both.
Besides, getting too dependent on free cloud services isn't that great of an idea because corporations change strategies sometimes. Right now we depend on GitHub, Travis-CI and Docker Hub, with the former being replaceable within minutes and the latter two being mainly used for convenience (i.e. our in-house Jenkins is still operational).

**Comment by hmenke** [comment]
My method now builds *all* documentation including User's Guide, Developer's Guide, Tutorials, Doxygen, and Sphinx and uploads them on GitHub pages.  An overview page is missing so far which is why this cannot be view from `https://hmenke.github.io/espresso/`.

https://github.com/hmenke/espresso/tree/gh-pages/

**Comment by hmenke** [comment]
Is there any progress on this?

**Comment by jonaslandsgesell** [comment]
I would like to see this merged. I like the idea

**Comment by mkuron** [comment]
The maintainers never chimed in to this discussion. Perhaps you should bring it up at tomorrow's meeting.

**Comment by RudolfWeeber** [comment]
http://espressomd.github.io/doc

**Comment by KaiSzuttor** [comment]
no, its now http://espressomd.org/html/doc/
