### ISSUE TITLE
Replace P3M log by Runtime Error Collector

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1090]
Currently the P3M writes its tuning stats to a log (which is a dynamically allocated char pointer).  This is not very elegant and can be done much better using the Runtime Error Collector.

---

I tried replacing the errors in the tuning log with `runtimeErrorMsg()` for a start.  However, the tuning loop becomes infinite then (???) and `strace` reports that ESPResSo is doing
````
open(".fftw3_1d_wisdom_back_n62.file", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=28350, ...}) = 0
read(3, "(fftw-3.3.4 fftw_wisdom #x458a31"..., 4096) = 4096
read(3, "vx 0 #x11048 #x11048 #x0 #x4b017"..., 4096) = 4096
read(3, "se2 0 #x10048 #x10048 #x0 #xd331"..., 4096) = 4096
read(3, "r 0 #x11048 #x11048 #x0 #xe2d5b5"..., 4096) = 4096
read(3, " #x0 #x57d7ce7a #x81642d8a #xc90"..., 4096) = 4096
read(3, " #x0 #xd5b45a23 #x5578823b #x32b"..., 4096) = 4096
read(3, "8 #x10048 #x0 #x64dbb4ce #x3b704"..., 4096) = 3774
read(3, "", 4096)                       = 0
close(3)
````
Where the number (here `n62`) keeps increasing.

**Comment by jngrad** [comment]
The dynamically allocated char pointer lead to a memory leak and was recently replaced by printfs (#4069). There is also a new optional `verbose` parameter to disable printing the tuning log. This can be closed.
