### ISSUE TITLE
ScriptInterfaceHelper.__getattr__ fails with Python3

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1101]
This was not noticed, because until #1100, no test case uses attribute retrieval on script objedcts without get_parmas()
The cause is that __getattr__ uses a string ("") for the attribute name,
whereas in Python3, PScriptInterface.valid_parameters() contains byte literals (b""),
probably, because that's what cython converts c++ strings into.

Test code:
import espressomd
from espressomd.shapes import Wall
w=Wall(normal=[1,2,3])
print(w.normal)

@mkuron @hmenke do you have a suggestion, how to resolve this?

**Comment by mkuron** [comment]
The byte literal should never be passed to Python. `espressomd.utils.to_str()` should be used in the interface code (right where the string is obtained by calling a a C++ function) to handle the conversion if it is needed.
