### ISSUE TITLE
checkpointing.py

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1109]
Documentation is bad/missing. Docstrings missing.

**Comment by jonaslandsgesell** [comment]
Documentation in the code is there. Documentation in io.rst is there but is not really readable.

**Comment by fweik** [comment]
@KaiSzuttor are there still urgent changes or bug fixes for the checkpointing that need to be done before the release?

**Comment by fweik** [comment]
Most of the methods seem to have docstrings now. I'd tend to close this one. Opinions? @KaiSzuttor @RudolfWeeber
