### ISSUE TITLE
script_interface.pyx

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1124]

**Comment by fweik** [comment]
The classes in this file are not used directly by the user, so I think this does not need to be checked.

**Comment by RudolfWeeber** [comment]
On Mon, Dec 04, 2017 at 04:41:21PM +0000, Florian Weik wrote:
> The classes in this file are not used directly by the user, so I think this does not need to be checked.
Developers do use it, though. One could de-milestone it, if need be.
