### ISSUE TITLE
visualizationMayavi.pyx visualizationOpenGL.pyx visualization.pyx

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1129]

**Comment by KonradBreitsprecher** [comment]
I 'll take care of that.

**Comment by RudolfWeeber** [comment]
@KonradBreitsprecher, could you adress this on the workshop, both the in code doc for the opengl visualizer and the overview doc in the user's guide?

**Comment by KaiSzuttor** [comment]
The visualization still lacks in-code documentation.

**Comment by KonradBreitsprecher** [comment]
Will do.
