### ISSUE TITLE
Implement Python support for LEES_EDWARDS

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1140]
It should also be possible to switch it on or off in the script, so we can remove the comiler switch and test it in maxset.
It would also be interesting to see, whether the resort_particle in every time step can be replaced by sth more relaxed.

**Comment by RudolfWeeber** [comment]
There is a tcl integration test @bindgens1 @rempferg

**Comment by RudolfWeeber** [comment]
@rempferg @bindgens1 Do we close this?

**Comment by bindgens1** [comment]
Python interface for LE should be working in the current Python branch. Documentation is missing. I will add the documentation within the next days and also extend the LB GPU documentation. Test cases will be provided as well.
