### ISSUE TITLE
Decide fate of MOL_CUT

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1143]
It does not have docs. What does it do?

**Comment by RudolfWeeber** [comment]
@junghans Could you comment on what this feature does?
Does it have a usecase without ADRES?

**Comment by junghans** [comment]
`MOL_CUT` determines the cutoff based on the distance of the centers of masses of two molecules instead of distance of two individual atoms.

Only use case outside AdResS I could think of is to avoid dipole moment errors for a purely short-range  Coulomb interaction (e.g. Reaction field).

**Comment by junghans** [comment]
If you don't want to support the latter, just drop `MOL_CUT`.
