### ISSUE TITLE
Decide fate of UMBRELLA

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1146]
Does not have docs

**Comment by jngrad** [comment]
The `UMBRELLA` macro was removed in #4032, yet the umbrella force/energy kernels remain, with no python interface to use them.

**Comment by jngrad** [comment]
This ticket has been open for more than 3 years, yet no one volunteered to contribute a python interface for the umbrella kernels. It is safe to assume there is no interest for it in the community. Furthermore, these kernels need to be touched every time we refactor the bonded interactions, but there are no tests to help us detect regressions. Let's remove it.
