### ISSUE TITLE
Decide fate of BOND_CONSTRAINTS (rattle)

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1148]

**Comment by RudolfWeeber** [comment]
The python interface is impleneted via a bonded interaction.
Needs a test case to see, whether it works

**Comment by fweik** [comment]
IIRC our last discussion of this we came to the conclusion that there is no advantage of rattle/shake over virtual sites.

**Comment by RudolfWeeber** [comment]
The feature can stay and wokrs, as soon as the pr containing the test and fixes is merged
