### ISSUE TITLE
Constructor of PScriptInterface creates a new script object even if it is supposed to refer to an existing one

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1155]
E.g. when getting the Shape object out of a ShapeBasedConstraint
In that case, set_sip() will be called later, and the script object created in the constructors of the PScriptInterface class will go out of scope.
This might result in performance problems, if many objects are instanced or parameter setting in the core is slow.

**Comment by fweik** [comment]
Looks to me like this is fixed?

**Comment by jngrad** [comment]
@RudolfWeeber is this issue still present in the current implementation of `PScriptInterface`?

**Comment by jngrad** [comment]
ping @RudolfWeeber

**Comment by jngrad** [comment]
The script interface underwent a major refactoring in 4.2-dev. Feel free to re-open with a MWE if the issue still exists.
