### ISSUE TITLE
Sphinx In-Code Documentation

### ISSUE THREAD

**Issue by richter-t** [espressomd/espresso#1162]
There seems to be no solution to reference a method that was inhereted from a base class. 
For example the UG trys to refer to :meth:\`espressomd.electrostatics.P3M.Tune\` in the description of the P3M coulomb solver, but this symbol is not created in the list of modules, since this was originally defined in the object ElectrostaticInteraction.

**Comment by KaiSzuttor** [comment]
http://stackoverflow.com/questions/40508492/python-sphinx-inherit-method-documentation-from-superclass

**Comment by richter-t** [comment]
This looks utterly complicated and solves the problem by pythonic hacks. If sphinx could automatically do the job...

**Comment by KaiSzuttor** [comment]
I think thats not the job of sphinx... You also don't get the docstring of inherited members from within python.

**Comment by RudolfWeeber** [comment]
Numpydoc seems to support that. At least, there is a 
numpydoc_show_inherited_class_members
option.

**Comment by KonradBreitsprecher** [comment]
@KaiSzuttor can this be closed?
