### ISSUE TITLE
Twice defiend name of bonded interactions

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1163]
Once in src/core/interaction_data.cpp: get_name_of_bonded_ia()
Once in the python interface, where sub-classes of BondedInteraction define a type_name() method.

Probably, the one in the core should stay (and be checked for completeness) and the BondedInteraction base class should get the information from the core.

**Comment by jngrad** [comment]
Fixed by #1723: commit 6a9667b removed the unused `get_name_of_bonded_ia()` core function.
