### ISSUE TITLE
Get rid of the (nearly) copy of the bonded force calculatino in the pressure/virial calculation.

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1165]
the one for forces lives in forces_inline.hpp:add_bonded_pair_force()
the one for virials in pressure.hpp:calc_bonded_pair_force() 
It is not immediately clear if the second one is complete.

Getting rid of the one in the pressure calculations requires the particles used in the force calculation be const, so that we can be sure bonded interactions do not secretly modify them. 
Then, bonded interactions only add forces to the particles, and pressure and virials can be calculated via scalar and dyadic products

**Comment by KaiSzuttor** [comment]
can we close this? see #2542

**Comment by jngrad** [comment]
fixed by #2542
