### ISSUE TITLE
Bug with particle advection in LB code?

### ISSUE THREAD

**Issue by sgekle** [espressomd/espresso#1203]
Based on the poiseuille flow tutorial, I created a modified version which includes a particle (attached).
If kT=0, in my view, the particle should be advected by the fluid. It is not, for some reason.
Setting kT=1e-4, some advections sets in. Setting kT=1e-3, advection increases.

Should the advection not always take place independent of kT? Is this a bug or am I missing something?

[poiseuille_mod.py.txt](https://github.com/espressomd/espresso/files/1074285/poiseuille_mod.py.txt)

**Comment by rempferg** [comment]
What you describe is not the expected behavior. The advection should be independent of kT. I can reproduce your problem on the GPU.

**Comment by rempferg** [comment]
The fluid velocity in the output seems independent of kT, but the value of interpolated_u used in calc_vicous_force seems to scale with kT.

**Comment by rempferg** [comment]
I believe you placed the particle in the wall with

     `system.part.add(id=0, pos=[5,0,0])`

replace that with 

     `system.part.add(id=0, pos=[5,5,5])`

to obtain the expected advective behavior. The LB fluid in the wall follows twilight zone physics for performance reasons.
