### ISSUE TITLE
unexpected len(system.part) when deleting a particle in the middle of id range

### ISSUE THREAD

**Issue by kosovan** [espressomd/espresso#1216]
When I delete a particle in the middle of the id range of already existing particles, len(system.part) decreases by one. Its return value then refers to the number of existing particles but not to the actual length of the python array system.part. This is confusing. See also the attached script.
[delete.txt](https://github.com/espressomd/espresso/files/1115417/delete.txt)

**Comment by RudolfWeeber** [comment]
On Fri, Jun 30, 2017 at 07:17:47AM -0700, Peter Kosovan wrote:
> When I delete a particle in the middle of the id range of already existing particles, len(system.part) decreases by one. Its return value then refers to the number of existing particles but not to the actual length of the python array system.part. 
system.part is not an array. Rather, view it as dictionary, i.e., id->particle mapping.
Also, len(system.part) and the iterator
for p in system.part:
   pass
need to be consistent.

You probably need system.part.highest_particle_id

**Comment by kosovan** [comment]
I am sorry for the confusion. Please ignore my comment and thank you for the explanation.
