### ISSUE TITLE
P3M forgetts parameters

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1228]
@kosovan  was pointing out to me that If P3M parameters are set before adding the actor,
they are not saved:

```python
from __future__ import print_function
import espressomd as es
from espressomd import electrostatics

bjerrum=2.0;
accuracy=0.001
p3m = electrostatics.P3M(bjerrum_length=bjerrum, accuracy=accuracy, tune=False, mesh=6, cao=5, r_cut=4.64152e-01, alpha=4.53518e+00, )
print ("p3m params:", str(p3m.get_params()));
```

**Comment by itischler** [comment]
i don't know if this is a bug, because the parameters get updated to the c++-core parameters once the p3m actor is added to the system. If one tries to read them out beforhand the c++-core parameters are set to 0 by default.

**Comment by RudolfWeeber** [comment]
On Thu, Oct 19, 2017 at 08:39:20AM -0700, itischler wrote:
> i don't know if this is a bug, because the parameters get updated to the c++-core parameters once the p3m actor is added to the system. If one tries to read them out beforhand the c++-core parameters are set to 0 by default. 
It should behave like script interrface classes. I.e., when added to
the system, the parameters should be transferred from the class to
the system. Tuning, is of course, an exception.

**Comment by fweik** [comment]
There is more issues in the Actor class: 

- Unpickling an inactive actor will activate it.
- Using set_params() on an inactive Actor will set params in the core.
- Activation and deactivation do not sync the parameters.
