### ISSUE TITLE
analyze pressure documented incorrectly

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#1233]
system.analysis.pressure()['total'] does not include ideal part of pressure. system.analysis.stress_tensor()['total'] does include the ideal part. The documentation claims they both do.

It makes sense to leave out the ideal part from the pressure to make the hydrostatic pressure available to the user, but it should be documented as such.

**Comment by RudolfWeeber** [comment]
> system.analysis.pressure()['total'] does not include ideal part of pressure. system.analysis.stress_tensor()['total'] does include the ideal part. The documentation claims they both do.
> 
> It makes sense to leave out the ideal part from the pressure to make the hydrostatic pressure available to the user, but it should be documented as such.
I don't think, leaving it out was intended. Total should be total. The ideal pressure/stress tensor is available separately, and if one needs to substract it, that can be done.

**Comment by fweik** [comment]
The ideal pressure should be in pressure()['total'], and it should hold that Tr[stress_tensor()] == pressure()['total']. This can be done by changing the interface.

**Comment by RudolfWeeber** [comment]
@rempferg, can this be closed?

**Comment by jonaslandsgesell** [comment]
I just moved the documentation from tcl to Python recently due to interest in the virial stress. I did not change the calculations. I think this is still open.

**Comment by RudolfWeeber** [comment]
as I understand testsuite/stress.py, it tests the consistency of stress and pressure tensor.
And both contain the kinetic part.
Can this be closed?

**Comment by jngrad** [comment]
The scalar pressure is equal to a third of the trace of the stress tensor for every contribution, including the kinetic contribution, since 4.0. This can be closed.
