### ISSUE TITLE
ScriptInterface: cannot set global script objects as parameter of local ones

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1238]
E.g. ClusterStructure (github.com/RudolfWeeber, branch py_cluster_analysis) needs to
have creation policy LOCAL, whereas the PairCriterion it uses does not have to be LOCAL
and may be used by other global script objects.

To reproduce, fetch the branch mentioned above, set creation policy of PairCriterion (pair_criteria.py) to local and run the cluster_analysis.py test case.

**Comment by fweik** [comment]
This is intended behavior. You can not just unwrap the parallel instance, setting parameters would then lead to an inconsistent state and this would cause lifetime issues (use_count would be no longer the same on all nodes), and calling methods on it might lead to MPI deadlock. At the moment I can not think of clean solution to this. To make it work in your case you can check if the argument passed is parallel and if so access the local underlying instance with get_underlying_object, which you then have to check for the correct type. You then can use this for all cases where you have checked that it is save, e.g. non-modifying and does not use MPI.

I agree that there is a deeper design issue here, but this is not easily fixed. E.g. there should only be const access to unwrapped instances parallel instances.

**Comment by fweik** [comment]
We discussed this offline. The anticipated solution is to give const access to the local instances of an SO passed as an parameter. Const access excludes call_method() and set_parameter(), and is safe to use everywhere as it can not mess with the consistency across the nodes.

**Comment by fweik** [comment]
I believe this is no longer an issue.
