### ISSUE TITLE
Bonds with more than one partners in H5MD will fail

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#1303]
https://github.com/espressomd/espresso/blob/aecc6622ea2b3082185b4c5910222761e63bd1e8/src/core/io/writer/h5md/h5md_core.cpp#L350

The bond list format is e.g. bondindex1 Id1 Id2 bondindex2 Id1 Id2 Id3 ...
The current implementation assumes single partner bonds. This will cause errors, types and Ids will be mixed.

If the H5MD format doesn't support that, skip the bond and throw a warning.

**Comment by jonaslandsgesell** [comment]
Stuff like that is covered by the standard.

**Comment by fweik** [comment]
This needs to be fixed.
