### ISSUE TITLE
Rotation, anisotropy and the thermostat

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1306]
Build with ROTATION, PARTICLE_ANISOTROPY and not ROTATIONAL_INERTIA is broken (this combination is not tested). Also, at least from a physics point of view, it would make sens if PARTICLE_ANISOTROPY would imply ROTATIONAL_INERTIA if ROTATION is turned on.

In the thermostat ROTATIONAL_INERTIA is mentioned in several places, but the rinertia property of the particles is not used anywhere. This seems wrong to me, maybe somebody can explain this. ROTATIONAL_INERTIA makes absolutely no difference for the system, it only means that all parts have the same inertia tensor.

**Comment by RudolfWeeber** [comment]
Can this be closed. Based on the extended langevbin test pr, I think, the cleaned-up thermostat code is sufficiently tested and correct.
