### ISSUE TITLE
Decide fate of uwerr error estimation

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1310]
There are some 300 lines of c code in src/core and some 800 in src/tcl
Is there a good reason to invest in python support? It would probably be more than half a rewrite.

**Comment by RudolfWeeber** [comment]
So far, no one spoke up for this feature. That probably means we remove it.

**Comment by RudolfWeeber** [comment]
uwerr was removed

**Comment by Marcello-Sega** [comment]
that was a useful piece of code, maybe those who are still interested can make good use of  https://github.com/dhesse/py-uwerr
