### ISSUE TITLE
Integrator test (NVT)

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1314]
This can be done by rewriting the following tcl tests (which differ by only a few lines of code) and the associated stored results.
intpbc.tcl intppbc.tcl layerd.tcl nsquare.tcl

**Comment by fweik** [comment]
I think most of this covered by the partners and lj tests from the short
range PR

**Comment by RudolfWeeber** [comment]
Closing, since the short range pr with its associated tests are merged
