### ISSUE TITLE
Tests for key interactions potentials

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1320]
non-bonded: lj, lj generic
Bonded: harmonic, fene, angle_harmonic
Probably check against the actual energy expressions rather than transfer the tcl test case.
Also check that  force is compatible with derivatigve of energy

**Comment by fweik** [comment]
Lj test is in the short range PR (compares about the stored results from
the old tcl test)

**Comment by pkreissl** [comment]
Will have a look at that.
