### ISSUE TITLE
Check coverage in CI

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1326]

**Comment by hmenke** [comment]
I have actually been working on this some days ago.  It's not yet working unfortunately.  For some reason `codecov` does not find any coverage reports.

Here is the relevant commit: https://github.com/hmenke/espresso/commit/c23a2f6491d6deefb48f203fcf5f72f010c998d9

**Comment by mkuron** [comment]
There is something special about codecov-ing a Python module in a non-codecov-ed interpreter, though I don't recall the details. Probably some dynamic library loading order issue.

**Comment by hmenke** [comment]
@mkuron No, that is not the issue.  After all we do not care about coverage in the Python interpreter itself.  The coverage reports `.gcno` and `.gcda` are properly generated (as `ls -lRa` on Travis CI reveals), but for some reason the `codecov` script does not find them.  In my pairinteraction project, which also has a Python interface, a similar setup works just fine: https://github.com/hmenke/pairinteraction/commit/968e02040626301337467abb5d14187a99bbdf42

**Comment by fweik** [comment]
Also I think that the code generated by cython should be exlucded
