### ISSUE TITLE
EK tests non-deterministically fail

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#1337]
Sometimes with incorrect results, sometimes with NaNs. cuda-memcheck reports no access out of bounds or to uninitialized memory.

**Comment by fweik** [comment]
This was fixed by removing the Ladd boundaries.

**Comment by fweik** [comment]
See https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/495
@rempferg  Please make tests deterministic.

**Comment by rempferg** [comment]
Seems like the error threshold was a bit too optimistic.
https://github.com/espressomd/espresso/pull/1481
