### ISSUE TITLE
Segmentation fault in Correlator

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1343]
The correlator segfaults on calling `finalize()`.
```python
from espressomd import System
from espressomd.observables import ParticlePositions
from espressomd.correlators import Correlator

system = System()
system.box_l = [10.0,10.0,10.0]
system.cell_system.skin = 0.1
system.time_step = 0.01

system.part.add(id=0,pos=.5*system.box_l)

int_length = 100

pos_id = ParticlePositions(ids=[0])
msd    = Correlator(obs1=pos_id,
                    corr_operation="square_distance_componentwise",
                    dt=system.time_step,
                    tau_max=int_length*system.time_step,
                    tau_lin=16)
system.auto_update_correlators.add(msd)

system.integrator.run(int_length)

system.auto_update_correlators.remove(msd)
msd.finalize() # BOOM!
```
Full backtrace: https://gist.github.com/anonymous/32e1adf996d5acc870aede0b06b544e4

**Comment by hmenke** [comment]
Can somebody confirm this?  It happens to me reproducibly on Ubuntu 16.04 with tools and libraries from the official repositories.

**Comment by kosovan** [comment]
I get no segfault on OpenSuse 42.2 with default myconfig.

**Comment by hmenke** [comment]
Thanks.  I just checked, I can reproduce on Ubuntu 16.04 with `maxset` and `default`.

**Comment by kosovan** [comment]
I am trying to see where the problem comes from but it is difficult when I cannot reproduce it.

Checking your backtrace, the following indices should normally have rather small values:
`        index_new = 4133993882
        index_old = 32767
        index_res = 4134721502
        error = 32767
        tau_lin = 4160266320
hierarchy_depth = 32767`

My interactive session running your python code gives the following (correct) values:
`tau_lin=16`, `tau_max=1`, `hierarchy_depth=4`

```

**Comment by RudolfWeeber** [comment]
Probably, in the long run, something along the lines of #878 is needed. That would also make it easy to bring checkpointing back.

**Comment by hmenke** [comment]
I deleted my build directory and hard reset my branch to the HEAD on GitHub.  Now I can no longer reproduce either.  There seem to have been leftovers of the Ladd boundary code in my repo.
