### ISSUE TITLE
Travis builds suceed even if cmake fails

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1358]
START CONFIGURE
==================================================
Using default myconfig.
>cmake -DWITH_PYTHON=OFF  /home/espresso/travis
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Config file: /home/espresso/travis/src/core/myconfig-default.hpp
-- Performing Test result__PRETTY_FUNCTION__
-- Performing Test result__PRETTY_FUNCTION__ - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found Cython version 0.23
-- Found Cython: /usr/bin/cython (Required is at least version "0.23") 
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found version "1.11.0") 
-- NumPy ver. 1.11.0 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  The Python module enum was not found.  (missing: PY_ENUM)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPythonModule.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:147 (find_python_module)

-- Configuring incomplete, errors occurred!
See also "/home/espresso/travis/CMakeFiles/CMakeOutput.log".
maintainer/travis/build_docker.sh: line 51: [: =: unary operator expected

Done. Your build exited with 0.

**Comment by fweik** [comment]
Iirc this is fixed in some pr

**Comment by mkuron** [comment]
Should have been fixed in #1352, but it seems like I missed something. The proper solution would be to put `set -e` at the top of build_travis.sh and build_cmake.sh and make the places explicit where non-zero exitcodes are permitted.
