### ISSUE TITLE
macOS testing setup takes too long

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1365]
The macOS travis tests regularly fail because building the dependencies takes too long.

**Comment by mkuron** [comment]
Installation of HDF5 is the problem. Homebrew does not provide binaries with MPI and building them every time takes a few minutes. Sometimes it works within the 10-minute limit (e.g. https://travis-ci.org/espressomd/espresso/jobs/271744619), sometimes it doesn't (https://travis-ci.org/espressomd/espresso/jobs/271952697). As a quick workaround, I can bump the timeout to 20 minutes, but in the long run we may want to buy a Mac mini and put it into Gitlab...
