### ISSUE TITLE
Add scripts from tutorials to testing

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1377]
where appropriate and fast enough.

**Comment by hmenke** [comment]
I don't think this is feasible.  Many tutorials take about 10 minutes (or more) to complete.

**Comment by mkuron** [comment]
You could run them for a very small number of integration steps. That would at least ensure they remain syntactically correct.

**Comment by RudolfWeeber** [comment]
Adding a test mode to tutorial scripts means adding code to them
which will confuse unexperienced users. I think, we'll have to do
this manually before releases and summer schools.
Once there will be production releases based on pypresso, tutorials
can and should be used with those. 
What we probably should do is note the last known working code
version in the tutorial scripts.

**Comment by mkuron** [comment]
The tutorials are always broken whenever someone uses them. Summer schools are not the only time when new people start using Espresso, and not everybody will be using releases, so we need some way to continuously ensure that they remain working.

We don't need to add a test mode to the code to achieve that. Just adding something simple like `sed -i 's/^(\s*T =) .*/$1 10/g'` to the test runner script can, with a bit of discipline in creating the tutorial code, automatically reduce all tutorials to 10 timesteps.

**Comment by fweik** [comment]
I think that rejecting changes that break stuff is vastly preferable to last minute bug fix sessions in panic when the stuff is needed but turns out to be not working.

**Comment by hmenke** [comment]
\*cough\* #1201\*cough\*

**Comment by jonaslandsgesell** [comment]
I think it would also be a fabolous idea to run the sample scripts in the tests. At least a subset of them. For example constraints.py
This would avoid the repeatedly broken syntax there.

**Comment by RudolfWeeber** [comment]
Postpone until tutorial are ipy notebooks
