### ISSUE TITLE
Script interface: add nullptr to Variant

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1389]
such that it can be safely returned from call_method(). 
Right now, it seems to be converted to one of the other types in Variant. On OpenSuse, it doesn't result in an error, but in the Ubuntu docker image, it gets converted to a string, and results in a runtime error, because there is no conversion from nullptr.

**Comment by fweik** [comment]
I think we should rather add a None type as the default type for Variant.
The you can return just {} to express empty. Unfortunately you can't just
leave out the return statement, as this is undefined behavior if you the
look at the return value...

**Comment by hmenke** [comment]
@fweik At least most compilers produce something that crashes with `Illegal Instruction` if you don't have a return statement.

**Comment by fweik** [comment]
Clang and gcc have -Werror=return-type.
