### ISSUE TITLE
Check all tutorials for the summer school 2017

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#1423]
- [x] 00-building_espresso  
- [x] 01-lennard_jones
- [x] 02-charged_system
- [x] 04-lattice_boltzmann
- [x] 05-raspberry_electrophoresis
- [x] 06-active_matter
- [x] 07-electrokinetics
- [x] 08-visualization
- [x]  09-catalytic_reactions

**Comment by fweik** [comment]
See also #1250.

**Comment by KunTares** [comment]
- [x] 00-building_espresso
- [x] 01-lennard_jones
- [x] 02-charged_system ~~analyze.rdf is broken~~
- [x] 04-lattice_boltzmann
- [x] 05-raspberry_electrophoresis
- [x] 07-electrokinetics
- [x] 08-visualization

**Comment by KonradBreitsprecher** [comment]
Will check 08-Visualization #1479

**Comment by fweik** [comment]
(Georg)
Sorry for deleting your comment, Flo. Messed up with the interface.

**Comment by rempferg** [comment]
#1471 is correct. David and I checked its results against one of David's RDF scripts. The script nacl.py in tutorial 02_charged_system gives a physically weird result though. The ++, --, and +- RDFs all look like an LJ fluid with a large first peak for +- and a smaller first peak for ++ and --. According to Fig. 2 in the Tutorial the ++ and -- RDFs should monotoneously approach their bulk value. Konrad and David are looking into it.

**Comment by rempferg** [comment]
make tutorials fails. None of the PDFs get built. building them individually with latexmk fails as well, because common.tex isn't located in under the tutorials directories. Changing \include to \input just reveals more problems. The PDFs weren't updated either after people changed the source files. Would have been great if someone said something earlier than the night before we want to print, or, you know, at all.

**Comment by fweik** [comment]
Building the tutorials works for me on ICP/ubuntu 16.04 with bb72f74ca520c21361dc0d06b9c13fc4843dfa51. See also #1486.

**Comment by rempferg** [comment]
I can't reproduce the error any more. Now works on the ICP Ubuntus and mine. No idea what was going on. Sorry for the freakout.

**Comment by rempferg** [comment]
Found out how to reproduce it. Delete one of the PDFs in doc/tutorials/python. Subsequent builds fail.
