### ISSUE TITLE
H5md does not write folded positions as required by the standard

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1437]
Particle positions are stored unfolded although they should be stored folded (pos in the central box + image). This behaviour is required e.g. by the H5MD writer to follow the H5MD specification with the current implementation.

The h5md writer showed wrong behaviour regarding writing folded positions and their images after the following commit:

git bisect bad
8a90942879d98716bf8bb387c9c704619320ca89 is the first bad commit
commit 8a90942879d98716bf8bb387c9c704619320ca89
Date:   Thu May 18 17:14:27 2017 +0200

    h5md: Use partCfg to account for id gaps

:040000 040000 047349ede6a5bb6d7f54244c474b70e0956176a8 241b59f5159a646e840f869e019238741483d5f0 M	src

Using the following line in PartCfg.hpp fixes the unwanted behaviour and the behaviour from before May 18th is recovered (particle positions are stored folded in partCfg):
using PartCfg = ParticleCache<GetLocalParts, PositionFolder>;

However then the Correlation test seem to break.

**Comment by fweik** [comment]
Particles in partCfg have unfolded positions, if you want them folded, you have to do that by hand at the point of use. There are several analysis methods that expect unfolded coords. Why would you think a global behavior change would be the right answer to your local problem?

**Comment by KaiSzuttor** [comment]
https://github.com/espressomd/espresso/blob/e0f37ee4f7eee0adbc1b436f57f5ff3fef9b5482/src/core/particle_data.hpp#L210

hmmmm...

**Comment by jonaslandsgesell** [comment]
Please note that according to particle_data.hpp the particle struct contains "periodically folded positions":
`/** Positional information on a particle. Information that is
    communicated to calculate interactions with ghost particles. */
struct ParticlePosition {
  /** periodically folded position. */
  double p[3] = {0, 0, 0};`
This implies that the changes on 18th May changed espressos behaviour and broke e.g. writing particle coordinates with h5md. Not sure whether other stuff broke too.

**Comment by fweik** [comment]
No, that is not correct. You are talking about the _particles_, the changes you mention are about the partCfg. partCfg has always had unfolded positions. (Btw. the comment on that particles is also misleading, because the coordinates are actually only folded up to skin).

**Comment by jonaslandsgesell** [comment]
I see. Well then the commit only broke the writer since get_particle_data() used particles (with folded positions) and partcfg was introduced which uses unfolded positions.

**Comment by fweik** [comment]
I'll post a fix in a second. I think the clean way is to just explicitly write the folded positions in h5md.
