### ISSUE TITLE
Python support for pdb parser

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1438]
Is probably rather useful to many users and uncomplicated since it is implemented in the core.

**Comment by KaiSzuttor** [comment]
Should this be discussed offline?

**Comment by RudolfWeeber** [comment]
On Tue, Nov 14, 2017 at 08:31:26AM +0000, Kai Szuttor wrote:
> Should this be discussed offline?
My suggestion would be to de-couple #1441 from a more general
discussion about I/O refactoring.

Once test and docs are proivded, I think #1441 could be merged.

**Comment by RudolfWeeber** [comment]
@fweik wants to pull this outinto a separate py module. Closing for now
