### ISSUE TITLE
Clash of ROTATIONAL_INERTIA and PARTICLE_ANISOTROPY

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1440]
Steps to reproduce:

1. Copy `maintainer/configs/maxset.hpp` as `myconfig.hpp`.
2. Comment out the line `#define PARTICLE_ANISOTROPY` in `myconfig.hpp`.
3. Try to compile.
4. ???
5. Profit.

**Comment by hmenke** [comment]
Can somebody please confirm?

**Comment by KaiSzuttor** [comment]
confirm with current python branch

**Comment by fweik** [comment]
Seems like I broke that with  #1404. Will fix.
