### ISSUE TITLE
reaction ensemble set_volume bug

### ISSUE THREAD

**Issue by helvrud** [espressomd/espresso#1450]
**RE=reaction_ensemble.reaction_ensemble(standard_pressure=1, temperature=1, exclusion_radius=1)**

**RE.set_volume()**
_TypeError: set_volume() takes no arguments (1 given)_

**RE.set_volume(100.0)**
_TypeError: a float is required_

**Comment by jonaslandsgesell** [comment]
Fix comes in a second
