### ISSUE TITLE
inter.rst 2nd iteration

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1463]
* Explain missing interaction types: single particle (constraints) and collective (coulomb, dipolar) actors.
* Explain querying of interaction parameters
* Correct wrong syntax for interaction setup:
   ...tabulated(params) should be ...tabulated.set_params(params)
* Docs for bond angle potentials are missing
* Sort out todo: .. todo:: Document missing implementation for actor.remove()
  Looking at the code in src/python/espressomd/actor.pyx, there seems to be an implementation
* Docs on Coulomb methods need an example and a clear statement that the class needs to be instanced and added as an actor
* The wald gpu doc contains tcl stuff
* Debye Hueckel docs on Py interface missing
* mmm2d docs py stuff missing
* Indicate memd not being implemented in Py yet
* Elc Python docs missing
* ICC Python docs missing
* Dipolar interactions missing python docs
* Tunable slip will be replaced by a constraint. Remove docs @fweik
* Dpd docs will come with new dpd interaction @fweik
* Capping docs will come with new capping implementaiton @fweik

**Comment by RudolfWeeber** [comment]
This one probably needs to be taken by at least two people. There is quite a lot to do.

**Comment by davidsean** [comment]
I can try a few, will need third iteration.

**Comment by KonradBreitsprecher** [comment]
Done with:
- Elc python docs
- Python docs missing
- ICC Python docs missing-
- mmm2d docs py stuff missing
- Correct wrong syntax for interaction setup:
...tabulated(params) should be ...tabulated.set_params(params)
- Capping docs (saw fweiks comment too late)

**Comment by davidsean** [comment]
I only did one section:
- bond-angle potential

**Comment by RudolfWeeber** [comment]
Remaining todos are (#1785)

 - Bonded interactions
     - [ ] Quartic bond
     - [ ] Bonded coulomb
     - [ ] Subtracted Lennard-Jones bond
    
 - Electrostatics
     - [x] Coulomb Ewald GPU (will be removed #1821 ) 
     - [x] Tuning Alpha Ewald GPU (will be removed #1821)
    
 - Magnetostatics / Dipolar interactions (needs doc)
      - [ ] Dipolar interaction
      - [ ] Dipolar P3M
      - [ ] Tuning dipolar P3M
      - [ ] Dipolar Layer Correction (DLC)
      - [ ] Dipolar all-with-all and no replicas (DAWAANR)
      - [ ] Magnetic Dipolar Direct Sum (MDDS) on CPU

**Comment by RudolfWeeber** [comment]
I'll do the magnetostatic stuff

**Comment by KaiSzuttor** [comment]
updated your comment to get a checklist

**Comment by KonradBreitsprecher** [comment]
I'll do the bonded interactions
