### ISSUE TITLE
Live plotting with pyplot not working anymore

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#1479]
pyplot is used in the visualization tutorial and in samples/visualization.py.
@mkuron any idea what might has changed?

**Comment by KonradBreitsprecher** [comment]
So this seems to be an issue related to the Ubuntu switch, the scripts are still working on Mac.

**Comment by davidsean** [comment]
perhaps the backend that got carried from matplotlibrc isn't working with Ubuntu?  I remember playing around with it last week (I hardly use live plotting), TkAgg seemed to work fine (I'll check samples/visualization.py) tomorrow.

**Comment by mkuron** [comment]
It‘s a backend thing. Both Mayavi and Matplotlib need to be using the same GUI toolkit (wx, Qt, GTK, ...).

Also, all plotting and visualization calls need to be made from thread 0.

**Comment by davidsean** [comment]
The script works on my desktop if I use WX or WXAgg as a backend

**Comment by fweik** [comment]
So what do we do about this? It would be nice if the visualization tutorials would work for next week.

**Comment by davidsean** [comment]
I see two possible solutions, 
1) select the working backend from the script
- makes the script a bit more busy
- the script fails on other systems
- script is a bit more transparent (users can tweak it at will)

2) select a system wide working backend via ~./config/matplotlib/maplotlibrc
- seamless
- obfuscates tweaks/workarounds if it dosn't work on their system

**Comment by fweik** [comment]
Can somebody please check if WX or WXAgg works on macOS?

**Comment by KonradBreitsprecher** [comment]
It works on maxOS with explicitly setting
```
import matplotlib
matplotlib.use('WXAgg')
```
but only after installing wxPython (via brew).

**Comment by davidsean** [comment]
it doesn't work "off-the-bat" on my laptop, but I can try to install dependencies....

Another option is to use the same approach as mayavi vs opengl:

```
from __future__ import print_function
import numpy
import matplotlib
# select a backend (or leave blank for default)
#matplotlib.use('WXAgg')
#matplotlib.use('MacOSX')
from matplotlib import pyplot
from threading import Thread
import espressomd
from espressomd import thermostat
from espressomd import integrate
from espressomd import visualization

```

**Comment by KaiSzuttor** [comment]
BTW what I find kind of weird is that I have to have mayavi installed if I want to use opengl visualization.

**Comment by KonradBreitsprecher** [comment]
I'd go with

> 2. select a system wide working backend via ~./config/matplotlib/maplotlibrc

if this will work on the cip machines. We should also do test runs with the summerschool user accounts (will do tomorrow).

**Comment by fweik** [comment]
Ok, maybe we can add a system wide config to the profile or something. This would also be helpful for teaching, so that plotting works for the students. IIRC what had something like this before, and it was also solved by a sytem wide config.

**Comment by KaiSzuttor** [comment]
I salted all ubuntu machines with a matplotlibrc using WX

**Comment by fweik** [comment]
The WX backend solution works on ubuntu for python2. Solution for python3 is under investigation...

**Comment by KonradBreitsprecher** [comment]
Could resolve this with a pyplot.pause(0.01) after pyplot.draw(). Backend TkAgg was fine.
