### ISSUE TITLE
PARTICLE_ANISOTROY may still be broken

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1482]
@fweik @psci2195

I extended the langevin_thermostat test to include rotational degrees of freedom.
I also added a verification of translational and rotational diffusion coefficients via Green-Kubo integrals of the velocity auto correlation function.
Unfortunately. the test does not pass for rotational degrees of freedom, when PARTICLE_ANISOTROPY is compiled in (independently of LANGEVIN_PER_PARTICLE). 

Please see the branch extended_langevin_test on my github.

**Comment by fweik** [comment]
From a quick inspection your test looks good, so this seems to be still broken. I'll have a close look next week.

**Comment by bogdan-tanygin** [comment]
I will take a look.

**Comment by fweik** [comment]
We did a change in how the features work, compared to the earlier versions. Now PARTICLE_ANISOTROPY should make the gammas directional (both if ROTATION), and ROTATIONAL_INERTIA enables the inertia tensor. Just that you know. It seemed clearer to
us to separate the diffusion part from the mechanics part.

**Comment by RudolfWeeber** [comment]
I looked at this some more. Apparently, the tests only fail when the inertia tensor is non-isotropic.
That may be physics rather than a bug due to the cross terms in the rotational eqn of motion.

**Comment by fweik** [comment]
But we can still do the Green-Kubo test for translation and rotaion separately right?

**Comment by RudolfWeeber** [comment]
On Fri, Oct 06, 2017 at 08:38:39AM -0700, Florian Weik wrote:
> But we can still do the Green-Kubo test for translation and rotaion separately right?
Yes. Just only with isotropic I-tensor

**Comment by bogdan-tanygin** [comment]
I've reviewed my analytical calculations.. Indeed, probably, the nonlinear system of Euler equations has no simple closed-form solution based on exponents. Hence, probably, Green-Kubo integrals cannot be derived from EOMs noisy solutions in this case as it can be done for a translation motion of an isotropic particle. Due to the analogous reason, I've not added originally a rotational diffusion Einstein relation validation to the anisotropic case in `mass-and-rinertia_per_particle.py`. Hence, one seems that this is not a bug, the isotropic I- and gamma_rot-tensor should be used in the test.

**Comment by RudolfWeeber** [comment]
On Fri, Oct 06, 2017 at 09:02:58PM +0000, Dr. Theo (Bogdan) Tanygin wrote:
> I've reviewed my analytical calculations.. Indeed, probably, the nonlinear system of Euler equations has no simple closed-form solution based on exponents. Hence, probably, Green-Kubo integrals cannot be derived from EOMs noisy solutions in this case as it can be done for a translation motion of an isotropic particle. Due to the analogous reason, I've not added originally a rotational diffusion Einstein relation validation to the anisotropic case in `mass-and-rinertia_per_particle.py`. Hence, one seems that this is not a bug, the isotropic I- and gamma_rot-tensor should be used in the test.
I agree. I'll close this for now. I will open a PR for the langevin
thermostat test, which by now should cover all possible
combintations of ROTATION, PARTICLE_ANISOTROPY, and
LANGEVIN_PER_PARTICLE.

I might add a test later which compares Es's solution for the Euler
eqn to a numerical integration of the eqn using scipy.
