### ISSUE TITLE
Analysis routines not documented (rdf, ...)

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1494]

**Comment by jonaslandsgesell** [comment]
The whole analysis.rst needs to be rewritten to match the python interface. Documentation of the commands should also happen in the code and not in the rst.

**Comment by fweik** [comment]
There are more specific tickets for all the commands. Also rdf has incode docs, but the rest is missing.

**Comment by davidsean** [comment]
I'll work on this one next for the next coding day
