### ISSUE TITLE
Implement clear() in py for ObjectRegestry-drived classes

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1500]

**Comment by christophlohrmann** [comment]
A clear() function for interactions or even the whole system would be nice, too.

**Comment by jngrad** [comment]
Update: the core `ScriptInterface::ScriptObjectRegistry` class now provides a `clear()` method. In python, derived classes `Constraints` and `LBBoundaries` both provide a `clear()` method, but not `AutoUpdateAccumulators`. Concerning interactions, they rely on different classes, and this should be treated in a separate issue.

**Comment by jngrad** [comment]
`AutoUpdateAccumulators` has a `clear()` method since 4.1.4.
