### ISSUE TITLE
REACTION_ENSEMBLE sort out ifdefs

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1536]
Currently, 
REACTION_ENSEMBLE 
is defined as a feature in features.def, but the code in the core is compiled in unconditionally.
Only the Python interface is not added, if the features is not defined.

Probably, the feature should be removed from features.def and the Python stuff also compiled unconditionally. Furthermore the skipIf decorator needs to be removed from the test.

**Comment by fweik** [comment]
I can see no reason why this needs to be a FEATURE in the first place. @jonaslandsgesell agrees.
