### ISSUE TITLE
Feature requirements get checked late if at all

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1538]
e.g., putting ELECTROKINETICS into myconfig.hpp and compiling without cuda.

ELECTROKINETCS requires CUDA as stated in features.def.

The checks are put in the build dir in src/core/config-features.cpp.
So
* either, config-features.cpp needs to be compiled before everything else
* or, the requirement checking should go into config-features.hpp. In that case, it would also be possible to output a warning and undef the feature rather than to prevent compilation (if thats wat we want).

src/core/gen_feature_config.py

**Comment by fweik** [comment]
We can make them into a lib and then make EspressoConfig depend on it, that would force to be compiled first. I would not continue if something went wrong. We should force the user to make an deliberate choice.
