### ISSUE TITLE
Don't allow attempted change of vector components

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#1550]
A pitfall for many users might be that `system.part[0].pos[2] = 123` will run but don't change the z component of the position. This only changes the returned numpy.array and not the underlying property's component. A way out would be:
```
ret = np.array(..)
ret.flags.writable = False
return ret
```
in all getters that return arrays, which then throws an error if the users attempts the component change.

**Comment by jonaslandsgesell** [comment]
I agree, I would have expected this syntax to modify the particle position.

**Comment by rempferg** [comment]
Would be great if someone *hint* *hint* would create a pull request.

**Comment by KonradBreitsprecher** [comment]
A pull request for the indicated solution?
However, as @RudolfWeeber  pointed out, this would prevent something like

```
pos1 = system.part[0].pos
pos1 *= 2
```

**Comment by jonaslandsgesell** [comment]
That's fine the User Just has to provide a whole vector instead of manipulating only components.

**Comment by KonradBreitsprecher** [comment]
I just realised that modifying operators like
```
system.part[0].pos += [1,1,1]
system.part[0].pos *= 2
```
also won't work with non-writable return arrays..

**Comment by mkuron** [comment]
How about a solution that actually makes `system.part[0].pos[2] = 123` work? Just subclass `numpy.ndarray` and overwrite the `__setitem__` method with one that sets the value in the core.
