### ISSUE TITLE
Tutorial which nicely demonstrates the differences between the constant pH method and the reaction ensemble

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1551]
The differences between both methods (https://arxiv.org/abs/1702.04911) can be nicely shown.
In the tutorial especially the number of H+ ions can be observed as a function of different box volumina.
*For the constant pH method one observes that the box volume does not affect the number of H+ ions
*For the reaction ensemble one observes a change in the H+ number.

*The different electrostatic screening between the reaction ensemble (in the K sweeping mode and the real titration mode) and the constant pH method at the same "pH" can be shown.

**Comment by RudolfWeeber** [comment]
@jonaslandsgesell, what's the status?

**Comment by jonaslandsgesell** [comment]
Can be closed.

RudolfWeeber <notifications@github.com> schrieb am Mo., 15. Okt. 2018,
14:21:

**Comment by kosovan** [comment]
@jonaslandsgesell Why do you consider this tutorial closed? We agreed that I will provide feedback after we finish the work on the reaction ensemble / constant pH review paper.

Last week, while working no the review we found out that it is not completely clear how and why the results follow the trend observed in Fig.2 of the tutorial. We plan to look into it together with Pascal this week.

After a brief look at the current pdf of the tutorial, I also find several minor issues with notation, and similar.

@RudolfWeeber I think that this issue should be re-opened until the controversy is resolved.

**Comment by jonaslandsgesell** [comment]
Please open a new issue for this. This issue was about the tutorial not
existing. The curve follows the trend because of screening effects and
particles which react to water being (almost surely) removed from the
simulation for ever.

Am Mo., 15. Okt. 2018 um 21:57 Uhr schrieb Peter Kosovan <
notifications@github.com>:
