### ISSUE TITLE
Prevent users from putting external dependencies in myconfig.hpp

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1554]
#define SCAFACOS
in myconfig.hpp whith scafacos not found/installed results in a compilation error late in the build process.
?Defining CUDA when compiling without cuda support will compile successfully (everything except cuda stuff) and fail on module import.

**Comment by fweik** [comment]
We could put a guard into the generated header (config-features.hpp), sth like
```c++
#ifdef SCAFACOS
#error SCAFACOS can not be defined in myconfig.hpp
#else
#define SCAFACOS
#endif
```
This does not scale of course. In the longer run we have to think about a replacement for the header-based configuration, e.g. via cmake.

**Comment by RudolfWeeber** [comment]
On Sat, Oct 21, 2017 at 03:16:49PM +0000, Florian Weik wrote:
> We could put a guard into the generated header (config-features.hpp), sth like
> ```c++
> #ifdef SCAFACOS
> #error SCAFACOS can not be defined in myconfig.hpp
> #else
> #define SCAFACOS
> #endif
> ```
> This does not scale of course. In the longer run we have to think about a replacement for the header-based configuration, e.g. via cmake.
For now, since the config-features.cpp/hpp are generated at build time by a
Python script, we can auto-generate these guards for all features
declared as external in features.def.
This has to happen after the myconfig-final.hpp is included but
before config_cmake.hpp is.
