### ISSUE TITLE
Eliminate all compiler warnings before releasing Espresso 4.0

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#1558]
Our CI builds currently show hundreds of compiler warnings. We should take care of all of them before Espresso 4.0 is released. To ensure that no new warnings are ever introduced after that, we might want to add `-Werror` to the compiler flags, which makes all warnings fatal, and `-pedantic`, which shows warnings when the C++ standard is violated.

**Comment by hmenke** [comment]
Some thoughts:
- We'd have to exclude `-pedantic` and `-Werror` from the Cython-generated code.
- We should aim to compile with `-Wall`.  Currently this triggers heaps of the following
  * `-Wsign-compare`
  * `-Wmissing-field-initializers`
  * `-Wreorder`
  * `-Wmaybe-uninitialized`
  * `-Wunused-variable`

  Apart from `-Wunused-variable` all of those indicate the possibility for undefined behaviour.  We should *really* fix all of those.

**Comment by mkuron** [comment]
I‘ll try to do this at next week‘s coding day.

Fixing the `-Wall` Warnings you mention is going to be a huge amount of work, so I‘ll add them one by one after all other warnings have been fixed.

**Comment by hmenke** [comment]
#1616 fixes all regular and `-pedantic` warnings from GCC 5.4.1 and all regular and `-pedantic` warnings for non-CUDA code from Clang 6.0.0.
