### ISSUE TITLE
engine_lbgpu broken in debug build

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1575]
The 3pt coupling part is broken. The offending commit is 74d2da99213a9230a35d1a149d2695d0324436d7, so it was broken from the beginning. I'll deactivate the 3pt test for now.

**Comment by fweik** [comment]
Removed section from test:
```python

         lbm = espressomd.lb.LBFluid_GPU(
             agrid=1.0,
             tau=S.time_step,
             fric=0.5,
             visc=1.0,
             dens=1.0,
             couple="3pt")
         self.run_and_check(S, lbm, tests_common.abspath("data/engine_lbgpu_3pt.vtk"))
```

**Comment by RudolfWeeber** [comment]
What do we do about this?

**Comment by fweik** [comment]
Can you check if this still holds?

**Comment by jngrad** [comment]
Update: 3pt coupling was completely rewritten in #2551, making this bug obsolete.

Re-introducing the engine 3pt coupling test is probably unnecessary since the existing 2pt coupling test covers the same code (`lb_calc_particle_lattice_ia_gpu()` is now a template for both 3pt and 2pt).
