### ISSUE TITLE
Gitlab CI should merge master before testing PR's

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1579]
Currently the PRs are directly checked, which is less useful than testing there merged code.

**Comment by KaiSzuttor** [comment]
that will cause failing checks if there are merge conflicts

**Comment by fweik** [comment]
The CI is not started if the PR can't be automatically merged. Travis does the same thing.

**Comment by fweik** [comment]
Ok maybe you are right.

**Comment by hmenke** [comment]
I don't see the problem.  If the PR cannot be merged it's not useful anyway, so failing checks are only a minor nuisance on top.

**Comment by KaiSzuttor** [comment]
its not usefull until master is merged manually but then the tests run again anyway, so I dont see any advantage in trying to merge within the webhook procedure

**Comment by KaiSzuttor** [comment]
can this be closed?

**Comment by KaiSzuttor** [comment]
This would also mean that we would have to trigger a merge for every open PR for every merge. That is kind of overkill
