### ISSUE TITLE
CUDA build with cuda 8 and debug flags broken

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1596]

**Comment by KaiSzuttor** [comment]
We should go back to the CUDA 7.5 to be able to to test again and investigate what does not yet work with cuda 8.

**Comment by fweik** [comment]
This appears to be an upstream issue in trust, see https://github.com/thrust/thrust/issues/864.
They claim this is fixed in cuda 9. So, I think a reasonable workaround is to disable debug flags for the relevant code.
