### ISSUE TITLE
observables are not documented

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1617]
Currently the user can only look into the source code and check which parameters to set in the interface.
The following observables are lacking documentation:
- [x] `class espressomd.observables.ComForce`
- [x] `class espressomd.observables.ComPosition`
- [x] `class espressomd.observables.ComVelocity`
- [x] `class espressomd.observables.Current`
- [x] `class espressomd.observables.CylindricalFluxDensityProfile` provided by PR #1613 
- [x] `class espressomd.observables.DensityProfile`
- [x] `class espressomd.observables.DipoleMoment`
- [x] `class espressomd.observables.FluxDensityProfile`
- [x] `class espressomd.observables.ForceDensityProfile`
- [x] `class espressomd.observables.LBVelocityProfile` not implemented for GPU, not tested for CPU
- [x] `class espressomd.observables.MagneticDipoleMoment`
- [ ] `class espressomd.observables.ParticleAngularVelocities` @RudolfWeeber maybe can provide info
- [ ] `class espressomd.observables.ParticleBodyAngularVelocities` @RudolfWeeber maybe can provide info
- [ ] `class espressomd.observables.ParticleBodyVelocities` @RudolfWeeber maybe can provide info
- [x] `class espressomd.observables.ParticleCurrent`
- [x] `class espressomd.observables.ParticleForces`
- [x] `class espressomd.observables.ParticlePositions`
- [x] `class espressomd.observables.ParticleVelocities`
- [ ] `class espressomd.observables.StressTensor` unclear what it does
- [ ] `class espressomd.observables.StressTensorAcf` unclear what it does

**Comment by KaiSzuttor** [comment]
@fweik @RudolfWeeber the remaining observables seem to be last touched by you. Can you please provide a documentation for these?

**Comment by KaiSzuttor** [comment]
@kosovan, I just noticed that you seem to be the author of the StressTensor observable calculation. Could you please provide documentation for the observable?

**Comment by kosovan** [comment]
@KaiSzuttor I could document the Stress Tensor but the question is in what timeframe. Next two weeks I will be pretty busy because of some project deadline.
