### ISSUE TITLE
Codebase-wide changes after merge freeze

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1624]
Larger changes that should be done after the merge freeze on 1st Dec:

- clang-format all the files
- autopep8 Py and Cy files
- Make local_cells non-global via [CoARCT](https://github.com/lanl/CoARCT)

Please feel free to add stuff, we will not have this opportunity often in the future.

**Comment by RudolfWeeber** [comment]
autopep8 Py and Cy files

**Comment by hmenke** [comment]
I've tried `include-what-you-use` on another project of mine today and I found that it is completely useless.  It chokes on Boost because of circular includes (by asserting and crashing) and gives stupid tips like including `<bits/shared_ptr.h>` instead of `<memory>`.  So better don't use it.

**Comment by fweik** [comment]
I've testet IWYU on espresso and it worked fine. That was on ubuntu 16.04 with IWYU from the package manager. It uses mapping files to avoid such issues as you describe, they have to match the boost and stdlib versions that are used, otherwise everything explodes.

It does not work perfectly on Espresso though, because there are mutual exclusive ifdefs.
