### ISSUE TITLE
py: Type checking for int and float needs to cope with numpy types

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1630]
E.g., access to system.non_bonded_inter[i,j] with i,j being output of ParticleSlice[:].type

**Comment by fweik** [comment]
I think this should be centralized.

**Comment by KonradBreitsprecher** [comment]
Slices of particle types are `<type 'numpy.int64'>`,
which works as input for  `system.non_bonded_inter`.
@RudolfWeeber is that what you meant?

**Comment by RudolfWeeber** [comment]
I was referring to the integer particle type ids in system.non_bonded_inter[i,j].
They are checked like
 if not (isinstance(_type1, int) and isinstance(_type2, int)):
This, (and a large number of similar checks throughout the code) fail for np.int types.

The solution is probably to have a
is_vald_type_for(value,t)
in utils.pyx, which handles int and float explicitly as in 
 Variant python_object_to_variant(self, value)
in script_interface.pyx

**Comment by KonradBreitsprecher** [comment]
Ok, will work on that.
