### ISSUE TITLE
I cannot compile espressomd in archlinux WITH_CUDA=ON and WITH_PYTHON=ON

### ISSUE THREAD

**Issue by hseara** [espressomd/espresso#1645]
Dear all,
it is being a long while since I used espressomd. I understand that you are about to finish the porting to python of the whole code. A great idea. I wanted to test the new version myself using the current git version (3.4.dev.r2998.g6cbef0e6b). Unfortunately, there are two fundamental features that I need to deactivate if I want to succeed compiling espresso in Archlinux using defaults.

First, I cannot compile with CUDA support  (WITH_CUDA=ON). I guess this is because your code does not support cuda 9. This is the default cuda version in archlinux and I guess that many others distribution will adopt it too.
```
[  4%] Building CXX object src/core/object-in-fluid/CMakeFiles/ObjectInFluid.dir/affinity.cpp.o
nvcc fatal   : Unsupported gpu architecture 'compute_20'
nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at ActorCuda_generated_Mmm1dgpuForce_cuda.cu.o.Release.cmake:218 (message):
  Error generating
  /home/hector/espresso-git/src/build/src/core/actor/CMakeFiles/ActorCuda.dir//./ActorCuda_generated_Mmm1dgpuForce_cuda.cu.o 
```
The same error appears for each cuda file.

Second, I cannot compile with python support (WITH_PYTHON=ON). It happens both using Python2.7 and 3.6. My system has python-numpy 1.13.3 and cython 0.27.3. There is an error that does not allow a successful compilation:

```
[ 86%] Linking CXX shared library _init.so

Error compiling Cython file:
------------------------------------------------------------
...
                self._params["isTuned"] = True

            self._set_params_in_es_core()

IF ELECTROSTATICS:
    cdef class MMM1D(electrostatics.ElectrostaticInteraction):
        ^
------------------------------------------------------------

/home/hector/espresso-git/src/espressomd/src/python/espressomd/electrostatics.pyx:435:9: 'electrostatics' is not declared
```
Using a restrictive myconfig.hpp solves the issue if you do not use problematic modules.

Also there are some warnings about the usage of a deprecated numpy API:
```
[ 84%] Building CXX object src/python/espressomd/CMakeFiles/minimize_energy.dir/minimize_energy.cpp.o
In file included from /usr/include/python3.6m/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python3.6m/numpy/ndarrayobject.h:18,
                 from /usr/include/python3.6m/numpy/arrayobject.h:4,
                 from /home/hector/espresso-git/src/build/src/python/espressomd/minimize_energy.cpp:549:
/usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated 
NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
```

Thanks for your great job and please let me know if you need further information.

**Comment by fweik** [comment]
The reason for the nvcc issues seems to be that compute capability 2.0 is no longer supported by cuda 9. I think the proper solution is to make the compute capabilities that should be build should be settable via cmake.

The numpy warnings can be ignored. This is a known upstream issue in cython and has to be dealt with by them.

**Comment by hseara** [comment]
Hi, it seems that all problems are on my side. I was using the outdated master branch and not the new python branch. Once I used the python branch for the compilation, all problems described above are gone. Therefore, no further action is needed.
