### ISSUE TITLE
reaction ensemble docs need to be corrected

### ISSUE THREAD

**Issue by kosovan** [espressomd/espresso#1650]
Sections 6.6 - 6.8 in the user guide need changes. Some statements are incorrect due to previous misunderstandings, others could be simplified.

Some parameters of the reaction_ensemble module need to be fixed:
pressure - its meaning is incorrectly described. 
default_charges - it is unclear from the docs how it is used

The order of types in the list of reactant_types and product_types matters for the algorithm although it does not matter for the thermodynamics. This point is presumably not mentioned.

I can plan to work on this on Monday November 27th.

**Comment by kosovan** [comment]
I am still working on this.

After reviewing the docs, I suggest that the reaction ensemble syntax should be be re-considered. There are numerous functions such as `fix_polymer_segments`,  or `set_polymer_start_id` which seem to be single-purpose functions with unclear relation to the reaction ensemble.

**Comment by jonaslandsgesell** [comment]
Commands like 

- fix_polymer_segments
- set_polymer_start_id, polymer_end_id
- global_mc_move_for_one_particle_of_type()
- set_cylindrical_constraint_in_z_direction()
- set_wall_constraints_in_z_direction(self, slab_start_z, slab_end_z)

are needed for the configuration changing Monte Carlo moves in the Wang-Landau reaction ensemble, where MD cannot be used. Of course those Monte Carlo moves can also be used in the normal Reaction Ensemble (replacing or complementing MD) or in principle even without the reaction ensemble.
global_mc_move_for_one_particle_of_type() e.g. moves one particle in the whole available volume (restricted by e.g. set_wall_constraints_in_z_direction() or set_cylindrical_constraint_in_z_direction()) using an acceptance probability which is different from the normal Boltzmann Criterion exp(-beta Delta E) if the Wang-Landau reaction ensemble is used.
