### ISSUE TITLE
Samples need cleanup

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1661]
dbebye_hueckel: outdated
villard: Segfaults if no graphics display
load/save_checkpoint are waiting for more tolerant parameter type checkint (int,float)
load_properties misses a file (no save_properties)
observables_correlator crashes with segfault
ireaction_ensemble: Outdated interface
store_bonds produces runtime errors

Some scripts contain irrelevant code
dev = "cpu"
and the like\

Some scripts should probably be combined (lj_liquid, lj_liquid_structure_Factor, lj_liquid_distribution)

**Comment by jonaslandsgesell** [comment]
I touched the reaction_ensemble example already

**Comment by fweik** [comment]
Is this still relevant after #1845?

**Comment by pdebuyl** [comment]
I have been checking the samples recently (as you could guess from my other PR). I did file fixes mostly about simple Python 3 issues, even though some revealed issues in the source tree, see #1879 ).

There are still a few other issues.

An annoying one (I find) is the call to `__getstate__` as the typical Python style is to not access underscored methods in user-facing code. Also, in Python 3 the code crashes when trying to access `espressomd.virtual_sites.VirtualSitesOff` with

> TypeError: unhashable type: 'instancemethod'

when calling pprint on `system.__getstate__`. Solutions:

1. Remove all instances of `__getstate__`
2. Place some valid output for the property representation

Also, a short paragraph (the first string, stored automatically in `__doc__`) explaining the purpose of the example would be nice. Would such a summary be welcome in PRs?

**Comment by jonaslandsgesell** [comment]
__getstate__ is related to pickle https://docs.python.org/2/library/pickle.html
I would not remove all instances of __getstate__

**Comment by pdebuyl** [comment]
My message was confusing, sorry about this. I meant to remove the calls to `__getstate__` in the samples. Not to remove it from the code overall.

**Comment by RudolfWeeber** [comment]
Regarding the __get_state__(): Some parts of Espresso do not have __str__() implemented yet, so __get_state__() is the only way to get the data.

More generally, the tests would still benefit from a clean up in the sense of removing outdated and duplicate stuff.

My impression is that this is not urgent for the release though, so I'm de-milestonin this for 4.0

**Comment by pdebuyl** [comment]
Hi @RudolfWeeber 

When I run `samples/lj_liquid.py` under Python 3, the output is

```python-traceback
(md_env) pierre.db@itf50:/pierre/code/espresso/samples$ ../build/pypresso lj_liquid.py 

=======================================================
=                    lj_liquid.py                     =
=======================================================

Program Information:
['COULOMB_DEBYE_HUECKEL', 'DPD', 'ELECTROSTATICS', 'EXPERIMENTAL_FEATURES', 'EXTERNAL_FORCES', 'FFTW', 'GAUSSIAN', 'H5MD', 'HAT', 'LENNARD_JONES', 'P3M', 'ROTATION', 'ROTATIONAL_INERTIA', 'SOFT_SPHERE', 'TABULATED']
LJ-parameters:
{'sigma': 1.0, 'cutoff': 1.12246, 'offset': 0.0, 'shift': 0.2499999999700293, 'epsilon': 1.0, 'min': 0.0}
Simulate 868 particles in a cubic simulation box 10.7437 at density 0.7.
Interactions:

Start with minimal distance 0.12199322315136626
Start warmup integration:
At maximum 30 times 100 steps
Stop if minimal distance is larger than 0.9
LennardJonesInteraction({'sigma': 1.0, 'cutoff': 1.12246, 'offset': 0.0, 'shift': 0.2499999999700293, 'epsilon': 1.0, 'min': 0.0})
{'cell_grid': array([7, 7, 7]),
 'cell_size': array([1.53481429, 1.53481429, 1.53481429]),
 'local_box_l': array([10.7437, 10.7437, 10.7437]),
 'max_cut': 1.12246,
 'max_num_cells': 2744,
 'max_range': 1.5224600000000001,
 'max_skin': 0.4123542857142857,
 'min_num_cells': 8,
 'n_layers': -1,
 'n_nodes': 1,
 'node_grid': array([1, 1, 1]),
 'skin': 0.4,
 'type': 'domain_decomposition',
 'use_verlet_list': True,
 'verlet_reuse': 5.2631578947368425}
{'box_l': Traceback (most recent call last):
  File "lj_liquid.py", line 148, in <module>
    pprint.pprint(system.__getstate__(), width=1)
  File "/usr/lib/python3.5/pprint.py", line 53, in pprint
    printer.pprint(object)
  File "/usr/lib/python3.5/pprint.py", line 139, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/usr/lib/python3.5/pprint.py", line 167, in _format
    p(self, object, stream, indent, allowance, context, level + 1)
  File "/usr/lib/python3.5/pprint.py", line 189, in _pprint_dict
    context, level)
  File "/usr/lib/python3.5/pprint.py", line 346, in _format_dict_items
    context, level)
  File "/usr/lib/python3.5/pprint.py", line 164, in _format
    p = self._dispatch.get(type(object).__repr__, None)
TypeError: unhashable type: 'instancemethod'
```

That occurs on the line `pprint.pprint(system.__getstate__(), width=1)` of the program.

`samples/save_checkpoint.py` and `samples/load_checkpoint.py` work fine however.

**Comment by RudolfWeeber** [comment]
I can reproduce this, but do not understand the cause.
The individual keys and corresponding values in the reutnr value of System.__getstate__()
can be pretty-printed. Just not the entire thing.
THe problem goes away when one leaves out the width=1 option.
I'll put that into #1933 for now, until someone has a better-informed solution.

**Comment by RudolfWeeber** [comment]
+ a bunch of further py3 fixes, mostly related to file modes and str/bytes

**Comment by pdebuyl** [comment]
The error went away, thanks.

I maintain though that promoting via the samples the call to a doubly underscored method is not recommended. I know PEP8 is not to be followed always but this part is really enforced by the large majority of Python code

From https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance

> Public attributes should have no leading underscores.

**Comment by RudolfWeeber** [comment]
> I maintain though that promoting via the samples the call to a doubly underscored method is not recommended. I know PEP8 is not to be followed always but this part is really enforced by the large majority of Python code
> 
> From https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance
> 
> > Public attributes should have no leading underscores.
I agree. We are, however, postponing further updates to the sample to the 4.0.1 release.

**Comment by jngrad** [comment]
The samples have changed substantially since this issue was opened. The runtime errors have been fixed and the samples are now tested in CI. Most samples now have docstrings. There are only two points left:
- removing calls to `system.__getstate__()`, or calling instead a yet-to-be-created method without the two underscores prefix that would call `__getstate__()` internally
- removing outdated samples and merging similar samples; I would suggest that further discussion of this point take place into the dedicated issue #2584
