### ISSUE TITLE
Debye Hueckel and Coulomb Debye Hueckel lack integration test

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1662]
There is an interface test

**Comment by davidsean** [comment]
Coulomb Debye Hueckel is a bit funny,

![cdh_f](https://user-images.githubusercontent.com/1529852/33374666-61a11b76-d507-11e7-8e47-935761421021.png)
![cdh_u](https://user-images.githubusercontent.com/1529852/33374669-63e1f996-d507-11e7-86b7-685eced02fa5.png)

The sign change for alpha helps but  does not completely fix the problem: the forces do not correspond to the energy.
