### ISSUE TITLE
MMM1D lacks integration test

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1663]
cpu and gpu

**Comment by jonaslandsgesell** [comment]
I am porting the test for the forces and the energy (taken from gpu mmm1d) https://github.com/espressomd/espresso/blob/tcl/testsuite/tcl/mmm1dgpu.tcl
https://github.com/espressomd/espresso/blob/tcl/testsuite/tcl/mmm1d.tcl

please assign me.
