### ISSUE TITLE
force_cap probably broken

### ISSUE THREAD

**Issue by kosovan** [espressomd/espresso#1682]
With @helvrud we found out that since commit d2ec3e4de force_cap scales all forces, not just non-bonded ones.  It leads to "bond broken ..." errors when diverging bonded interactions like FENE are present. This is because capping all forces allows for exceeding the maximum bond length with a finite force.

We will provide a minimal working example soon.

**Comment by fweik** [comment]
I see your point, I did not think of that. Did you try equilibrating such systems with energy minimization?

**Comment by kosovan** [comment]
Yes, energy minimization does the job. Probably the warmup with force capping can be completely replaced by energy minimization. So the question is whether the force_cap should be retained. But if it should be retained, then I think it should only cap the non-bonded interactions.

**Comment by fweik** [comment]
force_cap is still useful in situation with non-conservative contributions where the overlap can not remove with energy minimization, because it only acts on the positions. Imagine a setup where you have velocity depended forces that are to big to directly integrate as a result of overlapping DPD particles. Otherwise I see no reason to change the force_cap, it works as advertised. It can also still be used in situations with bonds by using a sufficiently small time step to not break the bonds.

**Comment by kosovan** [comment]
I agree that force_cap is useful. Oleg found out yesterday that the simple energy minimization works well only for short polymers N<20. For longer ones it is insufficient.

However, I do not agree that the current implementation of force_cap can be used with FENE bonds if the time step is small enough. When the forces are capped, the problem is not integrator instability due to long time step, but too small barrier to breaking the bonds because of capped forces. With harmonic bonds it is safe because the force is defined at any separation. But with FENE it causes irrecoverable errors because the force is undefined beyond R_max.

**Comment by fweik** [comment]
It's unclear to me why energy minimization would fail for larger polymers.

**Comment by kosovan** [comment]
Because nearest energy minimum for randomly created long chains usually still contains strong overlaps which lead to collapse of the integrator.

**Comment by fweik** [comment]
Do you happen to have an example script (and seed) where this is a problem?

**Comment by kosovan** [comment]
I will try to provide it today in the afternoon.

**Comment by kosovan** [comment]
Looks like we cannot reproduce it anymore. Probably we were previously running the script without energy minimization. With energy minimization everything seems to work correctly now. I think that you can consider the issue closed and if the problem shows up again, we can open it anew.
