### ISSUE TITLE
Cuda clang builds broken

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1693]
Probably related to an Dockerfile update today:
https://github.com/espressomd/docker/commit/21ee756ae3ba82ac9caffe068e7eecdd13b35246

E.g. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/6115, @mkuron could you please have a look?

**Comment by mkuron** [comment]
It must have been due to the CMake upgrade, but it is unclear to me why it ever worked... The problem was that CMake's `find_library` doesn't search non-standard places (even if they are in ldconfig and LD_LIBRARY_PATH).
