### ISSUE TITLE
statistics::aggregation has neither test nor documentation.

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1694]
@RudolfWeeber this seems like something that your cluster code can do?

**Comment by RudolfWeeber** [comment]
Statistics aggregation counts contacts between molecules. The pair criteria used by the cluster analysis, on the other hand, at this point act between two particles only and do not have state. So, some hacking would be required to get that working with the cluster analysis. Let's keep this for now.

**Comment by RudolfWeeber** [comment]
The underlying code was removed
