### ISSUE TITLE
min_global_cut can not be set before box_l

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1708]
MWE:
```python
import espressomd

system = espressomd.System()
system.periodicity = [1, 1, 1]
system.cell_system.skin = 0.4
system.time_step = 0.01
system.min_global_cut = 2.5      
system.box_l = [10.0, 10.0, 10.0]

system.part.add(pos=[2, 2, 2])

system.integrator.run(10)
```
This results in

```bash
ERROR: box_l in direction 0 is too small
ERROR: box_l in direction 1 is too small
ERROR: box_l in direction 2 is too small
ERROR: interaction range 2.9 in direction 0 is larger than the local box size 1
ERROR: interaction range 2.9 in direction 1 is larger than the local box size 1
ERROR: interaction range 2.9 in direction 2 is larger than the local box size 1
ERROR: number of cells 1 is smaller than minimum 8 (interaction range too large or min_num_cells too large)
```

**Comment by fweik** [comment]
Actually at the pointer where you set min_global_cut, the box is too small. Default box size is 1.

**Comment by KaiSzuttor** [comment]
Though, I think it's unexpected that you have to set the system parameters in a certain order. I think the right way would be that box_l does not have a default size.

**Comment by fweik** [comment]
Should be a constructor parameter of System.

**Comment by RudolfWeeber** [comment]
On Tue, Dec 12, 2017 at 06:07:22AM -0800, Kai Szuttor wrote:
> Though, I think it's unexpected that you have to set the system parameters in a certain order. I think the right way would be that box_l does not have a default size.
In my view, the actual bug is that there is no runtime error checking when setting system parameters.
The global cutoff is upper-bounded by the box_l. I think it is ok that the system it is enforced that parameters are consistent at the time you set them.

**Comment by KaiSzuttor** [comment]
In my opinion i should not be able at all to set min_global_cut if box_l is not set (the default value of 1 is in no to me known case useful). So how do we wan't to accomplish that?

**Comment by hmenke** [comment]
I'm not so much in favour of this.  It somehow defeats the notion of procedural programming.  It should be clear that `min_global_cut` cannot be set before `box_l`.  I also cannot get on the bus before it arrives.

**Comment by KaiSzuttor** [comment]
We had an offline discussion and agreed on having box_l as a parameter for the system class (min_global_cut is not the only thing that depends on the box length).
