### ISSUE TITLE
p3m cpu stress tensor lacks a test

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1711]

**Comment by jonaslandsgesell** [comment]
Is this a python interface problem or was this present in the tcl branch already?

**Comment by fweik** [comment]
That is under investigation.

**Comment by RudolfWeeber** [comment]
As I understand the state of affiars, the results from ESPResSo agree with those from Lamps. Do we close this issue or do we want an independent test, e.G. via Ewald expressions?

**Comment by jonaslandsgesell** [comment]
To be honest. I would like to see an explicit, analytic test for the electrostatic part of the stress tensor. Otherwise how could one trust these results fully?
