### ISSUE TITLE
Reaction ensemble broken with ELECTROSTATICS

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1742]
The constant ph method of the reaction ensemble is broken. There is an out of bounds read of ReactionAlgorithm::charges_of_types in ReactionAlgorithm::create_particle() at reaction_ensemble.cpp:737. This leads to sporadic segfaults due to use of uninitialized memory.
I've changed the line to a ranged check access to make it fail with an exception in the re_fail branch of my github to demonstrate the issue. From a short inspection of the code I'm also pretty sure it does not work as expected if the type indices have gaps.

There are some other invalid memory accesses that are picked up by valgrind, please fix all of them.

**Comment by jonaslandsgesell** [comment]
I might have fixed that very recently in another branch. I'll check for this.

**Comment by jonaslandsgesell** [comment]
Yes, I recently fixed that in the python branch (as far as I see it the tcl branch was not affected). The problem was in update_type_index().
Running 
valgrind --tool=memcheck --leak-check=full pypresso ../testsuite/constant_pH.py
gives no further problems. You can see the fixed version in https://github.com/jonaslandsgesell/espresso/tree/widom_insertion. The code also runs perfectly when types are not consecutive (e.g. type 1, 2, 5). Types not being consecutive are exactly the reason why I introduced a type_index. Since this was C code this was the way to go. Obviously the Cpp way would be to introduce a map. Since it is friday ... I will replace the c-style type_index related code with cpp code which uses maps. This will simplify the code a bit. 
  
  :)

**Comment by fweik** [comment]
The original one that I quoted is gone, but there are others left. You need to run valgrind directly on python, and not on pypresso, otherwise your just checking bash. You're doing it right if you get a bunch of false positives from python and mpi. The first one in Espresso that I can still see when running the constant_pH test on your branch is

```
==475471== Invalid read of size 4
==475471==    at 0x4A407E: PyObject_Free (in /usr/bin/python2.7)
==475471==    by 0x4D9811: code_dealloc.lto_priv.217 (in /usr/bin/python2.7)
==475471==    by 0x4D95BB: func_dealloc.lto_priv.290 (in /usr/bin/python2.7)
==475471==    by 0x4A0D81: PyDict_SetItem (in /usr/bin/python2.7)
==475471==    by 0x5027E2: _PyModule_Clear (in /usr/bin/python2.7)
==475471==    by 0x50240E: PyImport_Cleanup (in /usr/bin/python2.7)
==475471==    by 0x5000B8: Py_Finalize (in /usr/bin/python2.7)
==475471==    by 0x525657: Py_Exit (in /usr/bin/python2.7)
==475471==    by 0x522A62: handle_system_exit.lto_priv.2091 (in /usr/bin/python2.7)
==475471==    by 0x522355: PyErr_PrintEx (in /usr/bin/python2.7)
==475471==    by 0x42EA2A: ??? (in /usr/bin/python2.7)
==475471==    by 0x49E207: Py_Main (in /usr/bin/python2.7)
==475471==  Address 0x6630020 is 0 bytes inside a block of size 16 free'd
==475471==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==475471==    by 0x2CCF7A87: clear_particle_node() (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCC14C1: cells_resort_particles(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CDBC398: on_observable_calc() (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCED3AC: energy_calc(double*) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCE0DBC: master_energy_calc() (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCE1234: calculate_current_potential_energy_of_system() (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7DAEF: ReactionEnsemble::ReactionAlgorithm::generic_oneway_reaction(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7E1B3: ReactionEnsemble::ConstantpHEnsemble::do_reaction(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x3EE1516A: __pyx_pw_10espressomd_17reaction_ensemble_17ReactionAlgorithm_37reaction(_object*, _object*, _object*) (in /tikhome/fweik/Source/espresso/build/src/python/espressomd/reaction_ensemble.so)
==475471==    by 0x4C45F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==475471==    by 0x4C9D7E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==475471==  Block was alloc'd at
==475471==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==475471==    by 0x2CCF97B9: std::__detail::_Map_base<int, std::pair<int const, int>, std::allocator<std::pair<int const, int> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](int const&) [clone .constprop.835] (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCF9A24: mpi_who_has() (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCF9B58: get_particle_node(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CCFA67C: set_particle_type(int, int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7CFC9: ReactionEnsemble::ReactionAlgorithm::replace_particle(int, int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7D255: ReactionEnsemble::ReactionAlgorithm::make_reaction_attempt(ReactionEnsemble::SingleReaction&, std::vector<ReactionEnsemble::StoredParticleProperty, std::allocator<ReactionEnsemble::StoredParticleProperty> >&, std::vector<int, std::allocator<int> >&, std::vector<ReactionEnsemble::StoredParticleProperty, std::allocator<ReactionEnsemble::StoredParticleProperty> >&) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7DAEA: ReactionEnsemble::ReactionAlgorithm::generic_oneway_reaction(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x2CD7E1B3: ReactionEnsemble::ConstantpHEnsemble::do_reaction(int) (in /tikhome/fweik/Source/espresso/build/src/core/libEspressoCore.so.4)
==475471==    by 0x3EE1516A: __pyx_pw_10espressomd_17reaction_ensemble_17ReactionAlgorithm_37reaction(_object*, _object*, _object*) (in /tikhome/fweik/Source/espresso/build/src/python/espressomd/reaction_ensemble.so)
==475471==    by 0x4C45F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==475471==    by 0x4C9D7E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
```

This seems to suggest that some python cleanup code tries to find the particle node for a particle that does not exists, but it's not clear to me how this can be triggered by python code. Maybe this is not the original problem.

**Comment by jonaslandsgesell** [comment]
By the way these problems also occur when ELECTROSTATICS is not compiled in.

**Comment by fweik** [comment]
I think this can be ignored for now.

**Comment by jonaslandsgesell** [comment]
Thank you for the hint! As far as I can see it these problems are common when using python together with valgrind (https://stackoverflow.com/questions/20112989/how-to-use-valgrind-with-python). The explanation seems to be that python uses some custom allocations/ frees and valgrind is not aware of this.
Using a [suppression file](https://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp) get s rid of these issues if the following is commented out:
```
{
   ADDRESS_IN_RANGE/Invalid read of size 4
   Memcheck:Addr4
   fun:PyObject_Free
}

{
   ADDRESS_IN_RANGE/Invalid read of size 4
   Memcheck:Value4
   fun:PyObject_Free
}

{
   ADDRESS_IN_RANGE/Conditional jump or move depends on uninitialised value
   Memcheck:Cond
   fun:PyObject_Free
}
```
I think we should add a suppression file for #1745 when using valgrind.
Here I would close the issue.

**Comment by hmenke** [comment]
@jonaslandsgesell On Ubuntu 16.04
```bash
./pypresso --valgrind="--suppressions=/usr/lib/valgrind/python.supp" test.py
```

**Comment by jonaslandsgesell** [comment]
I thought about having a suppression file as a default. For new users which might not be aware of the need for using a suppression file for python it might be nice.

**Comment by hmenke** [comment]
I suspect that the Valgrind suppression file is version and platform specific, so the user has to use the one shipped with their Python installation.  Otherwise I wouldn't see why it is not bundled with Valgrind already.

**Comment by jonaslandsgesell** [comment]
By the way the user still has to comment out the lines i mentioned above, so one cannot use /usr/lib/valgrind/python.supp directly.
