### ISSUE TITLE
Debugging needs to be better documented

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1744]
The docs should point out that running tools on the pypresso script does not work as expected for most tools. It should also list the `--TOOL` options for the script.

**Comment by hmenke** [comment]
Well, pypresso is a script, so debugging will work the same as for any other script.
At the same time, we could link with `libSegFault.so` when Espresso is built with glibc to get fancy backtraces.

**Comment by mkuron** [comment]
We could also add some more tools to the script, e.g. Valgrind. An MPI debugger would also be useful, but there are no free ones -- though we have an old license for Allinea DDT and TotalView provides free student licenses.

**Comment by fweik** [comment]
@hmenke, it turned out in practice that people were not aware of this fact.
