### ISSUE TITLE
Constraints cannot be deleted.

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#1750]
It is currently not possible to remove constraints from the system.

Sample script 1:
```python
import espressomd
from espressomd.shapes import Wall

system = espressomd.System()
wall = Wall(dist=20, normal=[0.1,0.0,1])
c = system.constraints.add(shape=wall, particle_type=0)
system.constraints.remove(c)
```
fails with `IndexError: map::at`.

Sample script 2:
```python
import espressomd
from espressomd.shapes import Wall

system = espressomd.System()
wall = Wall(dist=20, normal=[0.1,0.0,1])
system.constraints.add(shape=wall, particle_type=0)
for c in system.constraints:
    print(c)
    system.constraints.remove(c)
```
also fails, with a different error:
`RuntimeError: Parameters passed to Parallel entities must also be parallel.`

**Comment by jonaslandsgesell** [comment]
For me the first script runs.

**Comment by KaiSzuttor** [comment]
Not for me

**Comment by fweik** [comment]
The first script is missing the actual remove line.

**Comment by pkreissl** [comment]
`system.constraints.remove(c)`
of course, sorry

**Comment by fweik** [comment]
So there are two issues, I'm working on a fix.
