### ISSUE TITLE
GitLab status is not properly updated

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1751]
In #1745 I annotated one commit with `[ci skip]` to prevent the CI from running for my trivial change.  Both Travis and GitLab skipped the job properly, but GitLab didn't updated it's status in the PR correctly.

![test](https://user-images.githubusercontent.com/1903556/34741311-1588fa96-f5e7-11e7-88fa-377bf08d4bdc.png)

If you click the [Details](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/commit/6ed1ba65f59d5150690420fc3ea70a34c7c4eff7/pipelines) link you'll find `Pipeline #1581 skipped`.

**Comment by KaiSzuttor** [comment]
thats due to the fact that the pending state is not set by gitlab

**Comment by fweik** [comment]
This can be fixed (yet) due to a missing feature in gitlab, c.f. https://gitlab.com/gitlab-org/gitlab-ce/issues/20727

**Comment by mkuron** [comment]
Actually, we can fix that in the shell script running on elk. If the commit message contains `[ci skip]`, we simply shouldn’t post the request to GitHub that sets the pending state. We don‘t need any GitLab fix for that.

**Comment by mkuron** [comment]
If you reopen the issue and assign it to me or @kaiszuttor, we can get it fixed tomorrow.

**Comment by mkuron** [comment]
Done. Please close this issue. The simple fix:
```
curl -s https://api.github.com/repos/espressomd/espresso/git/commits/$GIT_COMMIT | jq .message | grep -ioq '\[ci skip\]\|\[skip ci\]' && exit
```
