### ISSUE TITLE
reaction ensemble segmentation fault

### ISSUE THREAD

**Issue by helvrud** [espressomd/espresso#1754]
While running the following script segmentation fault appears

```python
###################################################
#  The most simple setup of Reaction  Ensemble 
###################################################

import espressomd
import socket
import numpy as np
from espressomd import reaction_ensemble
#~ from espressomd import grand_canonical
from espressomd import code_info
from espressomd import polymer
from espressomd import interactions

box_l = 100
system = espressomd.System()
system.time_step = 0.01
system.cell_system.skin = 0.4
system.box_l = [box_l]*3
        
RE=reaction_ensemble.ReactionEnsemble(standard_pressure=1, temperature=1., exclusion_radius=1)



type_names = ['Cl','Na','H','OH','Ca','NaCl','NaOH','HCl','CaCl','CaOH','HOH']
TYPES = {}
idx = 0
for type_name in type_names:
    TYPES[type_name] = idx; idx+=1
val = {
    'Cl': -1,
    'OH': -1,
    'Na': 1,
    'H' : 1,
    'Ca': 2,
    }

mu = {
    'Cl': 4.,
    'OH': 7.,
    'Na': 4.,
    'H' : 7.,
    'Ca': 2.,
    }
for part_type in ['H','OH','Na','Cl','Ca']:
    #~ print (part_type, self.TYPES[part_type], self.val[part_type])
    pos=np.random.random(3) * box_l
    system.part.add(pos=pos, type=TYPES[part_type], q=val[part_type])


equilibrium_constant = 10**(-mu['H'])*10**(-mu['OH'])

RE.add(equilibrium_constant=equilibrium_constant,
    reactant_types=[TYPES['HOH']],
    reactant_coefficients=[],
    product_types=[TYPES['H'],TYPES['OH']],
    product_coefficients=[1, 1]
)


RE.reaction(100)
```

**Comment by jonaslandsgesell** [comment]
It is always a good idea to run RE.get_status() since this performs additional checks on your provided input. It has to be run manually since otherwise it would require to perform a check everytime reaction() is called. This is an unwanted performance leak then.

Calling RE.get_status() reveals that you forgot to assign the charges for the given types. This is OK, if you do not include electrostatic interactions in your system. If you include electrostatic interactions your script will also segfault.

`RE.add(equilibrium_constant=equilibrium_constant,
    reactant_types=[TYPES['HOH']],
    reactant_coefficients=[],
    product_types=[TYPES['H'],TYPES['OH']],
    product_coefficients=[1, 1]
)`
this line is not valid since you need to provide an entry in the reactant_coeffients list. This is where the segfault came from. I added another check here in PR #1743. Before the user had to take care here. In PR#1743 this script runs.
```
###################################################
#  The most simple setup of Reaction  Ensemble 
###################################################

import espressomd
import socket
import numpy as np
from espressomd import reaction_ensemble
#~ from espressomd import grand_canonical
from espressomd import code_info
from espressomd import polymer
from espressomd import interactions

box_l = 100
system = espressomd.System()
system.time_step = 0.01
system.cell_system.skin = 0.4
system.box_l = [box_l]*3
        
RE=reaction_ensemble.ReactionEnsemble(standard_pressure=1, temperature=1., exclusion_radius=1)



type_names = ['Cl','Na','H','OH','Ca','NaCl','NaOH','HCl','CaCl','CaOH','HOH']
TYPES = {}
idx = 0
for type_name in type_names:
    TYPES[type_name] = idx; idx+=1
val = {
    'Cl': -1,
    'OH': -1,
    'Na': 1,
    'H' : 1,
    'Ca': 2,
    }

mu = {
    'Cl': 4.,
    'OH': 7.,
    'Na': 4.,
    'H' : 7.,
    'Ca': 2.,
    }
for part_type in ['H','OH','Na','Cl','Ca']:
    #~ print (part_type, self.TYPES[part_type], self.val[part_type])
    pos=np.random.random(3) * box_l
    system.part.add(pos=pos, type=TYPES[part_type], q=val[part_type])


equilibrium_constant = 10**(-mu['H'])*10**(-mu['OH'])

RE.add(equilibrium_constant=equilibrium_constant,
    reactant_types=[TYPES['HOH']],
    reactant_coefficients=[1],
    product_types=[TYPES['H'],TYPES['OH']],
    product_coefficients=[1, 1]
)
RE.set_default_charges(dictionary={"2": 1, "3": -1, "10": 0})
print(RE.get_status())

RE.reaction(100)
```

**Comment by jonaslandsgesell** [comment]
I think this request can be closed with PR #1743 .

**Comment by helvrud** [comment]
With the version from repository this script does not work it passes RE.get_status() but fails at RE.reaction(100) with error.

###################
espressomd/reaction_ensemble.pyx in espressomd.reaction_ensemble.ReactionAlgorithm.reaction (/home/kvint/hydrogel/espresso/es-build/src/python/espressomd/reaction_ensemble.cpp:3744)()

IndexError: _Map_base::at
###################

Before the add() procedure were accepting empty list for reactant_coefficients. I used it to model the annihilation of ion pair. This, as I understand, is how the Widom insertion can be implemented as well. Is there a need to introduce special procedure for widom insertion?

**Comment by kosovan** [comment]
I think that a generic solution to avoid the problem with setting default_charges would be to change the syntax of add_reaction() such that it accepts reactants+products as one list of tuples (particle_type, stoichiometric_coefficient, charge). I think that parsing of this list could be done at the python level, so that the cpp core code can be left unchanged.

What do you think?

**Comment by jonaslandsgesell** [comment]
@ peter @kosovan One could do this, but i would rather keep it as it is. Right now it is easier to see what reactant types are replaced by what product types.

Well for me the script runs.
Do you have the changes from https://github.com/espressomd/espresso/pull/1743/commits/61a5b1f4ced03fd32295dac156fe39a3079f6eac
in your src/core/particle_data.cpp ? Otherwise this explains the effect.

> Before the add() procedure were accepting empty list for reactant_coefficients. 

Yes and this is still poissible now. The problem with the script was the following:
```
    reactant_types=[TYPES['HOH']],
    reactant_coefficients=[],
```
This is not allowed, what would be Ok is the following

```
    reactant_types=[],
    reactant_coefficients=[],
```

**Comment by jonaslandsgesell** [comment]
@helvrud The widom Insertion method rejects all insertions and does Not perform removals of particles. Also it keeps track of the average potential energy of Insertion. That s why you need dedicated code for it.

**Comment by helvrud** [comment]
@jonaslandsgesell @kosovan 
What about introducing negative \nu coefficients, then there wil bee no need of two lists for products and reactants. Then add_reaction could become a function of two (optionally three lists), for example

add_reaction( [list_of_types], [list_of_coefficients], list_of_charges=[] )

**Comment by jonaslandsgesell** [comment]
@helvrud  As far as I understood that is exactly what Peter suggested. So what you propose is an interface change. That is unrelated and not a problem of the code. I would suggest to close the current thread here. Feel free to open a new issue regarding the proposed interface change.

Still: what i dislike about the proposal is the following:
right now you see directly that type a is attempted to be replaced with type c, and type b is replaced with type d if you write the following:
reactant_types=[a,b]
product_types=[c,d]

If you change the interface and write something like list_of_types=[a,b,c,d], list_of_coefficients=[-1,-1,1,1] it is less obvious which types are replaced with each other.

**Comment by fweik** [comment]
I'm with @jonaslandsgesell here, the explicit interface is way cleaner, and we should leave it as is.

**Comment by kosovan** [comment]
What Oleg suggested is the notation convention used in literature, i.e. negative stoichiometric coefficients for reactants, positive for products. In this respect, explicitly distinguishing reactants and products is redundant.

We have planned a skype discussion with Jonas today, so I expect that we will resolve the issue.

**Comment by kosovan** [comment]
In a skype discussion with Jonas today we agreed to postpone the interface changes until we reach a consensus.

**Comment by RudolfWeeber** [comment]
On Mon, Jan 15, 2018 at 01:50:19PM +0000, Peter Kosovan wrote:
> In a skype discussion with Jonas today we agreed to postpone the interface changes until we reach a consensus.
Please note that interface changes will be significantly more complicated after the release.

**Comment by jonaslandsgesell** [comment]
I would not change the way reactions are defined for espresso.
The changes that i discussed with peter are integrated in PR #1767

**Comment by jonaslandsgesell** [comment]
Please close
