### ISSUE TITLE
Domain Decomposition Issue in Python branch

### ISSUE THREAD

**Issue by HuadaLian93** [espressomd/espresso#1759]
Hi, 

The results from single core and multi-core are somehow different. Thus, I would guess there is an issue with the Domain Decomposition in the 'python' branch now. The sample code lj_liquid.py in espresso/samples was used to test. The results are shown below:

`pypresso lj_liquid.py`
**Results:**

> Start integration: run 5 times 1000 steps
> LennardJonesInteraction({'cutoff': 1.12246, 'min': 0.0, 'epsilon': 1.0, 'offset': 0.0, 'shift': 0.2499999999700293, 'sigma': 1.0})
> OrderedDict([**('total', 2290.730202421708)**, ('kinetic', 1674.8620456711803), ('bonded', 0.0), (('non_bonded', 0, 0), 615.8681567505274), ('non_bonded', 615.8681567505274), ('coulomb', 0.0)])
> [46.58833117717648, 22.286953055301833, 37.04281093870252]
> run 0 at time=9.000000
> OrderedDict([('total', 1880.2714129733358), ('kinetic', 1349.7584465044295), ('bonded', 0.0), (('non_bonded', 0, 0), 530.5129664689063), ('non_bonded', 530.5129664689063), ('coulomb', 0.0)])
> [10.522396206179572, -9.559934651374578, -17.383220894724733]
> run 1 at time=19.000000
> OrderedDict([('total', 1902.982956367589), ('kinetic', 1367.3353655471249), ('bonded', 0.0), (('non_bonded', 0, 0), 535.647590820464), ('non_bonded', 535.647590820464), ('coulomb', 0.0)])
> [-8.687217775052648, 22.21494202610864, -8.285956315369901]
> run 2 at time=29.000000
> OrderedDict([('total', 1771.698913054037), ('kinetic', 1263.792943872643), ('bonded', 0.0), (('non_bonded', 0, 0), 507.9059691813938), ('non_bonded', 507.9059691813938), ('coulomb', 0.0)])
> [59.19701438480022, 20.563852128239716, 7.139267247582523]
> run 3 at time=39.000000
> OrderedDict([('total', 1830.0244716675786), ('kinetic', 1321.4977980456285), ('bonded', 0.0), (('non_bonded', 0, 0), 508.5266736219501), ('non_bonded', 508.5266736219501), ('coulomb', 0.0)])
> [-9.963408531857995, 1.6542974518836857, 24.70611111301463]
> run 4 at time=49.000000
> OrderedDict([**('total', 1797.5551086398466)**, ('kinetic', 1320.1605389116494), ('bonded', 0.0), (('non_bonded', 0, 0), 477.39456972819727), ('non_bonded', 477.39456972819727), ('coulomb', 0.0)])
> [34.180267717255745, 27.600122015340016, -13.62633326801039]
> 

`mpirun -np 4 pypresso lj_liquid.py`
**Results:**

> Start integration: run 5 times 1000 steps
> LennardJonesInteraction({'cutoff': 1.12246, 'min': 0.0, 'epsilon': 1.0, 'offset': 0.0, 'shift': 0.2499999999700293, 'sigma': 1.0})
> OrderedDict([**('total', 1921.4799490842352)**, ('kinetic', 1424.1453373022707), ('bonded', 0.0), (('non_bonded', 0, 0), 497.3346117819645), ('non_bonded', 497.3346117819645), ('coulomb', 0.0)])
> [-5.983190356481351, -70.75254372906893, -54.85666303526328]
> run 0 at time=9.000000
> OrderedDict([('total', 1830.761744949681), ('kinetic', 1326.7654760801609), ('bonded', 0.0), (('non_bonded', 0, 0), 503.99626886952024), ('non_bonded', 503.99626886952024), ('coulomb', 0.0)])
> [50.143717025161315, 138.1637013678471, 52.839650997502]
> run 1 at time=19.000000
> OrderedDict([('total', 1843.776488470415), ('kinetic', 1317.4744021803886), ('bonded', 0.0), (('non_bonded', 0, 0), 526.3020862900264), ('non_bonded', 526.3020862900264), ('coulomb', 0.0)])
> [8.907345919522147, 55.856360537644576, -62.500083266997585]
> run 2 at time=29.000000
> OrderedDict([('total', 1856.936508470711), ('kinetic', 1358.296670542105), ('bonded', 0.0), (('non_bonded', 0, 0), 498.6398379286062), ('non_bonded', 498.6398379286062), ('coulomb', 0.0)])
> [125.3644192085535, -19.290120843251746, -23.409792520155122]
> run 3 at time=39.000000
> OrderedDict([('total', 1726.6623781915614), ('kinetic', 1239.613923755504), ('bonded', 0.0), (('non_bonded', 0, 0), 487.04845443605757), ('non_bonded', 487.04845443605757), ('coulomb', 0.0)])
> [4.0027067821739095, 24.02566284910229, -25.538752331889178]
> run 4 at time=49.000000
> OrderedDict([**('total', 1756.2997393573874)**, ('kinetic', 1261.555795630869), ('bonded', 0.0), (('non_bonded', 0, 0), 494.7439437265183), ('non_bonded', 494.7439437265183), ('coulomb', 0.0)])
> [-32.31899045771859, -48.74953820674085, 36.14827697672797]

**Comment by fweik** [comment]
Did you remember to set a seed to make the script deterministic? Otherwise it is never the same system, as it places the particles at random positions which will be different between runs, and it uses noise which will also be different between runs. So you would not expect identical results.

**Comment by HuadaLian93** [comment]
Yes, I did. The results I obtained above use the exact same seed for each core. [19931030] for single-core and [19931030]*np for multi-core.
