### ISSUE TITLE
Interface TAB interaction 

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#1760]
The bonded tabulated interaction interface does not take the "type" argument. See the following minimal example:
```python
import espressomd as md
from espressomd.interactions import Tabulated
tab_bond = Tabulated(type="distance",  npoints= 4, min = 0.0 , max = 4.0, force=[0, 0, 0, 0], energy=[1, 1, 1, 1])
```
Ends with:
```
TypeError: cannot concatenate 'str' and 'method-wrapper' objects
```

Also `type="1"` or  `type=1` or similar alterations do not work.

Probably smaller issue in the interface?

**Comment by hmenke** [comment]
The `Tabulated` bond has no parameter `npoints`.
http://espressomd.org/html/doc/inter.html#tabulated-bond-interactions

But there should definitely be a helpful error message instead of another error raised when generating the error message.

**Comment by bindgens1** [comment]
Oh damn... having a look at the UG would have actually helped. 
I was using the old syntax. 

Sorry!
