### ISSUE TITLE
Suggestion for Default Behaviour: Throw an exception for non-neutral systems during tuning of electrostatic methods unless the user explicitly states differently

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1786]
Typically simulations of charge are carried out such that the system is neutral within some limit (e.g. 1e-8 charges).
Sometimes the user fails in setting up the system  as charge neutral. Electrostatic methods like P3M can be used in a non-neutral system since they automatically introduce a background charge which neutralizes the system. However I assume that this default behaviour can lead to unexpected behaviour.

I suggest to throw an exception in the tuning routine of the electrostatics methods unless the user specifies a flag "simulate_non_neutral_system" that states e.g.
"The system is non-neutral. Please neutralize your system or explcitly state that you want to simulate a non neutral system via setting the flag simulate_non_neutral_system in the tuning routine."

**Comment by hmenke** [comment]
> Sometimes the user fails in setting up the system as charge neutral.

Why not offer a :dizzy: magic :sparkles:  `do_the_correct_physics_for_me()` command for those people?

**Comment by KaiSzuttor** [comment]
This comment is superfluous...
If we save 99% of the users from undesired particle setup, why not doing it?

**Comment by fweik** [comment]
@KaiSzuttor maybe we need community guidelines... ^^ The question is how much we want this? We could also check this "on_integration_start", but this would come add the cost of a global reduction, in the tuning it would be for free (the total charge is calculated there anyway), but would not catch all cases. Maybe do a warning when ADDITIONAL_CHECKS is enabled?

**Comment by KaiSzuttor** [comment]
@fweik it seems so... 😉 i think in the tuning would already catch most of the cases.

**Comment by fweik** [comment]
Hm, if you propose a sensible messure for what a small charge is I'll implement the warning...

**Comment by jonaslandsgesell** [comment]
What about 1e-10 per particle? Something around that? If you include the chosen value into the exception noone is surprised.

**Comment by RudolfWeeber** [comment]
> What about 1e-10 per particle? Something around that?
Does this work if someone uses SI units?

**Comment by fweik** [comment]
Nope, that's about 10^9 elementary charges in SI units. That is kind of my point.

**Comment by jonaslandsgesell** [comment]
So due to the arbitrariness of the unit system this would require to provide the size S of a typical charge in the system of N particles that have a summed charge Q. Then the charge neutrality can be determined via Q/(S*N) <10^-10.
Given the fact that in our simulations the typical size of a charge is 1 e0_const I would still introduce this check -
 given the number of users who use SI units in Espresso seems to be smaller than the number of users who use Lennard-Jones units. Further users who use SI units would not receive an error about their system being not neutral. The check would just leave those users where they are, having to check for electroneutrality on their own. You could include that fact in the name of the flag. 

However I am also willing to drop the suggestion if there seems to be no compromise on doing it that way.

**Comment by fweik** [comment]
`S = min_i(abs(q_i))` ?

**Comment by RudolfWeeber** [comment]
Since, to my understanding, the forces and energy are not affected
by the neutral background, I do not find a hcek and possible
exception necessary, especially since there doesn't seem to be a
clear criterion.

**Comment by fweik** [comment]
The energy is affected, and the point is rather that a non-neutral system is typically not what the user wanted. If you forgot your counter-ions that will of course alter the forces and energies.

**Comment by jonaslandsgesell** [comment]
Pressures are definitely affected. I also guess chemical potentials are affected!
I would maybe use S=sum_{I=1}^N |q_i|/N as typical charge, where i runs over all N charged particles

**Comment by jonaslandsgesell** [comment]
So if energies are affected, chemical potentials are affected

**Comment by jonaslandsgesell** [comment]
Unfortunately, the test for the electroneutrality in #1796 only tests that the reactions that are performed do not introduce new charges during the reaction. The initial charge neutrality (or the charge neutrality in the nvt ensemble) still needs to be tested. E.g. in the tuning.
