### ISSUE TITLE
virtual_sites checkpoint loading error

### ISSUE THREAD

**Issue by iammmiru** [espressomd/espresso#1795]
The following message comes up whenever I try loading a previous checkpoint.
It hadn't happened until I updated my espresso recently.
I also tried explicitly registering 'system.virtual_sites' but didn't work out.

------------------------------------------------------------------------------------------------------
```
loading last checkpoint
Traceback (most recent call last):
  File "4_rotational_diffusion.py", line 245, in <module>
    checkpoint.load()
  File "/home/mlee/espresso/build/src/python/espressomd/checkpointing.py", line 199, in load
    checkpoint_data = pickle.load(checkpoint_file)
  File "espressomd/system.pyx", line 146, in espressomd.system.System.__setstate__ (/home/mlee/espresso/build/src/python/espressomd/system.cpp:2891)
  File "espressomd/system.pyx", line 396, in espressomd.system.System.virtual_sites.__set__ (/home/mlee/espresso/build/src/python/espressomd/system.cpp:6067)
AttributeError: 'NoneType' object has no attribute 'implementation'
```

**Comment by RudolfWeeber** [comment]
On Wed, Jan 31, 2018 at 09:36:39AM +0000, iammmiru wrote:
> The following message comes up whenever I try loading a previous checkpoint.
> It hadn't happened until I updated my espresso recently.
> I also tried explicitly registering 'system.virtual_sites' but didn't work out.
> 
> 
> loading last checkpoint
> Traceback (most recent call last):
>   File "4_rotational_diffusion.py", line 245, in <module>
>     checkpoint.load()
>   File "/home/mlee/espresso/build/src/python/espressomd/checkpointing.py", line 199, in load
>     checkpoint_data = pickle.load(checkpoint_file)
>   File "espressomd/system.pyx", line 146, in espressomd.system.System.__setstate__ (/home/mlee/espresso/build/src/python/espressomd/system.cpp:2891)
>   File "espressomd/system.pyx", line 396, in espressomd.system.System.virtual_sites.__set__ (/home/mlee/espresso/build/src/python/espressomd/system.cpp:6067)
> AttributeError: 'NoneType' object has no attribute 'implementation'
First of all, checkpoints are not guaranteed to work across
different Espresso versions. In this particular case, please check
that your myconfig.hpp for the newer version contains
VIRTUAL_SITES and VIRTUAL_SITES_RELATIVE

**Comment by iammmiru** [comment]
I did complie with VIRTUAL_SITES and VIRTUAL_SITES_RELATIVE.
And I didn't load the checkpoint from previous espresso version. Saving and loading the checkpoint have done in the same newest version of espresso.

**Comment by RudolfWeeber** [comment]
On Wed, Jan 31, 2018 at 09:51:14AM +0000, iammmiru wrote:
> I did complied with VIRTUAL_SITES and VIRTUAL_SITES_RELATIVE.
> And I didn't load the checkpoint from previous espresso version. Saving and loading the checkpoint have done in the same newest version of espresso.
OK, I misunderstood that. Then, this is a bug.

**Comment by fweik** [comment]
Can you please provide a minimal script that demonstrates the issue?

**Comment by fweik** [comment]
The implementation of `__getstate__` of `System` only saves attributes that are in `setable_properties`, which excludes `_active_virtual_sites_handle`. Since unpickeling also does not run the constructor, `_active_virtual_sites_handle` is not initialized, and there for `None`, which causes the error. It's very well possible that this affects other properties too.
