### ISSUE TITLE
Remove EWALD GPU

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1809]
known not to be correct

**Comment by mkuron** [comment]
It used to be correct and we had working test cases back in the Tcl days. So it is probably just some interface thing. Unfortunately we don't have anyone who really understands the Ewald code anymore and it is not particularly well written, so fixing it may be hard.

**Comment by RudolfWeeber** [comment]
I made an unsuccessful attempt at fixing it. Ewald is still available via Scafacos
