### ISSUE TITLE
Exclusions Documentation still valid?

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1839]
Is the following documentation (http://espressomd.org/html/doc/particles.html?highlight=exclusion) still valid? I remember discussions about that:

```
exclusions also remove the short range part of electrostatics and dipolar interactions. Hence, exclusions should not be applied to pairs of particles which are charged or carry a dipole
```

**Comment by fweik** [comment]
No, that's not correct anymore, the check for the forces is on forces_inline.hpp:302 and only acts on the regular pair forces. Same for the energies.
