### ISSUE TITLE
Energy minimization propagates other fields

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1850]
E.g. LB and Maggs. It also considers non-conservative forces, which makes no sense and yields in a force that is not the gradient of the internal energy, which results in the method not minimizing the energy.

**Comment by fweik** [comment]
It also does collisions and catalytic reactions.
I don't think this can be properly accommodated without its own integration loop, which in turn requires some refactoring.

**Comment by RudolfWeeber** [comment]
I'd keep the system.integrator.set_steepest_descent() variant. 
It's not clear to me whether or not the minimize energy class restores the old integ_switch after completion.
