### ISSUE TITLE
Ctrl-C does not interrupt integration loop

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1892]
Waiting for an integrator.run(10000) to complete...

**Comment by RudolfWeeber** [comment]
this only occurs when pypresso is called without mpirun

**Comment by fweik** [comment]
Well if you want that you have to add a signal handler to espresso (or spawn a additional thread that checks PyErr_CheckSignals periodically). Or we could return control to python every now and then. The latter would be the preferred solution if this does not change behavior (I think it might).

**Comment by hmenke** [comment]
Just [`kill`](https://linux.die.net/man/1/kill) it?

**Comment by KaiSzuttor** [comment]
well, that's not a solution, I expect a python script to quit via ctrl-c
