### ISSUE TITLE
clang-tidy fails on get_value unit test

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1902]
The lines that causes the erros are currently NOLINTED, see https://github.com/KaiSzuttor/espresso/blob/11645e86b47882f991997999dd88ac05caf07d28/src/core/unit_tests/get_value_test.cpp

**Comment by mkuron** [comment]
I think I'll upgrade the docker image to Clang 6.0 and see what `NOLINT`s are still necessary.

**Comment by fweik** [comment]
Can you please check if
```c++
  std::vector<Variant> vec;
  Variant v = vec;
```
fixes the issue? This is less drastic than nolint.
I'll check boost.variant to see if there is a real issue here.

**Comment by KaiSzuttor** [comment]
This does not help.

**Comment by mkuron** [comment]
Fixed by #2110. Please close this issue.
