### ISSUE TITLE
`testsuite/thermalized_bond` test fails when run in parallel (4, 5 cores)

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#1916]
```
mpiexec -n 4 ./pypresso ../testsuite/thermalized_bond.py
```
yields
```
AssertionError: 0.016005163491671776 not less than or equal to 0.015
```
(also for `-n 5` cores).
Works again for `6` or `7` cores.
For 8 cores, it fails with different error, see #1915

**Comment by KonradBreitsprecher** [comment]
The problem here was the decreased sample length.. should be fixed with #1930
