### ISSUE TITLE
Convert all 0/1 flags to True, False in the python interface

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1942]
E.g. (and at *all* the other occations - which one would need to find)

```python
system.constraints.add(particle_type=0, penetrable=0, only_positive=0, shape=floor)
```
should read:
```python
system.constraints.add(particle_type=0, penetrable=False, only_positive=False, shape=floor)
```
this can be easily achieved e.g. in the interface. It would be a task for a Hiwi.

**Comment by hmenke** [comment]
That is probably a remnant from the TCL interface.  On the other hand, the integers are implicitly convertible to boolean, so the “wrong” syntax will remain valid.  Furthermore I believe that `particle_type` should *not* be a boolean.

Relevant lines:

https://github.com/espressomd/espresso/blob/ea28f3cb1f53f504be5282f7326a4c061d745577/src/core/constraints/ShapeBasedConstraint.hpp#L47-L48

https://github.com/espressomd/espresso/blob/ea28f3cb1f53f504be5282f7326a4c061d745577/src/core/constraints/ShapeBasedConstraint.hpp#L67-L68

All the rest is done by type inference in the `AutoParameters` magic.

**Comment by fweik** [comment]
The only implicit type conversions in the script interface are int -> float, this is on purpose because implicit conversions are evil. For the constraints class you can just change the core variable to bool, the rest is automatic, as Henri pointed out.

**Comment by jonaslandsgesell** [comment]
I want this to be replaced everywhere, shape based constraints are not the only occasion. Another arbitrary occasion is create_polymer(...,constraints=0) etc. I guess there are so many occasions that a student assistent could look for all these occasions and remove them.
Another arbitrary example is system.periodicity=[0,1,0], which coule more intuitively be [False, True, False]
