### ISSUE TITLE
Collision detection not able to checkpoint

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1943]
see https://travis-ci.org/espressomd/espresso/jobs/364132063

**Comment by fweik** [comment]
Any ideas as to why that is?

**Comment by hmenke** [comment]
It might not be the case, but it is possible that you run into this problem at some point, so I wanted to make you aware of it.

Python 3 strings are not compatible with C++ `std::string` which leads to a loss of data when passing a string from Python to C++.  This used to blow up our serialization in the [pairinteraction project](https://github.com/pairinteraction/pairinteraction/blob/0f5bd7ff844f24d47741b0d15379e8b194391958/libpairinteraction/Interface.i.cmakein#L52-L74) and here is how we fixed it (not Cython but SWIG).  Also note our zero-copy approach to `setstate`.
```cpp
// Make pickle work
// https://stackoverflow.com/questions/9310053/how-to-make-my-swig-extension-module-work-with-pickle
// remark: passing as std::stringstream does not work because swig calls the implicitly-deleted copy constructor of std::stringstream instead of the move constructor
%define %boost_picklable(cls...)
  %extend cls {
    PyObject* __getstate__() {
      std::stringstream ss;
      boost::archive::binary_oarchive ar(ss);
      ar << *($self);
      return PyBytes_FromStringAndSize(ss.str().data(), ss.str().length());
    }

    void __setstate_internal(PyObject* const sState) {
      char *buffer;
      Py_ssize_t len;
      PyBytes_AsStringAndSize(sState, &buffer, &len);
      boost::iostreams::array_source asource(buffer, static_cast<size_t>(len)); // prevents from copying
      boost::iostreams::stream<boost::iostreams::array_source> ss(asource);
      boost::archive::binary_iarchive ar(ss);
      ar >> *($self);
    }
  }
%enddef
```

**Comment by fweik** [comment]
Wouldn't you use `bytes` anyway in python 3? In my understanding the standard string class implies unicode. According to the cython docs `std::string` is convertible to and from `bytes` (== a char array), but not from `str`.

**Comment by RudolfWeeber** [comment]
This also depends on being able to control the order of restoring stuff, because the bonds used in the collision deteciton have to be present
