### ISSUE TITLE
Visualization of Flow Directions Incorrect

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#1946]
The visualization of flow directions using the openGL visualizer seems to have a probrem. When running the Poiseuille flow sample `samples/visualization_poiseuille.py`, the arrow heads and stems start to point into a wrong direction after some time.
I believe this issue already existed at some point and was fixed by @KonradBreitsprecher.

![visualization_opengl_0](https://user-images.githubusercontent.com/12623404/38555155-6a3252a2-3cc5-11e8-9be1-0df3301d7509.png)
![visualization_opengl_2](https://user-images.githubusercontent.com/12623404/38555198-98703d6e-3cc5-11e8-9715-e60594f65bc8.png)
![visualization_opengl_4](https://user-images.githubusercontent.com/12623404/38555187-8ec83244-3cc5-11e8-9f99-1922fa70495d.png)

**Comment by KonradBreitsprecher** [comment]
Yes I know more or less where this comes from.. will fix, thanks.
