### ISSUE TITLE
Types of particles

### ISSUE THREAD

**Issue by AlexanderDKazakov** [espressomd/espresso#1953]
I am attaching the simplest code for representation of the issue. 

Initially after initialization of the system espresso returns the number of type particles = 1. Finally, it returns 6, but types of particle are only 2.
```python
import espressomd

system = espressomd.System(box_l=[5, 5, 5])
print "Types:", system.part.n_part_types
system.part.add(id=0, pos=(1, 0, 0), type=0)
print "Types:", system.part.n_part_types
system.part.add(id=1, pos=(1, 1, 0), type=0)
print "Types:", system.part.n_part_types
system.part.add(id=2, pos=(1, 1, 1), type=1)
print "Types:", system.part.n_part_types
system.part.add(id=3, pos=(1, 1, 1), type=5)
print "Types:", system.part.n_part_types
print "Done."
```

Output:
```
Types: 1
Types: 1
Types: 1
Types: 2
Types: 6
Done.
```

**Comment by KaiSzuttor** [comment]
If you look into the core, you see the it states
``` c++
/** Maximal particle type seen so far. */
extern int n_particle_types;
```
so its not the number of types in the system but the type with largest integer.

**Comment by KaiSzuttor** [comment]
The relevant part is actually in particle_data.cpp:
``` c++
void make_particle_type_exist(int type) {
  if (is_new_particle_type(type))
    mpi_bcast_n_particle_types(type + 1);
}
```

**Comment by RudolfWeeber** [comment]
Is the conclusion that n_part_types in the Python interface needs to be renamed?
To actually get the number of used types:
len(set(s.part[:].type))

**Comment by KaiSzuttor** [comment]
yes im for renaming, the only usecase i can imagine is to automatically choose an unused type.

**Comment by hmenke** [comment]
We could rename it to, say `max_part_types` or `max_seen_type` (akin to the core variable `max_seen_particle`).

**Comment by AlexanderDKazakov** [comment]
Aha! Okay. Now it becomes clear! Thank you!

PS. However, probably this function is not so necessary. Because it just takes last value of inserted type and increases this value by one. But maybe I am wrong.
