### ISSUE TITLE
DD chooses bad default values

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1970]
The domain decomposition chooses default values that have very poor performance, because it does not take into account that the box needs not be cubic. E.g. if you have a `[10, 10, 100]` box and 3 nodes, Espresso will use a `[3, 1, 1]` node grid thus using `[3.33, 10, 100]` local boxes instead of the much saner `[10,10, 33]` and a `[1, 1, 3]` node grid.

**Comment by hirschsn** [comment]
`MPI_Dims_create` (which is currently used) cannot do that as the standard mandates that the output must be in descending order (and the dims themself as close to each other as possible). Also, sorting the `dims` array w.r.t. `box_l` is not a solution as you want `[1, 1, 9]` in your example for 9 processes and Dims_create gives you `[3, 3, 1]`.

As I needed exactly this functionality once, I wrote some greedy approximation code for it:
```c++
std::vector<int> prime_factors(int n) {
    std::vector<int> fs;
    for (int p = 2; n > 1; ++p)
        for (; n % p == 0; n /= p)
            fs.push_back(p);
    return fs;
}

std::array<int, 3> dims_create(int n, std::array<double, 3> box) {
    auto fs = prime_factors(n);

    std::array<int, 3> dims = {{1, 1, 1}};
    // Greedy algorithm
    // Need to assign largest values first in order for the greedy algorithm
    // to work. No need to sort, the result of prime_factors() is sorted.
    std::for_each(std::rbegin(fs), std::rend(fs), [&dims, &box](auto f) {
        auto i = std::distance(std::begin(box), std::max_element(std::begin(box), std::end(box)));
	box[i] /= f;
	dims[i] *= f;
    });

    return dims;
}
```

Greedy does *not* find the optimal solution for every number of processes, but it is usually good enough. OpenMPI, for example, uses it. (In just 3d you can also go ahead do an exhaustive search for the best partitioning.)

The code above will give you `[1, 1, 9]` for a 9 processes on a box of `[10, 10, 100]`.

**Comment by jngrad** [comment]
Users can re-assign domain decomposition at any time with `system.cell_system.node_grid = [1, 1, 9]`. This is routinely used in production scripts. It is not possible to programmatically decide of an optimal domain decomposition because different methods impose a specific ordering. For example, FFT-based methods (electrostatics, magnetostatics) require descending order while lattice-based methods (walberla LB and EK) require ascending order.
