### ISSUE TITLE
ESPResSo cannot be built with cuda at icp

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1983]
gcc/cuda compiler incompatibilty?
[...]
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "7.0") 
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
-- Boost version: 1.58.0
[...]

[  2%] Building NVCC (Device) object src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o
/usr/include/c++/5/functional(78): error: class "Cell" has no member "result_type"
          detected during:
            instantiation of class "std::_Maybe_get_result_type<_Functor, void> [with _Functor=Cell]" 
(86): here
            instantiation of class "std::_Weak_result_type_impl<_Functor> [with _Functor=Cell]" 
(184): here
            instantiation of class "std::_Weak_result_type<_Functor> [with _Functor=Cell]" 
(264): here
            instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=Cell]" 
(283): here
            instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=Cell]" 
(399): here
            instantiation of class "std::reference_wrapper<_Tp> [with _Tp=Cell]" 
/home/weeber/espresso-dev/src/core/Cell.hpp(20): here

/usr/include/c++/5/functional(266): error: class "Cell" has no member "argument_type"
          detected during:
            instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=Cell]" 
(283): here
            instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=Cell]" 
(399): here
            instantiation of class "std::reference_wrapper<_Tp> [with _Tp=Cell]" 
/home/weeber/espresso-dev/src/core/Cell.hpp(20): here

/usr/include/c++/5/functional(267): error: class "Cell" has no member "first_argument_type"
          detected during:
            instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=Cell]" 
(283): here
            instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=Cell]" 
(399): here
            instantiation of class "std::reference_wrapper<_Tp> [with _Tp=Cell]" 
/home/weeber/espresso-dev/src/core/Cell.hpp(20): here

/usr/include/c++/5/functional(268): error: class "Cell" has no member "second_argument_type"
          detected during:
            instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=Cell]" 
(283): here
            instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=Cell]" 
(399): here
            instantiation of class "std::reference_wrapper<_Tp> [with _Tp=Cell]" 
/home/weeber/espresso-dev/src/core/Cell.hpp(20): here

4 errors detected in the compilation of "/tmp/tmpxft_000129d8_00000000-10_cuda_common_cuda.compute_52.cpp1.ii".
CMake Error at EspressoCuda_generated_cuda_common_cuda.cu.o.cmake:262 (message):
  Error generating file
  /home/weeber/es-builds/maxset/src/core/CMakeFiles/EspressoCuda.dir//./EspressoCuda_generated_cuda_common_cuda.cu.o

src/core/CMakeFiles/EspressoCuda.dir/build.make:905: recipe for target 'src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o' failed
make[2]: *** [src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o] Error 1
CMakeFiles/Makefile2:1286: recipe for target 'src/core/CMakeFiles/EspressoCuda.dir/all' failed
make[1]: *** [src/core/CMakeFiles/EspressoCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mkuron** [comment]
The real problem here is that we require CUDA 7.5, but the lowest version we test in CI is 8.0. There is a 7.5 Docker image available with CentOS, but it has an older GCC version.

We always thought that CUDA 7.5 should be sufficiently tested by the developers as we have that on our desktop machines, but evidently it is not -- the present issue was already introduced in #1197.

I think that once our desktop machines are upgraded to Ubuntu 18.04 in a few months, we should bump the minimum CUDA version to 8.0 as that is CI-tested. Of course, this means dropping support for Ubuntu 16.04 machines where the CUDA SDK was installed from the repository and not downloaded from Nvidia.
