### ISSUE TITLE
Constraint energy calculated from unfolded position

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1986]
Forces are calculated using the folded one. Is this difference intended?

**Comment by fweik** [comment]
No, shapes are only defined inside of the box.

**Comment by fweik** [comment]
Are you sure about this? If you look at https://github.com/espressomd/espresso/blob/14c9e4716f64894dbdcbd10c950b0feb1757440b/src/core/constraints.hpp#L40 that seems pretty folded to me.
