### ISSUE TITLE
ek_eof_one_species_x fails randomly

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2004]
It failed e.g. in PR #1991 although only documentation was touched:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/20865

This was already reported and closed in issue #1944
It appears to me that in the PR mentioned in #1944 in the ...x... Tests the width of the box was not modified as opposed to in the ...y... and ...z.... Tests.

**Comment by fweik** [comment]
~~It needs to be seeded.~~

**Comment by fweik** [comment]
@mkuron and me concluded that the limits are to low for float precision.
