### ISSUE TITLE
Python cannot import espressomd

### ISSUE THREAD

**Issue by tienp** [espressomd/espresso#2023]
Hi,

I followed the instructions to install ESPreSso and built it with no error:

[100%] Linking CXX shared library visualization_opengl.so
[100%] Built target visualization_opengl
Scanning dependencies of target espressomd
[100%] Built target espressomd
Scanning dependencies of target pypresso
[100%] Built target pypresso

However, when testing:
./pypresso
>>> import espressomd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tien/Apps/espresso/build/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: /home/tien/Apps/espresso/build/src/core/cluster_analysis/libcluster_analysis.so.4: undefined symbol: _ZNK5boost3mpi12communicatorcviEv

I tried to install it again and again, and each time it returned the same error. Could anyone tell me what should I do in this case?

Thank you in advance,

Tien Phan.

**Comment by hmenke** [comment]
This looks like either you don't have Boost MPI installed, or the headers you have for Boost MPI have a different version from the library you link to.  What does
```
ldd /home/tien/Apps/espresso/build/src/core/cluster_analysis/libcluster_analysis.so.4
```
report?  Do you see `not found` somewhere?

**Comment by tienp** [comment]
I did ldd as you suggested : 

ldd /home/tien/Apps/espresso/build/src/core/cluster_analysis/libcluster_analysis.so.4

linux-vdso.so.1 =>  (0x00007ffd77edb000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbc89339000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbc89030000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbc88e1a000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbc88a50000)
/lib64/ld-linux-x86-64.so.2 (0x00007fbc898ea000)

I didn't see any "not found"s. What do you think?

**Comment by vanadiuz** [comment]
Hi,
I have the same problem. I guess I've already spent about 20 hours on fruitless attempts to solve it! 
To the above, I can add that when trying to call a `./pypresso ./../samples/billard.py` the following is output: 

[cpk10:45960] *** Process received signal ***
[cpk10:45960] Signal: Segmentation fault: 11 (11)
[cpk10:45960] Signal code: Address not mapped (1)
[cpk10:45960] Failing at address: 0x8
[cpk10:45960] [ 0] 0   libsystem_platform.dylib            0x00007fff60008f5a _sigtramp + 26
[cpk10:45960] [ 1] 0   ???                                 0x0000000000000080 0x0 + 128
[cpk10:45960] [ 2] 0   libboost_mpi-mt.dylib               0x000000010e3b3759 _ZN5boost3mpi11environmentC2Eb + 73
[cpk10:45960] [ 3] 0   libEspressoCore.4.dylib             0x000000010ec72997 _Z8mpi_initv + 167
[cpk10:45960] [ 4] 0   _init.so                            0x000000010e3a6d74 init_init + 996
[cpk10:45960] [ 5] 0   Python                              0x000000010e0ed630 _PyImport_LoadDynamicModule + 150
[cpk10:45960] [ 6] 0   Python                              0x000000010e0ec3c4 import_submodule + 273
[cpk10:45960] [ 7] 0   Python                              0x000000010e0ebf99 load_next + 263
[cpk10:45960] [ 8] 0   Python                              0x000000010e0eb0d2 PyImport_ImportModuleLevel + 772
[cpk10:45960] [ 9] 0   Python                              0x000000010e0ceacc builtin___import__ + 124
[cpk10:45960] [10] 0   Python                              0x000000010e05c160 PyObject_Call + 97
[cpk10:45960] [11] 0   Python                              0x000000010e0dbe1c PyEval_CallObjectWithKeywords + 159
[cpk10:45960] [12] 0   Python                              0x000000010e0d7185 PyEval_EvalFrameEx + 15244
[cpk10:45960] [13] 0   Python                              0x000000010e0d33e2 PyEval_EvalCodeEx + 1562
[cpk10:45960] [14] 0   Python                              0x000000010e0d2dc2 PyEval_EvalCode + 32
[cpk10:45960] [15] 0   Python                              0x000000010e0e9bd5 PyImport_ExecCodeModuleEx + 212
[cpk10:45960] [16] 0   Python                              0x000000010e0ec8fa load_source_module + 1047
[cpk10:45960] [17] 0   Python                              0x000000010e0ecb8e load_package + 328
[cpk10:45960] [18] 0   Python                              0x000000010e0ec3c4 import_submodule + 273
[cpk10:45960] [19] 0   Python                              0x000000010e0ebf99 load_next + 263
[cpk10:45960] [20] 0   Python                              0x000000010e0eb089 PyImport_ImportModuleLevel + 699
[cpk10:45960] [21] 0   Python                              0x000000010e0ceacc builtin___import__ + 124
[cpk10:45960] [22] 0   Python                              0x000000010e05c160 PyObject_Call + 97
[cpk10:45960] [23] 0   Python                              0x000000010e0dbe1c PyEval_CallObjectWithKeywords + 159
[cpk10:45960] [24] 0   Python                              0x000000010e0d7185 PyEval_EvalFrameEx + 15244
[cpk10:45960] [25] 0   Python                              0x000000010e0d33e2 PyEval_EvalCodeEx + 1562
[cpk10:45960] [26] 0   Python                              0x000000010e0d2dc2 PyEval_EvalCode + 32
[cpk10:45960] [27] 0   Python                              0x000000010e0f47ab run_mod + 49
[cpk10:45960] [28] 0   Python                              0x000000010e0f4852 PyRun_FileExFlags + 130
[cpk10:45960] [29] 0   Python                              0x000000010e0f43d4 PyRun_SimpleFileExFlags + 706
[cpk10:45960] *** End of error message ***
Segmentation fault: 11

Unlike tienp, I do not have the file "libcluster_analysis.so.4"! But in the "brew list" shows the following: boost		cmake		gcc		isl		mpfr		openssl		readline
boost-mpi	cython		gdbm		libevent	numpy		python		sqlite
boost-python	fftw		gmp		libmpc		open-mpi	python@2	xz

Please, help 😭

**Comment by vanadiuz** [comment]
The problem was on my side with openmpi!
1) To solve it, I had to achieve output like "Your system is ready to brew." to call "brew doctor"
2) reinstall espresso

**Comment by tienp** [comment]
Hi Ivan,

So you solved the problem? I installed espresso on Ubuntu 16.04 and CentOS as well.  Each case it reported no errors, but when I imported espressomd it returned similar error. Below is the error on the CentOS:

>>> import espressomd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/minhtien/Apps/espresso/build/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: /homes/minhtien/Apps/espresso/build/src/core/accumulators/libAccumulators.so.4: undefined symbol: _ZN5boost7archive23basic_binary_oprimitiveINS0_15binary_oarchiveEcSt11char_traitsIcEE4saveERKSs

I have no ideas about this! 😭

**Comment by hmenke** [comment]
I tried to reproduce your problem in our Cent OS 7 build container but was unsuccessful.  Here are my steps
```
~ $ git clone https://github.com/espressomd/espresso
~ $ cd espresso/
~/espresso $ mkdir build
~/espresso $ cd build
~/espresso/build $ cp ../maintainer/configs/maxset.hpp myconfig.hpp
~/espresso/build $ module load mpi
~/espresso/build $ cmake ..
~/espresso/build $ make -j 16
~/espresso/build $ ./pypresso
```
```python
>>> import espressomd
>>> system = espressomd.System(box_l=[1]*3)
>>> system.cell_system.skin = 0.1
>>> system.time_step = 0.01
>>> system.part.add(pos=[.5]*3,v=[0,0,.001])
<espressomd.particle_data.ParticleHandle object at 0x7f8b16d844e0>
>>> system.integrator.run(10)
>>> print(system.part[0].pos)
[ 0.5     0.5     0.5001]
```
I even tried to `module unload mpi` but not even that raised the error.
Maybe you are lacking packages.  You can take a look at the Docker file to see which packages we install: https://github.com/espressomd/docker/blob/master/docker/centos/Dockerfile

**Comment by vanadiuz** [comment]
tienp, yes, I solved the problem. But I also tried to install everything on ubuntu 18.04. Follow the steps from the instructions (sudo apt install build-essential cmake cython python-numpy \
libboost-all-dev openmpi-common) the espresso is not compiled. 💁‍♂️

**Comment by vanadiuz** [comment]
Dear Henri, 
Is it true that pypresso is installed only with the second version of the python (concluded from your Docker file)? If YES, then can I write my scripts on Python3 and launch them in pypresso? 🤓

**Comment by hmenke** [comment]
There are many different build environments for Espresso based on Docker images.  If you want to build Espresso using Python 3 on Ubuntu, take a look here for which packages you need: https://github.com/espressomd/docker/blob/master/docker/ubuntu-python3/Dockerfile
This is guaranteed to build and run, because it is tested automatically on [Travis CI](https://travis-ci.org/espressomd/espresso/jobs/390671049).

**Comment by tienp** [comment]
Hi Henri,

I just installed espresso in my home directory on the university's cluster with CentOS 7. Looking at the docker, I am quite sure that I loaded all the required modules from the instructions but unsuccessfully installed espresso. Are there any ways that we can know which packages are lacking because espresso was installed with no errors?

**Comment by KaiSzuttor** [comment]
Could you please paste the commands you perform to build espresso?

**Comment by tienp** [comment]
Here are the commands:
```
(my_root) [minhtien@eos Apps]$  git clone https://github.com/espressomd/espresso
(my_root) [minhtien@eos Apps]$ cd espresso
(my_root) [minhtien@eos espresso]$ mkdir build && cd build
(my_root) [minhtien@eos build]$ cp ../src/core/myconfig-default.hpp myconfig.hpp
(my_root) [minhtien@eos build]$ cmake .. -DBUILD_SHARED_LIBS=ON -DFFTW3_INCLUDE_DIR="/opt/software/software/FFTW/3.3.6-gompi-2017beocatb/include" -DFFTW3_LIBRARIES="/opt/software/software/FFTW/3.3.6-gompi-2017beocatb/lib/libfftw3.so"
```
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- Config file: /homes/minhtien/Apps/espresso/build/myconfig.hpp
-- Performing Test result__PRETTY_FUNCTION__
-- Performing Test result__PRETTY_FUNCTION__ - Success
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
-- Found PythonInterp: /homes/minhtien/.conda/envs/my_root/bin/python (found version "3.6.5")
-- Found Cython version 0.28
-- Found Cython: /homes/minhtien/.conda/envs/my_root/bin/cython (Required is at least version "0.23")
-- Found NumPy: /homes/minhtien/.conda/envs/my_root/lib/python3.6/site-packages/numpy/core/include (found version "1.12.1")
-- NumPy ver. 1.12.1 found (include: /homes/minhtien/.conda/envs/my_root/lib/python3.6/site-packages/numpy/core/include)
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /homes/minhtien/.conda/envs/my_root/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/homes/minhtien/.conda/envs/my_root/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.1", minimum required is "1.8") found components:  C
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- Checking for module 'scafacos'
--   No package 'scafacos' found
-- Found GSL: /opt/software/software/GSL/2.4-GCCcore-7.2.0/include (found version "2.4")
-- Found MPI_C: /homes/minhtien/.conda/envs/my_root/lib/libmpich.so;/homes/minhtien/.conda/envs/my_root/lib/libopa.so;/homes/minhtien/.conda/envs/my_root/lib/libmpl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so
-- Found MPI_CXX: /homes/minhtien/.conda/envs/my_root/lib/libmpichcxx.so;/homes/minhtien/.conda/envs/my_root/lib/libmpich.so;/homes/minhtien/.conda/envs/my_root/lib/libopa.so;/homes/minhtien/.conda/envs/my_root/lib/libmpl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   mpi
--   serialization
--   filesystem
--   system
--   unit_test_framework
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot
-- Found Sphinx: /homes/minhtien/.conda/envs/my_root/bin/sphinx-build (found suitable version "1.7.5", minimum required is "1.6.6")
-- writing /homes/minhtien/Apps/espresso/build/myconfig-sample.hpp
-- The following OPTIONAL packages have been found:

 * FFTW3
 * HDF5 (required version >= 1.8)
 * Git
 * PkgConfig
 * GSL
 * Doxygen
 * Sphinx (required version >= 1.6.6)

-- The following REQUIRED packages have been found:

 * PythonInterp
 * Cython (required version >= 0.23)
 * NumPy
 * MPI
 * Boost (required version >= 1.53.0)

-- The following OPTIONAL packages have not been found:

 * CUDA (required version >= 7.0)

-- Configuring done
-- Generating done
-- Build files have been written to: /homes/minhtien/Apps/espresso/build
```
```
make - j 10
...
[100%] Linking CXX shared library visualization_opengl.so
[100%] Built target visualization_opengl
Scanning dependencies of target espressomd
[100%] Built target espressomd
Scanning dependencies of target pypresso
[100%] Built target pypresso

(my_root) [minhtien@eos build]$ ./pypresso
>>> import espressomd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/minhtien/Apps/espresso/build/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: /homes/minhtien/Apps/espresso/build/src/core/accumulators/libAccumulators.so.4: undefined symbol: ompi_mpi_cxx_op_intercept
>>>
```
BTW, the modules were loaded on CentOS 7 before building:
```
(my_root) [minhtien@eos build]$ module list

Currently Loaded Modules:
  1) bzip2/1.0.6-GCCcore-7.2.0       8) Python/2.7.13-foss-2017beocatb               15) gompi/2017beocatb                                  22) GCCcore/7.2.0
  2) ncurses/6.0-GCCcore-7.2.0       9) Boost/1.63.0-foss-2017beocatb-Python-2.7.13  16) binutils/2.29-GCCcore-7.2.0                        23) Szip/2.1.1-GCCcore-7.2.0
  3) libreadline/7.0-GCCcore-7.2.0  10) GROMACS/2016.4-foss-2017beocatb-hybrid       17) GCC/7.2.0-2.29                                     24) HDF5/1.8.19-foss-2017beocatb
  4) Tcl/8.6.7-GCCcore-7.2.0        11) FFTW/3.3.6-gompi-2017beocatb                 18) OpenBLAS/0.2.20-GCC-7.2.0-2.29                     25) CMake/3.9.5-GCCcore-7.2.0
  5) SQLite/3.20.1-GCCcore-7.2.0    12) numactl/2.0.11-GCCcore-7.2.0                 19) ScaLAPACK/2.0.2-gompi-2017beocatb-OpenBLAS-0.2.20  26) GSL/2.4-GCCcore-7.2.0
  6) GMP/6.1.2-GCCcore-7.2.0        13) hwloc/1.11.7-GCCcore-7.2.0                   20) foss/2017beocatb                                   27) Anaconda3/5.0.1
  7) libffi/3.2.1-GCCcore-7.2.0     14) OpenMPI/2.1.1-GCC-7.2.0-2.29                 21) zlib/1.2.11-GCCcore-7.2.0

```

I have spent some days working on this, so any advice and suggestions will be greatly appreciated.

**Comment by mkuron** [comment]
Your problem is that it is picking up MPI from Anaconda (`Found MPI_C: /homes/minhtien/.conda/envs/my_root/lib/libmpich.so;/homes/minhtien/.conda/envs/my_root/lib/libopa.so;/homes/minhtien/.conda/envs/my_root/lib/libmpl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so`), while your Boost library was likely compiled against OpenMPI (cf. `ompi_mpi_cxx_op_intercept`). Please delete your Anaconda Python installation and load the Python module provided by your compute cluster.

**Comment by tienp** [comment]
That makes sense. So I start from scratch again, I unload Anaconda3, rebuild espresso and it works like a charm 👍. I think the same problem happened with my Ubuntu 16.04 box, I also used Anaconda python when building, it picked up MPI from Anaconda and messed things up. I thought it was great if I was able to use jupyter notebook with espresso. 😏

Thanks all.

**Comment by mkuron** [comment]
You can still use jupyter if you install the necessary packages from the Ubuntu/CentOS repository.

You might also be able to install Boost from the Anaconda repository so it ties in with Anaconda's MPI version. Don't do that on the compute cluster though as Anaconda's MPI will not be optimized for the cluster interconnect.

**Comment by vanadiuz** [comment]
Dear friends,

tell me please, what should I do, I installed an espresso with a python3 on the local computer and wrote my own script. Now it's time to run it on the cluster with mpi. But the fact is that there are not enough packets on the cluster to assemble the espresso with the python3 (and I'm not a root). After a day of torment, I  stumbled upon the anaconda. But you write that it will not working. 💁‍♂️

p.s. cluster on centos7 with slurm

**Comment by mkuron** [comment]
You can actually use Anaconda, but make sure it does not install any MPI or Boost packages.

Alternatively you could use the system Python and install any missing packages via pip (`pip3 install --user numpy` etc.).

**Comment by tienp** [comment]
I think you first use `module avail` to see all the modules installed on your cluster, then `module load` the requirements for `espresso`. In my case, I loaded `FFTW3, HDF5, GSL, Sphinx` and it worked. We don't usually have `root` permission on cluster but if you like Anaconda you can use `virtualenv` to create a virtual environment and use `conda` to install all requirement packages.

**Comment by KaiSzuttor** [comment]
actually you dont need sphinx nor hdf5 nor gsl to compile espresso if you dont want to use h5md or to build the documentation.

**Comment by vanadiuz** [comment]
Many thanks for your answers! 👍🏻
At some point, I just started to sort through dozens of different combinations of packages and I eventually found the right one 😀. I also tried the anaconda, but nothing happened. Most importantly, it's boost and mpi!

**If someone is dealing with VSC3, then here's what I got:**
```
0. ln -s /opt/sw/x86_64/glibc-2.17/ivybridge-ep/python/3.6.4/gcc/7.2/bin/python3 /home/lv70806/Vania/python
1. module load gcc/5.3 intel-mpi/2017 python/2.7 boost/1.62.0
2. module unload python/2.7 gcc/5.3
3. module load gcc/7.2 intel-mkl/2018 python/3.6 numpy/1.14.3 
4. module unload gcc/7.2
5. module load cmake/3.8.2
6. module load gcc/7.2.0 openmpi/2.0.2 fftw/3.3.7
7. module unload load gcc/7.2.0 openmpi/2.0.2
8. module load gcc/5.3
...
cmake .. -DBUILD_SHARED_LIBS=ON -DFFTW3_INCLUDE_DIR="/opt/sw/x86_64/glibc-2.17/ivybridge-ep/fftw/3.3.7/gcc/7.2.0/openmpi/2.0.2" -DFFTW3_LIBRARIES="/opt/sw/x86_64/glibc-2.17/ivybridge-ep/fftw/3.3.7/gcc/7.2.0/openmpi/2.0.2/lib/libfftw3.so

```
