### ISSUE TITLE
`system.part.bonds` cannot be pickled for Cython version < 0.26.0

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#2040]
Pickle `system.part[:].bonds` fails.

Example script:
```python
import espressomd
from espressomd.interactions import HarmonicBond
import pickle
 
system = espressomd.System(box_l=[5., 5., 5.])
harm = HarmonicBond(r_0=1., k=200.)
system.bonded_inter.add(harm)

system.part.add(pos=[1., 1., 1.], id=0, type=0)
system.part.add(pos=[2., 1., 1.], id=1, type=0)

system.part[0].add_bond((harm, 1))

pickle.dump({"bonds": system.part[:].bonds}, open("particle_bonds.dat", "w")) 
```
fails with
```
Exception: The constructor has to be called either with a bond id (as interger), or with a set of keyword arguments describing a new interaction
```

**Comment by pkreissl** [comment]
Was still working ~ two weeks ago.

**Comment by KaiSzuttor** [comment]
Works for me :/  Which pickle version do you use?
```python -c 'import pickle; print pickle.__version__'``` 
gives me
```
$Revision: 72223 $
```
Can you git-bisect and look which commit it was if it worked before?

**Comment by pkreissl** [comment]
Same version.

**Comment by pkreissl** [comment]
OK, `Cython` is the issue here. The minimal script above fails for Cython version 0.23.4.
After upgrading to version 0.28.3 and recompiling the issue disappears.

However, still a problem for those using a Cython version below the fixing 0.2X.Y <= 0.28.3.

**Comment by mkuron** [comment]
You can try `diff`ing the cpp files that the two Cython versions generate. We can probably find a workaround for whatever wrong code the old version is generating.

**Comment by KaiSzuttor** [comment]
i’d have to look it up but i think that they introduced some kind of autogenerated pickle functions at some point. I think thats the reason.

**Comment by fweik** [comment]
What @KaiSzuttor is saying: We came across this before. The solution is to add get the missing functions to the class (or do increase the required cython version). https://github.com/cython/cython/pull/1708

**Comment by KaiSzuttor** [comment]
Thanks @fweik for looking up the reference. I think we excluded the second solution last time since we want checkpointing to work on standard ubuntu 16 installations to work.

**Comment by pkreissl** [comment]
This would mean requiring Cython>=0.26.0.
The default cython version in the current Ubuntu 18.04LTS release is 0.26.1-0.4 according to [ubuntu.com](https://packages.ubuntu.com/bionic/cython). However, I agree with Kai.

**Comment by mkuron** [comment]
We should keep Ubuntu 16.04 support at least until the end of this year. Ubuntu 16.04 won't offer to automatically upgrade to 18.04 until six months after release. Add a few more months to give people time to do the upgrade. Not sure how popular Ubuntu is on compute clusters, but they are probably not affected as they tend to provide separate Python environments.

**Comment by KaiSzuttor** [comment]
@pkreissl  please try to find out which class is lacking proper ```__setstate__``` /``` __getstate__ ```methods.

**Comment by RudolfWeeber** [comment]
On Tue, Jun 26, 2018 at 08:11:48AM -0700, Michael Kuron wrote:
> We should keep Ubuntu 16.04 support at least until the end of this year. Ubuntu 16.04 won't offer to automatically upgrade to 18.04 until six months after release. Add a few more months to give people time to do the upgrade. Not sure how popular Ubuntu is on compute clusters, but they are probably not affected as they tend to provide separate Python environments.
A more relaxed take would be to support 16.04 until the release.

**Comment by mkuron** [comment]
You need to implement a `__reduce__` function and an unpickle function that returns/reads the class's `__dict__`, see https://github.com/cython/cython/pull/1708/files#diff-28c66ef9e2ff564619ef82aa9d72ee7dR1611. So far, there is only one place in Espresso where that is done: https://github.com/espressomd/espresso/pull/1701/files#diff-7ccfd5af256520586f57265d72d5e300R246

**Comment by KaiSzuttor** [comment]
You dont have to use the reduce syntax, afaik. The standard ```__getstate__``` /```__setstate__``` syntax is fine for most of the cases and easier to read, IMO.

**Comment by KaiSzuttor** [comment]
@fweik the "meta-question" is rather if we want to refactor the whole bonded interactions in the core and get a less ugly interface code then which is in turn easier to write checkpointing for.

**Comment by fweik** [comment]
You mean like #1224?

**Comment by KaiSzuttor** [comment]
uh yeah, totally forgot

**Comment by KaiSzuttor** [comment]
@pkreissl any success here? If not, we should have a look next week.

**Comment by pkreissl** [comment]
I am afraid not yet. I might have another look at it tomorrow. Otherwise let's talk on monday.

**Comment by KaiSzuttor** [comment]
btw, it seems to work if you use the latest pickle protocol (-1)

**Comment by mkuron** [comment]
Are you using Python 2 or 3? Python 2 defaults to protocol 0 and uses protocol 2 if you specify `protocol=-1`. Python 3 defaults to protocol 3. Python 3.4 and higher use protocol 4 if you specify `protocol=-1`.

**Comment by mkuron** [comment]
Are you using Python 2 or 3? Python 2 defaults to protocol 0 and uses protocol 2 if you specify `protocol=-1`. Python 3 defaults to protocol 3. Python 3.4 and higher use protocol 4 if you specify `protocol=-1`.

From your `pickle.__version__`, I guess it's Python 2. The important bit in [PEP 307](https://www.python.org/dev/peps/pep-0307/#case-2-pickling-new-style-class-instances-using-protocols-0-or-1) is probably:

> **Case 2: pickling new-style class instances using protocols 0 or 1**
> New-style classes, whether implemented in C or in Python, inherit a default `__reduce__` implementation from the universal base class 'object'.
> [...]
> The default `__reduce__` implementation will fail at pickling time [...] for new-style classes implemented in C: if they want to be picklable, they must supply a custom `__reduce__` implementation under protocols 0 and 1.
>
> **Case 3: pickling new-style class instances using protocol 2**
> Under protocol 2, the default `__reduce__` implementation inherited from the 'object' base class is ignored. Instead, a different default implementation is used, which allows more efficient pickling of new-style class instances than possible with protocols 0 or 1, at the cost of backward incompatibility with Python 2.2 (meaning no more than that a protocol 2 pickle cannot be unpickled before Python 2.3).
> The customization uses three special methods: `__getstate__`, `__setstate__` and `__getnewargs__` (note that `__getinitargs__` is again ignored). It is fine if a class implements one or more but not all of these, as long as it is compatible with the default implementations.

**Comment by KaiSzuttor** [comment]
thats the reason why it works with the checkpointing module. I think we can close this issue.

**Comment by pkreissl** [comment]
I used Python 2 here.
