### ISSUE TITLE
Rs mesh overflow warning

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2067]
1: rs_mesh overflow! (pos 5.000000, nmp=17)
1: allowed coordinates: 2.500000 - 5.000000

In coulomb_mixed_periodicity test with p3m+elc when node grid is manually sorted correctly.

Is there really an overflow or is the condition for the warning too broad

**Comment by fweik** [comment]
This is related to the particle sorting. In the past there was some ambiguity there, which may be the cause of this problem (p3m assuming an open right border vs dd assuming some tolerance). This will potentially go away with #1923, which consistently chooses the local boxes an removes the tolerance.

**Comment by RudolfWeeber** [comment]
The resort refactor was merged. Closing
