### ISSUE TITLE
Update CI Docker images

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#2068]
Before the release, we need to add Docker images and CI testing for some recent Linux distributions to ensure that Espresso 4.0 runs properly on all our users' machines:
- debian:stretch
- opensuse/leap:15.0
- ubuntu:bionic
- nvidia/cuda:9.0-devel-ubuntu16.04

The ubuntu-clang-cuda image should be upgraded to Clang 6.0, which is available in the xenial-updates repository and has better static analysis. The ubuntu-python3 image should be rebased on ubuntu:bionic which has Python 3.6. The ubuntu-intel image should be duplicated to also test Intel 2018.

We can drop debian:jessie as that has recently moved to long-term support and is pretty similar to Ubuntu 14.04 which we test CUDA 8.0 on. All the other distributions that we currently have are still supported and widely used, so we'll end up with a few more CI jobs.

#883 requested an image with address sanitizer enabled, which requires rebuilding Python. Maybe I can also take care of that one while I'm at it.

Please assign this ticket to me for the QA day.

**Comment by RudolfWeeber** [comment]
furthermore, the pull url for scafacos should be changed to
github.com/scafacos/scafaocs --branch dipoles
and the now exposed flag for availability fo dipolar methods included in the configuration logic.

**Comment by mkuron** [comment]
`--enable-fcs-dipoles`
