### ISSUE TITLE
Low test coverage: Candidates for downgrade or removal

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2071]
This ticket lists parts of Espresso that do not have (sufficient)
tests. 
These parts will likely be marked to require
#define EXPERIMENTAL_FEATURES
in myconfig.hpp, or they may be removed, if the situation persists.

As per https://codecov.io/gh/espressomd/espresso/tree/python/src/core

Potential users/developers/authors are mentioned, below

Accumulators/Correlator.cpp:
* several of the compression functions are untested

Electrostatic interactions:
elc (some 200 lines) @konradbreitsprecher
dipolar direct sum (with replica) (@RudolfWeeber)

Immersed boundary method (@sgekle):
The volume conservation part is entirely untested.
For the bonded interactions, the equations themselves are untested, but the correct minimum is verified.
See also #2305

object-in-fluid @icimrak 
* out_direction
* membrane collision (See also #2214)
* affinity
* For the volume and surface conservation forces, the explicit expressions are not tested, but the restoration of a distorted sphere is checked.
See also #2305

shapes 
stomatocyte (@jdgraaf)
half of rhomboid, hollowcone, slit_pore

Other:
Galilei transform
communication.cpp (200 lines. These are probably more indications of other stuff not being tested)
statistics.cpp (200 lines)
~~metadynamics (no Py interface)~~
spec_func (some 100 lines)

**Comment by KaiSzuttor** [comment]
codecov is currently not updating the coverage...

**Comment by KaiSzuttor** [comment]
thanks @mkuron

**Comment by mkuron** [comment]
@KaiSzuttor, seems like they changed the IP addresses used. I've updated our firewall rules now, so we should be getting coverage reports again.

Also, our coverage reports for the python branch are wrong. We don't mirror it to Gitlab, so it only gets coverage results from the maxset build (from the documentation deployment) and from Travis. Could you change that to mirror all branches to Gitlab?

**Comment by KaiSzuttor** [comment]
i don't quite get what you mean. We have not only the maxset build reporting to codecov, but also e.g. no_cuda_default

**Comment by jonaslandsgesell** [comment]
This issue got closed automatically while merging. I guess we want to reopen it.

**Comment by jonaslandsgesell** [comment]
mmm1d is tested as of merging of PR #2893

**Comment by Kischy** [comment]
I would hate to see the Gay-Berne potential removed. Who is allowed to contribute? If I am allowed to contribute, do you have guidelines for contributions?

**Comment by jonaslandsgesell** [comment]
You can create a pull request which implements the removal of the Gay-Berne potential. This is then reviewed and if approved it is merged.

Do you have some arguments why you want the interaction to be removed? Is it broken and can't be fixed? Do you plan an alternative implementation?

**Comment by Kischy** [comment]
I said, that "I would hate to see it removed". By this I meant, that I do **not** want it to be removed. Sorry for the unclear statement.

**Comment by jonaslandsgesell** [comment]
Sorry I misread your comment. It is best if you could contribute a test for the forces like the tests for the lennard-jones interaction. You can create a pull request which is the reviewed and merged.

**Comment by Kischy** [comment]
Okay, I'll look into it.

**Comment by fweik** [comment]
@jonaslandsgesell I think you misread @Kischy 's message, He does *not* want to have it removed.
On the subject: the plan is not to remove Gay-Berne, but rather improve it's testing and documentation.
Everybody is welcome to contribute to the project, and pull requests are very welcome. To contribute
you would create your own fork of Espresso, make your changes and then open a pull request against
this repository. On the topic of adding tests you can find documentation [in the wiki](https://github.com/espressomd/espresso/wiki/Testing). If you need further assistance you are also welcome to either open an issue here with our question, or contact somebody from the team like @jngrad or me via email.

**Comment by Kischy** [comment]
Okay, thank you.

**Comment by fweik** [comment]
I've opened the issue #2922 for Gay-Berne, if you have any questions don't hesitate to post there.

**Comment by Kischy** [comment]
Thanks.

**Comment by jngrad** [comment]
Updated version of the original post, which was written before the 4.0 release. We are currently working on 4.2.0 and 4.3.0.

This ticket lists parts of Espresso that do not have (sufficient) tests. Some of them have been removed, others have been marked with `#define EXPERIMENTAL_FEATURES` in myconfig.hpp.

- accumulators/correlators:
   - all accumulation/correlation methods are tested in 4.1.3
   - their script interface is well tested in 4.1.3 and fully tested in 4.2
   - their compression functions are tested in 4.2
- electrostatic/magnetostatic interactions:
   - ELC
      - coverage has increased, although more test cases are needed
      - ELC was disabled for non-neutral systems with dielectric contrast in 4.1
   - dipolar direct sum with replica was disabled for 0 replica in 4.2
   - `magnetic_non_p3m_methods.cpp` has 98% coverage in 4.2
   - MMM1D on GPU is tested in 4.2
- immersed boundary method (IBM)
   - `src/immersed_boundary` has 98% coverage in 4.2
   - the volume conservation part is tested in 4.2
   - for the bonded interactions, the equations themselves are untested, but the correct minimum is verified.
   - See also #2305
- object-in-fluid (OIF)
   - `out_direction`, `membrane collision` and `affinity` were removed in 4.2
   - For the volume and surface conservation forces, the explicit expressions are not tested, but the restoration of a distorted sphere is checked.
   - See also #2305
- shapes
   - `Stomatocyte` was removed in 4.2
   - `Hollowcone` was replaced in 4.2 by `HollowConicalFrustum`
   - `Rhomboid` 100% coverage in 4.1
   - `Slitpore` 100% coverage in 4.1.3
   - `shapes/src` has 99% coverage in 4.2
- others
   - `galilei.cpp`: 92% coverage in 4.1, 100% in 4.2
   - `communication.cpp`: 94% coverage in 4.1, 100% coverage in 4.2
   - `statistics.cpp`: 95% coverage in 4.2
      - duplicated features were removed in 4.2
      - `RDF` and `Observable_stat` were moved to dedicated files in 4.2
      - structure factor was refactored and fully tested in 4.2
   - `metadynamics.cpp`: removed in 4.2
   - `electrostatics_magnetostatics/specfunc.{cpp,hpp}`: only 50 lines remain untested (Chebychev series)
   - `reaction_ensemble.{cpp,hpp}`: 91% coverage in 4.2, unit tested

**Comment by jngrad** [comment]
All features mentioned in the original post have either reached a satisfactory C++ code coverage level, or have been removed.

![Plot showing the progression of code coverage as a function of time since July 2018. The curve branches out at every minor release and all bugfix releases are labeled. The coverage is 95.5% for 4.2-dev in June 2021, 87% for 4.1.4 and 70% for 4.0.2](https://user-images.githubusercontent.com/42201407/123310245-291a6000-d526-11eb-8718-3ee0cd2d6ae5.png)

There are a few minor points remaining, but they should not be an obstacle to the development of ESPResSo:
* the lack of energy contribution for IBM/OIF is documented in a separate ticket and no longer crashes simulations
* the untested Chebychev series code in `electrostatics_magnetostatics/specfunc.{cpp,hpp}` is not compiled in CI
* the reaction ensemble code coverage will go from 91% to almost 100% when we remove the Wang-Landau algorithm

From my side, this ticket can be closed.
