### ISSUE TITLE
QA Day: Samples

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2089]
* Check that all samples run with the current Espresso
* Put doc strings at the top of the sample files explaining what they do
* Put a list of required Espresso features in the samples and check for them

required_features = []
espressomd.assert_features(required_features)

**Comment by KaiSzuttor** [comment]
the samples are not in the best shape I think... maybe we should have a look at some point

**Comment by jngrad** [comment]
- [x] Check that all samples run with the current Espresso
   * the tests ensure they can always run, except lj-demo.py where the python dependencies are broken in Ubuntu 18.04 and the thermostat is not working properly
- [ ]  Put docstrings at the top of the sample files explaining what they do
   * I will take care of that and find a way to remove the out-of-date duplication in [introduction.rst](http://espressomd.org/html/doc4.1.0/introduction.html#sample-scripts)
- [x] Put a list of required Espresso features in the samples and check for them
   * already in place

I can also do some code cleanup, there are many unused imports/functions/variables that most likely originate from copy-pasting, and some samples could use `argparse`.
