### ISSUE TITLE
QA Day: Check tutorials with IPy

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2093]
Check usage of tutorials with IPY Notebooks and adapt to current syntax
There are pull requests for Tutorial 1-5

**Comment by RudolfWeeber** [comment]
Save sample output and corresponding parameters / calls in preparation for automatic testing

**Comment by RudolfWeeber** [comment]
Add feature check to tutorials

required_features = []
espressomd.assert_features(required_features)

**Comment by jonaslandsgesell** [comment]
Regarding ci testing: I would only check for runnability not for the results of the tutorials. There should be faster tests for each command that is used in the tutorials in the testsuite. Keep in mind that tutorials are meant to reproduce physics which may require long sampling. Therefore tutorials (if not shortened explicitly for runnability tests) are not well suited as a test case.

**Comment by jonaslandsgesell** [comment]
I found PRs 
#1605
#1654
#1603
#1572 
related to ipy. Checking for those

**Comment by RudolfWeeber** [comment]
@jonaslandsgesell, could you please report back on this.
For those tutorials, that are ready, please approve the corresponding pull requests.
For the others, please mention what is missing
Thanks

**Comment by jonaslandsgesell** [comment]
Miru, Ashreya and Cameron are testing runnability again.

**Comment by iammmiru** [comment]
Tut4ipy is running and pushed and fine.
Tut2ipy and 5ipy are running and pushed and fine.

**Comment by ashreyaj** [comment]
Tutorial 1 runs

**Comment by jonaslandsgesell** [comment]
I approved the PRs from above. There are some random testcase crashes, which look unrelated to the changes introduced here. Are the testcases stable?

**Comment by RudolfWeeber** [comment]
Tutorials 2 and 5 still have scripts/ folders. Is that really intended?

**Comment by jonaslandsgesell** [comment]
Yes there were references to scripts which were doing stuff not handled
more explicitly in the old tutorials.

RudolfWeeber <notifications@github.com> schrieb am Di., 7. Aug. 2018, 18:57:

**Comment by jonaslandsgesell** [comment]
Please close here
