### ISSUE TITLE
QA Day: Prepare build system for IPy tutorials

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2094]
Some tutorials will stay Latex/PDF in 4.0.
Preparations for automatic testing of IPy tutorials

**Comment by jonaslandsgesell** [comment]
That is a priority. Otherwise we will have diverging tutorials very soon again. I would only check for runnability - Not for results.

**Comment by KaiSzuttor** [comment]
I think cmake was meant, not CI

**Comment by hmenke** [comment]
I have done this before in pairinteraction.  We are also testing our tutorials in the CI for which we use `ipython nbconvert`.  This is added to the CMake tests and will then run when `make check` is called.
https://github.com/hmenke/pairinteraction/blob/a9d03f5838f77bf6d6c845700460f6aaefdbba33/doc/sphinx/CMakeLists.txt#L109-L130

**Comment by RudolfWeeber** [comment]
Build stuff came in with the tutorial prs. Automatic checking comes later
