### ISSUE TITLE
Lb Stokes sphere test on CPU

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2097]

**Comment by RudolfWeeber** [comment]
De-milestoning for 4.0.1. Poisseulle flow tests boundaries on cpu.

**Comment by RudolfWeeber** [comment]
@jainka, the gpu test is in 
testsuite/python/lb_stokes_sphere_gpu.py
The resulting test for cpu and gpu lb should use a shared source file.
See testsuite/python/lb.py for an example of that. There, the test for the GPU and CPU are derived from the same base class and only a few parameters are updated.
The combined cpu+gpu tests should run in about 30 secs, probably the cpu system has to be a bit smaller than the gpu one to get that.
The current test checks against the stokes force in an infinite system, although a periodic system is modelled.

If you'd like to improve on that, I think, there is a literature result for the periodic system.

**Comment by RudolfWeeber** [comment]
https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/on-the-periodic-fundamental-solutions-of-the-stokes-equations-and-their-application-to-viscous-flow-past-a-cubic-array-of-spheres/F0F666CB13F9F4508FF24329E5589709

**Comment by jainka** [comment]
The test has been changed to run on both CPU and GPU.
The test file is now named **lb_stokes_sphere.py**

**Comment by KaiSzuttor** [comment]
issue can be closed since #2366 is merged
