### ISSUE TITLE
Polymer command should not default to start pos (0,0,0)

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2104]
for the 1st polymer it places.

-> Random or explicitly passsed

**Comment by fweik** [comment]
Shoud be mandatory. Explicit is better...

**Comment by kosovan** [comment]
What is wrong with the default (0,0,0)? In my opinion, this argument can be left optional - the list of required arguments for the polymer command is long enough already.

**Comment by RudolfWeeber** [comment]
If I read the code correctly, this does not only place the 1st particle on 0,0,0 but possible also the second on top of that on 0,0,0.
The default for the pos2 argument should be a nulptr but is 0,0,0.

@peterkosovan: Why the origin, why not the box center? Also several polymer commands in a single script (e.g., for polydisperse systems) silently create highly overlapped polymers by all starting at the origin. This is basically impossible to relax.

**Comment by KaiSzuttor** [comment]
+1 for explicit since there is no sensible default here
see https://softwareengineering.stackexchange.com/questions/63908/default-values-are-they-good-or-evil
