### ISSUE TITLE
Remove ghost shifts for DD and layered

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2137]
For the `domain_decomposition` and `layered` cell systems the positions of the ghosts are shifted from the real particles, so that they corresponds to the respective periodic replica. This has the benefit that
all minimum image distances can be calculated with the plain Euclidean norm, and there is no special
treatment at the boundaries needed.

Unfortunately this has also several drawbacks:
- Ghost particles that represent particle local to the node (when the node is its own periodic neighbour)
   need to be copies of the originals, so that their position can be shifted. This considerably affects single node performance, as in this case ghost layers in all directions have to be maintained only to apply the shift, where without the shift ghost communication would not be needed at all.
- The considerably complicates the implementation of Lees-Edwards boundary conditions, as in this case the shift depends on parameters that are subject to change and not only on geometry.
and others. We therefore decided to remove the shifts. This will cause a small performance
impact because the distance calculation gets more expensive, and this is a very hot function, but we belief that the benefits outweigh the costs.

**Comment by fweik** [comment]
Just an update on this: I managed to make the MD work without the ghost shifts (the ghosts_shits2 branch in my repository). Unfortunately the LB coupling relies on the ghost shifts, so this can't be done easily. We should really consider a rewrite.

**Comment by fweik** [comment]
Depends on #2287.

**Comment by RudolfWeeber** [comment]
Done.
