### ISSUE TITLE
Decide fate of twist stack interaction

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2143]
not interfaced, not tested, not documented

**Comment by fweik** [comment]
All the bonds related to the cg dna model can be removed. That is HYDROGEN_BOND, TWIST_STACK and COULOMB_DEBYE_HUECKEL. I did those, and they were never really validated, CBH is known to be broken. I'll maybe reintroduce them later, but if so I'd use a different approach.
