### ISSUE TITLE
CI should ignore [ci skip] for python branch

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2153]
Otherwise the docs are not deployed. Also may be ci skip is not a great idea at all.

**Comment by KaiSzuttor** [comment]
if you dont change documentation...

**Comment by fweik** [comment]
What is gained by not running the CI? I don't think users should be able to skip the CI under any circumstance. It's for catching the things that you did not think of...

**Comment by mkuron** [comment]
The head of the python branch should always be a merge commit without its own message. Also, the head of the python branch should always run CI so that the CI badge displays correctly.

**Comment by mkuron** [comment]
Also, ci skip is a Gitlab feature we can't turn off.

**Comment by fweik** [comment]
Apparently the CI is skipped even with the merge commit.

**Comment by fweik** [comment]
Well then there needs to be an other mechanism to deploy the docs no?

**Comment by KaiSzuttor** [comment]
@mkuron, isnt the skip implemented on webhook level?

**Comment by KaiSzuttor** [comment]
i just checked, we only filter the commit message for '[ci skip]' for the commit status since the build will not happen on gitlab ci and we would have a pending state forever.

**Comment by fweik** [comment]
I think this is not worth the effort.

**Comment by mkuron** [comment]
It seems like this is @KaiSzuttor's fault. Whenever he merges a pull request, its commit message is
> _pull request title_ (#_pull request number_)
> 
> * _first non-merge commit message_
> 
> * _second non-merge commit message_
> 
> * ...

which obviously preserves the `[ci skip]` into the merge commit.

Whenever anyone else merges a pull request, its commit message is
> Merge pull request #_pull request number_ from _user_/_branch_
> _pull request title_

which is the usual GitHub behavior.

It seems like this started at some point between July 30th and August 9th. @KaiSzuttor didn't merge any pull requests in the ten days between these dates, so I can't narrow down the cause further.

**Comment by mkuron** [comment]
Aha, it seems like @KaiSzuttor likes to use squash-merging. So there are two solutions to this problem: either he promises to always remove any `[ci skip]` from the commit message whenever he uses that feature, or @fweik can go to the project settings and under "Merge button", uncheck everything except for "Allow merge commits".

**Comment by KaiSzuttor** [comment]
we decided to not do anything here because it does happen so infrequently that we can manually trigger the CI.
