### ISSUE TITLE
Non-running script in tutorial 5

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2159]

**Comment by fweik** [comment]
The notebook does not run either, fails with
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/scratch/fweik/espresso/doc/tutorials/05-raspberry_electrophoresis/05-raspberry_electrophoresis.ipynb in <module>()
     88     {
     89      "cell_type": "code",
---> 90      "collapsed": false,
     91      "input": [
     92       "import espressomd\n",

NameError: name 'false' is not defined
```

**Comment by fweik** [comment]
`figures/raspberry_snapshot.png` is missing. There is only a pdf with that name.

**Comment by RudolfWeeber** [comment]
And a particle being electrophoresed should move, ideally.
At least, the virtual sites implementation needs to be set.
Also, the ext_force on the particle is multiplied with a global "charge"  variable. I think, this should be the charge of the respective particle?

**Comment by fweik** [comment]
One *could* use an `constraints.ConstantElectricField` now...
