### ISSUE TITLE
Documentation on id assignment and index in particle slices is wrong

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2161]
Please assign with the label python. Normal users cannot tag. This should probably be changed either.
@atagliabue

**Comment by fweik** [comment]
Can you please elaborate?

**Comment by atagliabue** [comment]
This sentences "Note that the index and the property ID are not necessarily the same." in espresso documentation (http://espressomd.org/html/doc/particles.html) is probably wrong?
 
AT

**Comment by RudolfWeeber** [comment]
On Mon, Aug 20, 2018 at 01:31:33PM +0000, atagliabue wrote:
> This sentences "Note that the index and the property ID are not necessarily the same." in espresso documentation (http://espressomd.org/html/doc/particles.html) is probably wrong?
Also, the particle id cannot be set at all, once the particle has been added.
