### ISSUE TITLE
Put static versions of tutorial on web page after release

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2162]
~/espresso-dev/doc/tutorials$ ipython nbconvert --to html --template full */*.ipynb

**Comment by fweik** [comment]
We should consider doing this automatically when the normal docs are deployed.

**Comment by RudolfWeeber** [comment]
Should not be difficult but probably needs an update of the docker container cuda8-maxset with ipython-nootbook package.

**Comment by RudolfWeeber** [comment]
Can be merged

**Comment by fweik** [comment]
@RudolfWeeber this should probably go somewhere else.

**Comment by RudolfWeeber** [comment]
Meant #2165
