### ISSUE TITLE
Lees Edwards interface 

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#2181]
@pdebuyl 
@fweik or @RudolfWeeber: Please add this to the Lees Edwards rewrite project.

After change to the get_mi_vector we should decide on the Lees Edwards interface. In the current version there are for protocols that can be used: off, step, steady shear, oscillatory shear. They are set the following:

```
system.lees_edwards = ['off']
system.lees_edwards = ['step', 0.1]
system.lees_edwards = ['steady_shear', 0.05]
system.lees_edwards = ['oscillatory_shear', 0.2, 0.8]
```

If a protocol is used without the correct number of arguments e.g. `system.lees_edwards = [off, 5.8]` a ValueError is raised. 

Do you agree on that?

**Comment by pdebuyl** [comment]
please add quotes to the strings (`'off'`, etc).

I'd add the the settings can roundtrip: the property `lees_edwards` returns always a list, with `['step', 0.1]` for the step case for instance.

**Comment by bindgens1** [comment]
First part: Done!

**Comment by pdebuyl** [comment]
thanks. I guess that we'll have to wait for 4.0 to be released before we receive feedback on the interface.

**Comment by pdebuyl** [comment]
@rempferg @fweik @bindgens1 can one of you allow me to assign labels to issues? a label "per feature" would be nice (here: "lees-edwards")

**Comment by fweik** [comment]
@pdebuyl unfortunately this can not be done on github without also granting permissions to the repository.

**Comment by pdebuyl** [comment]
This is done in both mine and Sebastian's lees_edwards_rebase branch, I consider this done :-)

See https://github.com/pdebuyl/espresso/blob/lees_edwards_rebase/samples/lees_edwards_vis.py for a sample simulation.

**Comment by bindgens1** [comment]
Everyone fine with closing this?
The final implementation works completely different so this doesn't seem relevant anymore.
