### ISSUE TITLE
Columnar Cell System

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#2183]
@pdebuyl 
@fweik or @RudolfWeeber: Please add this to the Lees Edwards rewrite project.

The columnar cell system was suggested by @RudolfWeeber and @fweik to circumvent issues with the changing Lees Edwards offset while integrating. 

The columnar cell system should be based on the regular domain composition cell system enforcing one cell in the x-direction.

**Comment by RudolfWeeber** [comment]
Offline discussion yielded that instead of a separate cell system, we will add a `fully_connected` property to domain decomposition.
If true for a given direction, this will designate all cells in a column as neighbors of all cells in the same column across the boundary.

**Comment by bindgens1** [comment]
I will file a pull request with the changes, so it can be merged independent of the rest.

**Comment by bindgens1** [comment]
Pull request 
Fully connected #2314

Merged
