### ISSUE TITLE
Sporadic failures in `system.analysis.rdf_chain`

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2187]
Can be found by repeatedly running the test case (`analyze_chains.py`). Error occurs about 1% of the time.

**Comment by fweik** [comment]
This is still valid after #2212. It is also not clear if the test is correct.

**Comment by RudolfWeeber** [comment]
rdfchains:
My tentative conclusions from looking at the core code:
* The center of mass calculation probably does not cope with polymers spanning the periodic boundaries under all conditions.
* The center of mass implementation (and maybe other parts of the code) do not seem to cope with particle coordinates outside the primay simulation box. There seems to be some kind of capping going on.
* There are no guards against distances within a single polymer being larger than box_l/2. In that case, the distance is not well defined.
* It is not clear to me whether the testcase can cope with particle coordiantes <0.
Probably, the code for center of mass and radius of gyration should be extracted from the cluster analysis and used in both places. It also needs to be checked whether the unfolding applied in partcfg has restrictios which might affect the results.

**Comment by fweik** [comment]
If this is correct the code should be removed and reimplemented on top of correct primitives extracted from the cluster analysis or elsewhere.

**Comment by RudolfWeeber** [comment]
We will remove the code for rdfchain from the release.
