### ISSUE TITLE
Style checking for merge broken

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2210]
Fails with unclear error:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/36002

**Comment by fweik** [comment]
@mkuron could you have a look? Also there were no automatic comments today on PRs that needed style fixes according to the CI.

**Comment by mkuron** [comment]
The bot definitely works, see https://github.com/espressomd/espresso/pull/2211#issuecomment-417438779. Probably those PRs hadn't merged the python branch in the last few days.

I can confirm though that it doesn't work on the Python branch. I'm preparing a fix right now.
