### ISSUE TITLE
Equation in the manual (Gay-Berne interaction) has a slight error

### ISSUE THREAD

**Issue by Kischy** [espressomd/espresso#2230]
[http://espressomd.org/html/doc4.0/inter_non-bonded.html#gay-berne-interaction](http://espressomd.org/html/doc4.0/inter_non-bonded.html#gay-berne-interaction)

There is a slight mistake in the fourth equation of this chapter:
The first part of the right side of the equation there is written as:

![grafik](https://user-images.githubusercontent.com/42995291/45094343-4bdfed80-b11b-11e8-949e-ddaa1f6f6c1c.png)

It should be

![grafik](https://user-images.githubusercontent.com/42995291/45094352-51d5ce80-b11b-11e8-8aa5-7580461406e2.png)

according to  J. G. Gay, J. Chem. Phys. 1981, 74, 3316. (equation 3 in this paper, also equation 8 of the paper).

The dot product is **squared** in the original equation.

In the code (gb.hpp) it seems to be correct.

Is this the right place to post this?

**Comment by fweik** [comment]
Yes, this is the right place. Thank you!
