### ISSUE TITLE
Coldet: vs based modes may place particles outside box

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2231]
Yet another corner case:
The vs are initailly placed at the position of one of the colliding particles, to put them in a valid cell for the node.
After all collision are handled, a reosrt occurs, which will put the vs in the correct cell on the correct node.

However: the colliding particle may itself be outside of the node domain by up to a skin.
A possible solution might be to place based on p.l.p_old, since the last verlet update definitely happened at a valid position for the current node.

**Comment by fweik** [comment]
Why can't you just put it into the same cell as the the colliding particle? The position should not matter.

**Comment by fweik** [comment]
Fixed by #2344.
