### ISSUE TITLE
Structure Factor Scaling Query

### ISSUE THREAD

**Issue by CompRhys** [espressomd/espresso#2232]
I was wondering what the reasoning behind the structure factor implementation as it is cubic-runtime in the order. I fully appreciate that I am not an expert but as the routine returns s(q) and not s(q,theta,phi) are we not implicitly assuming that s(q) and therefore the system is isotropic?

If we assume an isotropic system I think it should be possible to have a routine that is linear-runtime in order. Such a routine would simply evaluate the 1D structure factor along multiple directions in reciprocal space and then return an average for better statistics. The current routine samples below the information limit 2*pi/L  in the quasi-1D isotropic system.  

This averaging approach is what appears to have been done in this paper by Daan Frenkel

> Kranendonk, W.G.T. and Frenkel, D., 1988. Simulation of the adhesive-hard-sphere model. Molecular physics, 64(3), pp.403-424.

I am happy to try implement this but I want to make sure that I am not overlooking any additional added value the current routine provides.

**Comment by fweik** [comment]
No I can't see one either. I think the implementation is just inefficient. It's also not clear to me why
you would need an explicit calculation of the structure factor. You could also just do a FFT of the RDF I think.

**Comment by CompRhys** [comment]
I require an explicit calculation to avoid finite size effects imposed by the need to truncate g(r) in accordance with the minimum image convention that although are often negligible are significant sources of error for my investigation. The idea is explained in part G of this paper:

> Frenkel, D., 2013. Simulations: The dark side. The European Physical Journal Plus, 128(1), p.10.

**Comment by CompRhys** [comment]
Update: Having tired to implement this I see that what I initially suggested doesn't actually work due to the quantisation of reciprocal space and so we are limited to evaluating on grid points defined by the reciprocal vectors to our real space co-ordinates. I think this means if we want to limit ourselves to evaluating s(q) at the information limit then the only thing we can do is average along the 100, 010 and 001 directions. If as suggested in the first frenkel paper we evaluate along the face and body diagonals as well we get samples at sqrt(2) * limit and sqrt(3) * limit as well which wasn't how I interpreted it when I first read the paper.

**Comment by CompRhys** [comment]
I am returning to this line of work and would like to integrate a faster method to get the structure factor as an additional routine i.e. structure_factor_fast or something similar. For personal use I previously just hacked in my solution but in order to make my work more reproducible I think it is best to try have the method included via a PR.

The idea is that rather than looking at every grid point we just look at grid points on the (100), (110) and (111) type directions. This means that we get linear scaling in the order rather than cubic. This method has been used in paper referenced above in the initial issue. 

Beyond changes to `src/core/statistics.cpp` and `src/core/statistics.hpp` what else do I need to add to be compliant?
