### ISSUE TITLE
Proper return type for Observables needed

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2233]
Observables return floating point tensors, but have no
way of communicating the dimensions of the data (just
the size). We can't use `boost::multi_array` for that because
there the rank is static, but we need dynamic rank for the
Observables.

**Comment by jngrad** [comment]
I've come up with a solution where each Observable class has a `std::vector<int> shape()` method that is called in Cython to reshape the flattened array into an N-dimensional array. Is it what you had in mind?
