### ISSUE TITLE
Failures in LB test

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2247]
There are again random failures in the LB test, c.f.
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/38388

**Comment by fweik** [comment]
This is still happening and needs to be resolved soon.

**Comment by KaiSzuttor** [comment]
problem: only ca. 2% fail rate

**Comment by KaiSzuttor** [comment]
IIRC LBs seed is not interfaced

**Comment by fweik** [comment]
The variance of <v^2> is 10  times larger for the GPU code than for the CPU code, and there is no apparent reason for that.

**Comment by RudolfWeeber** [comment]
The LB GPU rng needs to be seeded, otherwise the test will fail from time to time.
I did not check the variance of the variance for different seeds.
the current tolerance was chosen arbitrarily such that the test ran in a loop for some ten minutes. The failure rate shoud drop at least exponentially with the tolerance.

**Comment by fweik** [comment]
Also the GPU LB fails a simple shear test https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/39761, which works fine for the CPU. Could it be that the viscosity units are different for GPU and  CPU? That would also explain why the GPU version is more noisy with the same (numerical) parameters.

**Comment by fweik** [comment]
There are now also issues with the CPU LB, c.f. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/44784. Not sure if this is related. But I saw this at least twice today, could also be new.

**Comment by RudolfWeeber** [comment]
The pr which introduced better averaging in the test is merged
Furhtermore, the temperature fluctuations no longer differ with the current head, presumably due to the use of the Filox RNG in lbgpu.
Closing.
