### ISSUE TITLE
MDA_ESP does not work without ELECTROSTATICS

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2248]
Also I think there is no test.

**Comment by pdebuyl** [comment]
The line https://github.com/espressomd/espresso/blob/python/src/python/espressomd/MDA_ESP/__init__.py#L161

    charges.append(p.q)

requires the `q` particle property to be defined.

Solutions:
1. Always define `q`, even without ELECTROSTATICS 
2. Protect the access to q in MDA_ESP by a conditional

**Comment by fweik** [comment]
Yes, `q` should just be `static constexpr` and zero if !ELECTROSTATICS.
