### ISSUE TITLE
Move release tarballs from release repo to release page

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#2253]
@fweik, please move the tarballs from https://github.com/espressomd/release to https://github.com/espressomd/espresso/releases. They all have corresponding tags, except for 2.1.2j, which is 608ff0074436b43b9faab2bc5b5da3b38aa45ab7.

**Comment by fweik** [comment]
Not sure if/why this is needed. There exist automatic tarballs and tags for the releases.

**Comment by mkuron** [comment]
The tarballs have signatures and pre-generated autoconf/automake files.
