### ISSUE TITLE
The stress tensor is broken when used together with p3m

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#226]
Wed 08 Apr 2015 07:28:51 PM CEST, original submission:
The values in the stress tensor don't make sense when used together with p3m. Stretching in different directions does reflect the symmetry of the system. 
As example I have used just a cubic box with salt and stretched a polymer over the main diagonal. Simulations without p3m yielded that the normal components of the unchanged directions are the same. With p3m stretching yields completely different behavior. 
A script with the sample system is attached. 
Kind regards, 
Tobias Richter

**Comment by RudolfWeeber** [comment]
Is this still broken?
@richter-t

**Comment by fweik** [comment]
I think this was closed by #469
