### ISSUE TITLE
Create release checklist

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2269]
We need a check list  for the next release containing all the needed steps to
make sure the process goes smoothly next time.

Here is what we came up with in the last Espresso meeting:

## May change repository
- Update CI containers to recent version
  of libs and distributions
- Check /requirements.txt
- Check tutorials and samples
- Check and fix copyright headers
- AUTHORS list
- Check the version in /CMakeLists.txt
- Spell and grammar check comments and docs

- Make and test Tarball 
- Test make install

## No changes after this
- Tag release
- Fork to version branch
- Build and deploy static documentation

**Comment by mkuron** [comment]
One point to add after @junghans's OpenSUSE package builds showed a bunch of issues:
 - Test builds on i386 and some big-endian architecture
