### ISSUE TITLE
Use of deprecated Sphinx config value

### ISSUE THREAD

**Issue by RCreyghton** [espressomd/espresso#2270]
When make'ing sphinx on my configuration (python 2.7.15, sphinx 1.8.0) I get the following error:
```
Creating file /Users/ramon/espresso/esp40/buildall/doc/sphinx/modules.rst.
Warning, treated as error:
autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
```
I traced this to line 312 in build/doc/sphinx/conf.py, which uses autodoc_default_flags, which is indeed deprecated: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags 
Replacing this as follows solved this issue for me:
```
autodoc_default_options = {
    'members': None,
    'show-inheritance': None,
    'undoc-members': None}
```
I suspect line 312 of /doc/sphinx/conf.py.in can use some updating.

**Comment by KaiSzuttor** [comment]
We can only use ```autodoc_default_options``` after we require sphinx 1.8.
