### ISSUE TITLE
VirtualSitesInteratialessTracers do not conserve momentum

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2275]
See #2274. 
Also there is a lot confusion and code-duplication going on there. Also there are issues with the integration scheme when there are tracers and normal particles, because during the force calculation
the positions of the tracers is not update yet, but the one of the real particle is which leads to wrong forces. This can probably be repaired by updating the tracers like the other virtual sites at the beginning of the time step, which I think is overall more correct.

I'm not going to work no this, but somebody has to otherwise the feature has to be removed.

**Comment by RudolfWeeber** [comment]
The test has lbboundaries defined in the individual cpu and gpu files.
Without those, the momentum conservation passes.
The test files should be merged into a single file the same way as is done fo lb.

**Comment by fweik** [comment]
Argh. Thank you. Then there is still the issue of the integration order.

**Comment by RudolfWeeber** [comment]
On Sat, Sep 22, 2018 at 02:07:35AM -0700, Florian Weik wrote:
> Argh. Thank you. Then there is still the issue of the integration order.
Can you write down a test case demonstrating that?

**Comment by fweik** [comment]
Yes, will do. But it's obvious, the real particles are propagated before the force calculation, the tracers after.
