### ISSUE TITLE
mass-dependent observables shouldn't include virtual particles

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2276]
which is wrong, because they are not degrees of freedom and do not carry momentum or mass.

**Comment by RudolfWeeber** [comment]
On Fri, Sep 21, 2018 at 02:09:21AM -0700, Florian Weik wrote:
> which is wrong, because they are not degrees of freedom and do not carry momentum or mass.
This might also be true for kinetic energy

**Comment by fweik** [comment]
Also kinetic pressure.

**Comment by jonaslandsgesell** [comment]
#2714

**Comment by RudolfWeeber** [comment]
I'll do this
