### ISSUE TITLE
Code duplication in and between MMM2d and ELC

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2279]
The code for the two directions in the long range part of MMM2d and in ELC are largely identical but duplicated, so is the code for the sine/cosine cache. Also MMM2d and ELC are largely identical.

**Comment by RudolfWeeber** [comment]
Is this being worked on?

**Comment by fweik** [comment]
Yes, but depends on #2512.

**Comment by jngrad** [comment]
Fixed by #3340
