### ISSUE TITLE
Artifcats in particle-fluid coupling at periodic boundaries

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#228]
Tue 02 Dec 2014 03:34:31 PM CET, comment #1:
The artifacts are probably caused by halo nodes not correctly marked as boundary nodes, because the rhomboids in boundaries.tcl do not cover the halo region.

**Comment by fweik** [comment]
Mon 01 Dec 2014 03:24:41 PM CET, original submission:

**Comment by RudolfWeeber** [comment]
@rempferg

**Comment by fweik** [comment]
This is quite old, and I can not reproduce. Will close for now.
