### ISSUE TITLE
Add proper halo communication to LB so it does not rely on internals of the cell system.

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2287]
Currently The LB couples to local cells and ghost cells. This needs to be replaced with halo reduction for the force density field.

**Comment by fweik** [comment]
The required type of halo communication is not supported by the LB halo implementation (in `halo.{hpp,cpp}`). The separate halo communication in the P3M implements this, but can not be lifted out because it's tied to P3M internals. Also Maggs uses the same coupling/halo strategy as the LB and needs to be fixed too if we want to keep it.

**Comment by fweik** [comment]
Some more information on this:
Currently the LB coupling communication works as follows (this is only for coupling, for the LB streaming itself there is different stuff which is specific to LB): 
1. The 19 populations in the halo regions are communicated with a 3-step halo communication.
2. Random numbers are drawn for each local particle and stored on the particle.
3. There is a (particles) ghosts communication step that broadcasts the random numbers to the ghost cells.
4. The particle coupling (including the random numbers stored on the particles) is calculated for all local particles and those ghost particles that are within one cell of the local LB mesh.

The alternative (and better) way would be:
1. Calculate the local velocity field (3 numbers)
2. Do communication of halo region for velocity field
3. Calculate coupling for local particles.
4. Reduce halo layers of force density.

**Comment by RudolfWeeber** [comment]
While this would be architecurally more clean, we went for a different route, because the necessary communicaiton pattern is not implemented in Walberla and because for some parameters (large md skin) this would have resulted in a higher ghost communcation data volume.
