### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by Raketenjoint** [espressomd/espresso#2293]
I am using the distribution "Arch Linux" and would like to install espresso via the [AUR](https://aur.archlinux.org/). I am going to package it myself according to the [Arch packaging standards](https://wiki.archlinux.org/index.php/Arch_Packaging_Standards).
That's my first time so maybe I could need your help when trouble comes up (i.e. solved python3 issues). 
Kai told me that usually @junghans does this.

**Comment by junghans** [comment]
Sorry, I don't do Arch packages! So I cannot really help you there!

**Comment by RudolfWeeber** [comment]
Closing for now.

**Comment by Raketenjoint** [comment]
I packaged [`espressomd-git`](https://aur.archlinux.org/packages/espressomd-git/).
Dependencies are managed properly this way on Arch Linux.
Users have to activate features manually but I provide a default `/usr/bin/pypresso`.
