### ISSUE TITLE
Formatting: Upgrade pep8 version to the one from Ubuntu 18.4?

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2306]

**Comment by jngrad** [comment]
Once we decide on a new version, we'll have to update [`clang-python3:6.0`](https://github.com/espressomd/docker/blob/d92816d848819f0272db3bc3a4e28255a4cd8868/docker/clang-python3/Dockerfile-6.0#L21), revert 0f3d5bed9c and fix [this error](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/136094).

**Comment by mkuron** [comment]
Ubuntu 18.04 doesn't provide autopep8 packages for Python 3. I would suggest we install 1.3.4 (with pycodestyle 2.3.1) from pip, as that is the version it uses for Python 2. Since autopep8 can operate on Python 3 code even when running on a Python 2 interpreter, this allows people to just install the Python 2 version from the Ubuntu repository if they want to run the style checker on their desktop.

**Comment by jngrad** [comment]
Just tried @mkuron's combination on Ubuntu18.04. 180 files were updated. The formatting is now more consistent, however it is also more zealous, e.g.:
```diff
-        return self.__class__.__name__ + "(" + id_str + "): " + self._params.__str__()
+        return self.__class__.__name__ + \
+            "(" + id_str + "): " + self._params.__str__()
```
or
```diff
-    def distribution(self, type_list_a=None, type_list_b=None,
-                     r_min=0.0, r_max=None, r_bins=100, log_flag=0, int_flag=0):
+    def distribution(
+            self,
+            type_list_a=None,
+            type_list_b=None,
+            r_min=0.0,
+            r_max=None,
+            r_bins=100,
+            log_flag=0,
+            int_flag=0):
```
Just like in autopep8 v0.9.1, the formatting remains sub-optimal when the input is incorrectly formatted. For example if we put a carriage return after opening a square bracket, autopep8 v1.3.4 will not fix it, which causes this:
```diff
-bottom_shape = shapes.Rhomboid(corner=[0.0, 0.0, 0.0], a=[
-                               boxX, 0.0, 0.0], b=[0.0, boxY, 0.0], c=[0.0, 0.0, 1.0], direction=1)
+bottom_shape = shapes.Rhomboid(
+    corner=[
+        0.0, 0.0, 0.0], a=[
+            boxX, 0.0, 0.0], b=[
+                0.0, boxY, 0.0], c=[
+                    0.0, 0.0, 1.0], direction=1)
```
or this:
```diff
-        print("HA", system.number_of_particles(type=0), "A-",
-              system.number_of_particles(type=1), "H+", system.number_of_particles(type=2))
+        print(
+            "HA",
+            system.number_of_particles(
+                type=0),
+            "A-",
+            system.number_of_particles(
+                type=1),
+            "H+",
+            system.number_of_particles(
+                type=2))
```
We could drop one of the `--aggressive`, which would prevent things like:
```diff
-    f.write('The Doxygen documentation generated {} unique warnings (total: {},'
-            ' ignored: {}):\n'.format(n_unique, n_all, n_unique_raw - n_unique))
+    f.write(
+        'The Doxygen documentation generated {} unique warnings (total: {},'
+        ' ignored: {}):\n'.format(
+            n_unique,
+            n_all,
+            n_unique_raw -
+            n_unique))
```
or 
```diff
     print(
-        "Simulating for", args.walltime, "h, which is", n_int_cycles, "cycles x",
-        n_int_steps, "steps, which is", args.walltime * ns_per_hour, "ns simulation time")
+        "Simulating for",
+        args.walltime,
+        "h, which is",
+        n_int_cycles,
+        "cycles x",
+        n_int_steps,
+        "steps, which is",
+        args.walltime *
+        ns_per_hour,
+        "ns simulation time")
```
but this would deprive us from useful changes like:
```diff
-            if not id in self._system.part[:].id:
+            if id not in self._system.part[:].id:
```

**Comment by mkuron** [comment]
> We could drop one of the `--aggressive`

We should. These examples are just ugly.

> but this would deprive us from useful changes like:
```diff
-            if not id in self._system.part[:].id:
+            if id not in self._system.part[:].id:
```

That change is not useful enough to be worth the other uglyness. `if X not in` and `if not X in` are just different syntax for the same thing, right?

**Comment by jngrad** [comment]
that's the same syntax, `if not X in` is corrected because it is ambiguous (adding parentheses changes the behavior: `if (not X) in`)

**Comment by RudolfWeeber** [comment]
> > We could drop one of the `--aggressive`
> 
> We should. These examples are just ugly.
Aye!

**Comment by mkuron** [comment]
It's not ambiguous if we can expect our developers to know that the `in` operator has higher precedence than the `not` operator. This precedence should not be a surprise to anyone because member access (`.__contains__(X)`) obviously has higher precedence than negation.

**Comment by jngrad** [comment]
Here is the formatted code at different levels of aggressiveness:
* [default](https://github.com/jngrad/espresso/commit/14ba52968611abc71fd10520e92f4f947e2ca457): improves the formatting in a consistent manner
* [`--aggressive`](https://github.com/jngrad/espresso/commit/dc9d8944d35b55492bb8395cdebe88e5d1ff70b7): adds `BaseException`, trims decorative separators, wraps around comments longer than 80 chars, enforces 80 chars per line even if this means adding backslashes
* [`--aggressive --aggressive`](https://github.com/jngrad/espresso/commit/31dbb1b551a86a1810cb6decb6935cf6ca12ecfd): changes the `if not X in` and incorrectly formats code

I agree we shouldn't use the most aggressive level. The first aggressive level is OK in my opinion. If the line breaks are too annoying we could relax the 80 chars limit to maybe 82, which would reduce the number of insertions/deletions from 370(+)/209(-) down to 315(+)/168(-).

**Comment by RudolfWeeber** [comment]
I don’t find the line wrapping that important, but I’m also fine with –aggressive once.

Since you looked at it in the most detail, I suggest, you make the decision.

**Comment by jngrad** [comment]
@mkuron it looks like we cannot expect our developers to know `in` has higher precedence :)
https://github.com/espressomd/espresso/blob/03536720f4ac54a3ea201ed9f71265a13d6d8cd5/src/python/espressomd/electrokinetics.pyx#L39-L45
I'll change those and others to `not in` for consistency, as recommended in [PEP8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations). I'll use only one `--aggressive` and go through all the lines and rework anything that is sub-optimal.
