### ISSUE TITLE
Improve virtual sites and topology handling

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#232]
Thu 22 Mar 2012 06:02:32 PM CET, original submission:
VIRTUAL_SITES_RELATIVE and VIRTUAL_SITES_COM are implemented in opposite ways. 
VIRTUAL_SITES_RELATIVE uses particle properties, while VIRTUAL_SITES_COM uses the topology data. 
The first approach seems easy to generalize, however for many molecule the second one save memory as every molecule data is only stores once. 
Also the setup is very different VIRTUAL_SITES_RELATIVE uses the part command, while VIRTUAL_SITES_COM uses the "analyze set" command. 
The first one is more obvious to use as there is no documentation for the second one ("analyze set chain" is documented, but this is something else). 
The suggestion would be to make both accessible via the part command under a "vs" sub-command: 
part ... vs relative ... 
part ... vs relative_auto ... 
part ... vs com ... 
With this we can disallow the direct setting of the virtual property via the "part .. virtual {0|1}" command. 
Additionally the "analyze set" could be reworked into a topology command: 
topology create mol_id parts id id id type int excl {0|1} 
topology delete mol_id 
topology create mol_id chain .... 
With this we can disallow the direct setting of the mol_id property via the "part .. mol_id id" command.

**Comment by jngrad** [comment]
2019 update: feature `VIRTUAL_SITES_COM` is not functional anymore and will be removed in #3250.

**Comment by fweik** [comment]
This is not relevant anymore, the (molecule)-topology system does not exist anymore, neither does virtual sites com.
