### ISSUE TITLE
Remove LB GPU particle coupling code

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2322]
The LB GPU has it's one code to do viscous coupling. This should be unified with the CPU code to
remove this code duplication. A complete solution to integrate the viscous LB coupling into the rest of the Langevin code. This might depend on a clean up of the LB CPU coupling, see  #2287.

**Comment by RudolfWeeber** [comment]
I assume, we wil no longer do this, due to the switch to Walberla.

**Comment by mkuron** [comment]
Wasn't the plan to reuse the particle coupling code with the Walberla integration? That is, have a common particle coupling code for both existing LBs and Walberla?

**Comment by RudolfWeeber** [comment]
On Wed, Jul 03, 2019 at 02:36:10AM -0700, Michael Kuron wrote:
> Wasn't the plan to reuse the particle coupling code with the Walberla integration? That is, have a common particle coupling code for both existing LBs and Walberla?
In principle, yes. But there is no point in putting more work in LBGPU which we will replace very soon.

**Comment by mkuron** [comment]
That depends on how long it takes until we actually remove the old stuff and how much work it is to pull out the existing code vs. writing a third implementation.

**Comment by RudolfWeeber** [comment]
On Wed, Jul 03, 2019 at 09:59:17AM +0000, Michael Kuron wrote:
> That depends on how long it takes until we actually remove the old stuff and how much work it is to pull out the existing code vs. writing a third implementation.
There is no third implementation. Walberla re-uses the LBCPU coupling.
Thanks to Kai's work, very little new code was needed, there.
