### ISSUE TITLE
SWIMMER_REACTIONS: Missing test guards

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2329]
Fails with myconfig lj, partial_periodic and swimmer_reactions.

**Comment by RudolfWeeber** [comment]
@hmenke, could you take a look at this?

**Comment by fweik** [comment]
Can not reproduce.
`myconfig.hpp:`
```
#define LENNARD_JONES
#define PARTIAL_PERIODIC
#define SWIMMER_REACTIONS
```
and commit 2223737c8424fc8f6b7d16e0428c6d482d9f057a.
