### ISSUE TITLE
BOND_ANGLEDIST: Undefined symbol

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2330]
Myconfig: lj, partial_periodic, BOND_ANGLEDIST.
    
    
    import espressomd._init
ImportError: /scratch/weeber/guards/build/src/core/libEspressoCore.so.4: undefined symbol: _Z16angledist_energyP8ParticleS0_S0_P20Bonded_ia_parametersPd

**Comment by fweik** [comment]
This is fixed in mainline by #2338, but needs an extra fix for 4.0.1

**Comment by fweik** [comment]
So the reason is that the usage and prototype is if `BOND_ANGLEDIST`, and the implementation is `BOND_ANGLEDIST_HARMONIC`.

**Comment by fweik** [comment]
Closed by #2346.
