### ISSUE TITLE
Implement h5md output

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#235]
Check complexity and assign to sb

**Comment by jonaslandsgesell** [comment]
Work has been started by Kai and Sascha for the tcl interface (it will stay with us some time, hmm). There is some support for writing h5md files from tcl in a way that VMD can read it (see https://github.com/h5md/VMD-h5mdplugin). Further Sascha has already started to use h5py, which makes it easy to use together with the python interface.

**Comment by KaiSzuttor** [comment]
This is done for tcl-Interface.

**Comment by jonaslandsgesell** [comment]
Parallel IO is not available yet.

**Comment by fweik** [comment]
Is somebody currently working on that?

**Comment by KaiSzuttor** [comment]
@sehrhardt  is working on the h5md output of the python interface and is almost done as far as i know.

**Comment by fweik** [comment]
Apparently the people from Dirks group at IPVS are working on parallel IO in Espresso. I'm going to talk to them on Thu and will report back.
