### ISSUE TITLE
LB GPU uses random seed

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2356]
See https://github.com/espressomd/espresso/blob/478818f1625b1762ffee15776e8ae6182d709666/src/core/grid_based_algorithms/lbgpu.cpp#L234

That will go once we refactored out the particle coupling from the GPU LB.

**Comment by mkuron** [comment]
It wouldn't be difficult to interface that variable even now. The right solution is of course to require the user to seed manually as decided in #1211.

**Comment by KaiSzuttor** [comment]
We probably don't want to interface it. We would want it to use the seed already provided.

**Comment by mkuron** [comment]
That's what I meant: it should be deterministically set by some user-provided value. We probably shouldn't set it to the seed provided but to some number derived from it so we don't use the same sequence of random numbers in multiple places.

**Comment by fweik** [comment]
@KaiSzuttor this can be closed now?

**Comment by KaiSzuttor** [comment]
no, it's not resolved yet
