### ISSUE TITLE
LB GPU uses uniform random numbers instead of normal distributed

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2357]

**Comment by RudolfWeeber** [comment]
I thought that could be switched at compile time?
The CPU and GPU ones using different distributions might also be a
cause of the different width of the temperature fluctuations

**Comment by KaiSzuttor** [comment]
Yeah but... check lb.cpp line 101

**Comment by KaiSzuttor** [comment]
Btw it's also not tested that LB thermostat gives the right maxwell distribution of velocities.

**Comment by RudolfWeeber** [comment]
I did a quick check. With Gauss random cut, the standard deviations in cpu and gpu are similar.
I'll open a pr fixing lbcpu with other noise types

**Comment by KaiSzuttor** [comment]
Why is that actually switchable by the user?

**Comment by mkuron** [comment]
As far as I know, the actual random number distribution does not matter as long as their mean and variance is correct. There might be a publication by Alexander Wagner on this topic, but I couldn't find it. The switch may have been added for testing purposes at some point.

**Comment by jonaslandsgesell** [comment]
Please cite this paper in a comment in the corresponding parts of the code. This question will pop up in each developer generation.

**Comment by KaiSzuttor** [comment]
Dünweg, Burkhard, and Wolfgang Paul. "Brownian dynamics simulations without Gaussian random numbers." International Journal of Modern Physics C 2.03 (1991): 817-827.

**Comment by jonaslandsgesell** [comment]
Please cite in source as documentation!

**Comment by KaiSzuttor** [comment]
Ladd, Anthony JC. "A fast random number generator for stochastic simulations." Computer Physics Communications 180.11 (2009): 2140-2142.
