### ISSUE TITLE
CI failures due to LB and timeout

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2386]
Multiple PR are currently failing CI due to an LB thermostat error unrelated to the committed changes:
   * #2385, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3963): added a Markdown file
   * #2381, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3940): added an optional test, which is disabled by default
   * #2379, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3913): fixed a Shape test
   * #2378, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3911): simplified a function in reaction ensemble

Likely related to #2247 and #2226.

There is also an issue with the new rocm-maxset container whose 20 min timeout is too short, see for example #2381, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3940) and #2379, [CI](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3913). Other containers have a 1 hour timeout.

**Comment by mkuron** [comment]
The timeout on rocm is short on purpose because that's my desktop computer, not a dedicated machine. Normally the jobs take about 8 minutes, so the 20-minute limit should be plenty. If something runs into the timeout, it's usually a frozen test.
