### ISSUE TITLE
ENGINE: Un-needed data transfers

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2389]
@hmenke @jdgraaf
In its current form, the engine feature copies v_cs data 
(velocities at particle center and 2nd point, I assume) 
from the gpu and distributes it via mpi, independently of whether swimming particles are there.
This takes some 20% of the execution time in an unrelated lbgpu+particle simulation.
19.97%  python         EspressoCore.so.4               [.] _ZN12_GLOBAL__N_18set_v_csEN5Utils5RangeI16ParticleIterator

we are currently preparing to extend espresso's default myconfig to include nearly all features, so we can ship pre-built packages for common Linux distros.

Unless above issue is resolved, we cannot include the ENGINE feature in this default config.
That would be a pity, because there is a tutorial for this feature.

**Comment by hmenke** [comment]
That is certainly possible but would either introduce a new global variable or require a reduction over all particles to see whether the `swimming` property is enabled.

*N.B.*: `v_cs` stands for **V**elocity at the particle **C**enter and the **S**ource point of the counter force.

**Comment by mkuron** [comment]
Just use a global variable, that would be similar to how the actors/`SystemInterface` work. The first time a method is activated that needs a certain property on the GPU, a global variable (or maybe static variable in a class) is toggled.

The reduction is unnecessary as the only way to switch on `swimming` is via the interface.
