### ISSUE TITLE
printing of p3m tuning parameters

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2408]
tuning gives something along those lines:

> resulting parameters:
> 8    8    8    4   4.67773e-01 4.81653e+00 9.98796e-04 0.11

This is not readable ;) It should be provided what the indiviual parameters are (i.e. variable names).

**Comment by jngrad** [comment]
Here is the proposed output (#2465):
```
resulting parameters: mesh: (44 44 44), cao: 7, r_cut_iL: 1.9672e-01,
                      alpha_L: 1.6934e+01, accuracy: 9.8104e-05, time: 63.53
```
