### ISSUE TITLE
VMD visualization on fly

### ISSUE THREAD

**Issue by AlexanderDKazakov** [espressomd/espresso#2426]
I would like to ask you about visualization. The espresso version 3.3 has a communication protocol with VMD using sockets. Is it possible to migrate the same communication protocol for the last espresso using python?

**Comment by mkuron** [comment]
That feature was removed, sorry. It hasn‘t worked reliably in quite some time and we had trouble understanding the old code well enough to fix it. We have Mayavi live visualization though and a custom OpenGL visualizer with tight Espresso integration (see the tutorials), so Espresso should continue to fulfill your visualization desires.

**Comment by AlexanderDKazakov** [comment]
Okay! I will check them!

Thank you!
