### ISSUE TITLE
checkpoint testing needs a rewrite

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2436]
In the current test framework for the checkpoints mutually exclusive features can not be tested. That's a fundamental issue and should be resolved in general.

**Comment by fweik** [comment]
@jngrad are you interested in looking into this?

**Comment by KaiSzuttor** [comment]
the more sustainable way of handling checkpointing is probably to move some logic from the interface to the core

**Comment by jngrad** [comment]
Could jngrad/espresso/fix-2436@d5e4b08 be an option? The user would have to provide a list of mutually inclusive options like `lbgpu-p3m-lj` to generate multiple versions of the checkpoint test. This syntax could be extended with flags, for instance `lb.cpu-p3m.cpu`, `lb.gpu-p3m.gpu`, `re.constant_pH`, etc.

**Comment by KaiSzuttor** [comment]
I think that is the solution with least effort and should work for now but on the long run we should think about a more generic solution as already mentioned.
