### ISSUE TITLE
Tests on emulated platforms take too long

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2475]
There is a time limit of 3h for the jobs, for some of the tests that run in qemu that is too low.
I think it is sufficient to run them only scheduled, like every night, and not on every update.

**Comment by mkuron** [comment]
I have switched the schedule from weekly to nightly.

**Comment by fweik** [comment]
The tests were not reliably finishing within the 3 hr time limit enforced by gitlab, this limit needs to be increased before the tests can be enabled again.
