### ISSUE TITLE
Improve CI pipeline parallelism

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2476]
I think throughput of the CI could be improved if the build and test a split into two stages. Currently, for pull requests, if there are enough resources the runtime is basically the time for clang-6.0 (slowest job from 'build' stage) plus 'check_with_odd_no_of_proc'. If they would be split it would be only the clang-6.0 runtime (plus some overhead for downloading the artifacts).

**Comment by mkuron** [comment]
Just move check_with_odd_no_of_proc to the build stage; then it can run simultaneously with clang-6.0. This has the advantage of not burdening our GitLab server with all the build artifacts.
