### ISSUE TITLE
Multiple issues with swimmer reaction, decide faith

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2498]
Currently swimmer reactions does not properly handle ghosts and pair discovery: It does it's own n2 pair finding but does not take into account the facts that pairs can be found multiple times, that some of the reacting particles could be ghosts and does not synchronize reactions between nodes. Also the implementation is rather confusing and the details are not documented. In the current state we can not keep it.

**Comment by fweik** [comment]
It also shadows the old catalytic reaction method, which is a different method.

**Comment by RudolfWeeber** [comment]
The test case fails without ROTATION. It is also not clear to me, what it does without ROTATION.
@jdgraaf @hmenke, is the SWIMMER_REACTIONS feature actually being used?
Based on the issues mentioned in this ticket. I think that, either someone has to commit to clean it up or we will have to remove it.
