### ISSUE TITLE
Properly sync online docs

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2523]
The Sphinx and Doxygen documentations are currently deployed by the following `rsync` command:
https://github.com/espressomd/espresso/blob/a72bf2fe46bcfa3546fc04c65e9c48e031387302/.gitlab-ci.yml#L374-L378
The `--delete` flag only deletes extra files in subfolders. We currently send the `.../html/*` files, hence html files of .rst files that were removed or renamed in a PR are not deleted. See for example this recent [ML thread](http://lists.nongnu.org/archive/html/espressomd-users/2019-02/msg00005.html), which is based on [inter.html](http://espressomd.org/html/doc/inter.html), whose corresponding .rst file was removed in [74b3a11](https://github.com/espressomd/espresso/pull/1785/commits/74b3a116d2abb74fce90d20a592b1ea136551a09#diff-ca86133bfc5ad2fd91511606cf9dd3c6). The html file footer indicates it was last updated more than a year ago.

We could replace
```./* espresso@elk.icp.uni-stuttgart.de:/home/espresso/public_html/html/doc```
with
```./ espresso@elk.icp.uni-stuttgart.de:/home/espresso/public_html/html/doc/```
to erase outdated html files, however if the site maintainer added any extra file or symlink in the `public_html/html/doc/` folder, this will be erased too.

**Comment by KaiSzuttor** [comment]
There are not additional files in that directory, so we can just override
