### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2535]
Good morning,
later of ./pypresso
input:

sys
sys.path.insert(0, "/Users/diogo/Simulation/espresso-4.0.1/src/python/")
import espressomd

given:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/diogo/Simulation/espresso-4.0.1/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: No module named _init

Thanks

**Comment by KaiSzuttor** [comment]
Can you please show how you tried to build and if there were any error messages during the build

**Comment by KaiSzuttor** [comment]
You should not add the python directory of the source tree you your python path. Acutally that is not necessary if you use the pypresso python executable. Please have a look at http://espressomd.org/html/doc/installation.html

**Comment by diogomusical** [comment]
Good morning,

compiling does not give errors. I just do not know how to set the directory. If you could write the commands and the steps I have to do thank you.

**Comment by KaiSzuttor** [comment]
You don't have to set any directory. Just use the pypresso executable that is created in the build directory.

**Comment by jngrad** [comment]
Issue resolved (#2565)
