### ISSUE TITLE
Non amd64 tests fail due to timeout

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2540]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/78710

**Comment by mkuron** [comment]
Make lb_stokes_sphere shorter/faster/better. It's by far the slowest test on amd64 too. Also, I'm not even sure about the physics of it. I tried to recreate it in Walberla for https://i10git.cs.fau.de/walberla/walberla/merge_requests/163 and saw significant deviations when changing any parameters.

**Comment by RudolfWeeber** [comment]
Replaced by #2647
