### ISSUE TITLE
Removing constraints

### ISSUE THREAD

**Issue by AlexanderDKazakov** [espressomd/espresso#2547]
Hello! 

I tried to create a constraint and after some time I would like to remove it. 
I am attaching some simplest code for that. 
Here is Traceback:

 →  ./py-es constraints.py 
Traceback (most recent call last):
  File "constraints.py", line 19, in <module>
    system.constraints.remove(constraint=cylinder)
  File "/PATH/espresso/es-build/src/python/espressomd/constraints.py", line 80, in remove
    self.call_method("remove", object=constraint)
  File "script_interface.pyx", line 77, in espressomd.script_interface.PScriptInterface.call_method
RuntimeError: Wrong type: Shapes::Cylinder

```python
import espressomd
from espressomd import shapes
 
system = espressomd.System(box_l=[50,50,50])
system.cell_system.skin = 0.5 
system.time_step = 0.1 
 
system.part.add(pos=[1,1,1])
system.part.add(pos=[2,2,2])
 
 
cylinder = shapes.Cylinder(center=[20, 10, 2], 
                                    axis=[1, 0, 0], 
                                    direction=1,
                                    radius=8,
                                    length=5)
 
system.constraints.add(shape=cylinder)
system.constraints.remove(constraint=cylinder)
system.integrator.run(1)
```

Could you tell me, please, what I am doing wrong?  What type should I choose?

**Comment by RudolfWeeber** [comment]
On Fri, Mar 01, 2019 at 04:15:02PM +0000, AlexanderDKazakov wrote:
>  
> system = espressomd.System(box_l=[50,50,50])
> cylinder = shapes.Cylinder(center=[20, 10, 2], 
>                                     axis=[1, 0, 0], 
>                                     direction=1,
>                                     radius=8,
>                                     length=5)
>  
> system.constraints.add(shape=cylinder)
> system.constraints.remove(constraint=cylinder)
You are using a short-hand for
system.constraints.add(ShapeBasedConstraint(shape=cylinder))
you need to remove the ShapeBasedConstraint objects. The simplest
way is
constraint= system.constraints.add(shape=cylinder)
system.constraints.remove(constraint)

**Comment by AlexanderDKazakov** [comment]
A! Now I got it. I was losing the pointer to instance! Initially, I thought that the cylinder already is the pointer.

Great! Thank you for help!
