### ISSUE TITLE
Extend LB checkpointing tests

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2555]
* test multiple lattice sites
* test more properties: population, density, velocity, stress, ... per lattice site
* loading a checkpointed LB fluid into an LB object with different lattice geometry should raise an error (maybe write lattice dimensions to the checkpoint file)

**Comment by jngrad** [comment]
To fill the entire lattice with values without running a simulation, we could use numpy:
```python
import numpy as np
m = np.pi / 12
grid_3D = np.fromfunction(lambda i, j, k: np.cos(i * m) * np.cos(j * m) * np.cos(k * m),
                          (24, 24, 24), dtype=float)
```

To check the function produces different values on each grid point of a 2D slice:
```python
import matplotlib.pyplot as plt
plt.imshow(grid_3D[:,:,0], interpolation='bilinear')
plt.show()
```

**Comment by jngrad** [comment]
@jainka The GPU checkpoint file saves forces (3D array of float[3]) and boundaries (3D array of bool) but the CPU doesn't. These value should probably be unit tested on the GPU. If there is anything analogous on the CPU, and if so, should they be saved to the checkpoint file as well?

**Comment by jainka** [comment]
> @jainka The GPU checkpoint file saves forces (3D array of float[3]) and boundaries (3D array of bool) but the CPU doesn't. These value should probably be unit tested on the GPU. If there is anything analogous on the CPU, and if so, should they be saved to the checkpoint file as well?

I have been thinking about it. From my point of view checking only the 19 populations is enough in LBM as other quantities are more or less derived from it. I don't know why GPU checkpointing saves forces and boundaries, and why such decisions were made in the past. Please thus let me know if this should be like this, and if this should be checked in the tests? I think it just adds to the complications and confusions.

**Comment by KaiSzuttor** [comment]
I think it does not make sense to store the force densities since they're reset in every integration step. However, by storing the force densities the external force density is correctly restored. I'm not sure though if that is part of the state of the fluid, i tend to no.

**Comment by jainka** [comment]
> I think it does not make sense to store the force densities since they're reset in every integration step. However, by storing the force densities the external force density is correctly restored. I'm not sure though if that is part of the state of the fluid, i tend to no.

My view here more is if it makes sense to complicate the testing of checkpoint more. I think checking every lattice site and corresponding 19 populations is already too much. Furthermore, the tests are already overloaded with if-then-else, and a decision needs to be made whether to check forces/boundaries for GPU or not? I tend to no as well...

**Comment by KaiSzuttor** [comment]
I think the boundaries are restored via the state of the ```espressomd.System```. So I think, neither forces nor boundaries should be written.

**Comment by jainka** [comment]
Very well! I will change this..
