### ISSUE TITLE
Problem with dpd.py

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2565]
Hello

dpd.dy is what's in the samples folder.

when I make the input:
./pypresso dpd.py

gives the following error:
Traceback (most recent call last):
  File "dpd.py", line 25, in <module>
    espressomd.assert_features (required_features)
  File "/Users/diogo/Simulation/espresso/src/python/espressomd/__init__.py", line 52, in assert_features
    "Missing features" + "," .join (missing_features (* args)))
Exception: Missing features DPD

Goodbye, cump.

Diogo Silva

**Comment by jngrad** [comment]
Hi,
When compiling espresso, you can choose which features are enabled with the file `myconfig.hpp` (if you don't have one, you can create an empty one). Simply add these lines to `myconfig.hpp` and recompile espresso to enable DPD:
```c++
#define DPD
#define HAT
```
We don't enable all features by default for performance reasons. Please refer to the file `myconfig-sample.hpp` to see all available interactions that are not enabled by default, and copy those you need in `myconfig.hpp` to enable them (after recompilation).

**Comment by diogomusical** [comment]
Hello,

I forgot to recompile the espressomd. I had only had the script run.

Thank you,

Diogo
