### ISSUE TITLE
coulomb mixed periodicity test fails on i386

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2572]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/82953

**Comment by mkuron** [comment]
On amd64, it completes within 5 seconds, so I think it hangs. When it succeeds (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/83001), it takes 15 seconds on i386.

**Comment by KaiSzuttor** [comment]
i could not reproduce this

**Comment by fweik** [comment]
Seems to be gone, closing for now.
