### ISSUE TITLE
Decide which samples can go

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2584]
Since there are already tutorials for some features we probably do not need to keep all the samples.

Candidates:
  * [```samples/lj_liquid.py```](https://github.com/espressomd/espresso/blob/python/samples/lj_liquid.py)
  * [```samples/constraints.py```](https://github.com/espressomd/espresso/blob/python/samples/constraints.py)
  * [```samples/ekboundaries.py```](https://github.com/espressomd/espresso/blob/python/samples/ekboundaries.py)
  * [```samples/wang_landau_reaction_ensemble.py```](https://github.com/espressomd/espresso/blob/python/samples/wand_landau_reaction_ensemble.py)
  * [```samples/store_properties.py```](https://github.com/espressomd/espresso/blob/python/samples/store_properties.py)
  * [```samples/store_bonds.py```](https://github.com/espressomd/espresso/blob/python/samples/store_bonds.py)
  * [```samples/bonds-tst.py```](https://github.com/espressomd/espresso/blob/python/samples/bonds-tst.py)
  * [```samples/minimal_random_number_generator.py```](https://github.com/espressomd/espresso/blob/python/samples/minimal_random_number_generator.py)
  * [```samples/minimal-polymer.py```](https://github.com/espressomd/espresso/blob/python/samples/minimal-polymer.py)
  * [```samples/minimal-charged-particles.py```](https://github.com/espressomd/espresso/blob/python/samples/minimal-charged-particles.py)
  * [```samples/p3m.py```](https://github.com/espressomd/espresso/blob/python/samples/p3m.py)
  * [```samples/rigid_bond.py```](https://github.com/espressomd/espresso/blob/python/samples/rigid_bond.py)
  * [```samples/slice_input.py```](https://github.com/espressomd/espresso/blob/python/samples/slice_input.py)
  * [```samples/lbf.py```](https://github.com/espressomd/espresso/blob/python/samples/lbf.py)
  * [```samples/lbf_profile.py```](https://github.com/espressomd/espresso/blob/python/samples/lb_profile.py)

**Comment by KaiSzuttor** [comment]
@RudolfWeeber

**Comment by pdebuyl** [comment]
I believe that a nice set of samples is a good addition to the tutorials. After having built ESPResSo, running the samples from the command-line is really straightforward.

I would support keeping `minimal-polymer.py` for instance, and `lj_liquid.py`, probably with some cleanup.

**Comment by KaiSzuttor** [comment]
@pdebuyl you are probably right, but we are struggling with keeping the samples up to date. If you're an absolute beginner you should start off with a tutorial anyway because you don't really gain much knowledge from looking at a sample. Therefore I would only keep the most fundamental samples.
