### ISSUE TITLE
LB test has random failures

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2589]
E.g. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/84472, https://travis-ci.org/espressomd/espresso/jobs/505903357
Iirc it should be deterministic now.

**Comment by KaiSzuttor** [comment]
I'm not sure about this... Should be deterministic despite hardware issues of course. Do you know if it's always the GPU part and always the same runner?

**Comment by KaiSzuttor** [comment]
I just ran the test 100 times on my machine with no failure. Also on the machine where it failed with the same Docker images - no failure.

**Comment by fweik** [comment]
The failures are in the CPU code.

**Comment by KaiSzuttor** [comment]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/84472 this one is GPU

**Comment by fweik** [comment]
Yes., bit the other one is CPU

**Comment by fweik** [comment]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/88465

**Comment by fweik** [comment]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/90162

**Comment by RudolfWeeber** [comment]
iThis should be resolved, since the test is now deterministc.
Closing for now.
