### ISSUE TITLE
Problem h5md

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2590]
Hello,

input:

./pypresso h5md.py

output
Traceback (most recent call last):
  File "h5md.py", line 41, in <module>
    write_force=True, write_species=True, write_mass=False, write_charge=True, write_ordered=True)
  File "/Users/diogo/Simulation/simulacaotestespersonal/espresso/src/python/espressomd/io/writer/h5md.py", line 83, in __init__
    "ScriptInterface::Writer::H5mdScript")
  File "espressomd/script_interface.pyx", line 29, in espressomd.script_interface.PScriptInterface.__init__
ValueError: Class 'ScriptInterface::Writer::H5mdScript' not found.

Thank you,

Diogo Silva

**Comment by KaiSzuttor** [comment]
This is caused by a missing installation of the ```hdf5``` library. Please have a look at the [documentation](http://espressomd.org/html/doc/installation.html)

**Comment by diogomusical** [comment]
when does
ccmake ./
output

 BIBTEX                           BIBTEX-NOTFOUND                              
 CMAKE_BUILD_TYPE                 Release                                      
 CMAKE_INSTALL_PREFIX             /usr/local                                   
 CMAKE_OSX_ARCHITECTURES                                                       
 CMAKE_OSX_DEPLOYMENT_TARGET                                                   
 CMAKE_OSX_SYSROOT                                                             
 CUDA_HOST_COMPILER               /Applications/Xcode.app/Contents/Developer/To
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND                   
 CUDA_TOOLKIT_ROOT_DIR            CUDA_TOOLKIT_ROOT_DIR-NOTFOUND               
 CYTHON_FLAGS                     -2                                           
 GSL_CONFIG_EXECUTABLE            /usr/local/bin/gsl-config                    
 HDF5_C_LIBRARY_dl                /usr/lib/libdl.dylib                         
 HDF5_C_LIBRARY_hdf5              /usr/local/Cellar/hdf5/1.10.4/lib/libhdf5.dyl
 HDF5_C_LIBRARY_m                 /usr/lib/libm.dylib                          
 HDF5_C_LIBRARY_sz                /usr/local/opt/szip/lib/libsz.dylib          
 HDF5_C_LIBRARY_z                 /usr/lib/libz.dylib                          
 INSTALL_PYPRESSO                 ON  
 IPYTHON_EXECUTABLE               IPYTHON_EXECUTABLE-NOTFOUND                  
 MAKEINDEX                        MAKEINDEX-NOTFOUND                           
 MYCONFIG_NAME                    myconfig.hpp                                 
 PDFLATEX                         PDFLATEX-NOTFOUND                            
 SPHINX_API_DOC_EXE               /Users/diogo/Library/Python/2.7/bin/sphinx-ap
 WARNINGS_ARE_ERRORS              OFF                                          
 WITH_CUDA                        OFF                                          
 WITH_GSL                         ON                                           
 WITH_HDF5                        ON                                           
 WITH_SCAFACOS                    ON                                           
 WITH_TESTS                       ON                                           
 WITH_VALGRIND_INSTRUMENTATION    OFF

Thank you
