### ISSUE TITLE
Various issues with LB Stress

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2611]
In the development branch, lb the node stress for gpu and cpu don't agree for the lb_shear test case.
Compared to 4.0.2rc, the cpu value changed.

Currently I cannot get either to agree with the expected solution for Couette flow.
I have the impression, that in the lb_shear test, the variable
SHEAR_RATe does not actually denote the shear rate, since the boundary velocities are set to +,-0.5 * SHEAR_RATE independently of the system width, if I understnad the code correctly.

**Comment by fweik** [comment]
You are free to rename it to `SHEAR_VELOCITY`

**Comment by RudolfWeeber** [comment]
Fixed by #2633
