### ISSUE TITLE
Automatic formatting

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2612]
I think most of the time the formatting proposed by clang-format is just fine and we could automate the process instead of having to push a formatting commit every time. That is really annoying! The unlikely case of non-optimal formatting by clang-format can then by handle manually. What do you think @fweik @RudolfWeeber ?

**Comment by fweik** [comment]
I agree, but I'm not sure how to do it. Also obviously this would mean
automatic commits. If we had a staging branch we could do it when that is
merged into the master.

**Comment by mkuron** [comment]
Doing it automatically (either on the pull request or in the staging branch) will cause merge conflicts when someone continues working without pulling in the changes first. So it's not a particularly good idea. I would suggest you just create a pre-commit hook locally that applies the formatting.

**Comment by jngrad** [comment]
I don't think we should automate formatting. Formatting is not just about cosmetics, it can also reveal real coding errors, some of which are detected by `-Wmisleading-indentation` (part of `-Wall`). I always stage my changes, then run formatting via a Bash script (only formats the subset of modified files, so it's fast), then review the style changes with `git diff`. This is an excellent way to learn how to improve one's coding style, and to catch indentation errors in a time-effective manner.

Rudolf and I recently lost some time troubleshooting a function returning an incorrect error code. The code originally had the following logic:
```c++
if (stepA() == ES_ERROR)
  return -1;
if (stepB() == ES_ERROR)
  return -2;
if (stepC() == ES_ERROR)
  return -3;
```
Someone had refactored `stepB()` and `stepC()` as void functions, and updated the code accordingly:
```c++
if (stepA() == ES_ERROR)
stepB();
stepC();
```
The `return -1;` was removed by accident. Automatic style patch was then applied:
```c++
if (stepA() == ES_ERROR)
  stepB();
stepC();
```
The formatting masked the error, so the compiler did not issue a warning. I sometimes make this kind of mistake too, nobody's safe from it, but my stage-first, then-format strategy highlights it before I commit.

This strategy also works in Python. Consider code where indentation was accidentally mixed:
```python
def function():
    for i in range(5):      # correct: 4 spaces indentation
      print(i)              # mistake: 6 spaces indentation
        for j in range(i):  # correct: 8 spaces indentation
            print(j)        # correct: 12 spaces indentation
```
After applying autopep8-0.9.1:
```python
def function():
    for i in range(5):
        print(i)                # indentation is fixed
            for j in range(i):  # indentation is wrong
                print(j)
```
`git diff` will make this change visible.

**Comment by KaiSzuttor** [comment]
@jngrad if we had ```readability-braces-around-statements``` enabled for clang-tidy, this issue would not have popped up.

**Comment by mkuron** [comment]
@KaiSzuttor, that helps in this specific case, but there are other situations where automatic formatting reveals issues. Also, clang-tidy doesn't support Python.
