### ISSUE TITLE
Problem h5md

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2630]
hello

input: ccmake ./

 IPYTHON_EXECUTABLE               IPYTHON_EXECUTABLE-NOTFOUND                  
 MAKEINDEX                        MAKEINDEX-NOTFOUND                           
 MYCONFIG_NAME                    myconfig.hpp                                 
 PDFLATEX                         PDFLATEX-NOTFOUND                            
 SPHINX_API_DOC_EXE               /Users/diogo/Library/Python/2.7/bin/sphinx-ap
 WARNINGS_ARE_ERRORS              OFF                                          
 WITH_CUDA                        OFF                                          
 WITH_GSL                         ON                                           
 WITH_HDF5                        ON                                           
 WITH_SCAFACOS                    ON                                           
 WITH_TESTS                       ON                                           
 WITH_VALGRIND_INSTRUMENTATION    OFF                                          

input: ./pypresso h5md
output: Traceback (most recent call last):
  File "h5md.py", line 42, in <module>
    write_force=True, write_species=True, write_mass=False, write_charge=True, write_ordered=True)
  File "/Users/diogo/Simulation/simulacaotestespersonal/espresso/src/python/espressomd/io/writer/h5md.py", line 48, in __init__
    "ScriptInterface::Writer::H5mdScript")
  File "espressomd/script_interface.pyx", line 29, in espressomd.script_interface.PScriptInterface.__init__
ValueError: Class 'ScriptInterface::Writer::H5mdScript' not found.

What is the problem?

Install: -> brew install hdf5 -> doing
input: brew install hdf5 --with-mpi output: error

Thank you,

Diogo

**Comment by pdebuyl** [comment]
Hello,

1. You need to have a "toolchain" of compiler / MPI / HDF5 that is consistent (i.e. check that you can compile *and* run a sample MPI program and a sample HDF5 program). Else, either the installation is not appropriate or you need to specify explicilty the components with ccmake (what compiler is used, what mpi library is used, etc).
2. If you modify any of these components, the simplest course of action to reconfigure cmake is to remove all build files and run cmake again.

If you need more support, here or on the mailing list, it is best to state completely your software configuration (OS, compiler, etc), how you configured espresso, and the full text log of the errors.

**Comment by KaiSzuttor** [comment]
I think that @diogomusical did not use the current python branch but some release. We updated the error message if the h5md feature is not available in #2591. As @pdebuyl already mentioned you need a parallel version of the hdf5 library installed, otherwise you cannot use the h5md feature.
