### ISSUE TITLE
nvcc fatal: The version ('60000') of the host compiler ('clang') is not supported

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2645]
Solution:
```bash
cmake .. -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) \
         -DCUDA_NVCC_EXECUTABLE=$(which clang++)
make
```
```
[100%] Built target pypresso
```

Original issue:
```bash
cmake .. -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++)
make
```
```
[  4%] Building NVCC (Device) object src/core/CMakeFiles/EspressoCore.dir/electrostatics_magnetostatics/EspressoCore_generated_p3m_gpu_cuda.cu.o
nvcc fatal   : The version ('60000') of the host compiler ('clang') is not supported
CMake Error at EspressoCore_generated_p3m_gpu_cuda.cu.o.Release.cmake:218 (message):
  Error generating
  /work/jgrad/espresso-fork/build/src/core/CMakeFiles/EspressoCore.dir/electrostatics_magnetostatics/./EspressoCore_generated_p3m_gpu_cuda.cu.o
```
Using Ubuntu 18.04, Clang 6.0.0-1ubuntu2, nvcc 9.1.85, commit 169dff01db97.

**Comment by fweik** [comment]
Actually, it only checks the c compiler, so if you set a supported c compiler (which is not used), and a newer clang++ as cxx compiler, chances are that it will just work. What is your issue with this?

**Comment by mkuron** [comment]
CUDA 9.1 probably doesn't support Clang 6. your solution uses Clang _instead_ of nvcc, which works and is what we do inside tge clang Docker image.

**Comment by jngrad** [comment]
The nvcc error message has been an annoyance on my desktop machine for a few months now. Yet the nvcc9/clang6 combination already works out-of-the-box on the containers, so I didn't see the point of tinkering with local installations of various nvcc/clang versions until a combination that worked was found. This is time-consuming when you don't have root privileges; unpacking the clang-7 Ubuntu package in a local directory is simply not an option for CMake. Only yesterday did I learn about the undocumented `-DCUDA_NVCC_EXECUTABLE` option when looking into CMakeLists.txt. This is good enough for my needs. And today I found out about  the `NVCC` environment variable in the clang6 container, which probably does the same thing? Our CMake logic for enabling CUDA is not documented.

This can be closed: typing the nvcc error message in the Beta search bar now returns this workaround.
