### ISSUE TITLE
analyze distribution has no testcsae

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#266]

**Comment by AlexanderWeyman** [comment]
Draft - given distribution can not be reproduced with this testcase

[testcase_analyze_distribution.txt](https://github.com/espressomd/espresso/files/64042/testcase_analyze_distribution.txt)

[testcase2_analyze_distribution.txt](https://github.com/espressomd/espresso/files/64041/testcase2_analyze_distribution.txt)

**Comment by RudolfWeeber** [comment]
Seems to be duplicate of rdf. Will be removed

**Comment by davidsean** [comment]
fixed via #1660
