### ISSUE TITLE
System.seed for RNGs 

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#2660]
In the Philox version of the Langevin thermostat I require the user to set the seed for the RNG,
just like @KaiSzuttor in PR #2348 for the LB thermostat. In the current code, `system.seed` is required and a int-per-node array that seeds d_random() calls. This is still used in the following files:

- dpd
- reaction_ensemble.cpp
- bonded_interactions/thermalized_bond.hpp
- object-in-fluid/affinity.hpp
- swimmer_reaction.cpp
- polymer.cpp

Opt 1. Do we want to replace the old RNG with Philox in all these cases and have a separate seed given via the python interface (in addition to the internally handeled 'Salt') for each method? This would allow to get rid of system.seed at some point.

Opt 2. Or should we switch system.seed to int and use it for all counters. This would save us from requiring seeds for each method.

Opt 3. We could also keep both RNGs and specify what is affected by system.seed in the docs.
However this is bad I think.

I'd like to know this before I apply the new thermostat interface (currently Opt 1.) to all testcases, samples etc..

**Comment by KaiSzuttor** [comment]
the old interface has to go. it does not make sense to provide a seed and not knowing for which method it is used. so definitely we want opt1
