### ISSUE TITLE
Refactor Utils::get_linear_index / unravel_index

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2669]
these two functions purpose is very similar and should be combined into one. They differ in row-/column major and the possible number of dimensions. See #2640

**Comment by jngrad** [comment]
The `Utils::ravel_index()` and `Utils::unravel_index()` functions are no longer used in the Reaction Methods code. They are still used in the `Histogram` class, but we can refactor the histograms using `boost::multi_array` without any major performance penalty (~1% slower compared to the current implementation), in which case we could remove these two functions.
