### ISSUE TITLE
Integration scheme not documented

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2680]
The integration scheme for Langevin dynamics is not documented, at least I could not find something in the documents or code comments. LD can be done in different ways with a Verlet scheme, in Espresso it is even more complex because it also supports dissipative and inertia coupling to LB, DPD, anisotropy and more, as well as combinations of those. I think this is a central point that should absolutely be documented an well understood.

In my opinion the following points should be addressed, not only documenting what
_is_ implemented, but also explaining why it is done in a specific way if there is a choice:

- Discretization of Langevin Dynamics, including extensions like anisotropy, body and
  space fixed external foces, more complex drift terms like DPD, citing literature sources for the     validity of the scheme.
- Discretization scheme for NpT LD, including in combination with other extensions,
  citing literature sources for the     validity of the scheme.
- Discretization of the dissipative coupling with LB, citing literature sources for the validity
  of the coupled scheme.
- Discretization of the inertia coupling with LB, citing literature sources for the validity of
  the coupling scheme.

Without having clarity about these points, we can in my opinion not say with confidence
what the code actually calculates, and whether the numeric calculations approximate
some physical model in any limit. 
This understanding is also needed to properly handle initial forces in the future.

**Comment by RudolfWeeber** [comment]
@christophlohrmann,

The Velocity Verlet integrator is in 
src/core/integrate.cpp:integrate_vv()
Literature: Allen Tildesley, also, a google search for 
langevin velocity verlet
yields a few papers discussing the combination of the two.

LB Coupling:
src/core/grid_based_algorithms/lb_particle_coupling.cpp and lb_interpolation.cpp
Citations are in the code:
Ahlrichs and Duenweg, JCP 111(17):8225 (1999))

User's guide source files are in 
doc/sphinx

**Comment by fweik** [comment]
I think for the LB coupling stuff https://www.sciencedirect.com/science/article/pii/S0010465514002094
is a good starting point.

**Comment by christophlohrmann** [comment]
Ok thanks
