### ISSUE TITLE
Identify (and resolve) missing coverage for ELC

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2685]

**Comment by fweik** [comment]
See [coverage report](https://codecov.io/gh/espressomd/espresso/src/python/src/core/electrostatics_magnetostatics/elc.cpp). The misses mostly seem related to the `space_layer` parameter.

**Comment by KonradBreitsprecher** [comment]
Should be covered by an additional test with particles more close to the boundaries.
I'm a bit afraid but will try..

**Comment by RudolfWeeber** [comment]
@reinaual, what is the status here?
