### ISSUE TITLE
Move developer guide to Wiki on Github

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2690]

**Comment by jngrad** [comment]
If the `Page` box on the wiki becomes too crowded, we could consider [creating a sidebar](https://help.github.com/en/articles/creating-a-footer-or-sidebar-for-your-wiki), for example to create a developer guide hierarchy and group the ES meeting proceedings together. The `Page` box would still be available, but collapsed.

**Comment by jngrad** [comment]
I'm halfway through it. @fweik does [section 4.3](http://espressomd.org/html/doc/dg.html#adding-calls-to-the-master-slave-framework) reflect our current MPI communication strategy?

**Comment by fweik** [comment]
No. I can bring that up to date next week, I think I won't get to that tomorrow.
