### ISSUE TITLE
Cython and Python3: string conversion

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2709]
Python2 uses ASCII strings by default (`'ü'` returns `'\xc3\xbc'`) and UTF8 strings when explicitly specified (`u'ü'` returns `u'\xfc'`). In both cases the `print()` function is able to correctly display the accentuated character. Python3 uses UTF8 strings by default (`'ü'` returns `'ü'`).

Runtime error messages from the core are all ASCII, so they can be displayed natively in Python2 but in Python3 there is a character type mismatch, so Python3 stores these exception strings as bytestrings (`b'P3M...'`), which the `print()` function cannot display as a regular string. For example, newline characters don't create a new line:
```
  2/124 Test #103: drude ...................................***Failed    4.51 sec
b'P3M tune parameters: Accuracy goal = 1.00000e-04 prefactor = 1.38936e+03\nSystem: box_l = 5.00000e+01 # charged part = 4 Sum[q_i^2] = 8.58771e-01\nfixed mesh 18 18 18\nfixed cao 5\nmesh cao r_cut_iL     alpha_L      err          rs_err     ks_err     time [ms]\n18   5   4.71820e-01 6.42609e+00 9.98037e-05 7.071e-05 7.043e-05 0.41    \n\nresulting parameters: mesh: (18 18 18), cao: 5, r_cut_iL: 4.7182e-01,\n                      alpha_L: 6.4261e+00, accuracy: 9.9804e-05, time: 0.41\n'
ERROR: bond broken between particles 6 and 7. Distance vector: 2.77812 -7.05504 -20.1874
ERROR: bond broken between particles 6 and 7. Distance vector: 2.77812 -7.05504 -20.1874
```

This is maybe related to the following error that prevents sphinx from building the documentation when compiling espresso with python3:
```
Warning, treated as error:
autodoc: failed to import module u'espressomd.__cinit__'; the following exception was raised:
/work/jgrad/espresso-fork-PR/build/src/python/espressomd/_init.so: undefined symbol: PyUnicode_InternFromString
doc/sphinx/CMakeFiles/sphinx.dir/build.make:57: recipe for target 'doc/sphinx/CMakeFiles/sphinx' failed
make[3]: *** [doc/sphinx/CMakeFiles/sphinx] Error 2
CMakeFiles/Makefile2:778: recipe for target 'doc/sphinx/CMakeFiles/sphinx.dir/all' failed
make[2]: *** [doc/sphinx/CMakeFiles/sphinx.dir/all] Error 2
CMakeFiles/Makefile2:785: recipe for target 'doc/sphinx/CMakeFiles/sphinx.dir/rule' failed
make[1]: *** [doc/sphinx/CMakeFiles/sphinx.dir/rule] Error 2
Makefile:383: recipe for target 'sphinx' failed
make: *** [sphinx] Error 2
```

**Comment by jngrad** [comment]
Update: actually the bytestrings seems to print just fine with `./pypresso ../testsuite/python/drude.py` (compiled with python3), so it's more of a CTest-related issue.

**Comment by mkuron** [comment]
We have wrappers that should take care of the conversions:

https://github.com/espressomd/espresso/blob/bd1cce48aef5634fca29db584664760703bdceff/src/python/espressomd/utils.pyx#L126-L157

**Comment by jngrad** [comment]
Currently only I and Docker containers ([maxset-python3](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/98289), [osx-python3](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/98303), [python3](https://travis-ci.org/espressomd/espresso/jobs/520028202)) can reproduce the issue with bytestrings. By default C strings captured by Cython are stored as bytestrings and need to be cast using your function `to_str()` ([Cython docs](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#passing-byte-strings)). However the drude issue above comes from this function:
https://github.com/espressomd/espresso/blob/0524a202e9cd6f6e7e6d3a4bc5ff793b7252695f/src/python/espressomd/electrostatics.pxd#L132-L138
which doesn't cast the bytestring to a Python string (`cdef char *` is a bytestring in Cython), so the print statement sends a bytestring to stdout, i.e. `b'P3M tune parameters: Accuracy goal = ...\n'`. We cannot use `print(to_str(log))` here because of a cryptic `NameError: name 'to_str' is not defined` (even though `is_valid_type()` from the same `utils.pyx` is used here without this warning).

If you cannot reproduce this encoding issue, then your Cython version is interpreting `cdef char *` as a Python unicode string. We need to find out why. I originally thought about the Cython [auto encoding decoding feature for C++ strings](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#auto-encoding-and-decoding) that can be enabled at the script level with [a comment line](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#auto-encoding-and-decoding), at the CMake level with [compiler options](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) or at the function/class level with [fixtures](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#locally), but these directives are not used anywhere in the espresso code and CMake logic. The feature is not working properly for Cython < 0.29.6 anyway ([release notes](https://github.com/cython/cython/blob/master/CHANGES.rst#0296-2019-02-27)). I and `maxset-python3` use 0.26.1, `osx-python3` uses 0.27.3, `python3` uses 0.23.4. However 0.29.6 is not shipped in any Ubuntu version yet.

Concerning the `PyUnicode_InternFromString` issue, it was solved by using Sphinx built for Python 3.
