### ISSUE TITLE
LB Interpolation test works only for a particular velocity value

### ISSUE THREAD

**Issue by jainka** [espressomd/espresso#2727]
In relation to #2702 it was found that if the boundary velocity in lb_interpolation.py is changed, the test fails (assertions become unequal). Even a slight deviation in velocity (from 1.0 to 1.001) leads to a failure.

**Comment by KaiSzuttor** [comment]
this was trivial to fix, ~~what is of more concern is that the test breaks for values of agrid != 1~~
