### ISSUE TITLE
check_sphinx runs the build again

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2764]
See https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/104578,
from my understanding of the config it should get the the build folder from
the `cuda-maxset` job by artifact, but apparently this is not working.

**Comment by fweik** [comment]
I think it is not using the same parameters, but I'm not sure.

**Comment by KaiSzuttor** [comment]
its the timestamp... the checked out files are newer than the artifact.

**Comment by fweik** [comment]
Ah that makes sense. Can you think of a fix (besides touching the files)?
