### ISSUE TITLE
Un-needed compile time featues

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2807]
These don't exist in the core:
OVERLAPPED, EWALD_GPU, ICC_DEBUG

This doesnot have Python support
metadynamics

Features without performance impact:
IMMERSED_BOUNDARIES
OIF_GLOBAL_FORCES (probably)

Are we keeping the noise shapes for the LB?

Has anyone ever used those debug flags (appart from ADDITIONAL_CHECKS)?

**Comment by pkreissl** [comment]
I'll have a look.
