### ISSUE TITLE
Script-interface managed list-like properties are not checkpointed

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2823]
eg. LB Boundaires
The LB Instance is restored via the checkpoitning module and the populations via the LbFluid's load_checkpoint().

**Comment by RudolfWeeber** [comment]
The default serialization method from ScriptObjectBase saves the values of the parameters.
ScriptObjectRegistry manages its own container which is not a parameter in the ScriptInterface sense.
So, probably, it needs its own implementation of get_state() and set_state()

**Comment by fweik** [comment]
Then this is also true for e.g. constraints?

**Comment by RudolfWeeber** [comment]
and auto_update_accumulators and ek boundaries

**Comment by RudolfWeeber** [comment]
The fix was merged
