### ISSUE TITLE
Homogeneous magnetic field

### ISSUE THREAD

**Issue by vanadiuz** [espressomd/espresso#2824]
Dear developers,

how to turn on a uniform magnetic field? Unfortunately, there is not clear description in the documentation.

I have an idea, but absolutely not sure, if it's true:

```
H_constraint = espressomd.constraints.HomogeneousMagneticField(H=np.array([0.0, 10.0, 0.0]))

system.constraints.add(H_constraint)
```

Best regards
Vania

**Comment by RudolfWeeber** [comment]
Your code looks correct. In case an np.array is not accepted as parameter, please use a python list [].

**Comment by vanadiuz** [comment]
Thanks, Rudolf!
