### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2832]
At the moment scripts posting to GitHub PRs ([maintainer/gh_post_style_patch.py](https://github.com/espressomd/espresso/blob/python/maintainer/gh_post_style_patch.py), [maintainer/gh_post_docs_warnings.py](https://github.com/espressomd/espresso/blob/python/maintainer/gh_post_docs_warnings.py)) do not check for HTTP status codes. When the status code isn't 200, `comments.json()` returns a dict of the HTTP status instead of a list of key/value pairs, leading to cryptic messages ([logfile](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/112798)) because iterating a dict generates strings:
```
Traceback (most recent call last):
  File "/builds/espressomd/espresso/maintainer/gh_post_docs_warnings.py", line 43, in <module>
    if comment['user']['login'] == 'espresso-ci' and prefix + '_warnings.sh' in comment['body']:
TypeError: string indices must be integers
```
The python `request` module has a section on [checking status codes](https://2.python-requests.org/en/master/user/quickstart/#response-status-codes). We should implement a retry mechanism with delay for `requests.get()`, but for `requests.delete()` and `requests.post()` I'm not sure. Currently both Python scripts run through a bash script without `set -e`, so they fail silently.

**Comment by KaiSzuttor** [comment]
maybe we should have a look into github api wrappers, *e.g.* [PyGithub](https://github.com/PyGithub/PyGithub)

**Comment by KaiSzuttor** [comment]
this has not been an issue for quite some time

**Comment by jngrad** [comment]
> this has not been an issue for quite some time

True. Furthermore, the scripts now halt when an HTTP error code is found, instead of printing a cryptic error message (5636ee03cda5).
