### ISSUE TITLE
ROCm jobs have random failures

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2858]
Especially  `test_checkpoint_ek.gpu_0` and `save_checkpoint_ek.gpu_0`:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117494
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117559
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117560
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117562

**Comment by fweik** [comment]
Maybe same reason as fixed by #2856?

**Comment by jngrad** [comment]
The last commit of that PR actually failed the ROCm job twice with the same error message.

When restarting some of these failing jobs 2 days ago I noticed two ROCm jobs could run simultaneously. But our AMD runner coyote9 has a single GPU. Starting two GPU tests on the same device could cause theses failures.

**Comment by mkuron** [comment]
I have now set `concurrent = 1` in /etc/gitlab-runner/config.toml on coyote9. It used to be 3. We'll see whether that helps.

**Comment by jngrad** [comment]
The issue didn't surface since @mkuron's fix, I'm closing this.
