### ISSUE TITLE
LB CPU: Node velocity and interpolated velocity inconsistancy

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2870]
The node velocity getter in lb.cpp includes the +ext_force_density/2 term,
wheras the node_v() getter in lb_interpolation.cpp does not.
The test_a_ext_force_density() test in lb.py fails for lb cpu if an interpolated velocity is checked in additoin to the node velocity.

**Comment by jngrad** [comment]
@RudolfWeeber I can't find the code you're referring to in the 4.0, 4.1 and 4.2-dev releases. Is this ticket still relevant?

**Comment by RudolfWeeber** [comment]
I guess we are not looking into this anymore. This is resolved in the Walberla branch which has full double buffering for applied forces.
