### ISSUE TITLE
LB: Unclear unit conversion for density

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2871]
In lb.pxd in the node density getter, the result from the core funciton is devided by agrid^3.
My understanding so far was that the md and lb density unit were identical.
Either this is not so, or the getters in the core should be called lb_lbnode_get_mass()

**Comment by KaiSzuttor** [comment]
why should they have the same units?

**Comment by KaiSzuttor** [comment]
The density in the LB world is expressed with respect to a grid unit volume.

**Comment by KaiSzuttor** [comment]
why should they be identical? You have to convert between the different length dimensions.

**Comment by RudolfWeeber** [comment]
Right.
