### ISSUE TITLE
LB CPU+GPU: ext_force_density ignored in 1st time step

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2875]

**Comment by KaiSzuttor** [comment]
@RudolfWeeber could you please add some info?

**Comment by RudolfWeeber** [comment]
The setter updates the value in lb params and broadcasts it but does not update the per-node values being used in the upcoming integration step.
These only get updated after the integration. 
I have fixes for this in the Walberla branch. I'll extract those.

**Comment by itischler** [comment]
i could take a look at it on coding day
