### ISSUE TITLE
When staqrting Espresso (tcl an py), I get an error about h5md.tcl missing

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#288]

**Comment by KaiSzuttor** [comment]
couldn't reproduce that error

**Comment by fweik** [comment]
Also can't proproduce. Closign for now, that stuff has changed anyway.

**Comment by KaiSzuttor** [comment]
That can happen if ESPRESSO_SCRIPTS variable is linking to another scripts folder of another espresso in your environment.
