### ISSUE TITLE
Remove remaining manual memory management

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2900]
E.g. replace `Utils::malloc` and `Utils::realloc` by `std::vector` or similar.

**Comment by jonaslandsgesell** [comment]
I ll remove what is obvious

**Comment by RudolfWeeber** [comment]
This is merged, right?

**Comment by fweik** [comment]
No, not resolved.

**Comment by jngrad** [comment]
coding day: identify places where malloc and realloc are still used

**Comment by jngrad** [comment]
`grep -r --color -P '(m|re)alloc(?=\()' src/core`

Most matches are in `src/core/grid_based_algorithms`, which will be replaced by waLBerla. The only exception is `src/core/ParticleList.hpp`, where the container size grows linearly (a std::vector grows exponentially).

**Comment by fweik** [comment]
This, and then there is `Utils::List`, which is used for the bond and exclusion lists. Those have the advantage of being smaller than most implementations of `std::vector` if they are empty (because most impls store 3 pointers, and `List` is a pointer and two ints). In principle both can be replaced by boosts vector, which is the same size and has a customizable growth strategy, but this requires a newer boost version than what we currently require. (It's not clear which one).

**Comment by jngrad** [comment]
The LB GPU mallocs leak memory, the `EK_DEBUG` feature doesn't compile and the EK VTK files are broken.

**Comment by KaiSzuttor** [comment]
> The LB GPU mallocs leak memory, the `EK_DEBUG` feature doesn't compile and the EK VTK files are broken.

i think we can live with the leak for now, given that this part of the code will get replaced soon
