### ISSUE TITLE
Throw Error if system is partial periodic and particle is placed out of box in nonperiodic box direction

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2905]
Would have catched the problem I saw today

**Comment by fweik** [comment]
In the periodic direction particles are allowed to leave the box. There is nothing wrong with that.

**Comment by jonaslandsgesell** [comment]
Yes, but in the nonperiodic direction Espresso should throw an error.

**Comment by fweik** [comment]
I meant non-periodic.

**Comment by fweik** [comment]
This is expected behavior.

**Comment by jonaslandsgesell** [comment]
How is this sensible?
