### ISSUE TITLE
Whitelist latest python-sphinx versions

### ISSUE THREAD

**Issue by Raketenjoint** [espressomd/espresso#2920]
@KaiSzuttor blacklisted `python-sphinx` version 2.1.0 in the `requirements.txt` with commit #2884 .
Do you want to hold it back permanently?
Which change is incompatible?

[changes according to homepage](https://www.sphinx-doc.org/en/master/changes.html)
Release 2.1.0 (released Jun 02, 2019)
Incompatible changes
- Ignore filenames without file extension given to Builder.build_specific() API directly
- #6230: The anchor of term in glossary directive is changed if it is consisted by non-ASCII characters
- #4550: html: Centering tables by default using CSS
- #6239: latex: xelatex and xeCJK are used for Chinese documents by default
- Sphinx.add_lexer() now takes a Lexer class instead of instance. An instance of lexers are still supported until Sphinx-3.x.

I try to package espresso for my rolling release distro Arch but downgrading packages is not recommended.

**Comment by KaiSzuttor** [comment]
reason is a bug see https://github.com/sphinx-doc/sphinx/issues/6440

**Comment by Raketenjoint** [comment]
Thank you for the reference. So we have to wait for a fix from the source.
