### ISSUE TITLE
Check whether MMM1d does not suffer from errors in the original article

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2925]
There is a comment pointing out some errors in the original article of MMM1D. It needs to be verified and documented that the implementation is free from those errors:

Comment on “MMM1D: A method for calculating electrostatic interactions in one-dimensional periodic geometries” [J. Chem. Phys. 123, 144103 (2005)]
https://aip.scitation.org/doi/abs/10.1063/1.2346457

@mkuron can you comment on this?

Feel free to close if the implementation is free from those errors.
PS: the mailing lists did not contain a discussion

**Comment by jonaslandsgesell** [comment]
According to Christian the implementation is free from those errors and they were only introduced in the print version of the article.

**Comment by mkuron** [comment]
I can confirm that. My GPU implementation from 2013 took into account that comment and it produces the exact same results as the CPU implementation.
