### ISSUE TITLE
OpenMPI incompatible with 32bit builds using overlay2 backend

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2934]
The `ubuntu:armhf` container cannot use OpenMPI on the bwCloud (see espressomd/docker#108). In the rare event where a scheduled pipeline must be restarted during the day, while many jobs are already running, there is a chance the `ubuntu:armhf` job will be assigned to a bwCloud machine, which will cause a failure:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/128008

**Comment by mkuron** [comment]
If you want to test on bwCloud to actually fix the issue, I can create a virtual machine there for you. Just email me your SSH public key.

**Comment by KaiSzuttor** [comment]
don't put any resources into something we won't keep anyway...

**Comment by mkuron** [comment]
It might be an actual issue on armhf. I doubt that anyone will ever run Espresso productively on that, but if we want to be available in the Ubuntu repositories some day, it might be worth fixing anyway.

**Comment by RudolfWeeber** [comment]
On Mon, Jun 24, 2019 at 08:10:02AM -0700, Michael Kuron wrote:
> It might be an actual issue on armhf. I doubt that anyone will ever run Espresso productively on that, but if we want to be available in the Ubuntu repositories some day, it might be worth fixing anyway.
We can just use our own ppa, if it comes to that. I'd also not invest work in this.

**Comment by jngrad** [comment]
@michael I couldn't get the `openmpi-bin` package to run properly in the armhf image on the vm:
```bash
mpirun --version
```
```
/usr/bin/mpirun: Error: unknown option "--version"
```
```bash
mpirun
```
```
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
```
I've recompiled the binary from the same sources [3.1.3](http://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.gz) and installed it, but got linking issues:
```bash
mpiexec --version
```
```
/usr/local/bin/mpiexec: symbol lookup error: /usr/local/bin/mpiexec: undefined symbol: opal_libevent2022_event_base_loop
```
The package [bug tracker](https://launchpad.net/ubuntu/+source/openmpi/+bugs) shows no such error. I can't find what causes this issue. Since this is hardware-dependent, I'd say we only run the armhf job on our machines.

**Comment by mkuron** [comment]
I can actually reproduce this on my desktop machine (lama). It's not the QEMU version (I tried 4.0.0, 3.1.0 and 2.12.0), so it's somehow OpenMPI-related. Since the command line parsing is already broken, I guess it's something in the emulated integer arithmetic. For now, I guess we can just ignore this error since the QEMU builds are not run automatically anymore. By the time of our next release, the bug might already be fixed.

**Comment by mkuron** [comment]
Even worse: this is not related to bwCloud or QEMU at all. I have reproduced this issue with the i386 image on my desktop machine. So somehow the newer OpenMPI version doesn't like the new AMD CPUs.

```
mkuron@lama:~$ docker run -it gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/ubuntu:18.04 mpiexec -n 2 hostname
574c6b47d435
574c6b47d435
mkuron@lama:~$ docker run -it gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/ubuntu:i386 mpiexec -n 2 hostname
mpiexec: Error: unknown option "-n"
```

Looking at strace, it seems like OpenMPI just doesn't even attempt to load any of its modules from /usr/lib/i386-linux-gnu/openmpi/lib/openmpi3. If it doesn't do that, then of course it doesn't have any functionality (including these simple command-line arguments).

**Comment by mkuron** [comment]
Turns out the AMD CPUs are just correlation, not causation. It is actually the choice of the Docker storage backend that matters. These images work fine when that is configured to be _aufs_ (as is the case when Docker has been upgraded from some older version or when the scratch filesystem doesn't support certain flags), but fail when I switch to _overlay2_.
elk, lama, and bwCloud use _overlay2_, while the coyotes use the deprecated _aufs_ for historical reasons.

The images were built on bwCloud or elk, which means that they were built on _overlay2_. I have no idea why the choice of backend makes any difference here, but I will try to find out.

Switching storage backends is also not an option: it seems like we need to build on _overlay2_ and run on _aufs_ to avoid the error, and that would require separate build machines for the docker and espresso repos. So I need to figure out what is wrong with _overlay2_.

**Comment by fweik** [comment]
I would suggest to first switch to a single configuration, and then fix that one.

**Comment by mkuron** [comment]
```
$ gdb mpiexec
(gdb) break mca_base_component_repository_add
(gdb) run --version
(gdb) break opal_dl_foreachfile # https://github.com/open-mpi/ompi/blob/v3.1.3/opal/mca/dl/dlopen/dl_dlopen_module.c#L162
(gdb) break opendir
(gdb) break readdir
(gdb) c
Breakpoint 9, 0xf7e9a280 in opal_dl_foreachfile () from /lib/i386-linux-gnu/libopen-pal.so.40
(gdb) c
Continuing.

Breakpoint 26, __opendir (name=0x56574150 "/usr/lib/i386-linux-gnu/openmpi/lib/openmpi3") at ../sysdeps/posix/opendir.c:89
(gdb) c
Continuing.

Breakpoint 25, __readdir (dirp=0x56575c10) at ../sysdeps/posix/readdir.c:41
(gdb) finish
Run till exit from #0  __readdir (dirp=0x56575c10) at ../sysdeps/posix/readdir.c:41
0xf7e9a468 in ?? () from /lib/i386-linux-gnu/libopen-pal.so.40
Value returned is $5 = (struct dirent *) 0x0
(gdb) print ((DIR*) 0x56575c10)->size
$11 = 0
(gdb) print errno
$19 = 75 # EOVERFLOW
```
`readdir` reports the module directory as empty, even though in `strace` I can see that the corresponding `getdents64` syscall reports 120 entries and returns 5000 bytes. Confirmed independently of OpenMPI with
```c
#include <dirent.h>
#include <stdio.h>
#include <assert.h>
#include <errno.h>
#include <string.h>

int main() {
        DIR * d = opendir("/usr/lib/i386-linux-gnu/openmpi/lib/openmpi3");
        printf("opendir: %p\n", d);
        struct dirent * de = readdir(d);
        printf("readdir: %p\n", de);
        if(!de)
                printf("    errno: %s\n", strerror(errno));
        closedir(d);
        return 0;
}
```
which produces a pointer on aufs and `(nil)`/EOVERFLOW on overlay2. This means it's a kernel or glibc bug.

**Comment by mkuron** [comment]
The above minimal example works if I add
```c
#define _XOPEN_SOURCE
#define _FILE_OFFSET_BITS 64
```
which suggests that aufs and OpenMPI use 32-bit inodes, while overlayfs uses 64-bit inodes. Looking at the inodes directly, aufs seems to generate synthetic ones starting at 0 (so the issue would only appear if there were more than 4 billion files in the image), while overlayfs takes the lower 32 bits of the real inode and puts the layer number into the higher 32 bits. Now I just need to figure out how to change that...

**Comment by RudolfWeeber** [comment]
This affects only our CI infrastructure, where we gave up on 32bit builds.
