### ISSUE TITLE
LB Stress with thermalization broken

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2953]
On the GPU, when thermlization is enabled, the stress of consecutive time steps
alternates in sign. 
These are the first few enties of the acf. The box dimension was 11^3.
[ 2.90652982e-03 -2.33863491e-03  2.12404584e-03 -1.84423365e-03 1.65836345e-03 -1.44680546e-03  1.30270577e-03 -1.13605354e-03 1.02269729e-03 -8.90200318e-04  8.03000184e-04 -6.97059505e-04 6.31005908e-04 -5.46651711e-04  4.94775232e-04 -4.24976026e-04 3.85637808e-04 -3.28608186e-04  2.97681513e-04 -2.52380716e-04 2.30676038e-04 -1.94551742e-04  1.78710677e-04 -1.49859516e-04 1.38926344e-04 -1.16000798e-04  1.08313036e-04 -8.92120433e-05 8.33521338e-05 -6.94853129e-05  6.54856032e-05 -5.36193475e-05
Integration was for 10^6 steps.

The integral of the acf yields reasonable values for the viscosity, when only measuring every 2nd time step.

The code is
```

import espressomd
import espressomd.lb
from espressomd.interactions import HarmonicBond
import espressomd.lbboundaries
import espressomd.shapes as shapes
from espressomd.observables import StressTensor, LBFluidStress
import tidynamics as td
import numpy as np
import argparse
import scipy
import scipy.integrate

parser=argparse.ArgumentParser()
parser.add_argument("--fluid_density",type=float,required=True)
parser.add_argument("--fluid_visc",type=float,required=True)
parser.add_argument("--agrid",type=float,required=True)
args=parser.parse_args()
kT=1.
# box
dim=11
s=espressomd.System(box_l=[dim*args.agrid]*3)
s.time_step=0.01



# lb
lbf=espressomd.lb.LBFluidGPU(agrid=args.agrid,dens=args.fluid_density,visc=args.fluid_visc,tau=s.time_step,seed=18,kT=1)
s.actors.add(lbf)
s.cell_system.skin=0.01

lb_stress=LBFluidStress()


stress=[]
s.integrator.run(5000)
time=[]
for i in range(1000000):
  s.integrator.run(1)
  x=lb_stress.calculate()
  #print i,x
  stress.append(x)
  time.append(s.time)

stress=np.array(stress)[:,(1,3,4)]
stress= np.average(stress,1)
stress-=np.average(stress)
acf=td.acf(stress)
print acf[:200]
int = scipy.integrate.cumtrapz(y=acf, x=time ,initial = 0.)
print args.fluid_visc
print s.volume()/kT *int[:500]
```

On the LB CPu, the values for the stress are off completely.

**Comment by bindgens1** [comment]
The function  get_mesoscopic_values_in_LB_units 
always refers to n_a.

Probably it should be switched for every second integration step based on the intflag true or false.

**Comment by KaiSzuttor** [comment]
@bindgens1 that's not true. In the kernelcall ```*current_nodes``` is passed which is switched every integration step.

https://github.com/espressomd/espresso/blob/182020aa5d0c09c4283b3b55db7439038e98a7a2/src/core/grid_based_algorithms/lbgpu_cuda.cu#L2675-L2676

https://github.com/espressomd/espresso/blob/182020aa5d0c09c4283b3b55db7439038e98a7a2/src/core/grid_based_algorithms/lbgpu_cuda.cu#L2892-L2914

**Comment by bindgens1** [comment]
@KaiSzuttor 

I just had a quick look and indeed didn't see it. 
It just resembled the same behaviour that was an issue in another project using the GPU Code.
In the light of this: I can't really imagine why it should only work for every second time step if the nodes are indeed switched.

**Comment by RudolfWeeber** [comment]
We'll decide on this based on results from theramlized Walberla LB

**Comment by RudolfWeeber** [comment]
I also saw this behaviour in early results from Walberla's thermalized LB.
A possible explanation would be an overshoot in the stress  relaxation.
In that case, this should go away for lower viscosities or temperatures.

**Comment by KaiSzuttor** [comment]
Do we now know if this is expected or if it's a bug?

**Comment by RudolfWeeber** [comment]
Bug. @pkreissl is looking into it, AFAIK

**Comment by KaiSzuttor** [comment]
is this still up to date?

**Comment by bindgens1** [comment]
I didn't get any news on this here.

**Comment by RudolfWeeber** [comment]
>is this still up to date?

 

No. The current belief is that consecutive stress measurements are affected by over-correction. The behavior is comparable to what can be observed in lbmpy.

**Comment by KaiSzuttor** [comment]
so I "believe" that this issue can be closed
