### ISSUE TITLE
s.cell_system.tune_skin() ignores short range cutoff

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2961]
The maximum skin considered must be curtailed such that
r_c +skin <0.5 l
where r_c = short range cutoff, l = local box length.
Alternatively, it needs to throw a clear error msg.
To reproduce:

```
import espressomd
s=espressomd.System(box_l=[1,1,1])
s.time_step=0.01
s.non_bonded_inter[0,0].lennard_jones.set_params(epsilon=1,sigma=0.2,cutoff=0.3,shift="auto")
s.cell_system.tune_skin(min_skin=0.1,max_skin=0.6,tol=0.05, int_steps=3)
```

**Comment by pkreissl** [comment]
I can have a look at this at the coding day.
