### ISSUE TITLE
Dipolar P3M not tested

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2966]
DP3M has not tests at all. @RudolfWeeber what do you think how to do this?

**Comment by RudolfWeeber** [comment]
It was compared against p2nfft. Regression of #2833.

**Comment by fweik** [comment]
Ok, I'll leave this open because P3M is not mentioned in the other ticket (and technically it's an independent issue).

**Comment by fweik** [comment]
Also I think a test independent of scafacos would be nice.

**Comment by fweik** [comment]
Sorry I failed to grep correctly, there is a test against stored data.
