### ISSUE TITLE
Evaluating forces executes collisions

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3027]
Running `System.integrator.run(steps=0)` does run the collision detection, and therefor mutates the system. I think it should not, as system mutation should only occur if the system is propagated. Otherwise we have results depending on how often you looked at the system,
which would create our very own measurement problem.
Removed the collision handling in the initial force calculation breaks some tests. @RudolfWeeber is this behavior desired? I'm sure the collisions can be tested without this...

**Comment by RudolfWeeber** [comment]
>Running System.integrator.run(steps=0) does run the collision detection, and therefor mutates the system. I think it should not, as system mutation >should only occur if the system is propagated. Otherwise we have results depending on how often you looked at the system,
>which would create our very own measurement problem.
I was under the impression that recalculating the forces with integrator.run(0) only fils the collision queue but does not call handle_collisions().

So this should have no effect. If that is not so, I’ll take a look once I’m back at work in a week.

**Comment by fweik** [comment]
I thought so too, but it actually calls `handle_collisions` and the tests fail if this is removed. Thank you. (That's in line 253 of `integrate.cpp`).

**Comment by fweik** [comment]
Also the collision detection kernel should not be a part of the force kernel (`add_non_bonded_pair_force`).
