### ISSUE TITLE
Charged system tutorials run energy minimization with thermostat turned on

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3030]
This is not best practice and probably should not be shown in beginners tutorials. Also in this case it just makes convergence slower.

**Comment by jngrad** [comment]
With `system.thermostat.turn_off()` I couldn't get the minimization loop to converge, the `min_dist` variable seems to cycle between 0 and half `max_sigma`. With
```python
energy = system.analysis.energy()
print("Before Minimization: E_total = {:.2e}".format(energy["total"]))
system.minimize_energy.init(f_max=10, gamma=50.0,
                            max_steps=1000, max_displacement=1)
system.minimize_energy.minimize()
energy = system.analysis.energy()
print("After Minimization: E_total = {:.2e}".format(energy["total"]))
```
the energy cycles between 8e15 and 2e23.

**Comment by fweik** [comment]
Those parameters are not sensible.

**Comment by jngrad** [comment]
Didn't realize `max_displacement` was per time step. Using the steepest descent from part 2 of the tutorial (with an even smaller displacement) gave good results.

The C++ code for the steepest descent algorithm could be improved. For example, the maximal displacement is stored but never used, `f_max` is not a force cap (!), and `f_max`/`max_displacement` actually aren't compared to the respective normalized vectors but to their X, Y, Z coordinates.
