### ISSUE TITLE
Bonded potentials lacking documentation

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3049]
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L2529
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L2777
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L2859
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L2905
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L2951
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L3149
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L3195
* https://github.com/espressomd/espresso/blob/25cefff6ea21a5c1b0f0735fa7b32ec40995ff17/src/python/espressomd/interactions.pyx#L3250

**Comment by jngrad** [comment]
* AngleHarmonic, AngleCosine, AngleCossquare have some docs in [sections 7.3.1., ...](http://espressomd.org/html/doc/inter_bonded.html#harmonic-angle-potential) but constructor parameter descriptions would indeed be nice
* other classes should definitely have docstrings

**Comment by jngrad** [comment]
Would that be ok to move OIF interactions to the end of the [page](http://espressomd.org/html/doc/inter_bonded.html) and place the thermalized distance bond from the end of the page to the bonds section?
