### ISSUE TITLE
ENGINE: Test single time step behavior or depend on EXPERIMENTAL_FEATURES

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3052]

**Comment by fweik** [comment]
I think the first step is to split this up. As far as I can there are two modes, either the force dipole or a body fixed drift velocity. The latter is uncritical can can be moved out of the feature, this is the same as `LB_ELECTROHYDRODYNAMICS` just body-fixed, and is uncritical as the coupling points are just the same as for normal LB particles. The other one is the force dipole which uses an extra coupling site, this is where the problems are. Also of this only applies to LB, for langevin, both features are the same, an can be dealt with e.g. by allowing body-fixed external forces.

**Comment by RudolfWeeber** [comment]
On Mon, Aug 05, 2019 at 07:52:46AM -0700, Florian Weik wrote:
> I think the first step is to split this up. As far as I can there are two modes, either the force dipole or a body fixed drift velocity. The latter is uncritical can can be moved out of the feature, this is the same as `LB_ELECTROHYDRODYNAMICS` and is uncritical as the coupling points are just the same as for normal LB particles. 
The v_swim stuff depends on the particle orientation, whereas electrohydrodynamics does not. But it can probably still be fused

**Comment by fweik** [comment]
Yes, it's a body-fixed drift velocity. In the same sense that for Langevin its an body-fixed external force.

**Comment by hmenke** [comment]
I don't really understand what has to be done here.  If you can tell me, I would be willing to take this on to prevent removal of yet another feature.

**Comment by KaiSzuttor** [comment]
move from a data-driven test to a single step integrate and check the effect test.

**Comment by KaiSzuttor** [comment]
> to prevent removal of yet another feature

As stated in the title of this issue, we would mark the feature experimental as we cannot guarantee the correctness if there is no test. Actually, we shouldn't have merged it with the data driven test in the first place.

**Comment by RudolfWeeber** [comment]
@hmenke, thanks. Please coordinate with @christophlohrmann, who is also looking at this.
The initial plan was to place the swimmer on an lb node, use a dipole length of n*agrid and an orientation parallel to lattice vectors. 
Then, the outcome of a single coupling can be written down in Python and checked.

We're going to expose the LB node force applied in the last time step, so that that can be checked as well.
In a second step, force interpolation can be implemented as in lbf.get_velocity_at_pos(), then the test can be generalized to other orientations, dipole lengths and swimmer positions.

**Comment by christophlohrmann** [comment]
From manual inspection of swimmer trajectories I found the following:
- swimmers with v_swim don't get a second force center, the `dipole_length` parameter does not do anything
- swimmers with f_swim seem to work qualitatively as long as they do not cross a periodic boundary, in that case the second force center is not applied to the fluid (current python branch)
- In @fweik's pull request #3025 the second force center is correctly applied when crossing boundaries. The test probably fails because the second force center of particle with `id=2` touches the box edge at the very first time step

**Comment by fweik** [comment]
@christophlohrmann this isn't only about the force on the fluid: To get the correct forces on the particle, the fluid velocity at the force dipole site needs to be known. The forces for the particles
are calculated elsewhere and only for local particles, so the velocity (called `v_source`) needs to
be communicated back. I'm not sure that this part is working correctly.

**Comment by christophlohrmann** [comment]
@hmenke  I have two questions about the `rotational_friction` feature:
1.) why is this an "active" feature? I understand that it needs the fluid velocity at a body-fixed distance but the rotational friction does not depend on self propulsion.
2.) where does the formula for omega_swim come from? I do not see why the cross product has to be normalized and then rescaled with the norm of the velocity difference.
