### ISSUE TITLE
Improve tutorial tests

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3058]
Some tutorial tests only execute the tutorials, without checking numerical results:

- [x] 02 charged system: [part 2](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_02-charged_system-2.py)
- [x] 04 LB: [part 2](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_04-lattice_boltzmann_part2.py), [part 3](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_04-lattice_boltzmann_part3.py)
- [ ] 05 raspberry electrophoresis: [tutorial](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_05-raspberry_electrophoresis.py)
- [x] 10 reaction ensemble: [script cpH](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_10-reaction_ensemble__scripts__RE_vs_cpH.py), [script cpH polymer](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/tutorials/test_10-reaction_ensemble__scripts__RE_vs_cpH_poly.py) (removed)

**Comment by jonaslandsgesell** [comment]
01 lennard jones fluid: We could show the published result for the LJ rdf in the tutorial and use it in the test for the LJ tutorial:
https://www.sciencedirect.com/science/article/pii/S0301010404005452
However the number of fit parameters seem excessive to me. Maybe we can only check for the limiting behaviour lim r-> 0 g(r) =0, lim r-> infty g(r)=1.
