### ISSUE TITLE
Add section about interface changes to release notes

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3088]
* Removal of global seed
* Seed passed to individual methods: 
  * Langevin thermostat
  * DPD
  * LB Thermostat
  * Thermalized bodns
  * Reaction ensemble
* Changed LB Activation
* Changed polymer setup

**Comment by jonaslandsgesell** [comment]
The 

* Wang-Landau-reaction ensemble
* reaction ensemble
* constant pH ensemble 
* Widom insertion method
also take seeds now.

**Comment by RudolfWeeber** [comment]
https://github.com/espressomd/espresso/wiki/es_41_release_notes

**Comment by pkreissl** [comment]
Taking care of this.

**Comment by pkreissl** [comment]
The interface changes have been added to the draft for the release notes. Please remember that the links in on the release notes wiki page currently point to the **ESPResSo devel** documentation. Upon release the 4.1 documentation should be uploaded and the links updated accordingly.

**Comment by pkreissl** [comment]
@RudolfWeeber, you want to keep this issue open for last-minute interface changes before the deadline? Or is this one resolved?
