### ISSUE TITLE
Bump required cmake version to 3.10

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3090]
Cmkae fails for 3.8 and older.

**Comment by RudolfWeeber** [comment]
Ubuntu 16.4 has 3.9.2, which seems to work. So using that. PR is forthcoming

**Comment by jngrad** [comment]
This means we can replace [`if(NOT ${CMAKE_VERSION} VERSION_LESS "3.12")`](https://github.com/espressomd/espresso/blob/29488596c0ea6b8842fa0d5fded554d2c5df2947/CMakeLists.txt#L25) by the more readable `if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.12")` and remove the checks for [3.5.2](https://github.com/espressomd/espresso/blob/29488596c0ea6b8842fa0d5fded554d2c5df2947/CMakeLists.txt#L67) and [3.7.0](https://github.com/espressomd/espresso/blob/29488596c0ea6b8842fa0d5fded554d2c5df2947/testsuite/CMakeLists.txt#L4-L7).

**Comment by RudolfWeeber** [comment]
OK. It's more complicated. Travis uses 3.9.2 on its runners. Ubuntu 16.4 has 3.5.
It's not clear to me under what conditions older cmake versions work.
I'm not going to work on this for 4.1
