### ISSUE TITLE
Decide on minimum required versions for dependencies after 4.1

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3093]

**Comment by jngrad** [comment]
* Python (currently >= 3.3), Cython (currently >= 0.23)
* CMake: discussion in #3090
* boost: versions below 1.67 make the [CMake logic convoluted](https://github.com/espressomd/espresso/blob/d14acdb8642e3546b95a4a3ad9880df6422bf0b5/CMakeLists.txt#L378-L403),  dockerfiles require patches
* python packages: numpy, scipy, pylint, vtk, etc. should be written to [`requirements.txt`](https://github.com/espressomd/espresso/blob/python/requirements.txt)
* MPI via OpenMPI: depending on the OS, a different minimum version is required

**Comment by jngrad** [comment]
Concerning version numbers for python dependencies, the version numbers of the corresponding packages in the Ubuntu 16.04 repository (which we currently support in the Clang 6 image) would offer a conservative estimate, unless stated otherwise, for example `pint` is pinned to a higher version due to numpy-related compatibility bugs in the version available on Ubuntu.

**Comment by hmenke** [comment]
Also #1644 requires at least Boost 1.65.1, because it's now using Boost.Spirit X3 which is relatively new.

**Comment by jngrad** [comment]
Update: a discussion took place in [es meeting 2019-11-26](https://github.com/espressomd/espresso/wiki/Espresso-meeting-2019-11-26)
We'll probably need to increase the boost requirements in two steps: first 1.58, which we have to support until the Ubuntu 20.04 LTS release (we need to support Ubuntu 16.04 LTS until then), then 1.65. Python versions 3.3 and 3.4 are only supported on CentOS SCLo.

**Comment by jngrad** [comment]
Once we get rid of `clang:6.0` in CI (which uses 1.58), we should be able to bump to 1.65, which is used by `osx` in CI. We'll then be able to simplify CMake and remove all `#if BOOST_VERSION`. Python itself and Python packages will need to be kept in sync with NEP 29 (#3421), which should not be difficult considering we support Ubuntu LTS versions for 3 years.

**Comment by RudolfWeeber** [comment]
Based on Ubuntu 20:
* Remove Cuda 9 asupport
* Cuda 11 with coverage in every build
* CMake 3.16
* Cython 0.29
* Python 3.6
* Boost 1.66

Drop Centos build. Clusters use custom compilers and libraries via modules anyway.

**Comment by jngrad** [comment]
Boost 1.66 needs to be delayed, ICP machine won't be upgraded to boost 1.71 until another 2 weeks.
