### ISSUE TITLE
Add installation instructions for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3094]

**Comment by jngrad** [comment]
Here is a starting point for the documentation (thanks @RudolfWeeber):
> Install WSL 2 according to https://docs.microsoft.com/en-us/windows/wsl/install-win10 , Install Ubuntu from the Microsoft Store, Select run from the start menu and run "ubuntu", Follow installation instructions for Ubuntu, run "explorer.exe ."  to launch a Windows file explorer in your home dir.

The documentation in [installation.html](https://espressomd.github.io/doc/installation.html#installing-requirements-on-other-linux-distributions) could look like this:
* 2.1.2. Installing requirements on other Linux distributions
* 2.1.3. Installing requirements on Windows via WSL
* 2.1.4. Installing requirements on Mac OS X

I managed to install all Ubuntu dependencies on a Windows virtual machine using [this command line](https://github.com/jngrad/espresso/blob/a49bd89fbd5645f630fc10efa28577eb0fa27d01/.github/workflows/build.yml#L28) and could build ESPResSo and pass the tests.
