### ISSUE TITLE
Affinity needs to be refactored

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3121]
* The application of forces should not be mixed with creating/removing bonds.
This part of the functionality needs to be moved to collision detection and the upcoming bond breakage.

* There should be separate non-bonded interactions for separate force expressions.

* There is no test coverage.

* In the interest of performance, if the debugging file I/O is still needed after tests are written, it should probably be ifdef'ed.

* I have the impression, that the parameter 'type'  encodes two things (type and output period) which have nothing to do with each other.

**Comment by fweik** [comment]
This feature does no longer exist.
