### ISSUE TITLE
Langevin Test Fails on the institute machines

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#3135]
```
./pypresso ../testsuite/python/langevin_thermostat.py 
...F../testsuite/python/langevin_thermostat.py:49: DeprecationWarning: Passing normed=False is deprecated, and has no effect. Consider passing the density argument instead.
  vel[:, i], range=(-minmax, minmax), bins=n_bins, normed=False)
.s..

FAIL: test_03__friction_rot (__main__.LangevinThermostat)
Tests the rotational friction-only part of the thermostat.

Traceback (most recent call last):
  File "../testsuite/python/langevin_thermostat.py", line 184, in test_03__friction_rot
    o0 * np.exp(-gamma_r_i / rinertia * system.time), atol=5E-4)
  File "/tikhome/jlandsgesell/.local/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/tikhome/jlandsgesell/.local/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.0005

Mismatch: 100%
Max absolute difference: 0.00050059
Max relative difference: 0.00014899
 x: array([3.359489, 3.359489, 3.359489])
 y: array([3.35999, 3.35999, 3.35999])

----------------------------------------------------------------------
Ran 8 tests in 0.506s

FAILED (failures=1, skipped=1)
```

**Comment by jngrad** [comment]
[numpy.histogram docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html):
> normed : bool, optional
> 
>     Deprecated since version 1.6.0.
> 
>     This is equivalent to the density argument, but produces incorrect results
>     for unequal bin widths. It should not be used.
> 
>     Changed in version 1.15.0: DeprecationWarnings are actually emitted.

Our [requirements.txt](https://github.com/espressomd/espresso/blob/b363e1dd62bf3c97dc6fd3f536807b8125d18673/requirements.txt) doesn't say anything about the version number of numpy required in espresso. I'd say we replace `normed` by `density` in all calls to `np.histogram()`. Affected files:

* testsuite/python/langevin_thermostat.py
* testsuite/python/lb_thermostat.py
* testsuite/python/thermalized_bond.py

Concerning the test itself, I can't get it to fail on my machine using espresso devel and numpy 1.16.4.

**Comment by KaiSzuttor** [comment]
the deprecation warning is not connected to the failing test

**Comment by jonaslandsgesell** [comment]
I also use numpy version 1.16.4 and the current development branch

**Comment by KaiSzuttor** [comment]
please check what the difference is to the environment used in CI

**Comment by jngrad** [comment]
please post your myconfig.hpp

**Comment by jonaslandsgesell** [comment]
#define EXPERIMENTAL_FEATURES
#define EXTERNAL_FORCES
#define MASS
#define EXCLUSIONS
#define BOND_CONSTRAINT

/* Rotation */
#define ROTATION
#define ROTATIONAL_INERTIA

/* Electrostatics */
#define ELECTROSTATICS
#define VIRTUAL_SITES_RELATIVE
#define LENNARD_JONES
#define LENNARD_JONES_GENERIC
#define GAY_BERNE

**Comment by jngrad** [comment]
I can also get it to fail with maxset.hpp minus the `PARTICLE_ANISOTROPY` feature
