### ISSUE TITLE
system.analysis.linear_momentum is fishy

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3145]
because it uses
mass * velocity +Force/2 *timestep / mass (statistics.cpp:predict_momentum_particles())
for the particle momentum, independently of wheter or not the fluid momentum is requested or not.

I think, the F/2 in the particle momentum may be wrong even in conjunction with LB particle coupling, since:
* not all the forces on the particles originate from the LB coupling
* It is not clear to me, whether the LB coupling forces on the particles are behind by 1/2 dt in the first place.

I suggest to delete this function and expose the fluid momentum to Python directly.
Particle momentum can be calculated in Python using
np.matmul(system.part[:].v.T,system.part[:].mass)
or a 2-line loop.

**Comment by KaiSzuttor** [comment]
resolved in #3156

**Comment by RudolfWeeber** [comment]
Is that change already mentioned in the release notes in the ES wiki? Otherwise, please do so.
