### ISSUE TITLE
Coulomb tuning fails CI on AMD GPU

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3147]
Over the last 2 days:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/157535
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/157613
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/157493
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/157874
Restarting the job often fixes it.

**Comment by RudolfWeeber** [comment]
Wasn’t there a hack in the testsuite preventing p3m_gpu from running on the AMD GPU. That was, IIRC, for a specific card ID. Now, we have a different card in the new CI machine.

**Comment by mkuron** [comment]
Is there a reason why we never looked at why the tuning selects a bad set of parameters?

**Comment by mkuron** [comment]
To reproduce this issue locally, use lama (which has an AMD GPU) and run two instances of the test simultaneously. When only one is running, the issue does not occur. 
```bash
for i in $(seq 100); do
    echo $i
    ../../pypresso coulomb_tuning.py > tuning_${i}a.log 2>&1 &
    ../../pypresso coulomb_tuning.py > tuning_${i}b.log 2>&1 &
    wait
done
```
