### ISSUE TITLE
Python files indentation

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#315]
For debugging its a lot easier to find wrong indentation if indentation levels are clearly distinguishable (just experience when trying to debug some part of the interface).
Its quite easy to change that, simply by letting autopep8 make indentations with 4 spaces.

**Comment by fweik** [comment]
We should at least force consistent indentations. Maybe with a maintainer check. Is autopep8 safe? Can we run that automatically against valid python?

**Comment by KaiSzuttor** [comment]
autopep8 does nothing else then doing correct indentation if you dont turn on the "agressive"-flag.
The more elegant way would be to let pep8 check for wrong indentation by travis and through an error, so the user will have to take care by himself?

**Comment by fweik** [comment]
Sounds reasonable. Can you add that to the travis config?

On Thu, May 28, 2015 at 3:36 PM, Kai Szuttor <notifications@github.com>
wrote:

> autopep8 does nothing else then doing correct indentation if you dont turn
> on the "agressive"-flag.
> The more elegant way would be to let pep8 check for wrong indentation by
> travis and through an error, so the user will have to take care by himself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/315#issuecomment-106313012>
> .
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by KaiSzuttor** [comment]
Yes, ill try to add that. But for now should i also correct indentation for already existing python files?

**Comment by fweik** [comment]
Yes.
