### ISSUE TITLE
Numpy deprecated API calls

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#316]
The cython code uses parts of the Numpy C-API that will be deprecated in Numpy 2.0.

**Comment by HaoZeke** [comment]
Would this be the cause of this error? [Using python version 2.7.10]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espressomd/__init__.py", line 38, in <module>
    from espressomd.system import System
  File "espressomd/system.py", line 3, in <module>
    from espressomd import _system
  File "espressomd/_system.pyx", line 25, in init espressomd._system (_system.cpp:6849)
    from actors import Actors
ImportError: No module named actors
>>>

**Comment by fweik** [comment]
No. The Numpy warnings are just warnings. This seems to be a different
problem. Which version of Espresso are you using?

On Thu, Jun 11, 2015 at 1:14 PM, HaoZeke <notifications@github.com> wrote:

> Would this be the cause of this error? [Using python version 2.7.10]
>
> Traceback (most recent call last):
> File "", line 1, in
> File "espressomd/*init*.py", line 38, in
> from espressomd.system import System
> File "espressomd/system.py", line 3, in
> from espressomd import _system
> File "espressomd/_system.pyx", line 25, in init espressomd._system
> (_system.cpp:6849)
> from actors import Actors
> ImportError: No module named actors
>
>    —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/316#issuecomment-111087654>
> .
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by HaoZeke** [comment]
This is ESPResSo-3.4-dev-1003-g82a0aa2-dirty-git.

I've cloned the master branch and built from that..

**Comment by fweik** [comment]
Could you please checkout the current master an retry. I think this issue has been fixed. If not please open a ticket and give proper description there.
