### ISSUE TITLE
Guard CUDA-specific statement in Barnes Hut

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3187]
The following conditional macro is undefined behavior:
https://github.com/espressomd/espresso/blob/03536720f4ac54a3ea201ed9f71265a13d6d8cd5/src/core/actor/DipolarBarnesHut_cuda.cu#L845-L850
because `CUDA_VERSION` expands to nothing. To get it we need to `#include <cuda.h>` somewhere, and then we need to guard the conditional above with an additional check for CUDA via Nvidia. It is used twice in that file and causes the warning `__all() is deprecated in favor of __all_sync() and may be removed in a future release` during compilation in the cuda10 job ([logfile](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/164292)).

@mkuron do you know which if branch (`__all_sync` or `__all`) should be taken on HIP/AMD?

**Comment by fweik** [comment]
Are you sure about the "undefined behavior"? cppref says
> After all macro expansion and evaluation of defined [...], any identifier which is not a boolean literal is replaced with the number ​0​ [...].

which suggests that `CUDA_VERSION >= 9000` just evaluate to false if `CUDA_VERSION` is not defined.

**Comment by jngrad** [comment]
I should have looked harder. This explains why the macro takes the second branch.

**Comment by mkuron** [comment]
HIP still uses the `__all` branch. `__all_sync` does not exist there. So the current branching is correct, but you indeed need to add something like
```c++
#ifdef __CUDA__
#include <cuda.h>
#endif
```
to the beginning of the file.

**Comment by jngrad** [comment]
I'll add the include. For the conditional, I'd argue we should write
```c++
#if !defined(__HIPCC__) && CUDA_VERSION >= 9000
```
because testing a value that does not actually exist (when compiling with HIP) does not make sense, right?

**Comment by mkuron** [comment]
Actually, change it to `defined(__CUDA__) && CUDA_VERSION >= 9000`. One could also use hipcc to compile for a CUDA target, so there are situations where your suggestion would not work...
