### ISSUE TITLE
Files with same name, only difference is case

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#321]
Is it good practice to do so? I just encountered a problem when cloning espresso to my mac, because the filesystem is not case sensitive and therefore it cant distinguish between that files.
(src/tcl/actor/ewald... and src/tcl/actor/Ewald...)

**Comment by mkuron** [comment]
It's obviously bad practice. However, it looks like these two files are almost identical, so one of them was probably checked in by accident and is not even compiled. It appears as if the lower-case version is the unnecessary one. Please delete that, see if Espresso compiles and submit a pull request that deletes these two files.
