### ISSUE TITLE
`reaction_ensemble` module contains several independent classes

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#3284]
the `reaction_ensemble` class now contains several methods, not just the eponymic `ReactionEnsemble`. Perhaps it would be more appropriate to give a more generic name to the whole class, e.g. `reaction_mehods` or `chemical_reactions`.

Please also note that the Reaction ensemble itself hosts a MC method for configurational moves in the canonical ensemble (i.e. acc=min(1,exp(-\beta Delta E)))

Not sure what a good name for the module would be... Maybe something related to Monte-Carlo methods.

_Originally posted by @kosovan in https://github.com/espressomd/espresso/pull/3254_

**Comment by kosovan** [comment]
I think that `MC methods` is a good name for the class, if there are no other MC methods implemented in some other classes, Otherwise, it might lead to even more confusion than now.
