### ISSUE TITLE
Requirements for reworked collision detection

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3296]
This is my understanding of a dicsussion during the Espresso offline meeting

The feature creates bonds between colliding particles. 
It can additionally creates "non-sliding contacts" by creating virtual sites related to the colliding particles and bonds between those virtual sites.

There is an other "mode", in which, when two particles collide, a third particle in the vicinity is searched. If one is present, angle bonds are created to preserve the relative location of the three particles. 
This mode currently has only one customer, namely the soot particle agglomeration work by @hirschsn.

I'll focus on the 'local' scheme, which deals only with the colliding particles.
The criterion for triggering a collision should include
* a pair of particle types 
* a cut-off distance
* a probability (via a random number)
* question: Are more advanced criteria such as non-bonded pair energy needed? If so, how would one deal with potentials that have a long range contribution?
* Question: are more advanced criteria like distance-dependent probabilities needed?

Actions taken on collision:
* creation of a pair bond between the colliding particles
* type conversion of the colliding particles (to 'inactivate' reaction sites)
* creation of virtual sites relative to the colliding particles and a bond between them. The position of the virtual sites on the line connecting the colliding particles can be chosen. The type of the virtual particles can be chosen.
* safely interupt the integration loop to allow users to do extra model-specific stuff

Design:
* a two-stage process needs to be used. During the pair traversal, potential collisions are queued. Later, the queue is processed and actions are taken
* the code for performing the collision actions needs to be outside the collision detection code. 
* the current collision handling code is too complicated
* The challange is managing the particle ids of newly created particles. The collision detection needs to know these, to place bonds between them
  The most complicated collision action might be this:
    * paritcles p1 and p2 have collided. There types are t1 and t2
    * create a bond of type t_c between p1 and p2
    * create a virtual sites v1 relative to p1. It's position depends on the positoins of p1 and p2 and an offset coming from the collision detection parameters
    * create a virtual site v2 relative to p2 analogously
    * add a bond of type t_v between the virtual sites
    * change type of particle p1 to t1_n
    * change type of particle p2 to t2_n
* I'm under the impression that only two collision modes will remain
  * the two particle one, in which each individual collision action can be activated as needed
  * the three-particle angle bond one

Potential users, please comment on whether that covers your models' requirements.

**Comment by christophlohrmann** [comment]
Sounds good to me. As for the questions: I would be fine with the simple distance criterion.
Potential things to add: 
- collision with shapes
- not looking for collisions in each time step (when e.g. the binding rate is small)
- the collision-action of doing nothing and just making the information of the collision detection available

**Comment by itischler** [comment]
> question: Are more advanced criteria such as non-bonded pair energy needed? If so, how would one deal with potentials that have a long range contribution?
> Question: are more advanced criteria like distance-dependent probabilities needed?

I think for now they are not needed.

For my system I would need the collision detection to be possible between a virtual particle (a point at the surface of a main particle) and a real particle. This would skip the creation of the first virtual site (v1).

**Comment by RudolfWeeber** [comment]
> For my system I would need the collision detection to be possible between a virtual particle (a point at the surface of a main particle) and a real particle. This would skip the creation of the first virtual site (v1).
Do you need the creation of a second virtual site on collision, or just a bond to the colliding (non-virtual) particle?

**Comment by itischler** [comment]
In my cases the second virtual site is not needed. I would only need the bond between the reactive site (virtual particle relative to the catalyst particle) and the colliding particle.

**Comment by bindgens1** [comment]
For me the old bind_centers and bind_at_point_of_collision methods worked fine. Except for the need of a "binding probability" that might be useful like the probability for the bond breaking.

**Comment by hirschsn** [comment]
I want to throw in an additional point: Currently, the collision queue is allgathered on all processes. We could improve this by allgathering the local queues only in the respective process neighborhood.  Potentially, the cell_system could provide a MPI_Comm created by MPI_Dist_graph_create or similar.

**Comment by fweik** [comment]
@hirschsn I agree that this is a good idea, but the definition of neighborhood and the communicator have to be provided by the cell system.

**Comment by hirschsn** [comment]
@fweik Indeed that was also what I meant. Reading the last sentence from my last comment now again, it seems quite cryptic. :)

**Comment by jngrad** [comment]
Closing in favor of #4483.
