### ISSUE TITLE
Python Interface Importing Errors

### ISSUE THREAD

**Issue by HaoZeke** [espressomd/espresso#335]
The system I'm working on is an Archlinux 64-bit core i3 machine.
The sources are pulled from the master branch.
So,
This is ESPResSo-3.4-dev-1009-g69a2b86-dirty-git.
The configuration is done via
./configure --with-cuda=/opt/cuda --with-python-interface --prefix=/usr -v --with-mpi
The default python pointed to is 2.7.10
Running ./pypresso after make & then trying to import espressomd gives
 ./pypresso                                            
Python 2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import espressomd
*******************************************************
*                                                     *
*                    - ESPResSo -                     *
*                    ============                     *
*        A Parallel Molecular Dynamics Program        *
*                                                     *
* (c) 2010,2011,2012,2013                             *
*     The ESPResSo project                            *
*                                                     *
* (c) 2002,2003,2004,2005,2006,2007,2008,2009,2010    *
*     Max-Planck-Institute for Polymer Research       *
*     Mainz, Germany                                  *
*                                                     *
*******************************************************

This is ESPResSo-3.4-dev-1009-g69a2b86-dirty-git.

ESPResSo is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ESPResSo is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espressomd/__init__.py", line 38, in <module>
    from espressomd.system import System
  File "espressomd/system.py", line 3, in <module>
    from espressomd import _system
  File "espressomd/_system.pyx", line 25, in init espressomd._system (_system.cpp:6849)
    from actors import Actors
ImportError: No module named actors
>>>

**Comment by fweik** [comment]
Works for me in b4bcae859cbd5b0ba24da849c58d58074b65587a

**Comment by HaoZeke** [comment]
Now I get this 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espressomd/__init__.py", line 38, in <module>
    from espressomd.system import System
  File "espressomd/system.py", line 3, in <module>
    from espressomd import _system
  File "espressomd/_system.pyx", line 25, in init espressomd._system (_system.cpp:6849)
    from actors import Actors
ImportError: No module named actors

**Comment by tobiasrau** [comment]
I think you are compiling with old makefiles.
Try "make distclean && ./bootstrap.sh && ./configure && make".

**Comment by HaoZeke** [comment]
Worked perfectly. Thanks
