### ISSUE TITLE
blockfile reading

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#337]
When i restart simulation from blockfile checkpoint the following error occurs:
blockfile_read_auto_variable: setmd sd_radius -1.0 reported: radius must be > 0.

without using any feature of stokesian dynamics...

**Comment by HaoZeke** [comment]
Yeah, I've been seeing this error too. Even in the sample scripts.

**Comment by fweik** [comment]
Fixed by #338.

**Comment by RudolfWeeber** [comment]
Looks good, except that project version needs to be changed in CMakeList.txt and maybe also in src/config/version.hpp.in
Once that's done, it's ready

**Comment by RudolfWeeber** [comment]
Sorry, wrong ticket
