### ISSUE TITLE
The ComForce observable should be renamed to TotalForce

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3370]
at least that's what the documentation claims it calculates. That's also what would make sense, physically, I think.
The code currenlty calculates
sum F_i m_i
and doesn't normalize by sum_i m_i. I don't think, that makes sense.

**Comment by fweik** [comment]
If you rename it, it should be called `TotalForce`, which is a more common term (think total charge, total current, total momentum, ...).

**Comment by RudolfWeeber** [comment]
locations to work on:
/src/core/observables
src/script_interface/observables (including intialize.cppp)
src/python/espressomd/observable.py

**Comment by pkreissl** [comment]
I'll work on this one.
