### ISSUE TITLE
Fix Boost tests

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3426]
[`BOOST_CHECK_CLOSE`](https://www.boost.org/doc/libs/1_66_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_close.html) takes a percentage as tolerance. Epsilon values must be multiplied by 100.

In this example, the first line is incorrect:
https://github.com/espressomd/espresso/blob/d553bd52da3a74dc00d177e3ebb9330ff5d4b273/src/utils/tests/int_pow_test.cpp#L43-L44

In this example, the line is correct:
https://github.com/espressomd/espresso/blob/d553bd52da3a74dc00d177e3ebb9330ff5d4b273/src/utils/tests/interpolation_test.cpp#L254

This affects both 4.1 and 4.2.

**Comment by fweik** [comment]
I don't understand the boost documentation.

**Comment by jngrad** [comment]
According to section [tolerance-based comparisons](https://www.boost.org/doc/libs/1_66_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point/floating_points_comparison_impl.html), function `BOOST_CHECK_CLOSE` does a relative comparison and evaluates to `assert(abs(x - y)/abs(x) <= tol && abs(x - y)/abs(y) <= tol)` when both `x` and `y` are non-zero.

In the binary, `::boost::math::fpc::percent_tolerance(std::numeric_limits<double>::epsilon())` is used as the epsilon value, where `percent_tolerance()` divides by 100 while `percent_tolerance_t()` doesn't (according to section [tolerance (decorator)](https://www.boost.org/doc/libs/1_69_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/decorator_tolerance.html)). Here is a MWE:

```c++
#define BOOST_TEST_MODULE tolerance test
#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>
/* compile with g++ test.cc -lboost_unit_test_framework */
BOOST_AUTO_TEST_CASE(tolerance)
{
  BOOST_CHECK_CLOSE(1, 1.01 - 1e-8, 1); // passes: slightly less than 1%
  BOOST_CHECK_CLOSE(1, 1.01 + 1e-8, 1); // fails: slightly more than 1%
}
```
