### ISSUE TITLE
cylindrical_average is broken and should be removed

### ISSUE THREAD

**Issue by itischler** [espressomd/espresso#3450]
Fixing this issue is easy. 
However either a testcase should be written for it, because it was never correct, or remove the `cylindrical_average` completly, because the observable version `CylindricalDensityProfile` does exactly the same and is beeing tested.

**Comment by KaiSzuttor** [comment]
it should go

**Comment by RudolfWeeber** [comment]
If there is really no point in reparing them, please change the issue title

**Comment by pkreissl** [comment]
I could start with this one, tomorrow.
