### ISSUE TITLE
Sort out waLBerla CMake logic

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3454]
Find and implement one of these options:
1. cleanly integrate the waLBerla CMake logic with ESPResSo's
2. treat waLBerla as a module and use the fetch option (requires bumping to CMake 3.11)
3. compile the waLBerla files ourselves

**Comment by RudolfWeeber** [comment]
Regarding 1.
This is currently done via some CMake stuff I found on github. However, it changes the source tree, the way it is currently used.

**Comment by fweik** [comment]
I would strongly prefer the `FetchContent` version.

**Comment by RudolfWeeber** [comment]
On Thu, Feb 06, 2020 at 08:57:05AM -0800, Florian Weik wrote:
> I would strongly prefer the `FetchContent` version.
Bumping cmake version is not that big an issue, as it can be installed via pip.

This variant would have the advantage that the solution might stay functional if Walberla and its build system changes.

**Comment by jngrad** [comment]
@RudolfWeeber The fetch strategy works. You can find my solution in 48959e1e561 (from branch [jngrad/espresso/fix-3454](https://github.com/jngrad/espresso/tree/fix-3454)). The waLBerla CMake variables must be passed to the subproject with `set(WALBERLA_BUILD_TESTS off CACHE BOOL "")` or with `option(WALBERLA_BUILD_TESTS "" OFF )`.

If I correctly understood answers on the CMake mailing list, `option` is just syntactic sugar for the first command. I had to add target aliases in the waLBerla CMake logic to introduce a namespace using a patch file and a sentinel file to only patch once (in case you would run CMake twice).

Target aliases are const references to the original targets. Technically, you still have access to the original targets in the global namespace, i.e. you can drop the `walberla::` prefix in all target dependencies of espresso. In that case CMake seems to correctly figure out which targets belongs to espresso and which belongs to waLBerla despite the name collisions (when I tried it compiled just fine, with no segfault in the python tests). This is actually what is described in the waLBerla [CMake documentation for module dependencies](https://i10git.cs.fau.de/walberla/walberla/blob/master/cmake/waLBerlaModuleDependencySystem.cmake#L31-37), although the namespace version is more convenient for software integrating waLBerla.

@mkuron Not sure if we should integrate that patch in waLBerla. Although it should not cause side effect since the aliases are const references, there must be a better way to create that namespace from our side. Maybe @RudolfWeeber and I can tinker with `cmake/FindwaLBerla.cmake` to create a proper namespace. I've also found a proposal to introduce a namespace in subprojects by simply adding a namespace flag in the `add_subdirectory` CMake function ([cmake/cmake#16414](https://gitlab.kitware.com/cmake/cmake/issues/16414)).

**Comment by RudolfWeeber** [comment]
Thank you. I much prefer this to the current solution. 

 

If there is further need for discussion about raising the CMake requirement to 3.11 on the devel branch, anyone, please speak up by the end of the week.

Otherwise, I’m going to merge @jngrad’s solution into the Walberla feature branch.

@jngrad, @kaiszuttor, @fweik, @mkuron

**Comment by fweik** [comment]
+1

**Comment by jngrad** [comment]
A few points on the currently accepted solution:
* the `target_link_libraries(EspressoCore PUBLIC ${WALBERLA_LIBS})` has `walberla::core` and `walberla::domain_decomposition` linked twice, is this necessary?
* I've updated the branch [jngrad/espresso/fix-3454](https://github.com/jngrad/espresso/tree/fix-3454) with commit ad220de to avoid unnecessary CMake errors for CI images that won't get CMake 3.11
* my namespace solution offers no protection against name collision, e.g. if you accidentally write anywhere `add_library(core SHARED ${EspressoCore_SRC})`, CMake will fail with "add_library cannot create target 'core' because another target with the same name already exists." (can also happen if the waLBerla team one day creates a new target that collides with one of ours)
* importing waLBerla without namespace significantly improves the readability of our CMake logic (see f96c45748 in the alternative branch [jngrad/espresso/fix-3454-no_patch](https://github.com/jngrad/espresso/tree/fix-3454-no_patch))

There is a way to completely decouple our CMake logic from the waLBerla one and avoid name collisions using the CMake feature `ExternalProject`, available since 3.0. It allows us to create a namespace and run the walberla CMake logic in its own environment. It does exactly what we want, unfortunately the entire download, configuration and build process of the external dependency is condensed in a single target that is always out of date. This means *every time* we type any `make` command, e.g. `make check`, it pings the walberla git server to see if the `master` branch has changed (can be turned off with a sentinel and a lot of CMake code), runs the CMake configuration again (cannot be turned off) and runs the build (very fast when no file in the waLBerla source has changed). This is clearly over-engineered, and the configuration step is slow. This solution is implemented in commit 561f86a66205 from [jngrad/espresso/fix-3454-external-project](https://github.com/jngrad/espresso/tree/fix-3454-external-project).

To work around this automatic re-configuration step, I've experimented with a two-step build strategy, where dependencies are built first (in our case `make walberla`, but we could make a generic target `make dependencies` that would handle multiple projects) and then espresso is built with `make`. For a build without waLBerla, we only have `make`, as usual. This solution is implemented in commit 3c757d4d3a94 from [jngrad/espresso/fix-3454-external-project](https://github.com/jngrad/espresso/tree/fix-3454-external-project). This extra command `make walberla` needs to be done only once, but it's still annoying, and `make` won't rebuild the waLBerla static libraries if they were deleted or if their sources changed.

I find it unbelievable CMake doesn't feature a simpler way to setup a namespace include. They could achieve it via `include_subdirectory()` using a PR from the community, via `FetchContent` with an extra keyword, and via `ExternalProject` with an extra flag to toggle off automatic reconfiguration.

This leaves us with 3 options:
* `fix-3454`: the original solution with namespace, risk of name collision
* `fix-3454-no_patch`: simpler solution without namespace, risk of name collision
* `fix-3454-external-project`: two-step strategy with namespace and no risk of name collision

**Comment by jngrad** [comment]
When compiling waLBerla and an `ExternalProject` with Clang 9 and ASAN on Ubuntu 20.04, the CMake output shows `/usr/bin/c++` instead of `/usr/bin/clang++-9` in the configuration step but uses `clang++-9` in the build step, finds `MPI_C` (aka `libmpi.so`) but not `MPI_CXX` (aka `libmpi_cxx.so`, which is in the same folder!!), and fails with `fatal error: 'mpi.h'` because it doesn't find the path to the MPI headers. Manually setting the CMake variables for the MPI compiler and MPI headers doesn't fix the issue. This is a major drawback.

**Comment by jngrad** [comment]
The `FetchContent` solution with namespace `walberla::` was implemented in 8c75d8ea6d86. Closing.
