### ISSUE TITLE
waLBerla unit testing particle coupling

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3455]

**Comment by RudolfWeeber** [comment]
The Walberla LB connection uses full double buffering for the forces.
I.e., it is possible to examine both, the forces to be applied to the fluid in the next time step and those that were applied in the previous time step. 
This makes it possible to test the viscous particle coupling independently.

Note: There is a python test testsuite/python/lb_momentum_conservation.py. For parameters we typically use, stability issues are observed. The direct and full testing of the viscous coupling would be important to understand, whether this is accepatble numerics or an actual bug in the coupling.
Furthermore, the test fails for two mpi ranks.

**Comment by itischler** [comment]
i will look at this on coding day

**Comment by RudolfWeeber** [comment]
I'd suggest the following procedure:
* in the unit test, check that add_force_at_pos() and get_force_at_spo() are consistent. Use positions on the node, central between nodes and shifted non-tivially.
* Add get_last_applied_force_at_pos based on get_force_at_pos with hte last_applied_force_field. 
* Check that after an integration, the outcoem of get_last_applied_force_at_pos matches, what was applied via add_force_at_pos()
* Expose above methods to Python via lb_walberla_interface.cpp and lb_interface.cpp and lb.pyx. Then, the full viscous coupling can be tested, according to the eqn given in lb_particle_coupling.py 

I'd suggest doing this on a single core away from the boundaries first. Once that is validated, one can try nodes close to the domain boundaries of mpi ranks. All ranks with pos_in_local_halo() == true should be able to apply forces.
Note that the forces on ghost layers are currently not communicated. 
This will likely have to be changed, long term.

**Comment by RudolfWeeber** [comment]
This affects lb_momentum_conservation.py which does not work close to the domain boundary. Likely related to all issues pertaining to velocity interpolation at boundaries.
Test disabled in CMake

**Comment by RudolfWeeber** [comment]
lb momentum conservation test and newly added single coupling step force and force balance tests now pass. Closing
