### ISSUE TITLE
Check for side-effects in bonded and non-bonded kernels

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3456]

**Comment by RudolfWeeber** [comment]
Explanation: 
pair force functions (e.g., Lennard Jones) and bonded interaction kernels (e.g., Harmonic, Fene, AngleHarmonic) should only produce forces (and in case of rotation related kernels, torque).
In the past, these kernels were createively re-used for other purposes. We have eliminated some of them, but we aren't sure, we got all.

The task is to open tickets for those kernels, which have side effects, like changing some particle properties, or which have couplings to other parts of espresso, say the system time.
The same goes for the energy kernels.

Starting point may be the calls to short_range_loop() in forces.cpp and energy*.?pp.

**Comment by jngrad** [comment]
You can also check for functions named  `*_energy(...)` and `*_force(...)` in files `src/core/*bonded_interactions/*.hpp`. They should only take const references to objects. If they take a particle pointer as argument, this needs to be reported.

**Comment by pkreissl** [comment]
I'll have a look.

**Comment by pkreissl** [comment]
As far as I am concerned, the interaction kernels seem to not have side-effects.
