### ISSUE TITLE
Find duplicates in Analyze module

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3458]

**Comment by RudolfWeeber** [comment]
Some functionality is available twice identical or quite similar, once in system.analysis and once as an observable in src/core/observables.

The task is to identify those duplicates or close matches and open a ticket for them.
In case of exact matches, the version in src/python/espressomd/analysis.pyx should be removed.

**Comment by jrfinkbeiner** [comment]
Analysis.stress_tensor() and observables.StressTensor both calculate the (instantaneous) total stress tensor. Analysis.stress_tensor() however also returns specific contributions (kinetic, bonded, nonbonded, ...)

**Comment by RudolfWeeber** [comment]
On Tue, Feb 11, 2020 at 04:44:54AM -0800, jrfinkbeiner wrote:
> Analysis.stress_tensor() and observables.StressTensor both calculate the (instantaneous) total stress tensor. Analysis.stress_tensor() however also returns specific contributions (kinetic, bonded, nonbonded, ...)
This probably has to stay for the time being.
observables.StressTensor might be renamed to TotalStressTensor

**Comment by jrfinkbeiner** [comment]
Analysis.linear_momentum() and observables.ComVelocity are fairly similar. 
(One calculates momentum, the other one velocity by just dividing with the total mass in the end.)
linear_momentum() optionally includes LB fluid, ComVelocity does not. ComVelocity inherits from PidObservable...

**Comment by jrfinkbeiner** [comment]
Analysis.center_of_mass() and observables.ComPosition are almost identical.
center_of_mass() takes particle type as argument, ComPosition particle slices (as it inherits from PidObservable). 
(Implementation via statistics.centerofmass() looks nicer to me as it uses Utils::Vector3d, than the implementation in observables.ComPosition)

**Comment by KaiSzuttor** [comment]
is the issue resolved?

**Comment by RudolfWeeber** [comment]
>is the issue resolved?

Yes. I think everything that can (at present) be an observable is.
