### ISSUE TITLE
Removing counter-ions from diamond

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3459]

**Comment by RudolfWeeber** [comment]
The task is to remove the random counter ion placing code from the Espresso core. (src/core/diamond.cpp)
The same can be done by the user in a few lines of Python. Alternatively, ions can be placed randomly by the user and the standard techniques for overlap removal can be used.


Once the counter ion code is gone, the global (non-philox) random number generator and the system seed and user_has_seeded stuff can be removed from src/core/random.?pp
