### ISSUE TITLE
Walberla, prepare for switchable implementations

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3462]
Things like the LB stencil (e.g., D3Q19) are template parameters to Walberla.
The connection code needs to be changed, such that
* there is an abstract base class defining the interface
* and derived classes using different template Parameters, switching details of the implementatoin in Walberla.

My current understanding of how that should be done is to 
* write a base class with abstract member functions
* write a template class inheriting from the abstract base class with the Walberla template parameters exposed as template parameters
* based on the template class, write down classes with fixed template parameters, for all variants, we want to support.

**Comment by fweik** [comment]
The is called the "Type erasure" pattern, an clear cut example can be found at https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Type_Erasure#Example_Implementation_from_Sean_Parent_talk or in Espresso, where the mpi callback handlers in MPICallbacks.hpp are implemented in the same way.

**Comment by KaiSzuttor** [comment]
is this done?

**Comment by RudolfWeeber** [comment]
Yes.
