### ISSUE TITLE
Utils::Array should be equality comparable

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3474]
`template<class T, size_t N> Utils::Array<T, N>` and `template<class U, size_t M> Utils::Array<U, M>`
should be comparable if `T` and `U` are comparable, and `N == M`. Probably the comparison ops from `Vector` can be move to `Array`.

**Comment by jngrad** [comment]
It is unclear, how ESPResSo will benefit from this change. The `Utils::Array` class was mostly used in the CUDA kernels, where none of the convenience helper functions of `Utils::Vector` were useful. With the removal of the LB CUDA kernels in 4.3-dev, `Utils::Array` is now only used in the `LocalBox` class.

While using `Utils::Array` in place of `Utils::Vector` could potentially help improve compilation times (`Utils::Vector` depends on boost::qvm and on many STL headers), any translation unit that includes `Particle.hpp` also has to include `Vector.hpp`, which severely limits the impact of such a change. The walberla bridge is probably the only good candidate.
