### ISSUE TITLE
Walberla: Fix inertialess tracers

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3515]
Points to keep in mind:
* This should only be pursued after the LB momentum conservation test (and thus, standard particle coupling) works.
* The coupling code has been rewritten and now uses methods from lb_interpolation.cpp and lb_particle_coupling.cpp
* The correct catching/throwing of an exception when VS Tracers are used without active LB might be missing
* The test has been disabled at CMake level

**Comment by RudolfWeeber** [comment]
After some fixes, some tests now pass on one mpi core, but not on two.
A single coupling step needs to be tested as in testsuite/python/lb.py test_viscous_coupling.

**Comment by jngrad** [comment]
The test is non-deterministic and fails at random (e.g. for commit f2273d08):
```
 26/140 Test  #63: virtual_sites_tracers_walberla ......................***Failed   18.09 sec
======================================================================
FAIL: test_tribend (__main__.VirtualSitesTracersWalberla)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/espressomd/espresso/build/testsuite/python/virtual_sites_tracers_common.py", line 212, in test_tribend
    self.assertLess(angle, 1E-3)
AssertionError: 0.0011842941618742677 not less than 0.001
```
