### ISSUE TITLE
Walberla: Decide on whether or not programmatic access to LB populations should be possible. 

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3516]
If yes, re-add the implementation.
Keep in mind that the number of values per node is no longer fixed, as other stencils than D3Q19 might be used.

The setter/getter test is currently only tested in lb_walberla.py. Depending on the decision, it should be moved to lb.py or removed.
The lb_walberla.py test is currently disabled at CMAke level. In the end, anything in there that is not covered elsewhere should go to lb.py

**Comment by RudolfWeeber** [comment]
The test in array_properties.py also has to be re-enabled based on the decision

**Comment by jngrad** [comment]
The implementation was re-added in 2f9e8b34bb, which was necessary for checkpointing (#3513). The setter/getter test in `lb_walberla.py` and the check in `array_properties.py` were also re-enabled. The `Vector19d` typedef was removed.
