### ISSUE TITLE
Walberla: Decide on final rules/design of velocity boundary conditions

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3519]
Implementation in grid_based_algorithsm/lbbdounaries.cpp and lbboundaries/LbBoundary.hpp
The lb_boundary_velocity test is disabled at CMake level

**Comment by jngrad** [comment]
The walberla branch now relies on dynamic UBB for the velocity boundary conditions. At the moment, only the no-slip case works.
