### ISSUE TITLE
Scripts to run py style and pylint checks on specified files

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3524]
would be helpful

**Comment by jngrad** [comment]
I have developed such a tool a year ago. It is now a custom git command called `git style` that has the same syntax as `git diff`, e.g. you can filter files by their name with the double dash `--`, by a regex with `-G`, by added/deleted strings with `-S`, or by cache status.

**Comment by RudolfWeeber** [comment]
How do I get it?

**Comment by jngrad** [comment]
Copy `/tikhome/jgrad/bin/git-style` into a folder that is is in your path. `git style -h` for help.

**Comment by jngrad** [comment]
The `pre-commit` tool was added by #3622 to format only changed files.

The `git-style` tool was adapted accordingly. I don't think we should include `git-style` in ESPResSo, as in its current form it would re-introduce the complexity that was removed by #3622 and lead to undesired code duplication. In the future I might rewrite `git-style` to delegate all the version detection and code formatting to the scripts in `/maintainer/format`, but at the moment I need that tool to support both the 4.1 and 4.2 releases.

**Comment by jngrad** [comment]
Let me correct my previous statement: I can't delegate to `/maintainer/format/*.sh` because their command line arguments are populated by the `pre-commit` tool and the filenames are passed one by one by `pre-commit`.
