### ISSUE TITLE
Walberla: Sort out failed assertion in field destructor

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3528]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/208137
In lb_buoyancy.py. I cannot reproduce this locally.
Walberla disagrees with itself about the reference count.

**Comment by RudolfWeeber** [comment]
@mkuron, could you take a look please.
It seems like this is related to boundary handling.
Should there be a corresponding delete to the 
new
in the call operator of Lb_boundary_handling.
The code thee seems to be what is done in all Walberla samples, but the new looks fishy to me.

I'm disabling the buoyancy test for now. It needs to be re-enabled when investigating this.

**Comment by mkuron** [comment]
This happens when the block forest is destroyed at the end. Seems like you are doing something that decrements the refcount of some field by one even though it wasn't incremented before. No idea what could be doing that.

**Comment by RudolfWeeber** [comment]
Likely caused by symbols exisitng in several shared objects. Can't be fixed with the current structure of the Python interface.
We are intentially leaking the pointer at program exit to work around this.
