### ISSUE TITLE
Walberla; sort out parallelization on more than 2 cores

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3529]
Espresso and Walberla currently disagree about the mapping from the integer mpir rank to the region of space allocated to a process.
Row-major vs column-major.

This limits parallelization to 2 cores.

Short term workaround: Switch the mapping in Espresso
Long term solution: Discuss with the Walberla team how we can prescribe a domain decomposition in the block forest creation.

To test this, all the lb related tests should be run on 8 cores. They are limited to 2 in CMake now.

**Comment by RudolfWeeber** [comment]
Seems to be some kind of undefined behavior. This time it appeared in lb_shear.py on the pdf field.
I re-enabled the buoyancy test but forced the maxset-walberla build job to release build type to prevent the assertions to be executed.
This needs to be reverted, when resolving this issue.

**Comment by RudolfWeeber** [comment]
In the cases, where Walberla uses a Cartesian communicator,
src/blockforest/Initialization.cpp:227 matches what Espresso is doing, i.e., delegating the node position to rank mapping to MPI.
When not using a Cartesian communicator, blockforest/loadbalancing/CartesianDistribution.cpp decides. Apparently, it decides the opposite to what MPI is doing.

Ubuntu 18.04 has the broken OpenMPI which prevents use of the Cartesian communicator in Walberla.
Hence, only 2 ranks can be used on the current ICP installation.
The CI for Walberla already runs on Ubuntu 20.04. I just checked that lb_momentum_conservation.py works on 4 ranks, there.


We can either:
1. Decide not to support that MPI version with more than 2 cores in Walberla LB.
2. Patch CartesianDistribution to invert the ordering
3. Implement a clone of CartesianDistribution with the ordering we need.

Concerning
1.: Walberla LB will probably be merged in to the development branch this summer and will be released some time next year. We could decide not to support 18.04 in dev anymore starting this summer
2.: Not pretty, but we can keep the current initialization code as it is.
3.: Implementing the alternative distribution is probably not difficult. We would need a code example on how to setup the block forest with that load balancer, though.

**Comment by mkuron** [comment]
This is hopefully going to be fixed on the Walberla side. https://i10git.cs.fau.de/walberla/walberla/-/issues/117

**Comment by mkuron** [comment]
@RudolfWeeber, could you please test https://i10git.cs.fau.de/walberla/walberla/-/merge_requests/282? That should replace MPI_COMM_WORLD with the Cartesian communicator (and only print a warning message that MPI-I/O will be slower on broken OpenMPI versions).

**Comment by RudolfWeeber** [comment]
@mkuron, works. Thanks. As soon as that's merged in Walberla, and @jgrad's updated patch for the Walberla build system is ready, we can pin to that walberla version and switch all LB tests to max 8 nodes.

**Comment by jngrad** [comment]
@mkuron works for me too, including `lb_momentum_conservation` on 8 cores. I've also updated the CMake patch just now
