### ISSUE TITLE
Failure to invoke espressomd from the python code

### ISSUE THREAD

**Issue by dpo854** [espressomd/espresso#3534]
Hi everyone,
I have installed the latest version of espresso, which is 4.1.2, on my laptop, following the procedure outlined on its documentation website. The installation was quite smooth. However, when I tried to run one of the examples from the website, I ran into the following error. 

  File "/home/debadutta/Downloads/espresso/build/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: /usr/lib/libmpi_cxx.so.1: undefined symbol: ompi_mpi_real

My understanding from similar posts on this website is that such errors are caused by a clash between different versions of one of the requirements. However, owing to my inexperience in software installation, so to say, I am not able to fix the problem by myself. Any help in this regard will be appreciated. 

Thanks,
Debadutta Prusty

**Comment by jonaslandsgesell** [comment]
Hello Debadutta!
> ImportError: /usr/lib/libmpi_cxx.so.1: undefined symbol: ompi_mpi_real

This looks like an MPI error to me. What mpi package and version did you install?

**Comment by dpo854** [comment]
Hi Jonas,
I have the following library installed. 

Intel(R) MPI Library for Linux* OS, Version 2018 Build 20170713 (id: 17594)
Copyright (C) 2003-2017, Intel Corporation. All rights reserved.

**Comment by dpo854** [comment]
By the way, it's running fine on my cluster as well as on my office desktop.

**Comment by KaiSzuttor** [comment]
could you please check which MPI library is found by ```cmake``` and therefore is linked against? You probably have to set the ```LD_LIBRARY_PATH``` environment variable. This is necessary if you have multiple installations of the MPI library on your system.

**Comment by dpo854** [comment]
Doing cmake .. gave me the following:

-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   mpi
--   serialization
--   filesystem
--   system
--   unit_test_framework

**Comment by KaiSzuttor** [comment]
please post the output of the following command (called from your build directory)
``` bash
ldd src/core/EspressoCore.so | grep mpi
```

**Comment by dpo854** [comment]
libboost_mpi.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.58.0 (0x00007febcb506000)
	libmpicxx.so.12 => /opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib/libmpicxx.so.12 (0x00007febcaee7000)
	libmpi.so.12 => /opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib/libmpi.so.12 (0x00007febca1b5000)
	libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007febc9108000)

**Comment by KaiSzuttor** [comment]
so I guess ```/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib``` is not in your ```LD_LIBRARY_PATH```

**Comment by mkuron** [comment]
It‘s in `LD_LIBRARY_PATH `, otherwise `ldd` wouldn‘t pick it up. However, it is clearly mixing the C library (Intel) and the C++ library (OpenMPI?), which cannot work.

This looks like CMake is using the wrong `mpicc` during its MPI detection. Something is wrong in your `$PATH` or `$LD_LIBRARY_PATH` or your Intel MPI installation is incomplete.

**Comment by jngrad** [comment]
@dpo854 did you find a solution?

**Comment by dpo854** [comment]
No. I did not pursue it further since it is running fine on my cluster.
