### ISSUE TITLE
Register ESPResSo in DaRUS

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3565]
* Make the software citable (DOI for every major, minor, patch release), depends on #2253
* Create software metadata (software main contributors, home institute, publications, etc.)
   * The metadata can be retrieved by the Universitätsbibliothek Stuttgart (IZUS)
   * The metadata can be used to create a `CITATION.cff` file
* Links:
   * [DaRUS - the Data Repository of the University of Stuttgart](https://www.izus.uni-stuttgart.de/en/fokus/darus/)
   * [DaRUS repository](https://darus.uni-stuttgart.de/)
   * [Citation File Format (CFF) documentation](https://citation-file-format.github.io/)

**Comment by fweik** [comment]
> DOI for every major, minor, patch release

I don't think this is needed with historic versions.

**Comment by jngrad** [comment]
After discussing the topic with the DaRUS team, we reached the conclusion that DaRUS in its current form wasn't adequate for archiving ESPResSo releases, in comparison to platforms like Zenodo that have more specialized metadata for software.
