### ISSUE TITLE
Add headers to CMake source list

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3592]
We might consider adding header files to the target source as this can improve how some generators (e.g. visual studio) work with the project. I don't think that there is a downside. @KaiSzuttor any opinion on this?

**Comment by fweik** [comment]
Potentially this does not work with our CUDA targets...

**Comment by jngrad** [comment]
CMake 3.23 introduced [file sets](https://cmake.org/cmake/help/latest/command/target_sources.html#file-sets) feature which can be used to mark header files with `HEADERS`. This simplifies deploying header files in the destination include directory during installation, but ESPResSo doesn't ship with header files. It is also supposed to help with IDE integration, but from the little information I could find on that topic, the only use case is to make these header files visible in the file tree. It has been reported that some IDEs don't show header files that are not included in sources files that are part of a CMake target, yet Clion 2021.2.4 and VS Code 1.64.0 do show such files in the tree, and marking them a source header files in CMake has no effect on how they appear in these two IDEs. The feature is also still evolving according to the numerous merge requests attached to its lengthy tracker ticket [cmake/cmake#22468](https://gitlab.kitware.com/cmake/cmake/-/issues/22468).

I can see how useful this is for header-only libraries, but for ESPResSo I'm not totally convinced; it would actually be really easy to forget adding a header file to a CMake target sources, and we don't have any way to test for it. Although I'm not opposed to explicitly listing header files in target sources, I'm not sure how much we would gain from it, and it would make merge conflicts more difficult to resolve. We could revisit this idea if we decide at some point to make ESPResSo usable without the python interface, in which case we would need to deploy header files together with the shared libraries.
