### ISSUE TITLE
Performance regression when evaluating PidObservable

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3600]
Evaluating ParticlePositions for 40k particles takes 40 sec with a current ES, but <0.1s with an older version.
The profile suggests that most of the time is spent in building the particle cache.

Test script:
```
import espressomd
import espressomd.observables

import numpy as np
from time import time

n=40000
s=espressomd.System(box_l=[10,10,10])
s.part.add(id=range(n),pos=np.random.random((n,3))*s.box_l)
obs=espressomd.observables.ParticlePositions(ids=s.part[:].id)
tick=time()
x=obs.calculate()
tock=time()
print(tock-tick)
```

**Comment by fweik** [comment]
Unfortunately `class ParticleCache` is completely incomprehensible to me, I wonder who implemented that monstrosity... :-)

**Comment by fweik** [comment]
#3601 speeds the benchmark up to 15ms. Adding particles is still a little bit slow, but this is a separate issue.
