### ISSUE TITLE
LB Profile observables: incorrect interpolation positoins

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3603]
Can be tested by placing particles at the nodes of the lb, and then comparing
the particle velocities (and FluxDensityProfile) against LbVelocityProfile:

```
import numpy as np
import sys

import espressomd
from espressomd.lb import LBFluidGPU
import espressomd.observables

size_in_agrid = [12,14,17]
agrid = 0.7

box_size = agrid * np.array(size_in_agrid)
dt=0.01


system = espressomd.System(box_l=box_size)
lbf = LBFluidGPU(dens=1,agrid=agrid, tau=dt,visc=1,kT=0)
system.actors.add(lbf)

expected=np.zeros(size_in_agrid+[3])

for i in range(size_in_agrid[0]):
  for j in range(size_in_agrid[1]):
    for k in range(size_in_agrid[2]):
      p=system.part.add(pos=agrid *(np.array((i,j,k))+.5),v=2*np.array((i,j,k)))
      lbf[i,j,k].velocity=p.v
      expected[i,j,k,:]=p.v


lb_vel_profile=espressomd.observables.LBVelocityProfile(
        n_x_bins=size_in_agrid[0],
        n_y_bins=size_in_agrid[1],
        n_z_bins=size_in_agrid[2],
        min_x=0,
        min_y=0,
        min_z=0,
        max_x=system.box_l[0],
        max_y=system.box_l[1],
        max_z=system.box_l[2],
        sampling_offset_x=agrid/2,
        sampling_offset_y=agrid/2,
        sampling_offset_z=agrid/2,
        sampling_delta_x=agrid,
        sampling_delta_y=agrid,
        sampling_delta_z=agrid,
        allow_empty_bins=True)
particle_flux_dens=espressomd.observables.FluxDensityProfile(ids=system.part[:].id,
        n_x_bins=size_in_agrid[0],
        n_y_bins=size_in_agrid[1],
        n_z_bins=size_in_agrid[2],
        min_x=0,
        min_y=0,
        min_z=0,
        max_x=system.box_l[0],
        max_y=system.box_l[1],
        max_z=system.box_l[2])
np.testing.assert_allclose(particle_flux_dens.calculate()*agrid**3,expected)
#np.testing.assert_allclose(lb_vel_profile.calculate(),expected)
print(lb_vel_profile.calculate())
```

**Comment by RudolfWeeber** [comment]
I believe the calculation of sampling positions in LBProfileObservable to be incorrect:
```
  void calculate_sampling_positions() {
    sampling_positions.clear();
    if (sampling_delta_x == 0 or sampling_delta_y == 0 or sampling_delta_z == 0)
      throw std::runtime_error("Parameter delta_x/y/z must not be zero!");
    const auto n_samples_x = static_cast<size_t>(std::rint(
        (box_geo.length()[0] - sampling_offset_x) / sampling_delta_x));
    const auto n_samples_y = static_cast<size_t>(std::rint(
        (box_geo.length()[1] - sampling_offset_y) / sampling_delta_y));
    const auto n_samples_z = static_cast<size_t>(std::rint(
        (box_geo.length()[2] - sampling_offset_z) / sampling_delta_z));
    for (size_t x = 0; x < n_samples_x; ++x) {
      for (size_t y = 0; y < n_samples_y; ++y) {
        for (size_t z = 0; z < n_samples_z; ++z) {
          sampling_positions.push_back(
              Utils::Vector3d{{sampling_offset_x + x * sampling_delta_x,
                               sampling_offset_y + y * sampling_delta_y,
                               sampling_offset_z + z * sampling_delta_z}});
        }
      }
    }
  }
```
In my view:
* rather than the box size, the max_[x,y,z] should be used
* the number of bins should be taken from user input rather than recalculating it. As it is, the sampling_offset has to be removed from the expresssions fro n_samples_[x,y,z]

**Comment by KaiSzuttor** [comment]
> I believe the calculation of sampling positions in LBProfileObservable to be incorrect

Can you explain why you believe this? It's tested in ```testsuite/python/observable_profileLB.py```. The real downside of the implementation is that it's not production ready performancewise.

**Comment by RudolfWeeber** [comment]
Please take a look at the sample code provided in the ticket.

It places a particle at the center of each lb node and then retrieves the info via the lb profile observable. The result from the observable is stlightly shifted, due to a different step with (box_size -sampling_offset)/n rather than box_size/n.

 

The outcome is that the last “row” (result[n,:]) is empty.

This is not so for the FluxDensityProfile observable.

Obviously the two should match.

 

Even if one would argue, that the re-calculation of n and the step with in the observable is correct (which I don’t), the maximum x,y,z specified by the user should be respected. Then, one could specifiy box_size+sampling_offset as max_x,y,z and get the correct spacing back.

 

The observable_profileLB.py test also fails, if you set agrid to .7 and the box size to 17*agrid. I think it depends on whether or not the rint()-call in calculating the sample positions round up or down.
