### ISSUE TITLE
FENE bonds breaking during the simulation

### ISSUE THREAD

**Issue by dpo854** [espressomd/espresso#3605]
What is the default equilibrium bond length for FENE? Is it 1 or zero in distance units? Is it the reason polymer bonds often break during the simulation?

**Comment by KaiSzuttor** [comment]
The default for ```r_0``` is ```0.0```. That may or may not be the source of your issue. Please provide a minimal *not* working example.

**Comment by dpo854** [comment]
I see. But then how do you prevent two adjacent bonded particles from collapsing into each other? Does the non-boned potential act between two bonded particles?

**Comment by KaiSzuttor** [comment]
> Does the non-boned potential act between two bonded particles?

yes

**Comment by fweik** [comment]
In a typical (Kermer-Grest type) polymer model, you have the `r_0` of the bond at zero, but Lennard-Jones (LJ) interactions between the bonds, which keeps them at 1 sigma at equilibrium. This is also stable at unit temperature. You can have a look at `samples/minimal-polymer.py` for a minimal setup, this uses a purely repulsive LJ (=WCA), but this also works with an LJ that has an attractive part.

If you don't have a repulsive interaction between the beads, and don't want them so sit on top of each other, you have to set a non-zero `r_0`.
