### ISSUE TITLE
Replace partcfg[] by a hash-map

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#362]
The 
Particle\* partcfg 
data structure is used for non-parallelized analysis routines.
This is right now an array. 
For some algorithms (notably virtual sites at center of mass), and a few analysis routines, the index of the array has to be the particle's id. 
This is accomplished by sortPartCfg(). 
There are two problems:
- The sorting only works with consecutive particle numbering
- During the "sorting", the particle data exists twice in memory, in addition to the particles stored in the cells of the domain decomposition. For systems with 10000 particles, this is a problem.

Both problems would go away, if partcfg[] was a hash map with particle id as key and the particle data structure as value.

**Comment by fweik** [comment]
Will do.
