### ISSUE TITLE
Switch to c++11

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#363]
We'd like to switch to c++11 for the next major release.

**Comment by mkuron** [comment]
The Cray compiler does not currently have any C++11 support at all. That appears to be slated for inclusion in CCE 8.4 which should be released some time this year.
Cray posts the release notes for their monthly releases at https://twitter.com/craydocs, so to find out if 8.4 is out yet, just check the version listed for Cray Compiling Environment in the PDF file.

Some exotic compilers/platforms might support C++11 even though their standard library might not. One such example is the IBM BlueGene/Q platform with XL C++ compiler 12.1. Version 13.1 should have an updated standard library, but it's currently only available for Linux.

**Comment by RudolfWeeber** [comment]
One of the reasons for having c++11 is probably the dictionary/hash map in the stl. 
We could, of course, use some other hash map implementation for a while until the c++11 situation has converged. 
The cray compiler is probably something, we cannot ignore.

**Comment by fweik** [comment]
std::map was already in c++98. c++11 is more about new language features as auto and range-based for-loops. And for std::vector::data() by which stl-vectors can be transferred via MPI without making a copy first.

**Comment by mkuron** [comment]
According to http://en.cppreference.com/w/cpp/container/vector:
> The elements are stored contiguously \[...\] (since C++03)

According to http://en.cppreference.com/w/cpp/container/vector/data:
> For non-empty containers, returns `&front()`.

So in C++ < 11, we can just replace `std::vector::data()` with `&std::vector::front()`.

**Comment by fweik** [comment]
No. You need a _pointer_.

**Comment by mkuron** [comment]
How is that not a pointer?
```
std::vector<int> v(10,42);
std::cout << &(v.front()) << std::endl;
```
results in e.g. `0x7fe241d00000`. As does
```
std::cout << v.data() << std::endl;
```

**Comment by uschille** [comment]
> One such example is the IBM BlueGene/Q platform

Keep in mind that BlueGene has hit the end of its line.
