### ISSUE TITLE
Charge unit in espresso

### ISSUE THREAD

**Issue by dpo854** [espressomd/espresso#3633]
While going through the page on electrostatics, I realized that the prefactor should be KT*lB/(eo**2) instead of kT*lB as suggested by the package. Most example programs have mentioned the prefactor to be 2 and the charges to be integers.  How do these charges connect to the electronic charge?

**Comment by dpo854** [comment]
I guess the prefactor definition is wrong on the documentation webpage in that it should be eo**2/(4*pi*epsilon0*epsilonr). This makes it equal to lB*kBT and for temperature =1 (in hoomd units), the prefactor is 2 for a sigma value of 0.35 and a Bjerrum length of 0.7 nm, which is the case for water.

**Comment by jonaslandsgesell** [comment]
Indeed, the documentation under http://espressomd.org/html/doc/electrostatics.html is inconsistent. C should be equal to C=eo**2/(4piepsilon0epsilonr) in equation (1) and the equation before needs to be adapated (via using valencies z_i=q_i/e_0)

**Comment by jngrad** [comment]
Should we fix this or not?

**Comment by ggjj11** [comment]
Yes, for clarity this should be fixed.
