### ISSUE TITLE
maintainer/format/clang_format.sh broken

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3649]
It doesn't find clang-format-6.0 even though it is installed:

Could not find clang-format 6.0. /usr/local/stow/llvm-7/bin//clang-format is 7.0.0.

x-bit on the file woudl also be helpful, so they can be called easily

**Comment by KaiSzuttor** [comment]
i think this is an email to support

**Comment by RudolfWeeber** [comment]
No actually. I took a look and the script is wrong. 
there is an underscore instead of a hyphon, so it looks for clang-format_6.0 rather than -6.0
I'll submit a patch tomorrow.
