### ISSUE TITLE
Density profile determination using cylindrical_average

### ISSUE THREAD

**Issue by dpo854** [espressomd/espresso#3655]
Hi everyone,
Does the command "cylindrical_average" have the function of determining ion profiles around an axis?  The reason why I ask this is I am getting a huge standard deviation in density values computed for radial bins even when the number of analyzed frames is 1000. Originally, I was set out to do this density determination manually by creating bins in the radial direction and computing the number of particles in these beans by explicitly looping over all particles. Since this is a huge computational exercise given the fact that thousands of frames need to be analyzed in order to get good statistics, I turned to inbuilt functionalities. However, it turns out that with cylindrical_average, my standard deviation is quite huge (of the order of 10 times the average density for a single bean). It makes me wonder if I understood that functionality correctly in the first place.

Thanks,
Debadutta Prusty

**Comment by KaiSzuttor** [comment]
You can use an observable for that, namely [DensityProfile](http://espressomd.org/html/doc4.1.2/espressomd.html?highlight=observable#espressomd.observables.DensityProfile).

**Comment by dpo854** [comment]
Dear Kai,
What version are you referring to? This one(http://espressomd.org/html/doc4.0.2/espressomd.html) has  cylindrical_average and this one (http://espressomd.org/html/doc/espressomd.html#module-espressomd.analyze) doesn't have it. In the same module (observable), there is an observable for CylindricalDensityProfile. Is it the same as cylindrical_average? If yes, how accurate is it?

**Comment by KaiSzuttor** [comment]
The cylindrical average in the analysis module is deprecated by now (and removed in the current dev version). However, if you need a cylindrical average then you can use the observable, it's the more recent implementation and is tested.

**Comment by jonaslandsgesell** [comment]
Does the CylindricalDensityProfile work with fluctuating particle numbers for a given type (in grand canonical simulations)? Could I obtain the density profile of + ions if they are exchanged with a reservoir (and therefore have varying ids)

**Comment by KaiSzuttor** [comment]
No, because the observables are paritcle-ID based. So, you explicitly have to tell the observable for which ids to track the density.

**Comment by dpo854** [comment]
What is the output structure of observables? It says it's an array, for certain functions such as **CylindricalDensityProfile** (http://espressomd.org/html/doc4.0.2/espressomd.html#module-espressomd.observables). But, when I try to print the output of it, it gives me something else.

**Comment by jngrad** [comment]
Shouldn't it return a 1D list of doubles that can be reshaped with numpy into a 3D grid?
```python
obs_data = cylindrical_density_profile.calculate()
obs_grid = np.array(obs_data).reshape([n_r_bins, n_phi_bins, n_z_bins])
```

**Comment by KaiSzuttor** [comment]
@dpo854 have you looked at this again?

**Comment by dpo854** [comment]
Unfortunately, it's putting out negative values at somepoints for me.

**Comment by KaiSzuttor** [comment]
Could you please provide a minimal example that reproduces your issues.

**Comment by dpo854** [comment]
Hi Kai,
I finally managed to get profiles that make sense physically. However, a question still remains. How does cylindrical_density_profile compute the volumes of the cells? I ask that because the profiles from it are not in quantitative agreement with the results of manual density computations although there is agreement in terms of the general trend in how the density varies in the radial direction. I have attached the plots below for your reference, where the x-axis represents the distance from the cylinder axis in units of the diameter of ions. 
![cation](https://user-images.githubusercontent.com/61341750/85185142-60da3200-b258-11ea-9b53-b3e246a57832.png)
![anaion](https://user-images.githubusercontent.com/61341750/85185148-65064f80-b258-11ea-98ff-a15512a15ebe.png)


P.S- Since the observable "cylindrical_density_profile" requires the ids of the particles of interest to be input into it, I make a list of cations and anions, whose density profiles around a charged polymer are shown above, every time I do a computation manually by looping through each cation and anion. This is so because the particle numbers are changing throughout the simulation and as has been mentioned before, this observable cannot handle variable particle number cases. Another useful piece of info that I would like to run by you is both the number of phi bins and the number of z bins are set to 1 when only radial profiles are the quantities of interest. 

An update- Just to see which one of these methods gives more accurate results, I also solved the same system with Poisson-Boltzmann equation. While I do not expect a perfect agreement between P.B solution and simulation results since the theory is more of an approximation than of an exact solution, I still believe the more accurate method among the above two would be closer to PB. Based on that logic, my conclusion is that I really used it wrongly.

**Comment by jonaslandsgesell** [comment]
For checking with PB you need to go to the low coupling limit of the coupling parameter going to zero. You can achieve this via going to small Bjerrum lengths (high dielectric permittivities). Then the difference between PB and MD solutions has to approach zero too. Please do so and post your comparison again. For a Bjerrum length of smaller than 0.355 Angstrom I would suppose that the difference in Ion density profiles is already small.

I suppose that the density profile observable is not working for fluctuating particle numbers as Kai said so you are probably better off with your own python observable which calculates the positions in cylindrical coordinates and then performs a np.histogram.
