### ISSUE TITLE
Class 'Shapes::HollowConicalFrustum' not found

### ISSUE THREAD

**Issue by parisa-asd** [espressomd/espresso#3657]
hello
my espresso is 4.1.2 on ubuntu 18.04.4
what should I do with ValueError: Class 'Shapes::HollowConicalFrustum' not found.

**Comment by RudolfWeeber** [comment]
Hi, this feature is only part of the development branch of Esprseso (i.e., you have to pull the current Python branch from Github).

Possibly, you are using an older version (such as the 4.1.2 release)?
