### ISSUE TITLE
Future of sublj bond

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3664]
There is a bond type called `subt_lj`, which subtracts the LJ interaction between the bond partners. It seems to me that the same effect can be achieved with an exclusion (which also works for other interaction types, not only for lj). This interaction introduces a cyclical dependency between the bonded and non-bonded interactions? If this is really required, it needs to get its own set of LJ parameters.

@RudolfWeeber @jngrad any feedback on this?

**Comment by RudolfWeeber** [comment]
Wouldn’t an exclusion kill all non-bonded stuff, including DPD?

That’s the only case with two non-bonded interactions I can think of.

**Comment by jngrad** [comment]
I'm not opposed to removing it. It's not very flexible and the `exclusion` list does the same job,  albeit with particle ids instead of types, which makes `subt_lj` only relevant to simulations with particle insertions and deletions. Breaking the non-bonded/bonded cyclic dependency would be advantageous.

**Comment by fweik** [comment]
@jngrad `subt_lj` is a bond, so it acts only between specific particles, not types.

**Comment by fweik** [comment]
@RudolfWeeber exclusions do not affect DPD (nor electrostatics and magnetostatics).

**Comment by RudolfWeeber** [comment]
> <https://github.com/jngrad> @jngrad subt_lj is a bond, so it acts only between specific particles, not types.

Wasn’t there someone on the mailing list using that a while back. But with DPd and electrostatics being un-affected by exclusions, I really cannot imagine the purpose.

**Comment by fweik** [comment]
Last mention on the ML is from 2017...

**Comment by fweik** [comment]
Btw, the same effect can always be reached with just adding an additional type for the particle in question.
