### ISSUE TITLE
Flags in myconfig.hpp are not interpreted correctly.

### ISSUE THREAD

**Issue by HaoZeke** [espressomd/espresso#367]
The following myconfig flags

/* Virtual sites features */
//#define VIRTUAL_SITES_COM
#define VIRTUAL_SITES_RELATIVE
//#define VIRTUAL_SITES_NO_VELOCITY
#define VIRTUAL_SITES_THERMOSTAT
//#define THERMOSTAT_IGNORE_NON_VIRTUAL

Should, as I understand, allow for the thermostat to effect BOTH non-virtual and virtual particles.
However, compilation with these flags makes non-virtual atoms remain stationary, while virtual particles oscilate about their non-virtual particles under the influence of the thermostat.

The compilation was done cleanly, ie.
make distclean
make
make install

The thermostat tested was the langevin thermostat.

**Comment by RudolfWeeber** [comment]
In what version of the code did you see this? If it is development code, please provide the last commit id.

**Comment by HaoZeke** [comment]
I've tested it most recently today. Still getting the same problem.
48541eb77318e39c3db87dd69cf4182f07a9e658 was the latest commit id.
In general are virutal particles not meant to have any interactions?
the correlated real particle moves independently [moreorless] from the virtual particles, making any rigid particle system hopeless..

**Comment by RudolfWeeber** [comment]
Could you provide a short script, please?
