### ISSUE TITLE
cmake-format error does not post the style patch

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3672]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/224599
is probably not what should happen?

**Comment by jngrad** [comment]
Pretty confident I'm the one who suggested to @KaiSzuttor  to add the `|| exit 1` in 0c8382af7f at:
https://github.com/espressomd/espresso/blob/18ffb6f983201436d12b00a23fc127e1e2ede8d3/maintainer/CI/fix_style.sh#L32
I don't remember the motivation behind it, and can't find any trace of that in the 3 PRs on GitHub and in our offline conversation on Mattermost. @KaiSzuttor the `|| exit 1` should be removed. Do you remember what went wrong when `|| exit 1` wasn't present?

**Comment by fweik** [comment]
I think it would  be great if the patch could be posted, because running `clang-format` locally requires the tools, which most people probably don't have installed...

**Comment by jngrad** [comment]
I agree, right now the script doesn't push the patch and this needs to be fixed.
