### ISSUE TITLE
Cryptic cuda error message if no GPU available

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3675]
*e.g.*: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/224552

**Comment by mkuron** [comment]
We should check `cudaGetDeviceCount()` before performing any CUDA operations.

**Comment by KaiSzuttor** [comment]
> We should check cudaGetDeviceCount() before performing any CUDA operations.

every time?

**Comment by mkuron** [comment]
No, just the first time. Trace back where the error message comes from, then add the check before that place. https://github.com/espressomd/espresso/blob/python/src/core/cuda_init_cuda.cu#L42 might be a good place.

**Comment by jngrad** [comment]
We worked around these cryptic errors in CI by adding GPU fixtures in the testsuite.

To generate a meaningful error message, we could add assertions in python classes that rely on the GPU features, either in constructors (1be50234ff) to warn early, or in `_activate_method()` methods, as long as it works with objects created by loading from a checkpoint.

edit: in 1be50234ff I didn't look into GPU-based boundaries

**Comment by KaiSzuttor** [comment]
then someone adds a new gpu feature and you have the same story again... I think we should do that low-level as @mkuron said

**Comment by KaiSzuttor** [comment]
this seems to be resolved
