### ISSUE TITLE
"Current" observable wrong

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3679]
The observable is currently defined as
<img src="https://render.githubusercontent.com/render/math?math=I=\sum_i q_i v_i ">
which has dimensions [length] [charge] [time]^-1. whereas electric current has units of [charge][time]^-1

**Comment by KaiSzuttor** [comment]
actually what is called ```Current``` in the espresso observable is the current density times the volume

**Comment by RudolfWeeber** [comment]
@KaiSzuttor, could you please make a decision with regards to the Current observable.
Remove? Devide by volume and rename to CurrentDensity?

**Comment by RudolfWeeber** [comment]
Will be removed due to wrong units/name. Use FluxDensityProfile instead
