### ISSUE TITLE
Deprecated instructions in CUDA-generated assembly code

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3688]
Building the CUDA sources with Clang 9, CUDA 10.1 and thrust 1.9.5 on Ubuntu 20.04 revealed deprecated instructions in the generated assembly code:

```
ptxas /tmp/DipolarBarnesHut_cuda-a305b3.s, line 2154; warning : Instruction 'vote'
without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued
in a future PTX ISA version
ptxas /tmp/DipolarBarnesHut_cuda-a1b7b7.s, line 5414; warning : Instruction 'shfl'
without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued
in a future PTX ISA version
ptxas /tmp/DipolarDirectSum_cuda-1b6b2e.s, line 4085; warning : Instruction 'shfl'
without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued
in a future PTX ISA version
ptxas /tmp/electrokinetics_cuda-5bd803.s, line 30017; warning : Instruction 'shfl'
without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued
in a future PTX ISA version
ptxas /tmp/p3m_gpu_error_cuda-5a64ff.s, line 11717; warning : Instruction 'shfl'
without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued
in a future PTX ISA version
```

Full log file: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/226271

The `shfl`-related warnings come from code emitted by thrust reductions:

https://github.com/espressomd/espresso/blob/35e0865e6645cc62ed2718ee0eb1600bd9e440e0/src/core/actor/DipolarBarnesHut_cuda.cu#L1174

https://github.com/espressomd/espresso/blob/35e0865e6645cc62ed2718ee0eb1600bd9e440e0/src/core/actor/DipolarDirectSum_cuda.cu#L332

https://github.com/espressomd/espresso/blob/35e0865e6645cc62ed2718ee0eb1600bd9e440e0/src/core/electrostatics_magnetostatics/p3m_gpu_error_cuda.cu#L369

https://github.com/espressomd/espresso/blob/35e0865e6645cc62ed2718ee0eb1600bd9e440e0/src/core/grid_based_algorithms/electrokinetics_cuda.cu#L4010-L4013

These warnings are reproducible with Clang 10. Is there anything we can do from the espresso side to generate more recent assembly code? If not, I'll close this issue as "Won't fix".

**Comment by mkuron** [comment]
That's an upstream issue. Clang needs to stop generating these when targeting newer CUDA versions. 

Since these are only warnings, just ignore them for now. There is no way to suppress them that I am aware of. I guess they already fixed part of this issue in Clang 10: https://github.com/llvm/llvm-project/commit/5c6ab2a0b1f2da22c8ce4fbfc022f599aaa4a2a6

**Comment by jngrad** [comment]
Thanks for the explanation.
