### ISSUE TITLE
Add unit test and documentation for `get_mi_coord` and `get_mi_vector`

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3697]
We should tests for those important functions. Also they are not documented.

**Comment by fweik** [comment]
It might also be possible that there are better names for those functions.

**Comment by jngrad** [comment]
The docs are indeed missing, but there are some basic test cases in [src/core/unit_tests/grid_test.cpp](https://github.com/espressomd/espresso/blob/540b6f0f5f59bd8257f09b750281dc7ddd9533c0/src/core/unit_tests/grid_test.cpp). Do you have a more specific test scenario in mind?

**Comment by fweik** [comment]
Apparently I missed those, they seem fine.
