### ISSUE TITLE
only cuboid box geometries supported in Espresso? Note this in the user guide

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#375]
According to the user guide the command tclcommand_change_volume should return the volume of the box.
Actually it only returns box_l[0]*box_l[1]*box_l[2] which is only true for a cuboid box geometry. For a generic box geometry you need to use the triple product.

Maybe one should note that only cuboid box geometries are supported in the Espresso user guide in section "6.1. setmd: Setting global variables." under the paragrahp that deals with "box_l".

**Comment by fweik** [comment]
Isn't that obvious from how you set the box size? Also it is called "size"
and not geometry or the like.

**Comment by jonaslandsgesell** [comment]
Yeah, in a way it is but it could in principle also be a different box geometry. E.g. Gromacs allows to set a different box geometry. I would say it does not harm to state this explicitly in the userguide since it would have saved me some time :)
