### ISSUE TITLE
 all_gatherv_test segfaults on s390x

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3753]
```
66/68 Test #66: all_gatherv_test .................***Exception: SegFault 36.10 sec
Running 2 test cases...
[1;32;49m*** No errors detected
[0;39;49m
      Start 67: sendrecv_test
67/68 Test #67: sendrecv_test ....................   Passed    1.43 sec
      Start 68: PdbParser_test
68/68 Test #68: PdbParser_test ...................   Passed    0.00 sec
99% tests passed, 1 tests failed out of 68
Total Test time (real) = 131.09 sec
The following tests FAILED:
	 66 - all_gatherv_test (SEGFAULT)
Errors while running CTest
```

[build_s390x.txt](https://github.com/espressomd/espresso/files/4766658/build_s390x.txt)

**Comment by jngrad** [comment]
Segfault not reproducible with 4.1.2 + 48f04238 and 4.1.3rc, using boost 1.73.0 from the fedora:33 docker image as well as boost compiled from sources with boostorg/mpi#119, in a docker image emulated as s390x with QEMU. The unit tests themselves pass (the logfile says no errors were detected), and the test doesn't segfault with MPICH, so maybe the issue comes from OpenMPI 4.0.4?

**Comment by aminiussi** [comment]
Works fine with gcc 7.5.0 and openmpi-4.0.0

**Comment by aminiussi** [comment]
Works fine with gcc 7.5.0 and openmpi-4.0.4

**Comment by aminiussi** [comment]
And Intel's 2020 compiler and MPI

**Comment by jngrad** [comment]
@junghans We will soon release 4.1.3. Unless there is a need for a 4.1.4, this will be the last release where we test s390x. The s390x builds are disabled on Koji for [espresso-4.1.2-4](https://koji.fedoraproject.org/koji/buildinfo?buildID=1523012), [espresso-4.1.2-5](https://koji.fedoraproject.org/koji/buildinfo?buildID=1536683). Is this a temporary measure?

**Comment by junghans** [comment]
Yes, https://src.fedoraproject.org/rpms/espresso/blob/master/f/espresso.spec#_9

**Comment by RudolfWeeber** [comment]
We are only testing x64. I don't think, we can do something w/r to s3900.
