### ISSUE TITLE
Tutorial 02: electrostatics part 1

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3819]
* There are a lot of constants defined at the top. Yhry nrrf yo br rcplsinrf ot mobrf yo s plsvr, where the explanation has been made, already

* Do we keep to the convention that constants are all-caps?

* In this ttutorail, we should demonstrate creating several particles at once. One call for cat-ions, one for anions.

* The lj parameter definition is too hard to read.
    
    - change name of loop var
    - assign s[0], s[1] to type_name_a/b
    - assign numerical type-ids to type_id_a/b
    - use those vars in mixing rule and interaction setup

* It needs to be stated that overlap removal has to be done before electrostatics is turned on. Otherwise, chargeds may be pulled on top of each other.

* The P3M algorithm needs to be cited. It should be stated that this is the preferred solver for electrostatics in periodic boundaries

* The equilibration is not only for getting to the target temperature, but to get to a configuration somewhat consistent with the interactions present in the system.

* Mention that, from the rdf, one can see whether the system is in a fluid or crystal structure and identify the crystal structure.

* `part.select` needs to be explained

* rdf names should be based on type names "anion"rather than numerical type ids

* The concept of observable and accumulator needs to be re-iterated in one sentence

* The exercies of re-running with real units should be re-considered.
I think, we should explain (or let students figure out) converting from reduced to experimental units instead.

**Comment by jngrad** [comment]
Tutorial 02 Part 1 was replaced by the charged rod tutorial. Closing.
