### ISSUE TITLE
Noise behavior of stokesian dynamics and other thermostats differ

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3840]
SD seems to use a counter based noise source, as do the other thermostats. The counter value is derived from the simulation
time by calculating `sim_time / time_step`, which means that if the users resets the time, the noise is repeated. This differs from
the other thermostats, where the noise is derive from a monotonous counter which can not be reset. Also the SD version leads
to correlated noise if the time step is changed.

**Comment by jngrad** [comment]
The long-term solution is for SD to use the same framework as the other thermostats, once the framework is refactored to use a single counter.
