### ISSUE TITLE
stokesian dynamics affected by langevin thermostat even after `thermostat.set_sd()`

### ISSUE THREAD

**Issue by biermanncarl** [espressomd/espresso#3850]
I simulated an LB fluid, cleared everything and then simulated three SD particles. They were affected by the langevin noisy forces. Even after setting `thermostat.set_sd()`, the langevin thermostat was active. Trying to set the langevin thermostat temperature to zero didn't work, because it said those two thermostats were incompatible with one another.

The only way to work around it is to restart the Python kernel ... which is not a big deal. Only a minor annoyance in a Jupyter like workflow.

**Comment by KaiSzuttor** [comment]
please provide a M(N)WE that can be executed to reproduce the issue. What do you mean by "langevin noisy forces"? And what do you mean by "cleaned everything"?

**Comment by jngrad** [comment]
@biermanncarl could you please provide your script?

**Comment by biermanncarl** [comment]
Sry for the delay. Here it is. I do not really know what the correct behavior should be. But if the Langevin thermostat complains about the SD thermostat, then the SD thermostat should complain about the Langevin thermostat, too, right? (Or maybe even when activating the SD integrator, the Langevin thermostat should be deactivated)
```
import espressomd

system = espressomd.System(box_l=[1.0, 1.0, 1.0])

system.periodicity = [0, 0, 0]

system.time_step = 1.0
system.cell_system.skin = 0.4

# langevin thermostat active, e.g. from a previous simulation
system.thermostat.set_langevin(kT=1e-3, gamma=1.0, seed=42)

system.integrator.set_stokesian_dynamics(viscosity=1.0, radii={0: 1.0})
system.thermostat.set_stokesian(kT=0.0, seed=4)
# both thermostats "active" now (however, SD thermostat is at zero temperature)

# ******* ISSUE *******
# cannot undo langevin thermostat
system.thermostat.set_langevin(kT=0, gamma=1.0, seed=0)
# comment-out this line to see that the langevin thermostat affects the SD simulation below


# perform a one frame simulation with no forces --> no displacement expected
system.part.add(pos=[0, 0, 0])
system.integrator.run(1)
print("Particle displacement: {}".format(system.part[0].pos))
```

**Comment by jngrad** [comment]
That's a bug in the cython code. The DPD and SD thermostats have no compatibility checks. Easy fix, PR is coming. The only way to remove a thermostat is to reset all thermostats in the core via a call to `system.thermostat.turn_off()`.
