### ISSUE TITLE
ninja: error: build.ninja:2172: bad $-escape (literal $ must be written as $$)

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3861]
On Gentoo, I am getting the following error build with ninja:
```
ninja: error: build.ninja:2172: bad $-escape (literal $ must be written as $$)
```

The line in question is:
```
2169 # Custom command for src/CMakeFiles/check_unit_tests
2170
2171 build src/CMakeFiles/check_unit_tests: CUSTOM_COMMAND
2172  COMMAND = cd /var/tmp/portage/sci-physics/espresso-4.1.3/work/espresso-4.1.3_build/src && /usr/bin/ctest --timeout 300 $(ARGS) --output-on-failure
```
and I guess `$(ARGS)` is the issue. This might have been added by me in #2252! However, otherwise I don't see a way to exclude some of the flaky tests.

**Comment by junghans** [comment]
I guess the right things to do would be to make it a cmake options, that is not was flexible as a runtime option, but would work for Ninja as well.

**Comment by jngrad** [comment]
The `$(ARGS)` injects itself in the generated makefiles, which makes it incredibly useful for developers, as we can pass arguments to ctest through makefiles from bash. I'm using this feature daily in my workflow. The alternative would be to open a subshell everytime, e.g. `(cd testsuite/python; ctest --timeout 300 -j4 --output-on-failure <ARGS...>)`, which I would quickly replace by a custom-made bash script, as it's really inconvenient to use.

Making `ARGS` a CMake variable means it's static, in which case we can replace it by [CMAKE_CTEST_ARGUMENTS](https://cmake.org/cmake/help/v3.17/variable/CMAKE_CTEST_ARGUMENTS.html) in the future, once we require CMake 3.17. I couldn't find anything on this `$(ARGS)` trick except for the [August 2013 mail from Orion Poplawski](https://cmake.org/pipermail/cmake/2013-August/055423.html), so it must be non-standard practice. The ninja project has a closed ticket about it (ninja-build/ninja#1387).

**Comment by jngrad** [comment]
Somewhat related: ninja doesn't fully support `VERBATIM` custom targets [cmake/cmake!18062](https://gitlab.kitware.com/cmake/cmake/-/issues/18062).

Is there a CMake resource advocating against writing Makefile variable expansion commands in custom targets?

**Comment by eli-schwartz** [comment]
I have just spent an extremely long time debugging why this package doesn't build or test properly on Gentoo, as apparently it never really ran tests anyway -- gentoo has always called ctest directly so whether or how to call it via make and pass arguments (that gentoo's build system doesn't publicly expose) shouldn't have mattered.


> The `$(ARGS)` injects itself in the generated makefiles, which makes it incredibly useful for developers, as we can pass arguments to ctest through makefiles from bash. I'm using this feature daily in my workflow. The alternative would be to open a subshell everytime, e.g. `(cd testsuite/python; ctest --timeout 300 -j4 --output-on-failure <ARGS...>)`, which I would quickly replace by a custom-made bash script, as it's really inconvenient to use.

It sounds like what you really want is something like https://mesonbuild.com/Reference-manual_functions.html#add_test_setup_is_default :( unfortunately cmake can't do that for you.
