### ISSUE TITLE
Replace pressure_tensor_acf test with test of variances

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#3876]
During discussion of bug fix #3847 the need for testing the variances of fluctuations of the thermalized LB pressure tensor became apparent. This test could replace the slow acf test, to also provide CPU LB pressure testing by default.

**Comment by RudolfWeeber** [comment]
Actually, we are now using the pressure tensor ACF in a lot of scientific work.  Testing that the integrated acf is consistent with viscosity is actually useful.
