### ISSUE TITLE
Custom criteria for Steepest Descent: minimal distance vs. relative energy

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3898]
Until now (as of 07f2a3ae7c8) the documentation gives examples of custom convergence criteria for Steepest Descent that are only based on inter-particle distances. This is not always re-usable, for example it's not suitable for dense, mixed LJ liquids where particle sizes are significantly different (the inter-particle distance must be as large as the largest sigma, yet there might not be enough space in the box to satisfy this criterion for small particles). Using a relative energy criterion to halt integration when, for example, the system energy changed by less than 5%, could be more robust and applicable to more cases. This would however make steepest descent an energy-minimization method.

If we decide to update the documentation in that direction, the samples and tutorials would have to be updated to use a relative energy as the convergence criterion. We could also consider updating the steepest descent class to take either a number of steps or a lambda function to decide when to halt.

**Comment by schlaicha** [comment]
IMHO the purpose of offering a steepest descent algorithm is to allow people to relax their simulations such that they don't explode when not equilibrated. This means that the forces (or energies, respectively) should be minimized; there is no physical reason to assume that a certain distance criterion (overlap removal) would be beneficial.

As such I think that using steepest descent as energy minimization method is exactly what is intended! What would be disadvantageous in doing so?

In general I like the idea of having custom convergence criteria passed via lambda functions, however this adds complexity in the code and more importantly in the UI, so I'm not in favour of this. So a force/energy convergence criterion should be default, maybe with the optional possibility to use a distance criterion (again, I personally don't see a use case where this is better). Once this is implemented as default for the steepest descent as stop criterion (together with a maximal number of steps), changing the tutorials/samples is done quickly.

**Comment by RudolfWeeber** [comment]
Assuming `kT=1`

```

While system.analysis.energy()[“total”] > len(system.part):

    System.integrator.run(10)

```

Or force

```np.amax(np.abs(system.part[:].f))```

**Comment by KaiSzuttor** [comment]
i don't understand your snippet

**Comment by RudolfWeeber** [comment]
those are the two variants I'd mention in the docs. The one with forces is probably better in principle, since those actually matter for integrator stability. In big mpi parallel simulations, accessing the full slice in Python might become a performance issue, though.
Since the loop is rather harmless, I'm not in favor of integrating something with lambdas into the interface, here.

**Comment by KaiSzuttor** [comment]
what I had in mind is more something like the following:
``` python
 energy = system.analysis.energy()['total']
 relative_energy_change = 1.0
 while relative_energy_change > 0.05:
        system.integrator.run(100)
        energy_new = system.analysis.energy()['total']
        relative_energy_change = (energy - energy_new) / energy
        logging.info(f"Minimization, relative change in energy: {relative_energy_change}")
        energy = energy_new
```

**Comment by schlaicha** [comment]
Completely agree with @KaiSzuttor - in the end I guess if you take the energy or the force convergence should not make a bih difference.
