### ISSUE TITLE
Improve error message in number_of_particles_with_type()

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3908]
The method `system.number_of_particles(type)` can throw an exception when `type` is not in the list of tracked particle types.

Here is the relevant core function:

https://github.com/espressomd/espresso/blob/f760050199b94226b9127b309bfa7db569507605/src/core/particle_data.cpp#L1048-L1053

The runtime error should be replaced by something that supports streams to produce a more descriptive error message, e.g.:

```c++
runtimeErrorMsg() << "The provided particle type " << type << " is currently not tracked by the system";
```

which would alert users that they need to call `system.setup_type_map()`. The docstring of `system.number_of_particles()` should be extended with the following paragraph:

```
Raises
------
RuntimeError
    If the particle ``type`` is not currently tracked by the system. To select which particle
    types are tracked, call :meth:`setup_type_map`.
```

Issue reported by @schlaicha.

**Comment by jngrad** [comment]
actually we don't need `runtimeErrorMsg()`, simply use `std::string` to concatenate strings to ints, and catch the error in cython, see example in 408ca69

**Comment by pstaerk** [comment]
I am working on this.
