### ISSUE TITLE
The Gay-Berne potential should take quaternions as args

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3922]
because the calc_direcotr() calls on both particles can be omitted if the potential is turned off (which is most of the time)

**Comment by RudolfWeeber** [comment]
Alternatively, the call in energy_inline.hpp::calc_non_bonded_pair_energy() should be guarded by a cutoff distance check. See forces_inline.hpp::add_non_bonded_pair_force().

IMO, using quaternions as arguments would be preferrable both for energy and force, since then, the calling code doesn't hvae to know, how the Gay-Berne potential stores its cutoff.

**Comment by jngrad** [comment]
This is a 10 min job: call the force/energy Gay-Berne kernels with particle quaternions instead of directors, then adapt the kernels by calling `Utils::convert_quaternion_to_director()` on the two quaternions.
