### ISSUE TITLE
Create installation FAQ in the wiki

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3947]
The user guide gives a good overview of installation instructions for ESPResSo on various platforms, but some users experience issues when their build environment is not properly set up. We could write troubleshooting information in a FAQ in the wiki. The user guide is not the best place for that, because setting up a proper build environment is not specific to ESPResSo. The wiki can also be edited by anyone in the group without having to wait for CI results.

Here are a few candidates:
* failure to run `import io` when building the cython code: well known bash-related `PYTHONPATH` issue, the solution is in the list of closed issues and on the mailing list, but can be hard to find
* tutorial 12 fails with `pint`: Ubuntu 18.04 ships `pint` 0.8 which has several known bugs, the user guide explains how to install a more recent version
* CMake version is too old: Ubuntu 18.04 ships an old CMake version, the user guide explains how to install a newer one with `pip`
* can we get ESPResSo binaries: the software is available via the package manager on CentOS/Fedora/OpenSUSE
* can we get docker images with a fully functional build environment: we provide docker images on DockerHub for various Linux operating systems

**Comment by fweik** [comment]
Ah, something I forgot to forward form the tutorials: Apparently it was not clear to everybody who tried the tutorials on their own machine that ipython is required for that. Maybe somebody could check if this is sufficiently clear in the docs, this is also maybe a candidate for the installation wiki page (?)

**Comment by jngrad** [comment]
add boost 1.74 bug in espresso 4.1.4
