### ISSUE TITLE
vtk unavailable on macOS 

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3950]
See e.g. GitHub Action [1253428513](https://github.com/espressomd/espresso/runs/1253428513)
```
ERROR: Could not find a version that satisfies the requirement vtk (from versions: none)
ERROR: No matching distribution found for vtk
Error: Process completed with exit code 1.
```
From:
https://github.com/espressomd/espresso/blob/cf157f52280adbecbd135ab7476e5b5922664679/.github/workflows/build.yml#L12-L15

@KaiSzuttor is it a temporary issue? I can pip install `vtk` from a docker image without any problem.

**Comment by KaiSzuttor** [comment]
that may depend on the python version, maybe mac os got an update?

**Comment by jngrad** [comment]
You're right, macOS 10.15 changed from version 20201003.1 to version 20201011.1 yesterday, which replaces Python 3.8.5 with 3.8.6 and pip from 20.1.1 / python 3.8 ([readme](https://github.com/actions/virtual-environments/blob/macos-10.15/20201003.1/images/macos/macos-10.15-Readme.md#package-management)) to 20.2.3 / python 3.9 ([readme](https://github.com/actions/virtual-environments/blob/macos-10.15/20201011.1/images/macos/macos-10.15-Readme.md#package-management)). Their issue tracker shows the new version causes CI pipelines to fail installing packages, but it's due to `brew` or `CocoaPods` instead of `pip`.

**Comment by jngrad** [comment]
Maybe the VTK project doesn't have a wheel yet for the latest python 3.8 version. I'm temporarily removing it so that CI can pass.

**Comment by jngrad** [comment]
There is an additional issue with packages getting installed for python 3.9 instead of 3.8. Happens randomly, though.

**Comment by jngrad** [comment]
The macOS image was rolled back to the previous version. I've restarted the failed GitHub Actions.
