### ISSUE TITLE
The pylint check should only run on files which are actually tracked by git

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3952]
maintainer/CI/fix_style.sh

**Comment by jngrad** [comment]
This can be achieved using this command:
```sh
maintainer/lint/pylint.sh --score=no --reports=no --output-format=text \
  $(find $(git ls-tree -r HEAD --name-only -- src doc maintainer testsuite samples) \
         $(git diff --cached --name-only --diff-filter=A -- src doc maintainer testsuite samples) \
         \( -name '*.py' -o -name '*.pyx' \)) \
  | tee pylint.log
```
The `git ls-tree` subcommand lists tracked files, the `git diff --cached` subcommand lists untracked yet staged files.

I prefer using my custom script `git style HEAD`, which only touches tracked and staged files (`/tikhome/jgrad/Documents/protocols/DevOps/git-style/git-style`).

**Comment by KaiSzuttor** [comment]
the cleanest solution is to put pylint into the pre-commit configuration.
