### ISSUE TITLE
Add installation instructions for Windows via WSL

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3953]
ESPResSo can be built on a Windows 2019 runner using WSL, with some effort ([`cf157f52...jngrad:ci_wsl`](https://github.com/espressomd/espresso/compare/cf157f52280adbecb...jngrad:ci_wsl)). Works for 4.2-dev ([logfile 1266087811](https://github.com/jngrad/espresso/runs/1266087811?check_suite_focus=true)) and the walberla branch ([logfile 1265818337](https://github.com/jngrad/espresso/runs/1265818337?check_suite_focus=true)). The [Setup WSL](https://github.com/marketplace/actions/setup-wsl) service is quite recent (created on Sep 4 2020) and is not perfect: slow build time (1 hour), relies on a [recently deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) command that prints warning ([logfile 310876709](https://github.com/jngrad/espresso/actions/runs/310876709)), and on rare occasions can have connection issues (happened once in 50 pipelines, [logfile 1266054903](https://github.com/jngrad/espresso/runs/1266054903?check_suite_focus=true)).

The user guide should briefly mention how to install ESPResSo on Windows by providing a link to the WSL2 installation instructions (e.g. https://docs.microsoft.com/en-us/windows/wsl/install-win10) and explaining that one can simply re-use the instructions for Ubuntu (or one of the Dockerfiles for Debian/Fedora/etc.) when installing ESPResSo dependencies. It should also be mentioned whether GPU support is possible, and that ESPResSo cannot be executed as root with OpenMPI (it will fail).

**Comment by mkuron** [comment]
Is it really worth adding a CI job for WSL2? After all, it‘s just an Ubuntu VM running on Hyper-V (with guest integrations for shared filesystem access and [CUDA support](https://developer.nvidia.com/cuda/wsl)). Unlike WSL1, it even uses a plain Linux kernel.

**Comment by RudolfWeeber** [comment]
>Is it really worth adding a CI job for WSL2? 

>After all, it‘s just an Ubuntu VM running on Hyper-V (with guest integrations for shared filesystem access and  <https://developer.nvidia.com/cuda/wsl> CUDA support). Unlike WSL1, it even uses a plain >Linux kernel.

I also don’t think, we need to test this for now. It’s unlikely that it breaks as long as CI Ubuntu passes

**Comment by jngrad** [comment]
The CI job itself is still in a prototype stage. There are a few things in it which are fragile, e.g. the user cannot use all features of CMake. I worked on it by trial and error whenever I had a few minutes between two `docker run` for the 4.1.4 release candidate. I'm not planning to work on it further, though.

**Comment by jngrad** [comment]
Duplicate of #3094. Closing.
