### ISSUE TITLE
Write Tutorial 02 part 2: ELC system with dielectric boundaries

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3955]

**Comment by KaiSzuttor** [comment]
please add some details why and how

**Comment by RudolfWeeber** [comment]
Part 1 was changed to charged rod. The crystal stuff was not kept since there were issues with it (@schlaicha) 

The 2nd part still deals with crystal stuff

**Comment by schlaicha** [comment]
I think the general point that should be clarified is if

- we want to provide samples/tutorials that teach physics primarily

or 

- they should primarily show Espresso capabilities.

In the current state part 1 contains a lot of physics and simply uses P3M whereas part 2 is intended as a show case that can use many of the special electrostatics algorithms (ICC, ELC, ...). With @christophlohrmann we started to work on this.

I agree that the current splitting of part 1 and part 2 is arbitrarily/artificial but unless the points above are clarified I would not work further on this specific problem. Note that the clarification concerns also most of the other tutorials.

**Comment by RudolfWeeber** [comment]
@areinauer. Part 2 will be small number of ion pairs with dielectric boundaries and elc.
Crystal part iwll not be kept
