### ISSUE TITLE
Error estimation in ES + tutorial

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3958]
@cbiermann with @schlaicha and @RudolfWeeber

**Comment by biermanncarl** [comment]
The tutorial side of this issue is being worked on in [this](https://github.com/biermanncarl/espresso/tree/error-analysis-tutorial) branch. I am waiting for a review by someone who has experience in this area, before I move on to the auto-covariance analysis part.

**Comment by KaiSzuttor** [comment]
can't you just open a draft pull request and reference this issue?
