### ISSUE TITLE
Harmonic dumbbell bond uses parameters of harmonic bond interaction

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3964]
https://github.com/espressomd/espresso/blob/572f85484bcb96d3c2b8f55af8e73791a10be2ca/src/core/bonded_interactions/harmonic_dumbbell.hpp#L96

**Comment by KaiSzuttor** [comment]
Not covered by tests.

**Comment by fweik** [comment]
It is also not momentum conserving ;-) I think this is a bespoke solution for a particular application who's general usefulness can be debated...

**Comment by RudolfWeeber** [comment]
So, we remove it?

**Comment by RudolfWeeber** [comment]
Offline discussion: will be removed
