### ISSUE TITLE
Walberla: Thermalization + force != momentum conservation

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3969]
Unthermalized Walberla-based LBs fulfill:
current momentum = time step * forces applied in previous time steps +1/2 * time step * force applied in last time step

The thermalized LB does not fulfill this if a force has been applied in the last time step. I.e. the f/2 correction seems to be different.

After integration steps in which no force was applied, the equation holds, i.e.:
current momentum = time step * forces applied in previous time steps

See 
https://github.com/RudolfWeeber/espresso/blob/walberla/src/core/unit_tests/LbWalberla.cpp#L300

**Comment by RudolfWeeber** [comment]
This is probably why thermalized simulations with particle coupling explode after a while.

**Comment by RudolfWeeber** [comment]
@mkuron, any idesas?

**Comment by mkuron** [comment]
I think the correct version of your equation is:
current momentum = time step * forces applied in previous time steps +1/2 * time step * force applied in last time step -1/2 * time step * force applied in first time step. The thermalization does not create a force though, so I don't see how it could violate the equation.

**Comment by KaiSzuttor** [comment]
> The thermalization does not create a force though, so I don't see how it could violate the equation.

We had this issue recently in our LB version where the bug in the thermalization resulted in unphysical fluid flow: https://github.com/espressomd/espresso/issues/3804

**Comment by RudolfWeeber** [comment]
>We had this issue recently in our LB version where the bug in the thermalization resulted in unphysical fluid flow:  <https://github.com/espressomd/espresso/issues/3804> #3804

 

 

Differnt story, probably.

The thermalization only touches off-diagonal elements in the stress tensor. That can create flows but not linear momenta.

Also, the test against the mentioned bug in Espresso was introduced in LbmPy.

 

I’ll now try to reproduce the issue in LbmPy, and if I can’t get it there, in Walberla. That should narrow it down.

**Comment by RudolfWeeber** [comment]
Caused by a (now resolved) issue in lbmpy. Closing
