### ISSUE TITLE
Big Memleak with change_volume 

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#398]
Below commit removed hacks from Espreso which made sure that mallocs and reallocs of size 0 actually are free()s.
The removal of this safeguard resutls in a significant memory leak as a result of the change_volume tcl-command.
The long term solution would probably be to use the MEM_DEBUg functions also removed with the commit to identify the location, but for now the commit should probably just be reverted.

commit 771becc176e1d8ffde401dca6fa1dfd020855b48
Date:   Fri Jul 31 13:32:29 2015 +0200

    Removed redefinition of malloc and realloc and moved 'Espresso'-versions to Utils namespace.

**Comment by fweik** [comment]
Actually that commit (should) have changed nothing, it just moved the espresso versions of malloc and realloc from the :: namespace to the ::Utils:: namespace.

**Comment by RudolfWeeber** [comment]
Actually, the commit message is accurate. "Removed redefinition of malloc and realloc" is excactly
what it does in utils.hpp.

**Comment by fweik** [comment]
Me (and Eclipse) missed some spots to rename. Will fix today.

**Comment by fweik** [comment]
Should be fixed with #399.

**Comment by fweik** [comment]
I assume this is fixed?
