### ISSUE TITLE
Walberla: Move interface code to separate library

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4004]
The part of the Walberal interface that does not depend on Espresso schould be moved into a separate library `walberla_bridge` or similar located under /src.
The following files should go there:
LbWalberlaBase.hpp // astract base class defining the LB interface
LbWalberlaImpl.hpp // Default implementaiton tempalte
LbWalberlaD3Q19MRT.hpp // Unthermalized MRT specialization
LbWalberlaD3Q19FluctuatingMRT.hpp // Thermalized MRT specialization
MRT_LatticeModel.cpp/hpp // unthermalized MRT kernels
FluctuatingMRT_LatticeModel.cpp/hpp // thermalized MRT kernels

The following files should remain with EspressoCore:
* lb_walberla_instance.cpp/hpp // Construciont/destruciton of the instance pointer
* lb_walberla_interface.cpp/hpp // Implementation of the MPI callbacks (comapre lb_collective_interface)
* lb_interface.cpp/hpp: Espresso LB head-node interface

**Comment by RudolfWeeber** [comment]
walberla_utils.hpp should also be part of the bridge library.
It contains code not specific to LB.

The bridge library depends on the Utils libray.

**Comment by RudolfWeeber** [comment]
Underscores from '..._LatticeModel.h/cpp' are gone to match Espresso's convention.

**Comment by jngrad** [comment]
The files were moved to `src/walberla_bridge`. The espresso core no longer has access to the walberla header files.

The walberla unit test depends on both `EspressoCore` and `WalberlaBridge`, so it has to stay in the core unit test module. It also depends on the specializations of the `LbWalberla` class (FluctuatingMRT and friends), preventing me from implementing the pitchfork layout, in which I would have hidden these generated kernels from the espresso core by placing them in a `src/` subfolder and moved the public header files in an `include/` subfolder.
