### ISSUE TITLE
Check "boost geometry" for coordinate transformation code replacement candidate

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#4005]

**Comment by fweik** [comment]
How does this relate to #4014  ?

**Comment by KaiSzuttor** [comment]
it turned out that the boost library does not contain the necessary code to replace our coordinate transformation. However, there is the boost qvm library that could at least be used for involved roational transformations.

**Comment by fweik** [comment]
From a quick inspection I disagree, but if this is your conclusion you should close this ticket.
