### ISSUE TITLE
Throw if particles enter ELC gap region

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4009]
In case ELC does a pass over all particles, anyway, it could be checked that none is in the gap region. This is, if ELC can distinguish between normal particles and image charges

**Comment by fweik** [comment]
> This is, if ELC can distinguish between normal particles and image charges

Image charges are not actually created as particles, this shouldn't be a problem.

**Comment by biermanncarl** [comment]
I could try this on coding day

**Comment by jngrad** [comment]
There needs to be a check in the python testsuite, for example something like the following:
```python
    @utx.skipIfMissingFeatures(["P3M"])
    def test_elc_gap_exception(self):
        system = self.system
        elc_gap = 2.
        system.actors.add(
            espressomd.electrostatics.P3M(prefactor=1, mesh=3 * [32],
                                          cao=5, accuracy=1e-3, tune=False))
        system.actors.add(electrostatic_extensions.ELC(gap_size=elc_gap,
                                                       maxPWerror=1e-3))
        system.part.add(pos=[0, 0, 1], q=+1)
        system.part.add(pos=[0, 0, system.box_l[2] - elc_gap / 2], q=-1)
        with self.assertRaises(Exception):
            system.analysis.energy()
        with self.assertRaises(Exception):
            system.integrator.run(0)
```

The magnetostatics counterpart, DLC, has the same issue:
https://github.com/espressomd/espresso/blob/59d100cfe2606533cc1cc46c1364228589f6d607/src/core/electrostatics_magnetostatics/mdlc_correction.cpp#L493-L496
The check could be added in `get_DLC_energy_dipolar()` and `get_DLC_dipolar()` before the first `for` loop, using a call to e.g. `dlc_gap_check(particles)` with such an implementation:
```c++
static void dlc_gap_check(const ParticleRange &particles) {
  auto const h = dlc_params.h;  for (auto const &p : particles) {
    if (p.p.dipm > 0 and p.r.p[2] > h) {
      runtimeErrorMsg() << "Particle " << p.identity() << " entered the DLC gap";
      break;
    }
  }
}
```

**Comment by jngrad** [comment]
Beware, `system.actors.clear()` *doesn't* clear the list of electrostatics/magnetostatics actors! This is important to remember when writing the python test outlined above for both ELC and DLC. More details in #4033.
