### ISSUE TITLE
Walberla: how much control should users have over relaxation times

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4013]
The kernels we use have four relxatation times for different LB modes:
shear, bulk, odd, even.

In practice, we use two relaxation times, where 
* omega_1 is used for shear,bulk,even modes
* omega_2 is used for odd modes

there are different ways to arrive at them. What choice should we let users make?
1. shear viscosity, magic number fixed at 3/16 to calculate second relaxation time?
2. shear viscosity and the option to choose your magic number
3. full control over all rates

So far, I'm not aware of a case in which someone changed the default behavior in Espresso, except for testing.
I'd therefore vote for 1st or second option. Full control could be added, if someone actually needs it.
At present, it seems to be more interface clutter than necessary.

At present, shear viscosity is used as input and the magic number is fixed.

**Comment by fweik** [comment]
At least for TRT there are different choices for the magic numbers with different properties. There is at least a trade-off between boundary slip and compressibility, there is some Ginzburg paper about the different sets of magic numbers. We have used this in
the past to reduce boundary slip. Is there some specific reason why you can't just expose the most general versions or provide multiple overloads?
