### ISSUE TITLE
Make particle id less prominent in system setup and particle doc

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4029]
In the system setup and particle related sections of the user's guide, a lot of emphasis is put on referring to particles by their numerical id.
This is not the preferred way to work with particles, since it results in error-prone scripts and id-based slicing behavior can be surprising.

The docs should be changed to emphasize, that
* specifiying the particle id is optional
* system.part.add() returns either a single particle handle or a particle slice of the created particles. This can be stored in a variable and referred to later
* Bonds can be created using those references
* system.part.select() can be used for creating filtered slices

The underlying discussion is in #3992.

**Comment by biermanncarl** [comment]
I could have a look at this on Coding Day

**Comment by jngrad** [comment]
A lot of particle ids and access-by-ids were removed from the testsuite. There's still a lot of it left, here is how to find them:
```sh
ls -1 testsuite/python/*.py | xargs -d '\n' grep --color -P '\.part\[[^:]+?\]'
ls -1 testsuite/python/*.py | xargs -d '\n' grep --color -P '[^a-zA-Z_]id='
```
These tests typically don't rely on iteration. Instead, the particle ids are carefully chosen for the test logic, sometimes with intentional gaps or patterns. Once we decide on the new particle access mechanism, we can revisit them.

**Comment by biermanncarl** [comment]
Section 7 of the user guide (bonded interactions) needs some rework, too, to get rid of numerical particle IDs

**Comment by biermanncarl** [comment]
What I personally find a bit annoying is the fact that ParticleSlice objects aren't subscriptable. Sure, one can iterate over them with
```python
for p in my_slice:
    ...
```
but for debugging, bond setup and various other purposes, it would be convenient to be able to access one single particle out of a slice without much effort, like ```print(myslice[0].pos)```. This is easy when accessing particles with numerical ids. Would it be hard to make slices subscriptable?

**Comment by jngrad** [comment]
> Would it be hard to make slices subscriptable?

The current particle slice implementation supports slices with gaps: https://github.com/espressomd/espresso/issues/3992#issuecomment-728063238. Once we're done removing particle ids from the docs and tests, we can design a more pythonic slice implementation that supports subscription.
