### ISSUE TITLE
Visualizer: particle info on double click

### ISSUE THREAD

**Issue by reinaual** [espressomd/espresso#4038]
In the OpenGL-Visualizer one was able to double-click a particle to see the particle traits. Currently this action results in 
`TypeError: _get_particle_info() takes 2 positional arguments but 3 were given`
which is because of a function-signature change introduced with f55cbeab49bc3bed8aebc0a92df17ff1277840da that is incompatible to the assumed callback signature.
Reverting the function signature change in line 1517 of `src/python/espressomd/visualization_opengl.py` of f55cbeab49bc3bed8aebc0a92df17ff1277840da gives back a working version.

```
--- a/src/python/espressomd/visualization_opengl.py
+++ b/src/python/espressomd/visualization_opengl.py
@@ -1530,7 +1530,8 @@ class openGLLive():
         if self.drag_id != -1:
             self.trigger_reset_particle_drag = True
 
-    def _get_particle_info(self, pos):
+    # pylint: disable=unused-argument
+    def _get_particle_info(self, pos, pos_old):
         part_id, _ = self._get_particle_id(pos)
         if self.show_system_info:
             self.show_system_info = False
```

**Comment by pkreissl** [comment]
I have recently looked into the visualizer, currently preparing a PR. This issue will be fixed.
