### ISSUE TITLE
Python interface with mpi broken

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#404]
The current version of the python interface crashes at exit.

This can be avoided by removing the sys.setdlopenflgas() magic from 
src/python/espressomd/__init__.py, but if that is done, pypresso
no longer works when compiled with mpi.

I tried to add an exit handler using
import atexit
atexit.register() 
with a handler which restores the old dlopenflags, but that did not solve
the issue.

For now, I'll submit a patch to remove the dlopen magic, which will get
pypresso working on a single cpu, but this is obviously no long term solution

Apparenlty the dlopenflga RTLD_GLOBAL makes symbols from shared libraries
global. This seems to be needed in those cases, where one shared object calls 
symbols form an other shared object. Openmpi seems to need that.

**Comment by RudolfWeeber** [comment]
This is actually not mpi related. It also occurs when using fakempi.
It seems to be caused by the interaction of the
sys.setdlopenflags(...) to RTLD_GLOBAL (without which Espresso doesn't seem to work)
some part of Espresso, Cython, libfftw, libtcl or a combination thereof.

One can use
strace python 2>trace.txt
and grep trace.txt for ^open( to get an idea of the shared objects getting loaded.

**Comment by RudolfWeeber** [comment]
As an aside: to get rid of the error message as long as this isn't fixed:
export MALLOC_CHECK_=0

**Comment by mkuron** [comment]
RTLD_GLOBAL can adversely affect any library that is not intended to be loaded that way. Therefore, the `sys.setdlopenflgas()` needs to be replaced with a different solution. I am currently trying to only load the OpenMPI library into global namespace.

**Comment by mkuron** [comment]
I have a partial fix. It doesn't get rid of the `RTLD_GLOBAL` yet, but I'm still working on that. It should at least remove the crash at exit time.

**Comment by mkuron** [comment]
Underlying problem: every Python module has its own instance of all symbols:
```
$ nm src/python/espressomd/.libs/*.so | grep mpi_init00000000000a79c8 T _Z8mpi_initPiPPPc
00000000000b41d4 T _Z8mpi_initPiPPPc
000000000009bdf8 T _Z8mpi_initPiPPPc
0000000000099fe0 T _Z8mpi_initPiPPPc
000000000009ad88 T _Z8mpi_initPiPPPc
000000000009986c T _Z8mpi_initPiPPPc
0000000000099c10 T _Z8mpi_initPiPPPc
000000000009a6ec T _Z8mpi_initPiPPPc
000000000009b280 T _Z8mpi_initPiPPPc
000000000009a61c T _Z8mpi_initPiPPPc
000000000009dc6c T _Z8mpi_initPiPPPc
00000000000c7a08 T _Z8mpi_initPiPPPc
000000000009aebc T _Z8mpi_initPiPPPc
000000000009a828 T _Z8mpi_initPiPPPc
0000000000099ef8 T _Z8mpi_initPiPPPc
00000000000a5c10 T _Z8mpi_initPiPPPc
00000000000a661c T _Z8mpi_initPiPPPc
000000000009ae78 T _Z8mpi_initPiPPPc
000000000009bdf8 T _Z8mpi_initPiPPPc
00000000000a52b0 T _Z8mpi_initPiPPPc
```

`RTLD_GLOBAL` merges these duplicate symbols. It seems like libEspresso is statically linked into each Cython .so file. Robin's CMake branch does not have this issue.
If you want to test it, 9afc629574c27114a39d69268b6419d92d819dfa removes `RTLD_GLOBAL` for all libraries except OpenMPI.

**Comment by mkuron** [comment]
@fweik: I tried, but couldn't figure out how to get automake + libtool to produce shared libraries (libEspresso, libEspressoTcl and libEspressoTcl4Py) and link the Python modules to those. I'm pretty sure that would fix it and you probably know how to do it.
Also, 9afc629574c27114a39d69268b6419d92d819dfa needs -ldl added to the LDFLAGS. Again, I didn't find the proper place for that in Automake.
