### ISSUE TITLE
Document the particle director

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#4054]
it's not self-explanatory and not a standard term. Using a popular translator to german also gives results that do not help.
Maybe the naming is not optimal here.
<img width="238" alt="Screenshot 2020-12-17 at 13 30 52" src="https://user-images.githubusercontent.com/2150555/102488274-17826800-406c-11eb-98bc-ab9ea7321ae3.png">

**Comment by KaiSzuttor** [comment]
```direction``` for example would be a better fit, imo

**Comment by RudolfWeeber** [comment]
>it's not self-explanatory and not a standard term. Using a popular translator to german also gives results that do not help.
>Maybe the naming is not optimal here.

Z_direction, body_z_direction, z_axis?

**Comment by KaiSzuttor** [comment]
still prefer ```direction``` or ```orientation```

**Comment by KaiSzuttor** [comment]
but at least it should be documented
