### ISSUE TITLE
MMM1DGPU: Segmentation fault without correct periodicity

### ISSUE THREAD

**Issue by reinaual** [espressomd/espresso#4056]
adding `MMM1DGPU` to the system without providing the correct periodicity results in a segfault.

```python
import numpy as np
from espressomd import System, electrostatics

system = System(box_l = [1, 1, 1])
system.time_step = 0.01
system.cell_system.skin = 0.4
# system.cell_system.set_n_square()
# system.periodicity = (0, 0, 1)

mmm1d = electrostatics.MMM1DGPU(prefactor = 1, maxPWerror = 1e-2)

system.part.add(pos=(0.5, 0.5, 0.75), q=1)
system.part.add(pos=(0.5, 0.5, 0.25), q=-1)

system.actors.add(mmm1d)
```

**Comment by jngrad** [comment]
It's just a missing `except+`, although looking at the cuda code, we could probably replace a lot of `std::cerr` by `throw`, and more importantly, add python tests to check for these exceptions.

**Comment by jngrad** [comment]
As it turns out, MMM1D on GPU was never tested in CI, because the GPU class is a verbatim copy of the CPU class: they both import the CPU actor.

**Comment by jngrad** [comment]
offline discussion: the exception mechanism for MMM1D CPU and GPU is quite tangled in the core. Also, it depends on #4020. The test doesn't pass for MMM1D GPU due to large deviations from the analytical solution. We should benchmark MMM1D on GPU to see if it's worth investing more time into fixing it, otherwise we'll remove it in 4.2.

**Comment by jngrad** [comment]
MMM1D with 1000 particles and 500 time steps: 60s on CPU with 4 cores, 1s on GPU. ScaFaCoS, CPU and GPU implementations agree on forces up to 1e-6. ScaFaCoS and CPU agree on energy up to 1e-6, while GPU energies are way off.
