### ISSUE TITLE
Add ELC test without constant potential

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4065]
The `elc_vs_analytic` test takes 1min 20s to run in coverage builds, which represents 6% of the job runtime. It needs to be moved to the statistical tests framework. This will create a drop in coverage for ELC, because there is no other test with `const_pot=False`. Such a test needs to be written. It can be very simple, with only 2 particles (see `elc` test).

**Comment by reinaual** [comment]
For the `elc_vs_analytic` testcase it might be enough to just reduce the amount of positions tested with `number_samples = 25` because the testcase is the most simple possible setup which is just involving two particles. Otherwise using different P3M settings also can speed up the test i guess.

**Comment by reinaual** [comment]
Also one point on my todo-list is to modify the test for the flipped setup where the dielectric contrast is at the upper boundary. In the implementation these two setups are calculated using different paths, which i didn't capture with the original test.
