### ISSUE TITLE
CylindricalLBFluxDensityProfileAtParticlePositions not clear or wrong

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4067]
My intuition (which is the best I have with no available documentation) would tell me that ``CylindricalLBFluxDensityProfileAtParticlePositions`` would calculate, per bin, the average of [lb fluid velocity * lb density], where the probe positions come from the particle positions.
In the code, we calculate the sum of lb velocities in the bin, normalized by the volume of the bin.
Am I wrong and the intention of the observable is something different?

**Comment by jngrad** [comment]
I could be wrong, but `DensityProfile` in the context of ESPResSo should mean a histogram that is normalized by the total number of particles, while a `Profile` is normalized by the number of particles bin-wise. See for example the output of command

```sh
diff src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.cpp \
     src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.cpp
```

**Comment by christophlohrmann** [comment]
For a LB observable that uses the LB velocity I do not see why we should normalize with particles.
In general it seems I have no idea what that observable should do.
In the context of #4023 I could write a test that does not fail but I do not know what the expected behaviour of the observable is, so I guess the test would be meaningless.

**Comment by KaiSzuttor** [comment]
on a side note: all / most of the LB observables are too slow to be of any use in practice

**Comment by KaiSzuttor** [comment]
flux density is density times velocity

**Comment by christophlohrmann** [comment]
Then the observable does not deliver what was promised. Unless what you want is LB velocity * particle density

**Comment by KaiSzuttor** [comment]
please check the testcases and if they are wrong we should remove them

**Comment by RudolfWeeber** [comment]
>on a side note: all / most of the LB observables are too slow to be of any use in practice

I’m using them. But yes, they are slow.

 

Unless someone needs them faster urgently for a current research project, let’s deal with it on the Walberla branch.
