### ISSUE TITLE
Implicit float conversions raise warnings in Clang 10

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4082]
Clang 10 enabled the constant-checked version of `-Wimplicit-float-conversion` by default (see [D64666](https://reviews.llvm.org/D64666#1596634)). It checks that integers can be represented exactly as a float during an implicit conversion. If you pass it to the compiler, it will flag all cases where an integer is implicitely converted to a float. If you don't pass it, Clang will still flag implicit conversions, but only in a constant context, i.e. the warning is raised only when the implicit conversion:

* can be evaluated at compile time
* involves an integer variable explicitely marked as `constexpr` or `const`, or an integer literal
* results in an off-by-1 (or more) deviation from the original integer

To complicate matters, flag [`-Wimplicit-float-conversion`](https://releases.llvm.org/10.0.0/tools/clang/docs/DiagnosticsReference.html#wimplicit-float-conversion) enables a subset of more specialized flags, and in Clang 11, the specialized flag [`-Wimplicit-int-float-conversion`](https://releases.llvm.org/11.0.0/tools/clang/docs/DiagnosticsReference.html#wimplicit-int-float-conversion) enables the more specialized flag `-Wimplicit-const-int-float-conversion`. Here is a MWE for Clang 10 ([compiler explorer output](https://godbolt.org/z/s67dz6)):

```c++
#include<limits>
double foo() {
    // compiler warning because variable 'a' is const
    std::size_t const a = std::numeric_limits<std::size_t>::max();
    double const b = 1. / (a + 1.);
    return b;
}
double bar() {
    // no compiler warning because variable 'a' is not const
    std::size_t a = std::numeric_limits<std::size_t>::max();
    double const b = 1. / (a + 1.);
    return b;
}
```

This is confusing, as simply adding a `const` somewhere can trigger one of those warnings. To avoid inconsistent behavior across compiler versions, we can simply fix these compiler warnings in all of our codebase. This is what the waLBerla codebase did.

ESPResSo is already affected by that warning, when using Clang 10 and enabling the Stokesian Dynamics feature. The MWE is actually adapted from the Stokesian Dynamics library. It was fixed upstream in hmenke/espresso-stokesian-dynamics#3.

**Comment by RudolfWeeber** [comment]
How many cases are we talking about, here, roughly?
I assume the time to fix the warning is <1min per occurance?

**Comment by jngrad** [comment]
We're talking around 300 spots in the code, although the majority can be fixed with a simple string-based search/replace. What's surprising to me is that we already have GCC's flag `-Wfloat-conversion`, which is supposed to detect the same errors.
