### ISSUE TITLE
VS+too short min_global_cut not caught on one mpi core

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4083]
Using VIRTUAL_SITES_RELATIVE together with npt on a single mpi rank causes a segfault if
* min_global_cut is smaller than the distance between virtual site and main particle is larger than min_global_cut
* and the virtual site is in a region affected by ghost communication (outermost cell layer in the ssytem).
The segfault is in cell_cell_transfer() which is called through virtual_sites->update() which calls a ghost update.

With more than one mpi rank, the error message (min_global_cut too small...) appears.
With Langevin and velocity Verlet, the issue does not occur.

Example:
```
import espressomd
from espressomd.virtual_sites import VirtualSitesRelative
import numpy as np

BOX_L=100
KT=1.0
GAMMA_0=2
GAMMA_V = 0.02
P_EXT = 0
DT = 0.01
PISTON_MASS=1
SKIN=0.4

PAIR_DIST = np.array((5,5,5))
PAIR_POS= np.array([BOX_L]*3) -1.1*PAIR_DIST

system = espressomd.System(box_l=[BOX_L]*3)
system.periodicity = [True, True, True]
system.time_step = DT
system.cell_system.skin=SKIN
system.virtual_sites = VirtualSitesRelative(have_quaternion=False)
p = system.part.add(pos=PAIR_POS, rotation=[True,True,True])
system.part.add(pos=p.pos+PAIR_DIST).vs_auto_relate_to(p.id)

system.thermostat.set_npt(kT=KT, gamma0=GAMMA_0, gammav=GAMMA_V, seed=1)
system.integrator.set_isotropic_npt(ext_pressure=P_EXT, piston=PISTON_MASS)
#system.thermostat.set_langevin(kT=1,seed=1,gamma=2)
system.integrator.run(1)
```

**Comment by KaiSzuttor** [comment]
shouldn't it be possible to automatically calculate the global min cut?

**Comment by RudolfWeeber** [comment]
No longer segfaults. On a single mpi rank, setting the min_global_cut is also no longer needed.
