### ISSUE TITLE
bin command is undocumented

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#409]
The [02-charged_system](https://github.com/espressomd/espresso/blob/master/doc/tutorials/02-charged_system/02-charged_system.tex) tutorial makes use of the bin command. This command is [implemented](https://github.com/espressomd/espresso/blob/master/src/tcl/bin_tcl.cpp) and appears to work, but it is not documented in the user's guide. The only piece of documentation I've found is in the Espresso 1.9.4g from more than a decade ago and I have no idea whether that's still up-to-date:

```
Added new command 'bin', which allows to analyze distributions by binning 
given numbers into given subsets, e.g.
    bin -linbins 0 10 10 {0 0 2 3 1 7 3 1 1}
for 10 bins [0,1], (1,2],...,(9,10], normalized to a weight of 1, 
    bin -linbins 0 10 10 {{0 1} {0 2} {2 1} {3 4} {1 1} {7 9} {3 4} {1 0} {1 1}}
for sorting the second entries into the bin given by the first one, while
    bin -linbins 0 10 10 -binctrwdth 
returns the centers and widths of the bins for pretty printing.
Instead of -linbins you can also use -logbins or simply -bins, which takes a 
list of bin boundaries as argument and allows for arbitrary bins.
```

Rather than having me document this based on what I see in the code, I'd appreciate if someone who actually knows and uses this command could add that to the user's guide.

As the 02-charged_system tutorial will be used during the Espresso Summer School next month and we really shouldn't be using undocumented commands in the tutorials, documenting this command is somewhat urgent.

**Comment by jonaslandsgesell** [comment]
@richter-t git blame asserts that you contributed a lot to the bin command. Could you please write some of the documentation since this appears to be an interesting command when analyzing slit/ double membrane geometries.

**Comment by jonaslandsgesell** [comment]
The Binning Process should in my opinion in anyway not be implemented in the tcl interface. This hinders the command from being easily ported to python.

**Comment by mkuron** [comment]
Actually, in Python we don't need to implement it ourselves: people can just use `numpy.histogram`. So please document the current version for the TCL interface and mention somewhere that it won't be ported to Python as it is not needed.

**Comment by KaiSzuttor** [comment]
What about analysis in the core? It would be more efficient...

**Comment by mkuron** [comment]
Nobody appears to have ever needed that extra efficiency to date, otherwise they would have implemented it in the core. Implementing it just for completeness seems like a waste of time to me. Just don't port `bin` to Python and suggest using `numpy.histogram` as a replacement.

**Comment by KaiSzuttor** [comment]
> Nobody appears to have ever needed that extra efficiency to date, otherwise they would have implemented it in the core
I don't think that is reality, but maybe one should keep to more important stuff with respect to the summer school.

**Comment by KaiSzuttor** [comment]
> Nobody appears to have ever needed that extra efficiency to date, otherwise they would have implemented it in the core 

> 

I don't think that is reality, but maybe one should keep to more important stuff with respect to the summer school.

**Comment by jonaslandsgesell** [comment]
Do I see it right that in this case we can label this report as won't fix and close it?

**Comment by fweik** [comment]
No. The tcl documentation is still missing.

**Comment by fweik** [comment]
Also, an imllementation in the core would have to be parallel to be significantly gaster than numpy. I agree with Michael that we e should not put any effort into this.

**Comment by jonaslandsgesell** [comment]
If we do not port the command, is it that important to have a documentation if the command will be dropped from interface (command not in the python interface and tcl interface to be removed)? Therefore if we do not port this command to python (due to the good alternative numpy.histogram) I think that we can also drop documentation of the command?

**Comment by mkuron** [comment]
We will continue to support the `bin` command until the Tcl interface is dropped. The `bin` command is part of the Tcl tutorial, which we will also support until the Tcl interface is dropped. Therefore, it needs to be documented. And as the documentation usually lists Tcl and Python equivalents, the alternative of `numpy.histogram` would need to be mentioned there to explain why this command only exists in the Tcl interface. Once the Tcl interface is dropped, the command can of course be dropped from the documentation entirely. But until then, it needs to be documented.

**Comment by richter-t** [comment]
Since I got mixed up in this discussion: I did not do anything on the bin command. It could be a remnant of a coding day long passed, where we tried to split interface and core to prepare for the interface change.

**Comment by fweik** [comment]
So this should be documented and nobody is going to do it?

**Comment by mkuron** [comment]
Exactly. Just assign somebody to do it on the coding day. They'll need to read the C code to figure out what `bin` does and what arguments it takes, then write a short paragraph of documentation. In the Python documentation, it should be mentioned that this command does not exist and one should use `numpy.histogram` instead.

**Comment by KaiSzuttor** [comment]
The whole conv is probably about 10 times longer than the documentation :D sorry
