### ISSUE TITLE
broken LB fluid momentum with walls

### ISSUE THREAD

**Issue by Marcello-Sega** [espressomd/espresso#412]
The script below generates from time to time a fluid momentum > 1e200 instead of 0. This could be caused by un-initialised populations in inner boundary nodes (i.e. those *not* at the interface with the fluid) 

    setmd box_l  1 1 3
    setmd time_step  1
    setmd skin  0.1
    lbfluid cpu agrid 1.0 dens 1.0 visc 1.0 tau 1
    lbboundary wall dist 0 normal 0 0  1
    lbboundary wall dist -2  normal 0 0 -1

    for { set i 0 } { $i < 4 } {  incr i } {
        integrate 1
        puts  "The total momentum is [analyze fluid momentum]"
    }

As a workaround (see pull request https://github.com/espressomd/espresso/pull/411), my suggestion would be to set to zero all populations, which are going from a boundary node to another boundary node (as anyway, AFAIU, that piece of information makes never its way back to the fluid). This seems to fix the issue, but I would anyway appreciate any feedback from somebody else on this subject.

**Comment by rempferg** [comment]
We used to set boundary populations to zero until Stefan rewrote the bounce-back kernel. There were also problems with the particle coupling that we fixed. I am in favor of fixing this bug the way you did and not changing the core functionality so as to not increase the number of bugs again.

**Comment by uschille** [comment]
This is just to remark that setting the populations to `0.` in the code will not set them to zero because they are stored as f_i - w_i \rho_0 (at least they were way back).

**Comment by Marcello-Sega** [comment]
You're right, "zeroing" the populations actually sets them to their equilibrium value, but to my understanding a node next to a "zeroed" one won't be affected by it, exactly because each neighbour will send around the same (equilibrium) populations, with no net change. Is that correct?

The following script tests that if a node within the boundary region has some net velocity, this won't be transferred to the fluid. 


     setmd box_l 1 8 1   ;  setmd skin 0.1    ; setmd time_step 1.0
    
     lbfluid agrid 1 tau 1 visc 1 dens 1 ext_force 0.0 0 0
    
     lbboundary wall normal 0 1 0 dist 2
     lbboundary wall normal 0 -1 0 dist [expr -6]
    
     integrate 1

     lbnode 0 0 0 set u 0 0.1 0
     lbnode 0 1 0 set u 0 0.1 0
    
     integrate 1
    
     for { set i 0 } { $i < 8 } {incr i } {
       # yields zero for each node
       puts "[lbnode 0 $i 0 print rho ] :: [lbnode 0 $i 0 print u]"
     }

I hope this is safe enough.

**Comment by uschille** [comment]
I guess as long as no information is exchanged with the fluid it is safe.

**Comment by fweik** [comment]
Just a short update: Georg and Ulf have fixed the wall slip problem, but apparently this broke the thermalization, which is why the fix is not yet merged. This is still work in progress and will hopefully be sorted out soon.
