### ISSUE TITLE
Refactor globals.cpp:bcast_parameter can of worms...globals

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4133]
This relies on gloals.cpp::fields which maps flags to memory localtion of globals.
Ghey are then sent via mpi without serialization.
Afterwards some logic in events.cpp is used to do follow-up changes that aris from the parameter broadcast.

All of this needs to be replaced:
* For each of the objects (box_l, periodicity, skin, ...) an mpi callback pair needs tobe created that does the data transfer and handles the follow up logic on the receiving end.

I stumbled up on this, because I wanted to make m_length and m_periodic in BoxGeometry private (as they should be). This would have allowed to pre-cauclate half_box_l and box_l_inv for more efficient get_mi_vector in bond-heavy and Lees-Edwards systems.

**Comment by KaiSzuttor** [comment]
In general, we want to get rid of all of those globals in the long term, right?

**Comment by RudolfWeeber** [comment]
As isolated globals, yes. Most of them will be part of algorithm-specific data structures, e.g., the temperature will be part of the thermostats that use them.

 

Some of them are already part of data structures, e.g.h box length and periodicity. Changing them individually probably needs to remain possible, because different follow-up actiosn are required.
