### ISSUE TITLE
CylindricalLBVelocityProfile is not tested

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4149]
The corresponding Test only checks getters/setters, not the actual profile

**Comment by christophlohrmann** [comment]
can do

**Comment by davidbbeyer** [comment]
I can take a look at this on the CodingDay.

**Comment by jngrad** [comment]
@christophlohrmann is it still untested?

**Comment by christophlohrmann** [comment]
> @christophlohrmann is it still untested?

yes, still untested
