### ISSUE TITLE
Improve testing of the Reaction Ensemble

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4157]
At the time this ticket is written, RE code coverage is 51% for [`reaction_ensemble.hpp`](https://codecov.io/gh/espressomd/espresso/src/415f8d4f66bd8b1bb417a7617c14b01577834dad/src/core/reaction_ensemble.hpp) and 32% for [`reaction_ensemble.cpp`](https://codecov.io/gh/espressomd/espresso/src/415f8d4f66bd8b1bb417a7617c14b01577834dad/src/core/reaction_ensemble.cpp). Lines without coverage are not checked for undefined behavior and memory corruption in the automated testing. Code without coverage is also harder to maintain, because there is no way to detect regressions during bugfixes and refactoring projects.

Most RE tests under `testsuite/python` are statistical tests, i.e. they check a statistic of the RE system like the potential or heat capacity, instead of checking components of the RE code (like `testsuite/python/reaction_ensemble.py` does). These statistical tests are labeled as `long` in [`testsuite/python/CMakeLists.txt`](https://github.com/espressomd/espresso/blob/415f8d4f66bd8b1bb417a7617c14b01577834dad/testsuite/python/CMakeLists.txt) and cannot be executed in code coverage builds and sanitizers builds due to their running time.

**Making the code unit testable**

The `SingleReaction` constructor is written in a separate class (`ReactionAlgorithm`). Moving the constructor to the `SingleReaction` class (7add1c62323aef02) makes the class self-contained, and therefore unit testable ([`974e8e9`](https://github.com/espressomd/espresso/commit/974e8e9f21e2d8db49a76d9ecfbdbed1400878b8#diff-45b815ff7150960d0366bfd97f1cde005eaf9c46d309f2f59d410312c42860d8R120-R138)).

Most methods in RE classes can be made `const`, and often their arguments can be made const too (for `std::map` to be const, the setter/getter [`operator[]`](https://en.cppreference.com/w/cpp/container/map/operator_at) must be changed to the getter [`at()`](https://en.cppreference.com/w/cpp/container/map/at)). This change helps identifying testable methods and simplifies the unit test logic, since a const method cannot alter the state of the tested object.

Methods `calculate_acceptance_probability()` are implementation details and are currently `private`; switching to `protected` (acf5786d2b5) would still hide them from outside code, but would make them unit testable via public inheritance ([`3d22a1d`](https://github.com/espressomd/espresso/commit/3d22a1d8e872b94ad1b643dc15200d2635d1d24f#diff-45b815ff7150960d0366bfd97f1cde005eaf9c46d309f2f59d410312c42860d8R244-R277)).

**Writing unit tests**

By linking a Boost unit test against `Boost::mpi` and `MPI::MPI_CXX`, it is possible to instantiate a minimally working ESPResSo system via `Communication::init(mpi_env)`. In such a system, particles can be created and deleted (see unit test in 974e8e9f21e2d). However some components of the ESPResSo system might not necessarily work, e.g. observables or energy kernels.

**Writing python tests**

Attempts at reducing the runtime of the RE statistical tests without reducing their statistical power have been unfruitful. The best way forward is to come up with new python tests where individual components of RE classes can be tested, for example a test that would check the outcome of a single reaction step. Such a test needs to be fully deterministic. Maybe there is a way to set up a chemical reaction so that a Monte Carlo move is guaranteed to be accepted in the next time step, for example due to a large excess of an adduct type, to a large pH-pKa difference, or to a large potential difference.

**Comment by jonaslandsgesell** [comment]
You intend to add additional unit tests and retain the integration tests? I agree this is a sensible idea. Testing for statistical properties of the algorithm however has its own advantages and does not take long in release mode. Therefore, I would advocate against removing the statistical tests.

**Comment by jngrad** [comment]
The plan is to add extra python tests, for now. The future of the statistical tests is unclear. Their last refactoring showed they were hard to maintain, and their runtime depends greatly on the RNG sequence and the speed of the energy evaluation function, both of which are implementation details that can vary independently of the Reaction Ensemble. This means the statistical tests can become a problem again in the future. We're experiencing that right now with ESPResSo 4.1.4 on Fedora: [Bugzilla 1903952](https://bugzilla.redhat.com/show_bug.cgi?id=1903952).

**Comment by RudolfWeeber** [comment]
```

>The future of the statistical tests is unclear. Their last refactoring showed they were hard to maintain, and their runtime depends greatly on the RNG sequence >and the speed of the energy evaluation function, both of which are implementation details that can vary independently of the Reaction Ensemble. This means the >statistical tests can become a problem again in the future. We're experiencing that right now with ESPResSo 4.1.4 on Fedora: Bugzilla 1903952 <https://bugzilla.redhat.com/show_bug.cgi?id=1903952> .

```

 

I agree that, from a software engineering point of view, statistical tests are a pain in the neck. From the user/physicist point of view, though, I’d only believe an implementation of an algorithm like RE or Langevin dynamics, if the expected statistics is demonstrated with a reasonable accuracy.

**Comment by jonaslandsgesell** [comment]
The tests are run with an ideal system. If espresso is smart in this case, skips the energy computation loop and returns energy 0, then the test cases should not be slowed down due to this.

**Comment by KaiSzuttor** [comment]
>  I’d only believe an implementation of an algorithm like RE or Langevin dynamics, if the expected statistics is demonstrated with a reasonable accuracy.

Why is that? Can't you decompose the algorithm and implement mocks such that you can avoid statistical tests?

**Comment by KaiSzuttor** [comment]
https://link.springer.com/article/10.1186/s40411-018-0053-5#Sec7
