### ISSUE TITLE
Remove code duplication in non bonded test

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4168]
Without the code duplication, tests could be expanded, e.g., with regards to checkpointing, effectively.

In testsuite/python/interactions_non-bonded.py, for each non bonded interaction, the same test code is repeated:
* loop over some distances
* move particle
* compare energy/force/pressure

this should be done analogous to the interactions_bonde.dpy:
There, for each interaction, a lambda which maps distance to force and energy is defined.
This is then passed to a common test function, which runs the loop.

This task requires Python knowledge only and there is a template  (the bonded test) to work from.

**Comment by davidbbeyer** [comment]
I will take a look at this.

**Comment by jngrad** [comment]
@davidbbeyer There will be a merge conflict with #4180 (diff view: [`interactions_non-bonded.py`](https://github.com/espressomd/espresso/pull/4180/files#diff-4fd3b8fa2a1f52d97bcd61eeccca10357a2f056367057c94e73fbe7e150cdae2))
