### ISSUE TITLE
Bonded interactions cannot be deleted

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4169]

**Comment by RudolfWeeber** [comment]
If they could be, serialization could be tested...

We should try to get this as part of moving bonded interactions to the script interface.

**Comment by fweik** [comment]
Can you explain a bit what you mean by that, and what the ideal behavior would be for you? Do you mean that bonded interactions can not be removed from the list of active interactions in the core?

**Comment by RudolfWeeber** [comment]
>Do you mean that bonded interactions can not be removed from the list of active interactions in the core?

 

Yes. If one could, then one could check from a single script whether the checkpointing restores (combinations of) bonds correctly. 

 

This one should be fixed while we move the bond interface from manual Cython code to script interface. At that point, we have to replace the code for communicating and managing `bonded_ia_params` anyway.

**Comment by fweik** [comment]
Thank you for clarifying the issue!
