### ISSUE TITLE
Build failure on Debian Bullseye

### ISSUE THREAD

**Issue by fortysixandtwo** [espressomd/espresso#4184]
Hey there,

I've just tried my hand at building espresso on a Debian Bullseye (Debian 11) host and sadly had a failure with regards to
libboost.

You can find the terminal output of `make -j1` attached:
[build_fail.log](https://github.com/espressomd/espresso/files/6217578/build_fail.log)

I'm running libboost 1.74.0.3

**Comment by fortysixandtwo** [comment]
I forgot to clarify: This is happening on 4.1.4, but seems to be fixed on the current master b069c6a7882f35f42b80dbe99756d472a54636a9 so feel free to close the issue (or leave it open until a new release is tagged?).

**Comment by jngrad** [comment]
Hi, this is a know bug in Boost 1.74: [FAQ: Compiler error with boost::optional](https://github.com/espressomd/espresso/wiki/Installation-FAQ#compiler-error-with-boostoptional). It's already been fixed from our end in the upcoming 4.2.0 release, and the 4.2.0 patch can be manually applied to 4.1.4 sources. There will be no 4.1.5 release for technical reasons.
