### ISSUE TITLE
Implement string stream << for Utils::Vector

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4189]
Otherwise, it is not possible to write BOOST_CHECK_EQUAL and friends with vectors.

**Comment by fweik** [comment]
I can do that.

**Comment by KaiSzuttor** [comment]
Why not using  ```BOOST_TEST``` which is available since 1.59? We already use it, .e.g. in src/core/unit_tests/Particle_test.cpp:127

**Comment by KaiSzuttor** [comment]
However I think it might still be handy to have this operator for our static array type.
