### ISSUE TITLE
Implement == for cdef class LBNode and LBSlice

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4204]
Nodes and slcies shoudl be considered equal, if the index/slice is equal﻿

Otherwise 
```
lb_nodes1 = [some list of lb node objects retrieved by index]
lb_nodes2 = [some list of lb nodes overlapping with lb_nodes1 also retrieved by index]
all_nodes =set(lb_nodes1+lbnodes2)
```
can have duplicate entries

This would be solved by implementing `__eq__()`.

Particle handles might also be affected.

**Comment by jngrad** [comment]
Suitable task for @KaiserMartin @stekajack
