### ISSUE TITLE
EK parameter changes after activation do not apply

### ISSUE THREAD

**Issue by itischler** [espressomd/espresso#4210]
Changing the EK parameters (like external force density) after the method was activated was activated would not apply, because those parameters are only communicated to the GPU during ``ek_init()`` which is only called on activation or species creation.

**Comment by christophlohrmann** [comment]
After 10 hrs of two man work and 3 pairs of eyes on the problem, we decided it is not possible with reasonable effort to make this work. We suggest to make ekin immutable.

**Comment by RudolfWeeber** [comment]
>After 10 hrs of two man work and 3 pairs of eyes on the problem, we >decided it is not possible with reasonable effort to make this work. We >suggest to make ekin immutable.

OK, let’s do that
