### ISSUE TITLE
Revisit cylindrical Poiseuille test

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4245]
On the Walberla branch, the effective radius in the analytical comparisson hat to be changed by 0.03 agrid for the test to pass.
With only 16 grid cells per direction, the test is not that precise anyway. 
The test srrvives a change of box size but not agrid.
The results (including the f/2 correction) should be looked at in a plot to see whether there are systematic errors.

The test for direct checking and the observable should be unified if possible.

**Comment by jngrad** [comment]
Suitable task for @KaiserMartin @stekajack
