### ISSUE TITLE
Reaction Methods: Make hidden particle type user-specified

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4257]
The reaciton algorithms change the type of a particle to hide it from itneractions.
The particle type 100 is hard-coded as that hidden type (without checking that no interactions are defined for it).
This is in src/core/reaction_methods/ReactionAlgorithm.hpp.

100 is a bad choice, because at integration start, the maximum interaciton range is recalculated. This operation scales like N^2, wher N is the higher non-bonded interaciton (i.e.100).
Even in a simulatino wiht P3m, 20% of tutorial 12 is spent on this funciton.

Solution: Make the particle type used for "hiding" particles a required user-provided parameter when setting up the reaciton methods. Advise users in the docs to pick the lowers not-used particle type number.

@kosovan, @dbeyer, @pm-blanco

**Comment by pm-blanco** [comment]
Maybe I am being naif here, but wouldn't it be better at the begining of the integration to define the hidden particle type depending of the existing particle types? For instance, the hidden particle type could simply be the largest particle type + 1.

**Comment by jngrad** [comment]
> Maybe I am being naif here, but wouldn't it be better at the begining of the integration to define the hidden particle type depending of the existing particle types? For instance, the hidden particle type could simply be the largest particle type + 1.

If the user later adds new particles with type equal to the largest particle type in the simulation script + 1, then the reaction method will give unexpected results.

**Comment by jonaslandsgesell** [comment]
The documentation https://espressomd.github.io/doc/advanced_methods.html says

''''
set_non_interacting_type(self, non_interacting_type)
Sets the particle type for non-interacting particles. Default value: 100
....
'''''

**Comment by kosovan** [comment]
I like the solution proposed by @RudolfWeeber 

 Make the particle type used for "hiding" particles a required user-provided parameter when setting up the reaciton methods. Advise users in the docs to pick the lowers not-used particle type number.

If it is required that the user has to specify the type for hiding the particles, then it assures that he is aware of it and there is no need to hard-code a high enough number.

**Comment by pm-blanco** [comment]
In my opinion, the solution proposed by @RudolfWeeber  is good for solving the issue quickly. In the long term, I think that the hidden particle type should not be something that the user must choose but something espresso should intelligently set. Even if we state on the documentation how this hidden particle type should be set, I foresee that it could become the source of bugs in the scripts of many novel users of espresso either setting the hidden particle type too large or coincident with another particle type already present. The problem pointed out by @jngrad  could be easily solved checking that new particle types added to the system do not coincide with the hidden particle type and if it does just  changing the type of the hidden particles.

**Comment by RudolfWeeber** [comment]
IMO, in the long term, particles should be delete rather than hidden.

This is currently not done, because for the current implementation of bonds, it is expensive to delete bonds binding the particle.

 

Reason: Bonds are only stored on one of the bond partners. Therefore one needs to scan all particles to check whether they have a bond to the particle that is being deleted.

 

Long term, bond storage will probably have to be changed, anyway. Then, we can plan for quick particle deletion and the hiding becomes obsolete.

**Comment by jngrad** [comment]
We could use a negative particle type, but it's not a great idea. For example `-1` is already used for uninitialized particles, so we would have to use `-2`.

**Comment by kosovan** [comment]
Just a note on user experience: calling `RE.set_non_interacting_type(len(TYPES))` in the constant-pH tutorial gave me a factor of two speedup out of the box. So, I think it is really important to set it dynamically, or use a negative type.

**Comment by KaiSzuttor** [comment]
would a feature like the existing exclusions but based on types instead of ids be the way to go?

**Comment by RudolfWeeber** [comment]
>would a feature like the existing exclusions but based on types instead >of ids be the way to go?

 

No. The RE “hides” specific particles not all particles of a type.

Anyway, hiding via type is not safe under all conditions, because it doesn’t hide the particle from e.g., external potentials, dipolar interactions.

**Comment by KaiSzuttor** [comment]
> would a feature like the existing exclusions but based on types instead >of ids be the way to go?
> No. The RE “hides” specific particles not all particles of a type. Anyway, hiding via type is not safe under all conditions, because it doesn’t hide the particle from e.g., external potentials, dipolar interactions.

I'm just thinking of ways to make the non-interacting type explicitly setable. Of course this would only work for short range interactions.

**Comment by kosovan** [comment]
Just a note on user experience: calling `RE.set_non_interacting_type(len(TYPES))` in the constant-pH tutorial gave me a factor of two speedup out of the box. So, I think it is really important to set it dynamically, or use a negative type.

**Comment by jngrad** [comment]
Fixed by #4325.
