### ISSUE TITLE
system.part does not behave like an array

### ISSUE THREAD

**Issue by itischler** [espressomd/espresso#4278]
choosing a random particle via ```np.random.choice``` will fail, if there is only one particle in the system and if this particle has not the id of 0

```
import espressomd
import numpy as np

sys = espressomd.System(box_l=[10,10,10])
sys.part.add(pos=[4,4,4])
for i in range(10):
  print(np.random.choice(sys.part).id) ### works fine

sys.part.add(pos=[5,5,5])
sys.part.add(pos=[6,6,6])

for i in range(10):
  print(np.random.choice(sys.part).id) ### works fine

sys.part[0].remove()

for i in range(10):
  print(np.random.choice(sys.part).id) ### still works fine

sys.part[2].remove()

print(np.random.choice(sys.part).id) ### fails but particle 1 is still in there
```

**Comment by KaiSzuttor** [comment]
what is "failing"?

**Comment by itischler** [comment]
```  File "choice_test.py", line 22, in <module>
print(np.random.choice(sys.part).id) ### fails 
File "particle_data.pyx", line 110, in espressomd.particle_data.ParticleHandle.id.__get__
File "particle_data.pyx", line 58, in espressomd.particle_data.ParticleHandle.update_particle_data
RuntimeError: Particle node for id 0 not found!
```

**Comment by KaiSzuttor** [comment]
so, your MWE can be made more "minimal":

``` python
import espressomd
import numpy as np

sys = espressomd.System(box_l=[10,10,10])
sys.part.add(pos=[4,4,4], id=1)
print(np.random.choice(sys.part))
```

**Comment by KaiSzuttor** [comment]
the issue is that the particle list in espresso is not "array-like" because it can have gaps and the index is interpreted as the id (which is not the best idea), right?

**Comment by itischler** [comment]
yes, and np.random.choice thinks if the length of a list is one the index must be 0

**Comment by KaiSzuttor** [comment]
okay, but is it a bug or expected behavior? looking at https://espressomd.github.io/doc/espressomd.html#espressomd.particle_data.ParticleList I'd say it's documented behavior

**Comment by jhossbach** [comment]
> so, your MWE can be made more "minimal":
> 
> ```python
> import espressomd
> import numpy as np
> 
> sys = espressomd.System(box_l=[10,10,10])
> sys.part.add(pos=[4,4,4], id=1)
> print(np.random.choice(sys.part))
> ```

I am using numpy v1.20.3 and I can't reproduce this problem. However running the same snippet with numpy v1.17.4 returns the mentioned error. Seems like this has been resolved somewhere inbetween.

**Comment by RudolfWeeber** [comment]
This is duck-typing at its worst. If it has [], it must be a list. Unfortunately, dictionaries use [] too.

If we are prepared to break the interface, we can remove the [] operator and instead have
system.part.by_id(id) as a replacement for []
and
system.part.select(predicate) for more complex stuff

**Comment by KaiSzuttor** [comment]
> > so, your MWE can be made more "minimal":
> > ```python
> > import espressomd
> > import numpy as np
> > 
> > sys = espressomd.System(box_l=[10,10,10])
> > sys.part.add(pos=[4,4,4], id=1)
> > print(np.random.choice(sys.part))
> > ```
> 
> I am using numpy v1.20.3 and I can't reproduce this problem. However running the same snippet with numpy v1.17.4 returns the mentioned error. Seems like this has been resolved somewhere inbetween.

it might be that the underlying implementation in numpy changed, but as I said it's not an issue of numpy but an issue of our ParticleList implementation that does not behave like an "array-like" which is the requirement for the numpy function. This is in principle also connected to #3992 and #3369

**Comment by KaiSzuttor** [comment]
btw: our list is also officially non-pythonic:

>Sequences
 These represent finite ordered sets indexed by non-negative numbers. The built-in function len() returns the number of items 
 of a sequence. When the length of a sequence is n, the index set contains the numbers 0, 1, …, n-1. Item i of sequence a is 
 selected by a[i].

... and

> Mutable sequences
 [...]
 Lists
 The items of a list are arbitrary Python objects. Lists are formed by placing a comma-separated list of expressions in square 
 brackets. (Note that there are no special cases needed to form lists of length 0 or 1.)

https://docs.python.org/3/reference/datamodel.html

**Comment by RudolfWeeber** [comment]
>btw: our list is also officially non-pythonic:

When comparing to Py built-in types System.part should be thought of a dict, I guess.

**Comment by KaiSzuttor** [comment]
> btw: our list is also officially non-pythonic:
> When comparing to Py built-in types System.part should be thought of a dict, I guess.

That's why we call it ```ParticleList```? :smiley:

**Comment by KaiSzuttor** [comment]
> btw: our list is also officially non-pythonic:
> When comparing to Py built-in types System.part should be thought of a dict, I guess.

Python dictionaries also do not support slicing.

**Comment by jngrad** [comment]
This is an issue in the OpenGL visualizer, which relies on particle ids to index arrays. Thanks @mebrito for finding this out!

Here is how the list of bonds is serialized:
https://github.com/espressomd/espresso/blob/9f8072f1379f3d044b80303e0e5d569ccb681499/src/python/espressomd/visualization_opengl.py#L861-L874

The visualizer breaks as soon as a particle id larger or equal to the number of particles is hit (access out of bounds):
https://github.com/espressomd/espresso/blob/9f8072f1379f3d044b80303e0e5d569ccb681499/src/python/espressomd/visualization_opengl.py#L1117-L1118

**Comment by RudolfWeeber** [comment]
This is done, to my understanding
