### ISSUE TITLE
Cutoffs should be accessible from Python

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4294]
It should be possible to obtain the various cutoffs from Python.
This was, iirc, in system.cell_system.get_state() at some point.

**Comment by jngrad** [comment]
They have been moved out of the dict, since they can be recalculated from the state of the cellsystem and the list of interactions:

```python
import espressomd
system = espressomd.System(box_l=[1., 1., 1.])
print(system.cell_system.max_cut_nonbonded)
system.non_bonded_inter[0, 0].wca.set_params(epsilon=1.0, sigma=1.0)
print(system.cell_system.max_cut_nonbonded)
print(system.cell_system.max_cut_bonded)
```
output:
```
0.0
1.1225
-1.0
```
