### ISSUE TITLE
Brownian dynamics: Virtual sites do not contribute to friction

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4295]
For raspberry particles, the friction of the virtual sites is not taken into account for the real particle.
MNWE:
```python
from espressomd import System, virtual_sites

system = System(box_l = 3*[10])
system.time_step = 0.01
system.cell_system.skin = 0.5
system.min_global_cut = 2
system.virtual_sites = virtual_sites.VirtualSitesRelative()

force = 0.3
fric = 1.2

p_real = system.part.add(pos = [1,0,0], ext_force = [force, 0, 0])
p_virt = system.part.add(pos = [2,0,0], virtual = True)

p_virt.vs_auto_relate_to(p_real)

system.thermostat.set_brownian(
    kT = 0., gamma = fric, act_on_virtual = True, seed  = 1)
system.integrator.set_brownian_dynamics()

system.integrator.run(1)

print('velocity is ', p_real.v[0])
print('velocity should be ', force/(fric*2))
```

This also creates problems for rotational dynamics: If I use ``gamma_rotation = 0, act_on_virtual = True``, the rotational friction should come from the virtual beads. At the moment this friction is 0 and any torque leads to undefined angular velocity.

**Comment by Koppeprojects** [comment]
I wasn't quite conscious that the virtual sites don't feel any friction at all. 
If the virtual sites experience friction after solving the issue, how does this look like?
Consider:
If you have for example a lengthy raspberry particle (rod), the transversal friction parallel to the long particle axis should be smaller than the friction parallel to a short axis. 
At least that's what I think my Perrin-factors try to tell me.
Can such effects be covered efficiently?

**Comment by jngrad** [comment]
The Brownian thermostat can no longer act on virtual sites in ESPResSo 4.2.2 and in the python branch.
