### ISSUE TITLE
Walberla: Phase out lattice model

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4303]
the Walberla bridge should not make use of the LatticeModel class template in Walberla.

* It is not supported on the GPU
* Its floating point precision cannot be changed from whatever is the compile-time default for Walberla. So we cannot let the user choose at runtime the precision they want.

Tasks:
* [X] Generate collide and stream sweeps independent from a lattice model
* [X] Switch the streaming sweep to the newly generated one
* [x] Switch collision sweep to the independent one. This implies moving the relaxation rate handling from the template specializations like MRTLatticeModel into LBWalberlaImpl
* [x] Supporting the vectorized kernels
* [x] Generating initialization kernels and using them, replacing addPdfFieldToStorage
* [x] Generating value getters for velocity/density/stress based on lbmpy conserved quantity calculation. alternatively, at least the velocity field could be generated by the streaming kernel for the entire flow field

**Comment by RudolfWeeber** [comment]
Current progress is on my github in the branch walberla_wo_lattice_model

**Comment by jngrad** [comment]
The `LatticeModel` is now only used for boundary handling (as of d1ab2d1f3ae01). The generated sweep `Dynamic_UBB` was added in a work-in-progress commit (jngrad/espresso@a00424a33c2d98), but I must admit I don't really understand how to use it, and the waLBerla codegen documentation only has one example with a noslip boundary whose geometry is read from a file. @RudolfWeeber could you please have a look at it?

**Comment by jngrad** [comment]
The `LatticeModel` classes have been completely removed in branch [`jngrad:walberla`](https://github.com/RudolfWeeber/espresso/compare/walberla...jngrad:walberla). The VTK writers have been disabled, since they rely on `LatticeModel`. The LB momentum function is broken at the moment, so many LB tests had to be disabled. The UBB is still a WIP. There is now a `m_pdf_tmp_field_id` field, which is needed by Lees-Edwards.

**Comment by RudolfWeeber** [comment]
As I understand your code, the getters for densty and pressure tensor still depend on the lattice model. Those would have to be replaced as well by generarws kwenwla, I  guess.

**Comment by RudolfWeeber** [comment]
And similarly for setters. The velocity getter is not needed, because we now use the "cached" value calculated during streaming.

**Comment by jngrad** [comment]
The last use of the `LatticeModel` was removed in a9c4e1de4fcaa3f47692f861bda4e2aba2cb8a84.
