### ISSUE TITLE
lj-demo.py is broken

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4347]
The physics in [`samples/lj-demo.py`](https://github.com/espressomd/espresso/blob/cc0b79f46f89a796c689a9b8ea26b5e2e1ee6df7/samples/lj-demo.py) is broken since ESPResSo 4.0. The script is also completely untested, and has diverged, e.g. the NpT option doesn't work because the integrator function signature changed in 4.1. It's possible to fix the sample without a MIDI board.

Tasks:

* Remove the phase diagram plot. It is unclear how it was obtained, and the dot temporarily moves into the solid phase when the volume is increased, which is not correct; as the box volume increases, it takes time for the fluid to occupy the newly available space, which is why the dot temporarily enters the solid region. However a phase diagram describes the state of a system at equilibrium, and during the time it takes for the fluid to occupy the new space, the system is strongly out-of-equilibrium. I also couldn't find an analytical solution for the phase diagram of a simple LJ system, and according to the literature it depends strongly on the cutoff value for the LJ potential (Smit 1992, doi:[10.1063/1.462271](https://aip.scitation.org/doi/10.1063/1.462271)).
* Fix the overflow issue when the GUI sliders are moved too quickly.
* Fix NpT error caused by the change of signature of the NpT integrator.
* Add a minimal test case, if feasible. It's not going to be pretty. `testsuite/scripts/samples/test_visualization_npt.py` can be used as template, should *probably* work with the following patch:

<details>
  <summary>patch (click to unroll)</summary>

```python
def disable_GUI_and_MIDI(code):
    # disable MIDI and traits interface
    breakpoint = 'from traits.api import HasTraits, Any, Range, List, Enum, Float\nfrom traitsui.api import View, Group, Item, CheckListEditor, RangeEditor'
    assert breakpoint in code
    code.replace(
        breakpoint,
        'from unittest.mock import MagicMock()\n' +
        '\n'.join(
            f'{x} = MagicMock()' for y in breakpoint.split('\n') for x in y.split(' import ')[1].split(', ')))
    breakpoint = 'system.thermostat.set_langevin(kT=controls.temperature, gamma=1.0)'
    assert breakpoint in code
    code.replace(breakpoint, 'system.thermostat.set_langevin(kT=1, gamma=1.0)')
    breakpoint = 'new_box = np.ones(3) * controls.volume**(1. / 3.)'
    assert breakpoint in code
    code.replace(breakpoint, 'new_box = [3, 3, 3]')
    breakpoint = 'new_part = controls.number_of_particles'
    assert breakpoint in code
    code.replace(breakpoint, 'new_part = 100')
    # integrate without visualizer
    breakpoint = 't = Thread(target=main_thread)'
    assert breakpoint in code
    code = code.split(breakpoint)[0] + 'controls = Controls()\nmain_thread()'
    return code


sample, skipIfMissingFeatures = importlib_wrapper.configure_and_import(
    "@SAMPLES_DIR@/lj-demo.py", int_n_times=10,
    substitutions=disable_GUI_and_MIDI, cmd_arguments=["--opengl"])
```
</details>

**Comment by davidbbeyer** [comment]
I will take a look.

**Comment by jngrad** [comment]
@davidbbeyer any update?

**Comment by davidbbeyer** [comment]
Sorry, I haven't fixed the overflow issue yet, I will do it in the next days.
