### ISSUE TITLE
WIP: Implement breakable bonds

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4367]
Purpose of this features is to dynamically remove bonds from the simulation, if they get stretched beyond a specified length.

The methods
* takes as argument a list of [bond type, breaking distance, delete operation]
* Delete operation can be `RemoveBond` or `RevertBindAtPointOfCollision`
* RevertBindAtPointOfCollision is the opposite of the BindAtPointOfCollision collision detection scheme. It is defined for the bond between the virtual sites. It deletes this bond and also any bonds between the particles the virtual sites are related to. The virtual sites are NOT deleted (because of the one-sided bond storage, deleting particles on the fly is too expensive).
* The method maintains a queue of actions to take. It is cleared before force calculation. At the time of bond force calculation, the breakeage criterion is evaluated and breaking bonds' delete actions are queued. After force calculation, the queued delete actions are executed.

## Data structures
* DeleteAction: boost::variant of implemented actions
* DelteBond: struct [paricle id, bond id]
* RevertBindAtPointOfCollision: struct [particle id, bond_id, partner vs id]
* BreakageSpec: struct [breakeage distance, DeleteActionType]
* breakage_specs: std::unordered_map<bond id, BreakageSpec>
* queue: std::vector<DeleteAction>

## functions

* bool should_break_bond(const BreakageSpecs spec, int bond_id, double distance)`: looks up breakage distance for the bond id from `breakage_specs` map and compares it to `distance`.
* DeleteAction create_delete_action
* `handle_bond_brekage_queue()`: MPI gather-scatter the queue, so it is synchronized on all mpi nodes. Iterate over the queue and use boost::apply_visitor() on the queued delete actions
* Visitors for the two delete actions described above, which do the according action

## Script interface bindings
* BreakageSpec
* breakage_specs: Using the map->python dict  implementation from the bondstorage refactoring

**Comment by RudolfWeeber** [comment]
It became clear that one nees to queue only bond type and particle id. Everything can be handled later (when the q is processed)

**Comment by jngrad** [comment]
Implemented in #4464 and #4463.
