### ISSUE TITLE
Walberla: GPU support

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4379]
This involves the following steps:
* Generate the kernels for the gpu in mainainter/walberla_kernels
* Figure out how to implement the macroscopic value setters/getters (velocity, density, pressure).
    * Option 1: Write a Cuda kernels that set or get populations on a specific node, use cpu function to extract vel, stress, density from populations and to calculate populations for a given density and velocity
    * Option 2: Write setters/getters as cuda kernels for all three quantities.
* Figure out, how to do particle coupling
    * Option 1: Re-use the current Espresso GPU coupling kernels. Then, only the access to the fields has to be implemented using Walberlaa functions
    * Option 2: Implement coupling via pystencils

**Comment by jngrad** [comment]
Fixed by #4734.
