### ISSUE TITLE
Re-work Python particle access

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4389]
The goal is to get rid of the ambiguities concerning access to particle ranges by id slicing.

Due to the fact that python uses `[]` for both list and dictionary access, the semantics of particle access is currently unclear. Does `system.part[:10]` refer to particles with id <10 or to the ten particles with lowest ids?

## Proposed solution:
* Where ever possible, references should be used: `p = system.part.add(...)`
* An individual particle can be accessed by id using `system.part.by_id(id)`, where `id` is the numerical particle id. This will return a `ParticleHandle`
* A slice of particles can be accessed via an iterable of ids with `system.part.by_ids(id_list)`, which returns a `ParticleSlice`
* `system.part.all()` returns a slice containing all particles
* The order in which particles will be provided when iterating over a slice will stay fixed, once the slice has been instanced. I.e, `for pos, vel in zip(system.part.all().pos, system.part.all().v)` will produce the expected result.
* The `[]`-operator on `system.part` will be removed
* Selection by criterion (either using `key=value` or a lambda) can be done with the existing `system.part.select()`

This is a non-silent interface change. Users are encouraged to avoid access to particles via their ids in any case.

**Comment by christophlohrmann** [comment]
If this is coding day material, I can look into it.
I like the proposed new syntax, but would wish for an all-particle access.
