### ISSUE TITLE
MDAnalysis bindings break with MDAnalysis >= 2.0.0

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4395]
The 2.0.0 release of MDAnalysis comes with significant API changes ([release notes](https://github.com/MDAnalysis/mdanalysis/releases/tag/release-2.0.0)) that break the ESPResSo bindings.

We should take this opportunity to modernize the binding. They currently rely on private implementation details, which can change at any time because they are not part of the API. Take for example this piece of code:

https://github.com/espressomd/espresso/blob/7978ce2ec5d6d5508c0c152ed864c786075660c7/src/python/espressomd/MDA_ESP/__init__.py#L190-L211

The `MDAnalysis.coordinates.base.Timestep._unitcell` is no longer stored as a flattened 3x3 matrix with Fortran layout, but as a flattened triangular matrix, probably with C layout. Assuming the ESPResSo system box is a cuboid with origin at (0., 0., 0.), the solution might look like this:

```python
    @property
    def dimensions(self):
        assert len(self._unitcell) in (6, 9)
        if len(self._unitcell) == 9:
            # This information now stored as _ts_order_x/y/z to keep DRY
            x = self._unitcell[self._ts_order_x]
            y = self._unitcell[self._ts_order_y]
            z = self._unitcell[self._ts_order_z]
            # this ordering is correct! (checked it, OB)
        else:
            x = np.array([self._unitcell[0], 0., 0.])
            y = np.array([0., self._unitcell[1], 0.])
            z = np.array([0., 0., self._unitcell[2]])
        return triclinic_box(x, y, z)
```

Someone should look into this in more detail. It's not just about incorrect box coordinates, other issues pop up when running `samples/MDAnalysisIntegration.py`, e.g. `AttributeError: 'TRRWriter' object has no attribute 'write_next_timestep'`

Once these issues are resolved, one has to update the MDAnalysis version requirements in multiple places (see e0b5c62f111de886f0).

**Comment by davidbbeyer** [comment]
I will take a look.
