### ISSUE TITLE
Make LBFluidRoutines a script interface object

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4397]
Currently the LB node setters and getters are scattered in multiple files:
* `lb_walberla_interface.cpp`: contains the MPI callbacks, e.g. `get_node_density()`, which are exported
* `lb_interface.cpp`: contains the head node function, e.g. `lb_lbnode_get_density()`, which call the callbacks
* `lb.pxd`: contains the corresponding Cython function, e.g. `python_lbnode_get_density()`,  which call the head node functions and do the unit conversion

This code duplication is unnecessary and increases the maintenance costs of the LB code. It also exposes MPI callbacks, which should be private.

The plan is to remove these intermediate functions and narrow the LB interface. This is part of our efforts to delete `lb_interface.cpp`.

Tasks:
* `src/core/grid_based_algorithms/lb_walberla_interface.cpp`
   * make all setter and getter MPI callbacks `static` and rename them from `get_node_X()` to `mpi_get_node_X_local()`
   * write the corresponding `mpi_get_node_X()` functions, whose body is taken directly from the  `lb_lbnode_get_X()` in `lb_interface.cpp`
* `src/core/grid_based_algorithms/lb_walberla_interface.hpp`
   * rename `get_node_X()` to `mpi_get_node_X()` for setters and getters (we are now exporting the head functions instead of the callbacks)
* `src/core/grid_based_algorithms/lb_interface.cpp`
   * remove the  `lb_lbnode_get_X()` setters and getters
* `src/core/grid_based_algorithms/lb_interface.hpp`
   * remove the  `lb_lbnode_get_X()` setters and getters
* `src/script_interface/walberla/LBFluidRoutinesWalberla.hpp`
   * do `cp src/script_interface/walberla/FluidWalberla.hpp src/script_interface/walberla/LBFluidRoutinesWalberla.hpp`
   * remove the `do_call_method()`, `lb_fluid()` and `lb_params()` methods
   * remove the `m_ctor_params`, `m_is_single_precision`, `m_is_active`, `m_lb_fluid` and `m_lb_params` members
   * adapt the constructor to define setters and getters for all properties of the `LBFluidRoutines` Cython class, for example:
     ```c++
        {"density",
         [this](const Variant &v) {
           auto const density = get_value<double>(v);
           Walberla::mpi_set_node_density(m_ind, density);
         },
         [this]() {
           return Walberla::mpi_get_node_density(m_ind);
         }},
     ```
   * make sure to do the unit conversion where necessary
   * relevant section in the dev guide: [The AutoParameters framework](https://github.com/espressomd/espresso/wiki/Software-design#The_AutoParameters_framework)
   * add a read-only `ind` parameter to store the node indices during object construction
* `src/script_interface/walberla/initialize.cpp`
   * register the new script interface object with this patch:
     ```diff
     diff --git a/src/script_interface/walberla/initialize.cpp b/src/script_interface/walberla/initialize.cpp
     index 02e01bcfd..50b5dd5f0 100644
     --- a/src/script_interface/walberla/initialize.cpp
     +++ b/src/script_interface/walberla/initialize.cpp
     @@ -23,2 +23,3 @@
      #include "FluidWalberla.hpp"
     +#include "LBFluidRoutinesWalberla.hpp"
      #include "LatticeWalberla.hpp"
     @@ -35,2 +36,3 @@ void initialize(Utils::Factory<ObjectHandle> *om) {
        om->register_new<VTKHandle>("walberla::VTKHandle");
     +  om->register_new<FluidWalberla>("walberla::LBFluidRoutinesWalberla");
      }
     ```
* `src/python/espressomd/lb.pyx`
   * make `LBFluidRoutines` a script interface class that lives on the head node, i.e.:
      ```py
      @script_interface_register
      class LBFluidRoutines(ScriptInterfaceHelper):

          _so_name = "walberla::LBFluidRoutinesWalberla"
          _so_creation_policy = "LOCAL"
      ```
   * delete all properties: they are already defined by `LBFluidRoutinesWalberla.hpp`
   * relevant section in the dev guide: [Using handles to core and script interface objects](https://github.com/espressomd/espresso/wiki/Software-design#using-handles-to-core-and-script-interface-objects)
* `src/python/espressomd/lb.pxd`
   * remove all `python_lbnode_get_X()` setters and getters
   * remove all `lb_lbnode_set_X()` includes

**Comment by stekajack** [comment]
I can look in to this. (icl.  @KaiserMartin and Magaret).

**Comment by jngrad** [comment]
The changes from 324d2b62f89 are now part of the walberla branch. Thanks!
