### ISSUE TITLE
Reaction methods should be script interface classes

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4398]
Many Cython classes in the reaction methods have the following design:

```cython
cdef class ReactionEnsemble(ReactionAlgorithm):

    cdef unique_ptr[CReactionEnsemble] REptr

    def __init__(self, *args, **kwargs):
        self._params = {"kT": 1, "exclusion_radius": 0, **kwargs}
        self.REptr.reset(new CReactionEnsemble(int(self._params["seed"])))
        self.RE = < CReactionAlgorithm * > self.REptr.get()
```

The `ScriptInterface` framework provides a convenient interface to store a shared pointer to a core class. It has many advantages:
* no need to manage a unique pointer, this is done by the script interface
* no need to store a raw pointer to the parent class of the managed object
* no need to re-declare (and maintain) the core class in the .pxd file
* the Cython class can be converted to a regular Python class
* the class can be checkpointed

Instructions can be found in the developer guide, section [Using handles to core and script interface objects](https://github.com/espressomd/espresso/wiki/Software-design#using-handles-to-core-and-script-interface-objects).

While this can be done without breaking the API, there is an opportunity to replace the setters and getters by properties, which would e.g. allow doing `reaction.volume = box_l**3` and `print(reaction.volume)` instead of doing `reaction.set_volume(box_l**3)` resp. `print(reaction.get_volume())`.

**Comment by pm-blanco** [comment]
I will work on it during tomorrow's coding day
