### ISSUE TITLE
Add checks for cell system compatibility

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4428]
Goal: Algorithms that rely on specific cell structures should check for them either at the point where the method is called or (if that's impractical) in a sanity check on integration start
(In preparation for #3662)

Steps:
* In `cellStructure.hpp` make the `type` an enum class
* Move the definition of this enum calss to a separate file `CellStructureType.hpp`. This let's you use it elsehere without giving access to the full cell structure header.
* Add a check for the domain decompositoin type to the following places (list may be incompletet). Use Espresso's RuntimeErrorMSG() mechanism where possible.
* Avoid giving various places in Espresso access to the cell_structure, if they do not need it. Preferrably pass in the cell structure type as an argument.

Relevant places 

* CPU P3M, ELC, ICC (see force_calc() in forces.cpp)
* Dipolar P3m and DLC
* The Scafacos electrostatics and magnetostatics solvers
* LB CPU (propagate and particle coupling. Dispatched from the main integraiotn loop (integrate.cpp) and fore_calc() (forces.cpp), respectively)
* The external potential featues (?)
* The Scafacos electrostatics and magnetostatics solvers* Anything else that uses regular grids
Err on the side of caution.

Places that proabbly don't care about the decompositoin:
* cluster analysis
* collision detection
* reaction ensemble
* all GPU methods
* dipolar direct summation,
* Debye-Hueckel

Unclear:
* MMM1D

**Comment by pkreissl** [comment]
I will work on this one now.

**Comment by jngrad** [comment]
All magnetostatic and electrostatic methods now implement such checks, and they are triggered when adding such an actor, or when changing the cell structure while an actor is active.
