### ISSUE TITLE
Implementation-independent interface for particle properties

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4430]
Goal: The Particle class should have interface funciton to access particle properties. The actual detial of the storage should be hidden from the customers of the Particle class.

## Example
```C++
  auto const& pos() const { return r.p; };
  auto & pos() { return r.p; };
  
  const auto & mass() const { return p.mass; };
  auto & mass() { return p.mass; };
```

## Notes

* Both, the writeable reference and the `const auto& ... const` version are needed. The first, so that `p.pos() = ...;` can be used, the latter to allolw access on a `const Particle`.
* Property names shoudl match those from the Python interface, where possible
* Flags should have `is_...()` getters and `set_...(bool)` setters, to allow us to merge several flags into a bitset, later
* When properties have constexpr values, if the relevant feature is not compiled in (e.g., `constexpr const mass =1`, getter function shoudl be declared `constexpr const` as well, and settes shoudl throw.
* The actual roll-out of the new interface throughout the code base will not be done immediately, to limit the number of merge conflicts

**Comment by christophlohrmann** [comment]
can do

**Comment by jngrad** [comment]
> * The actual roll-out of the new interface throughout the code base will not be done immediately, to limit the number of merge conflicts

Places to skip, so as to not introduce merge conflicts with coding day projects and ongoing refactoring projects: cell structure, integrators, thermostats, electrostatics, magnetostatics, reaction methods, mpiio, polymer linear.
