### ISSUE TITLE
Rename LB viscosity

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4431]
Figure out whether ES (in the walberla branch) takes dnamic or kinetmatic viscosity. then, rename the parameter, both, in the Python interface and core, accordingly.

**Comment by christophlohrmann** [comment]
update: it is the kinematic viscosity (can be checked in the poiseuille test). Renaming the parameter would still be nice

**Comment by RudolfWeeber** [comment]
Not difficutl. Just renaming stuff.
Work on the Walberla branch 

there are proably the follinw places to search (for 'visc')
* src/scriptinterface/walberla/* (here, the parameter names visible from Python are defined)
* Everything lb-relaed in testsuie/python and doc/tutorail
* The User's guide (doc/ug)
* The in-code docstring in src/python/espressomd/lb.py

**Comment by Koppeprojects** [comment]
I'm working on that today.

**Comment by capomav** [comment]
I'll be joining Simon on this issue today.
- Chinmay
