### ISSUE TITLE
write_vtk_velocity segfaults 

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4434]
I get segfaults when I want to save vtks with LBFluidGPU

MNWE
```python
from espressomd import System, lb, visualization

system = System(box_l=[40,20,20])
lbf = lb.LBFluidGPU(tau=1,
                    agrid=1,
                    visc=1,
                    dens=1)
system.actors.add(lbf)
lbf.write_vtk_velocity('./test.vtk')
```

I get no segfaults with CPU-LB or when visualization is not imported.
For GPU with visualization imported and box size (30,20,20), the segfault does not happen every time.

note: segfault or not, I always get
```
WARNING: Imported VTK version (9.0) does not match the one used
         to build the TVTK classes (7.1). This may cause problems.
         Please rebuild TVTK.
```

**Comment by jngrad** [comment]
This VTK function assumes the box is cubic. The regression was introduced in 4.2-dev by a copy-paste error ( 5a6592ca8dac82586).
