### ISSUE TITLE
Reaction methods should take an exclusion radius per particle type

### ISSUE THREAD

**Issue by pm-blanco** [espressomd/espresso#4437]
Many systems  have particles with rather different radii (e.g. colloidal systems). If one wants to simulate such systems including a reaction that creates/destroys particles (e.g. acid/base reactions), it is necessary more than one exclusion radius.  The reason is that there is no good choice for the exclusion radius for such system since:
i) if one sets the exclusion radius to match the size of the small particles then one can get insertions inside the bigger ones.
ii) if one sets the exclusion radius to match the size of the big particles then the smaller ones effectively occupy more than they should. If you have many small particles (imagine systems with explicit salt) then one basically has no space to insert particle while the system actually does have it. 

I like the solution proposed by @jngrad  to simply change the exclusion radius to a dictionary (similar to `default_charges`) where the user defines one exclusion radius per particle type. If we all agree in this change, I can take care of implementing it.

**Comment by jonaslandsgesell** [comment]
This is a good idea. For now you can just use the biggest necessary exclusion radius at the cost of a potentially reduced sampling efficiency: the efficiency would be low if the size difference of particles is extreme. In this case one would require more MC moves for proper sampling. If the size difference is small then the efficiency reduction is small.

Already now (i.e. when taking the biggest necessary exclusion radius) the result of the algorithm is guaranteed to obey detailed balance, yielding the correct result.

**Comment by pm-blanco** [comment]
I am not sure if it is completely safe even when taking the biggest necessary exclusion radius. I can imagine a system where one has big particles (let's say with radius 5 sigma) and small particles (let's say with radius 1 sigma), which could be for example a colloidal solution with salt ions. If one proposes a reaction that implies the insertion/destruction of the small particle with a exclusion radius of 5 sigma, I can imagine that for a large enough concentration of salt ions it would be impossible to insert particles due to their effective size (including the larger exclusion radius) even if in principle there is volume available in the system.

**Comment by jonaslandsgesell** [comment]
Your feeling is correct. The sampling is only correct if it is not completely blocked from a steric point of view. If the exclusion radius is chosen too big, then the sampling can be arbitrarily inefficient - yielding an incorrect result with finite sampling times
