### ISSUE TITLE
Particle creation too slow in large simulations

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4447]
Something scales poorly in the particle creation code (even if added in a singel system.part.add() command).
On 256 cores, creation of 100k particles takes several seconds.

It needs to be checked, using a profile attached to MPI rank 0, where the time is wasted.

Candidates:
* the code determining the next free id
* the call to particle_exists() which checks that the id is free

Both rely on a cache which might be invalidated, when a particle is added.

**Comment by jngrad** [comment]
The slow-down only occurs when the particles are inserted without an id, in which case the core has to determine the current largest id, which scales with O(N) at the moment. Here are my observations on a 32 core NUMA workstation:
* traversing the ` particle_node` to find the largest particle id scales with O(N)
* traversing the `local_cells` in parallel followed by a reduction scales with O(N^2)
* book-keeping the largest particle id during particle insertion and removal scales with O(1)

I went with the third option, which was actually implemented in ESPResSo 4.0 if I recall correctly. I tried it on the Bee cluster with `srun --ntasks=128 ./pypresso mwe.py` using several hundred thousand particles and particle insertion didn't slow down. The cached max seen particle is only invalidated when removing the particle with max seen id *and* the id immediately before doesn't exist, in which case the particle range contains a gap and a O(N) traversal is carried out to find the new largest id. This is however only an issue in simulations that introduce gaps in the id list.
