### ISSUE TITLE
Fene bond for distance=0 and r_0 != 0 wrong

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4453]
When the equilibrium distance is not 0, the force function for a particle distance of 0 should either throw or return a random force.
Currently it returns (0,0,0), which is wrong.

Currently, we have a situation where the bonded energy is non-zero but the bonded pressure tensor is zero, which is an excellent sink for user time.

The harmoinc bond needs to be checked, too.

**Comment by christophlohrmann** [comment]
I can look at that on Monday
