### ISSUE TITLE
OIF module

### ISSUE THREAD

**Issue by nitramcastel** [espressomd/espresso#4485]
Hello,
I am a newbie trying to use espresso on macOS (Monterey 12.3, Apple M1 pro chip), especially the module object in fluid. I don't know if this is the right place to ask questions about its installation.

The simulation works fine with the samples (except OIF module), so I guess the installation went well.
 In the general documentation of espresso, I find mentions about this object in fluid module, but when trying to build espresso the file myconfig-samples.hpp, which is supposed to contain all possible features, does not contain the two features: 

```c++
#define OIF_LOCAL_FORCES
#define OIF_GLOBAL_FORCES
```

When I try to build espresso adding these to a personal myconfig.hpp file, I got the following error message:

```
Consolidate compiler generated dependencies of target pdbparser
[  0%] Built target pdbparser
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[  0%] Built target version
[  0%] Built target myconfig
[  0%] Built target generate_config_features
Unknown feature 'OIF_GLOBAL_FORCES'
Unknown feature 'OIF_LOCAL_FORCES', did you mean 'EXTERNAL_FORCES'?
There were errors in '/Users/martincastelnovo/espresso/build/src/config/myconfig-final.hpp'
make[2]: *** [src/config/CMakeFiles/check_myconfig] Error 1
make[1]: *** [src/config/CMakeFiles/check_myconfig.dir/all] Error 2
make: *** [all] Error 2
```

Obviously, something went wrong. I don't where to look at in order to include OIF features...
Is there anyone that could help me?
Thank you in advance!

**Comment by jngrad** [comment]
These two macros were removed in ESPResSo release 4.1.3 ([changelog](https://github.com/espressomd/espresso/blob/da788f1741d9e37555bf698d533a237476ecb3cf/NEWS#L71-L76)). The OIF feature is now always available.

**Comment by nitramcastel** [comment]
Thank you! You helped me figuring out the problem in my case!

**Comment by jngrad** [comment]
You're welcome!
