### ISSUE TITLE
ewaldgpu test case fails when building maxset

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#449]
The relevant part of the test actually sets should_suceed to 0,
suggesting that the operation should fail. The failure is however
not caught.

**Comment by mkuron** [comment]
I'll have a look at that tomorrow. The Ewald test case was derived from my MMM1DGPU test case. The `should_succeed = 0` test checks whether setting different parameters post-initialization actually takes effect. I think the test script correctly checks for that, so perhaps something broke the parameter setting.

**Comment by fweik** [comment]
I broke this while changing the Ewald tuning. I'm going to fix that some time later this week.

**Comment by mkuron** [comment]
#424?

**Comment by fweik** [comment]
Yes. I just changed the tuning though, so not sure if is just an old problem showing up or a regression.
