### ISSUE TITLE
Walberla: oder of instantiation affects Lees-Edwards

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#4498]
The order of instantiation matters for the Collision Kernels.

If the LB is instantiated before Lees Edwards is, the regular collision kernels are used. Also one can't start an LB, to e.g. form or equilibrate a structure and turn on the shear afterwards. The only way is to start with a LE and shear velocity zero. 

There should either be a check on integration start if LE is used or we should mention it in the user guide / display a warning.

**Comment by jngrad** [comment]
This is also an issue for checkpointing: we need to make sure the order in which we restore the state of Lees-Edwards and LB doesn't cause side-effects. I can have a look into that. Lees-Edwards checkpointing will be added by #4519.

**Comment by jngrad** [comment]
Fixed by RudolfWeeber/espresso@550eed37e33134458.
