### ISSUE TITLE
Espresso doesn't build without Boost >= 1.48

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#461]
The configure step stops with the following message if boost version >= 1.48 is not found.

checking for boostlib >= 1.48... configure: We could not detect the boost libraries (version 1.48 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: WARNING: boost was not found on you system, parts of the test system will not be available.
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: error: Could not find a version of the library!

A temporary workaround consists of commenting out the following lines in the "" section of configure.ac (thank you Florian Weik):

AX_BOOST_BASE([1.48],, [AC_MSG_WARN([boost was not found on you system, parts of the test system will not be available.])])
AX_BOOST_UNIT_TEST_FRAMEWORK

**Comment by fweik** [comment]
As far as I can tell this only happens if there is a boost installed that is older as 1.48. Configure works if there is no boost (as tested on a freshly installed ubuntu 15.10 server system). 1.48 is pretty old, so I'd say won't fix.

**Comment by mkuron** [comment]
RedHat Enterprise Linux/CentOS 6, like on our cluster, actually comes with Boost 1.41... So the configure script should check the boost version and give a sensible error message on Boost 1.58.

**Comment by fweik** [comment]
Hm ok. Maybe 1.41 is even sufficient.
