### ISSUE TITLE
Introduce an `EspressoSystem` class in the core

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4615]
... which holds the state of the simulation.

* in the long run, each `espressomd.System` python class whoudl one one of them, via the script interface
* to ease the transition, the core class can be made available via a global, initially.
* globals, as far as they are still needed, would become members of this class

**Comment by jngrad** [comment]
There is `src/core/EspressoSystemStandAlone.hpp` which is currently just a facade to emulate the python `System` class in C++ unit tests, and `src/core/EspressoSystemInterface.hpp` which is a facade to control data exchange with the GPU.

Both of these classes can be removed once the "real" class is implemented.
