### ISSUE TITLE
Implement neighbor list loop

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4620]
## Goal

* Implement a function template that calls a kernel on each particle, providing a list of neighboring particles
* To be used, e.g., for ML potentials, which calculate a descriptor based on a article's surrounding, and then use an ML model to obtain a force from that descriptor
* This is different from the `short_range_loop()` that calculates the LJ interaction
    * as it does not work on pairs, but for each particle provides a list of all short range neighbors
    * there is no assumption of pairwise symmetry ($f_{ab} = f_{ba}$)

## Sketch/example

```c++
template <typename Kernel>
particles_neighbor_list_loop(Kernel kernel) {...};

void add_force_ml(Particle& p, Utils::Span<Particle*> neighbors) {
auto descriptor = calculate_descriptor(neighbors);
auto force = ml_model(descriptor);
p.force() +=force;
}

particles_neighbor_list_loop(add_force_ml)
```

## Steps

* The function template that runs a kernel on all short range neighbors of a single particle is `CellStructure::run_on_particel_short_range_neighbors()`
* Use that to write a `Utils::Span<Particle*> get_particle_short_range_neighbors()`. See `src/core/cells.cpp:mpi_get_short_range_neighbors_local` for inspiration, omit the use of the optional, use a `Particle&` reference rather than a numerical particle id as input
* Write the `particles_neighbor_list_loop` template
    * Loop over all local particles `CellStructure::local_particles()` 
    * Obtain the span containing pointers to the neighbors using the function from the previous step
    * Call the kernel with the current particle and the neighborhood span.
* to test, write a kernel that fills a `std::vector<std::vector<int>>` with lists of particle ids, where the first id in the inner list is the particle for which the neighbor list is obtained and the remaining ints are the ids of the neighbors. See `src/core/cells:non_bonded_loop_trace()` for inspiration.

**Comment by jhossbach** [comment]
I can start working on it.
