### ISSUE TITLE
Checkpointing does not preserve particle director

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4633]
```python
import espressomd
import espressomd.checkpointing
import numpy as np

direc_before = [1,0,0]
system = espressomd.System(box_l= 3*[100])
part = system.part.add(pos=3*[0], director=direc_before, id = 7)

checkpoint = espressomd.checkpointing.Checkpoint(
    checkpoint_id="test",
    checkpoint_path="./",
)

checkpoint.register("system")
checkpoint.save()
system.part.clear()
checkpoint.load(0)
direc_after = system.part.by_id(7).director

np.testing.assert_allclose(direc_after, direc_before, atol=1e-14)
```

This also creates problems with virtual sites, e.g., raspberry particles all point to ``[0,0,1]`` after checkpoint loading which can crash simulations

**Comment by jngrad** [comment]
The magnetic dipole overwrites the quaternion during checkpointing, yikes! This regression was introduced in 4.2.0.

While I write the bugfix, you can disable feature `DIPOLES` from your myconfig file.

**Comment by jngrad** [comment]
Likewise, the angular velocity `omega` was wrong, since it was reloaded before the quaternion. It was thus calculated using the default-constructed quaternion.
