### ISSUE TITLE
Steps in velocity of a single particle in GPU LB

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#466]
I place a single particle in an LB fluid, apply a force to the particle and a counteracting force to the fluid, such that the net momentum transfer is zero. I then look at the stationary state velocity of the particle. For the CPU LB, this works as expected. With the GPU LB, the particle's velocity remains constant for long stretches of time, but then decreases rapidly and assumes a new steady state velocity.

Stepping pattern for different observables:

particle velocity: down, down
particle force magnitude: down, down
fluid velocity at particle position: down, down
fluid velocity at (0,0,0): down, up

The steps happen after having crossed the box 260 and 2280 times.

![velocity](https://cloud.githubusercontent.com/assets/1030677/11284225/85181126-8f00-11e5-8c28-e2f068bf97fc.png)

[singleparticle.txt](https://github.com/espressomd/espresso/files/39458/singleparticle.txt)

**Comment by Marcello-Sega** [comment]
Can you check mass conservation on the gpu run ?

We did observe mass loss with the gpu shan chen (not with the cpu)
implementation during extremely long runs, which we believe to be caused by
single precision.

M



On Thu, Nov 19, 2015 at 10:01 PM, Georg Rempfer <notifications@github.com>
wrote:

> I place a single particle in an LB fluid, apply a force to the particle
> and a counteracting force to the fluid, such that the net momentum transfer
> is zero. I then look at the stationary state velocity of the particle. For
> the CPU LB, this works as expected. With the GPU LB, the particles velocity
> remains constant for long stretches of time, but then decreases rapidly and
> assumes a new steady state velocity.
>
> Stepping pattern for different observables:
>
> particle velocity: down, down
> particle force magnitude: down, down
> fluid velocity at particle position: down, down
> fluid velocity at (0,0,0): down, up
>
> The steps happen after having crossed the box 260 and 2280 times.
>
> [image: velocity]
> <https://cloud.githubusercontent.com/assets/1030677/11284225/85181126-8f00-11e5-8c28-e2f068bf97fc.png>
>
> singleparticle.txt
> <https://github.com/espressomd/espresso/files/39458/singleparticle.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/466>.
>



-- 
University of Vienna, Institute of Computational Physics

**Comment by rempferg** [comment]
The fluid mass steps down, down. It's initally too high and steps towards the correct value.
![gpu_mass](https://cloud.githubusercontent.com/assets/1030677/11288114/e32c5cb4-8f18-11e5-85b1-5938da2b8c22.png)

The particle momentum steps down, down and doesn't drift.
![gpu_momentum_particle](https://cloud.githubusercontent.com/assets/1030677/11288130/09e3daa8-8f19-11e5-8ce2-9c229623cf33.png)

The fluid momentum steps up, up and drifts up.
![gpu_momentum_fluid](https://cloud.githubusercontent.com/assets/1030677/11288141/2293356c-8f19-11e5-91f3-b481024b26a6.png)

The net momentum doesn't step but drifts up
![gpu_momentum_total](https://cloud.githubusercontent.com/assets/1030677/11288153/31e71f88-8f19-11e5-8b7c-6aa32038065f.png)

The CPU LB doesn't show any of this.

In addition there are several more problems:

1) The net force on the particle in the stationary state is not 0 but -0.05. Since the particle doesn't accelerate, this is probably due to the LB and the order of applying and measuring the force.

2) The total momentum is wrong. It's about -1, but should be 0. Initially everything is at rest and momentum should be conserved.

3) That drift in the net fluid momentum is way too big and directed.

I had other plans for this week...

**Comment by Marcello-Sega** [comment]
Hi,

On Fri, Nov 20, 2015 at 1:02 AM, Georg Rempfer <notifications@github.com> wrote:
>
> The fluid mass steps down, down. It's initally too high and steps towards the correct value.

I'm a bit puzzled about the "initially too high". I guess at step 0 or
step 1 the mass should be the right one. Is there a rapid initial
increase that cannot be resolved in the figure?

Another thought (about single precision): if the force, velocity, and
friction on the particle are all of order 1 and external force on the
nodes around the particle is 8e-6, we might be in the ballpark of
relevant roundoff errors. Making the volume smaller might help (i.e. a
box of 10x1x1)

Also, it might help to make the force on the particle and time_step
smaller (e.g. f=0.01, dt=0.001) just to rule out problems with the
integrator.

M.


>
> The particle momentum steps down, down and doesn't drift.
>
> The fluid momentum steps up, up and drifts up.
>
> The net momentum doesn't step but drifts up
>
> The CPU LB doesn't show any of this.
>
> In addition there are several more problems:
>
> 1) The net force on the particle in the stationary state is not 0 but -0.05. Since the particle doesn't accelerate, this is probably due to the LB and the order of applying and measuring the force.
>
> 2) The total momentum is wrong. It's about -1, but should be 0. Initially everything is at rest and momentum should be conserved.
>
> 3) That drift in the net fluid momentum is way too big and directed.
>
> I had other plans for this week...
>
> —
> Reply to this email directly or view it on GitHub.




-- 
University of Vienna

**Comment by rbardak** [comment]
The initial shift in net momentum could be explained from the fact that
fluid velocity is defined as u+tau*F_ext when applying external forces,
this means that when sampling the fluid momentum it may be one timestep
ahead of the particle, may also be a half timestep, I'm not sure on that.

**Comment by Marcello-Sega** [comment]
Hi,

there factor is 1/2. But this does not explain the change in the mass
mode....well, unless Georg calculated the mass mode as momentum / velocity.
Probably I should have specified that one should look directly at the mass
mode: there is a function for the shanchen case that can be easily ported
to the single component.

Cheers,

M.





On Fri, Nov 20, 2015 at 9:31 AM, Robin Bardakcioglu <
notifications@github.com> wrote:

> The initial shift in net momentum could be explained from the fact that
> fluid velocity is defined as u+tau*F_ext when applying external forces,
> this means that when sampling the fluid momentum it may be one timestep
> ahead of the particle, may also be a half timestep, I'm not sure on that.
>
> On 20 Nov 2015 9:03 am, "Marcello Sega" <notifications@github.com> wrote:
>
> > Hi,
> >
> > On Fri, Nov 20, 2015 at 1:02 AM, Georg Rempfer <notifications@github.com
> >
> > wrote:
> > >
> > > The fluid mass steps down, down. It's initally too high and steps
> > towards the correct value.
> >
> > I'm a bit puzzled about the "initially too high". I guess at step 0 or
> > step 1 the mass should be the right one. Is there a rapid initial
> > increase that cannot be resolved in the figure?
> >
> > Another thought (about single precision): if the force, velocity, and
> > friction on the particle are all of order 1 and external force on the
> > nodes around the particle is 8e-6, we might be in the ballpark of
> > relevant roundoff errors. Making the volume smaller might help (i.e. a
> > box of 10x1x1)
> >
> > Also, it might help to make the force on the particle and time_step
> > smaller (e.g. f=0.01, dt=0.001) just to rule out problems with the
> > integrator.
> >
> > M.
> >
> >
> > >
> > > The particle momentum steps down, down and doesn't drift.
> > >
> > > The fluid momentum steps up, up and drifts up.
> > >
> > > The net momentum doesn't step but drifts up
> > >
> > > The CPU LB doesn't show any of this.
> > >
> > > In addition there are several more problems:
> > >
> > > 1) The net force on the particle in the stationary state is not 0 but
> > -0.05. Since the particle doesn't accelerate, this is probably due to the
> > LB and the order of applying and measuring the force.
> > >
> > > 2) The total momentum is wrong. It's about -1, but should be 0.
> > Initially everything is at rest and momentum should be conserved.
> > >
> > > 3) That drift in the net fluid momentum is way too big and directed.
> > >
> > > I had other plans for this week...
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> >
> >
> >
> >
> > --
> > University of Vienna
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/espressomd/espresso/issues/466#issuecomment-158316447>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/466#issuecomment-158322193>
> .
>



-- 
University of Vienna

**Comment by rempferg** [comment]
I use the following commands to get the fluid mass and momentum

    set m [analyze fluid mass]
    set p_f [analyze fluid momentum]

I checked the code and found that they calculate the mass and momentum directly from the modes.

F = -gamma * (v - u+0.5*tau*F_ext) yields exactly the measured force. Doesn't that imply it's incorrect to add 0.5*tau*F_ext to the velocity?

Longer runs over night gave no new results. There are no more steps occurring, the CPU LB doesn't do anything weird over longer times. The net momentum in the GPU LB keeps drifting linearily and made its way from -1 to 1.

**Comment by rempferg** [comment]
I'm running the same script with an output resolution of 1 time step. I seems as if initially everything is correct, but it then quickly changes.

These are all plottet over the number of time steps (dt=0.01)

![gpu_momentum_particle](https://cloud.githubusercontent.com/assets/1030677/11298478/2a474fba-8f77-11e5-82cf-638d2cd9eac4.png)
![gpu_momentum_fluid](https://cloud.githubusercontent.com/assets/1030677/11298480/2d56115a-8f77-11e5-9e25-c74754bcea64.png)
![gpu_momentum_total](https://cloud.githubusercontent.com/assets/1030677/11298482/2f66356a-8f77-11e5-9dee-7b9c3f866858.png)

This one is plottet over the x position of the particle
![gpu_momentum_total_x](https://cloud.githubusercontent.com/assets/1030677/11298560/e39331d2-8f77-11e5-9629-a487c9c35b0b.png)

**Comment by rempferg** [comment]
For L=10, F=0.01, dt=0.001 the same thing happens. The momenta just all jump back and forth every time step. This certainly is an effect of the weird LB coupling in the VV integrator.

**Comment by rempferg** [comment]
The script just reached the first step. There is no more information in the single step output. The step happens over roughly 300 integration steps and those high frequency oscillations are just superimposed.

**Comment by rempferg** [comment]
I forgot to change the time step for the lbfuid. Thank you for checking, Marcello. The high frequency oscillations disappear. I'm rerunning.

**Comment by rempferg** [comment]
The steps disappear with tau = time_step. I assume they came about as a combination of two effects:

1) tau != time_step caused the back and forth oscillations in every time step
2) I measured every 100th time step, thereby not seeing the back and forth

The step was then just a switch in the phase of the fast oscillations - my output switched from "back" to "forth" or the other way around.
