### ISSUE TITLE
WALBERLA: clean up langevin thermostat

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4718]
The dry Langevin and the thermalised LB thermostat share the way they calculate friction and random noise from a friction parameter. Currently, the code is duplicated and the LB thermostat only has a part of the functionality (no particle-specific or anisotropic gamma).

The friction and noise calculation should moved to a function that both Langevin and LB thermostats can call.

**Comment by RudolfWeeber** [comment]
Christoph, would yo be willing to do this at the coding day?

**Comment by christophlohrmann** [comment]
I can give it a shot. Will we have the usual zoom-meeting for all participants?

**Comment by jngrad** [comment]
Most of the body of the function `friction_thermo_langevin()` from `src/core/thermostats/langevin_inline.hpp` needs to be extracted to a free function that can be re-used inside in the particle coupling code of the LB, such that anisotropic particles can get their noise matrix transformed from lab-frame to body-frame before coupling to the fluid. Currently, the LB coupling code only contains a copy of the isotropic component of the Langevin code in  `couple_particle()` and `lb_lbcoupling_calc_particle_lattice_ia()`  from `src/core/grid_based_algorithms/lb_particle_coupling.cpp`.

Adapt `testsuite/python/thermostats_anisotropic.py` to verify the coupling of anisotropic particles is correct.

**Comment by jngrad** [comment]
Closing since it was achieved as part of #4743.
