### ISSUE TITLE
Separate short-range forces by signature

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4755]
For the struct-of-arrays based short-range loop (#4754), short range forces need to be separated by their input/output signature:

This ticket is suitable for new developers, as the work is pretty localized and does not require advanced C++ concepts

* central, radial: 

    * returns scalar force (along the connecting vector)
    * takes distance and interaction parameters as input
    * examples: Lennard-Jones, soft-sphere, tabulated

* central radial with charge:

    * input: distance, product of charges, interaciton parameters
    * output: force along the connecting vector
    * Example: P3M short range
* non-central
    * dipoles short-range contributoin, elc short range contribution, etc.

Depending on which classes of forces are active, the struct-of-arrays short-range calculaoitn can decide, which quantities to pre-calculate

## Technical details

* Split the short-range force soccurring in 
forces_inline.hpp:add_nonbonded_pair_force and calc_nonbonded_pair_force into separate funciotns based on the categorizaiton listed above.
* From the add_nonbonded_pair_force function then call the functions for the individual categories and add up their result.
* Work on energy kernels should be deferred.

**Comment by jngrad** [comment]
Check potentials:
```sh
./pypresso ../testsuite/python/interactions_non-bonded.py -v
```
Run all tests:
```sh
cmake . -DESPRESSO_CTEST_ARGS=-j$(nproc)
make -j$(nproc) check_python_skip_long
```
