### ISSUE TITLE
ELC energies (and forces?) might be of by factor 2

### ISSUE THREAD

**Issue by schlaicha** [espressomd/espresso#4786]
Working on the new ELC-IC tutorial (#4784) @Frieda95 and myself realized that there might be a factor 2 missing somewhere.
Looking through the test in [testuite/python/elc.py](https://github.com/espressomd/espresso/blob/python/testsuite/python/elc.py) I realized that there only the interaction of the charges with the walls and applied field is tested.

#4785 proposes to add a test on the Madelung energy: A cubic latttice unit cell is created between two grounded metal interfaces such that the image charge interactions are the same as in an infinite crystal lattice.

According to this, the energy obtained from ELC-IC is twice as large as expected...

**Comment by jonaslandsgesell** [comment]
Is this potentially related? https://github.com/espressomd/espresso/issues/3001#issuecomment-514396801 there it looked like a scaling factor as well
