### ISSUE TITLE
Switch tutorials to JupyterLab

### ISSUE THREAD

**Issue by schlaicha** [espressomd/espresso#4789]
According to the Jupyter project,

> [Jupyter Notebook](https://github.com/jupyter/notebook) is deprecated and it is advised to transition to JupyterLab.

The [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) have been abandoned in favor of [jupyterlab-contrib](https://jupyterlab-contrib.github.io/extensions.html) and support only up to releases 4&5 of Jupyter (current is 7!).

Although spending more than half a day I could not get a compatible chain of jupyter/nbextensions/nbconvert/exercise2 installed via pip, which means that an average user will not be able to run the notebooks as intended locally.

[jupyterlab-solutions](https://www.npmjs.com/package/@rmotr/jupyterlab-solutions) seems like the perfect replacement for exercise2 and from a brief look we would only have to search-and-replace 'exercise2' by 'solution' in the notebook metadata and adapt a few scripts.

Therefore, I strongly suggest to switch to Jupyterlab as soon as possible!

**Comment by jngrad** [comment]
Thank you for looking into this. As far as I can tell, [jupyterlab-solutions](https://www.npmjs.com/package/@rmotr/jupyterlab-solutions) is in alpha and has been abandoned by its author. The corresponding GitHub repository was deleted in 2020. I'm not sure we are gaining much compared to exercise2, especially considering JupyterLab is actively maintained and might eventually break backward compatibility.

Our notebooks and exercise2 cells are compatible with all major vendors: [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html), [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/), [VS Code Jupyter](https://github.com/microsoft/vscode-jupyter). We provide installation [instructions for all of them](https://espressomd.github.io/doc4.2.1/installation.html#setting-up-a-jupyter-environment) and explain how to [convert the exercise2 cells to vendor-specific cells](https://espressomd.github.io/doc4.2.1/running.html#interactive-notebooks). The [JupyterLab extension migration table](https://jupyterlab-contrib.github.io/migrate_from_classical.html) currently doesn't have a replacement for exercise2.

**Comment by schlaicha** [comment]
Sorry, I did not check if the package is maintained :-(

The installation instructions will not work anymore, 
`pip3 install --user nbformat notebook 'jupyter_contrib_nbextensions==0.5.1'`
for me pulls in Jupyter-7.0 which is incompatible with nbextensions.

So you need to manually specify basically all versions (note that nbconvert again is not compatible with all versions, then there comes jupyter-server, jupyter-client, ...). Can you provide a `jupyter --version` for a setup which we have in the CI? Then I can try again to install...

The hint concerning how to [convert the exercise2 cells to vendor-specific cells](https://espressomd.github.io/doc4.2.1/running.html#interactive-notebooks) is what I overlooked.

**Comment by jngrad** [comment]
```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 7.31.1
ipykernel        : 6.7.0
ipywidgets       : not installed
jupyter_client   : 7.1.2
jupyter_core     : 4.9.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.6
nbconvert        : 6.4.5
nbformat         : 5.1.3
notebook         : 6.4.8
qtconsole        : not installed
traitlets        : 5.1.1
```

**Comment by schlaicha** [comment]
Thank you @jngrad , with the output of `jupyter --version` I could resolve everything.

Note, however, that the information provided in #4790 was not sufficient for me, resulting in
```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.15.0
ipykernel        : 6.25.2
ipywidgets       : not installed
jupyter_client   : 8.3.1
jupyter_core     : 5.3.2
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.13
nbconvert        : 6.4.5
nbformat         : 5.1.3
notebook         : 6.4.8
qtconsole        : not installed
traitlets        : 5.10.1
```
and thus giving an error ```ModuleNotFoundError: No module named 'jupyter_server'```.

So one really needs to make sure to specify the versions for **all** packages mentioned above in the installation instructions.
