### ISSUE TITLE
Inaccuracy in the lattice boltzmann tutorial

### ISSUE THREAD

**Issue by sH4MbLe5** [espressomd/espresso#4804]
In espressomd/espresso/tree/python/doc/tutorials/lattice_boltzmann/lattice_boltzmann_sedimentation.ipynb
the 'dist' parameter of the espressomd.shapes.Wall object should be set to spacing not to 1.

**Comment by jngrad** [comment]
Thank you for your feedback. As far as I remember, this spacing value was deliberately chosen such that the ceiling wall wouldn't exert a non-bonded force on the top layer of the particle cloud during the first time step. For the LB algorithm, the distance is actually rounded down, thus a distance of 1.0 or 1.22 will in either case create a LB boundary of thickness 1. The user guide doesn't seem to mention this rounding-down feature, though. I've opened a PR to add a paragraph to that effect (see [`99f4275d:doc/sphinx/lb.rst`](https://github.com/espressomd/espresso/pull/4810/commits/99f4275d3b5473e3ec46ed9156552fa9afa62642#diff-f3cbdabf6a663f9aa84dbbeb4f09ca8f72355e4409d9879c6c5749e33dedf589)).
