### ISSUE TITLE
Thermostats need better documentation

### ISSUE THREAD

**Issue by christophlohrmann** [espressomd/espresso#4812]
The documentation for the brownian thermostat should mention the equation of motion and the way it is solved numerically.
Use the Langevin doc as inspiration.

Well suited for espresso newcomers at their first coding day

**Comment by jngrad** [comment]
Some of the other thermostats are also quite poorly documented.

Feel free to recycle the LaTeX equations written down in https://github.com/espressomd/espresso/issues/4015#issuecomment-779372048

**Comment by jngrad** [comment]
In addition, the notation for the particle position is inconsistent and is missing arrows, so it's not always obvious whether equations relate to the 1D case or 3D case. See https://github.com/espressomd/espresso/pull/4898#discussion_r1549625189 for more details.
