### ISSUE TITLE
Lees-Edwards update after LB construction

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4874]
LB ignores Lees Edwares boundary condition, if it is set up after LB. To reproduce, switch the initializaiton order from 
1. LE
2. LB
to the opposite in the Lb Lees Edwards tests.

As an aside, the code that constructs the LeesEdwards Pack pased to LbWalberla should probbably be somewhere in teh core rather than in the script interface.

**Comment by jngrad** [comment]
Offline discussion: the best way forward would be for the lattice-Boltzmann object to update its collision operator whenever the Lees-Edwards protocol changes using a hook.

**Comment by RudolfWeeber** [comment]
When the Lees Edwards boudnary condition is changed:
* a (new) event funciotn System::on_lees_edwards_change should be called
* This, in turn shoudl call the (new) event funciont in the LB class in the core (src/core/lb/solver.hpp)
* Which should call LBWalberlaImpl::set_collision_model() with the corresponding Lees Edwards pack (src/walberla_bridge/src/lattice_boltzmann/lb_walberla_impl.hpp)
* The code to set  up the lees edwrds pack is currently in the script interface (/src/script_interface/walberla/LBFludi.cpp)
