### ISSUE TITLE
Configuring failed because of cmake version

### ISSUE THREAD

**Issue by sqwwww** [espressomd/espresso#4900]
hi，

I used “espresso-4.2.1.tar.gz” download from github. after I entered "cmake ..", it gave an error and exit. the error message is as following:

> CMake Error at CMakeLists.txt:22 (cmake_minimum_required):
>   CMake 3.16 or higher is required.  You are running version 2.8.12.2
> 
> 
> -- Configuring incomplete, errors occurred!

Is there a way that I can cross the error and finish the Configuration?

I saw a file called "[espresso-4.2.1.tar.gz.sig](https://github.com/espressomd/espresso/releases/download/4.2.1/espresso-4.2.1.tar.gz.sig)" in the release page, Is it an singularity container of espresso? Singularity container would be very convenient to use in my cluster.

Thanks

**Comment by jngrad** [comment]
Hi,

Clusters typically provide more recent versions of CMake than the one installed in `/usr/bin`. Run `module spider cmake` to list them all. If none of them satisfy our requirements, you can install a newer version in your python environment with some variation of `python3 -m pip install --user 'cmake>=3.24.2'` (the quotes are important).

The .sig file is a GnuPG signature used to verify the authenticity of the tarball file.
