### ISSUE TITLE
AngleCosine bond crashes the simulation after rescaling the simulation box

### ISSUE THREAD

**Issue by Yashas17** [espressomd/espresso#5008]
I am trying to simulate a gel with FENE, WCA and AngleCosine bond potentials. My script looks like this:

```python
import numpy as np
import espressomd
import espressomd.interactions
import espressomd.polymer

final_box_factor = 0.5
steps_per_sample = 200
sim_steps = 100000

MPC = 20
bond_length = 0.966

a = (MPC + 1) * bond_length / (0.25 * np.sqrt(3))
final_box_l = final_box_factor * a

system = espressomd.System(box_l=3 * [a])

system.time_step = 0.01
system.cell_system.skin = 0.4

system.non_bonded_inter[0, 0].wca.set_params(epsilon=1, sigma=0.97)

fene = espressomd.interactions.FeneBond(k=30, d_r_max=1.5)
system.bonded_inter.add(fene)

espressomd.polymer.setup_diamond_polymer(
    system=system, bond=fene, MPC=MPC, type_nM=0, type_cM=0
)

node_ids = np.linspace(1, 7, 7)

angle_cosine = espressomd.interactions.AngleCosine(
    bend=1.0, phi0=109.5 * np.pi / 180.0
)
system.bonded_inter.add(angle_cosine)

for node_id in node_ids:
    p = system.part.by_id(int(node_id))
    temp_ids = system.analysis.nbhood(pos=p.pos, r_catch=bond_length * 1.0001)
    temp_ids.remove(int(node_id))
    for i in range(3):
        for j in range(i, 4):
            p.add_bond(
                (
                    angle_cosine,
                    system.part.by_id(temp_ids[i]),
                    system.part.by_id(temp_ids[j]),
                )
            )

system.integrator.set_steepest_descent(f_max=0, gamma=1e-3, max_displacement=0.01)
while system.analysis.min_dist() < 0.9:
    system.integrator.run(20)

system.integrator.set_vv()

system.thermostat.set_langevin(kT=1.0, gamma=1.0, seed=42)

system.integrator.run(10000) 

total_isotropic_pressures = []
steps_size = 1
steps_needed = int(abs(a - final_box_l) / steps_size)
for j in np.arange(0, steps_needed):
    print("box now at ", system.box_l)
    system.change_volume_and_rescale_particles(
        d_new=system.box_l[0] - np.sign(a - final_box_l)*steps_size, dir="xyz"
    )
    print("box now at ", system.box_l)
    system.integrator.run(100)
```

It crashes after the box is resized and when I try to integrate it again and throws an error for multiple particles moving more than the box length in one time step and the simulation crashes. This behaviour is not observed with the other two angular bonds- Cossquare and Harmonic. I have also tried reducing the step_size down to 0.01, and it still did not help.

**Comment by jngrad** [comment]
Add `print(p.id, temp_ids[i], temp_ids[j])` into the innermost loop that adds the bond and you will see what's wrong.

Would you be willing to contribute to the Python code of ESPResSo? You would need to add an extra check after this one:
https://github.com/espressomd/espresso/blob/1f672a00e22a9bc5fec1f7070bd28ff7718a706e/src/python/espressomd/particle_data.py#L617-L619
The check should be written in such a way that it works for all types of bonds, including size 0 (`Virtual` bond). Then add exception assertions in the test suite file `testsuite/python/particle.py` at the end of `test_bonds()`, one for each size of bond (except size 0), plus one for the case where the id of the central particle appears in the partners list (corresponds to the exception in the code sample linked above).
