### ISSUE TITLE
Move checkpointing to boost::serialization

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#508]
Convert all io code to boost::serialization code where possible, except from hdf5 code maybe. This let us get rid of lots of redundant and error prone code, and actually has advantages, e.g. you can change the file format without touching the code. This means that we maybe need an implementation of boost:archive for blockfiles.

**Comment by jngrad** [comment]
The global state of ESPResSo is now managed by the script interface. Resources owned by script interface objects are automatically serialized using `Utils::pack()`, which relies on `boost::archive::binary_oarchive` under-the-hood.

I'm closing this in favor of #4542, which keeps track of our progress removing the last remaining `__getstate__()` and `__reduce__()` methods in the python interface.
