### ISSUE TITLE
Errors using sample file "lj_liquid.py"

### ISSUE THREAD

**Issue by sehrhardt** [espressomd/espresso#511]
Sample file "lj_liquid.py":
* Command "system.skin=0.4" -> segfault 
* If feature "#define ROTATIONAL_INERTIA" not activated -> error "undefined symbol: _Z15particle_existsi" at runtime

**Comment by sehrhardt** [comment]
The command  "system.skin=0.4" was still working at commit:
70449a19fefa844483d2512392536c4e1559cc7f

**Comment by fweik** [comment]
This is a problem with the linking of the shared objects. I'm on it.

**Comment by fweik** [comment]
Should be fixed.

**Comment by RudolfWeeber** [comment]
The ssegfault is still there, but it is not so clear that it is related to shared object stuff.
The segfault apparently occurs in the linear momentum calculation and from there in the gpu lb momentum calculation, even though the lj liquid test case doesn't have that.
(@KaiSzuttor)

**Comment by fweik** [comment]
samples/python/lj_liquid.py works for me, I checked that.

On Tue, Jan 26, 2016 at 4:08 PM, RudolfWeeber <notifications@github.com>
wrote:

> The ssegfault is still there, but it is not so clear that it is related to
> shared object stuff.
> The segfault apparently occurs in the linear momentum calculation and from
> there in the gpu lb momentum calculation, even though the lj liquid test
> case doesn't have that.
> (@KaiSzuttor <https://github.com/KaiSzuttor>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/511#issuecomment-175066460>
> .
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by rbardak** [comment]
default config works for me, then I tried running it on a minimalistic config, which was just

#define LENNARD_JONES

it worked fine too. Then I tried activating some of the features the script supposedly requires. I ran into trouble when activating LB_GPU.

@sehrhardt @RudolfWeeber : what configs did you use?

**Comment by RudolfWeeber** [comment]
the maxset config, maybe with small changes.

/* maximal set of features usable at the same time */
#define PARTIAL_PERIODIC
#define ELECTROSTATICS
#define DIPOLES
#define ROTATION
#define ROTATIONAL_INERTIA
#define EXTERNAL_FORCES
#define CONSTRAINTS
#define MASS
#define EXCLUSIONS

#define BOND_VIRTUAL
#define ROTATION_PER_PARTICLE

#define LB
#define LB_BOUNDARIES
#define LB_ELECTROHYDRODYNAMICS

#ifdef CUDA
#define LB_GPU
#define LB_BOUNDARIES_GPU
#endif

#define AREA_FORCE_GLOBAL   
#define VOLUME_FORCE   

#define TABULATED
#define LENNARD_JONES


#define BOND_ANGLE
#define BOND_ANGLEDIST
#define BOND_ANGLEDIST_HARMONIC
#define BOND_ENDANGLEDIST
#define BOND_ENDANGLEDIST_HARMONIC

#define VIRTUAL_SITES_RELATIVE

**Comment by fweik** [comment]
Is fixed, it was not checked if the LB is actually turned on before accessing the fluid (via lb_calc_fluid_momentum_GPU)
