### ISSUE TITLE
Jekins and Travis integration for Cmake

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#521]

**Comment by fweik** [comment]
I'm considering removing tavis again. We can get the same functionality with jenkins, and then we could not have to maintain two systems. Also the waiting times on travis have been so long lately that it would better be called not-so-continuous integration. Any opinion on that?

**Comment by mkuron** [comment]
Travis has a nicer Github integration. It shows the status right there in the pull request. Is it really that much work to maintain both? Besides the ongoing CMake migration, there are probably not many times when the CI needs to be touched.

Regarding the waiting times: Perhaps [done.io](https://drone.io) is better?

**Comment by fweik** [comment]
The documentation of the jenkins github plugin claims they have the same level of integration. Jenkins also has the advantage that we can test CUDA code in pull requests.

**Comment by RudolfWeeber** [comment]
> I'm considering removing tavis again. We can get the same functionality with jenkins, and then we could not have to maintain two systems. Also the waiting times on travis have been so long lately that it would better be called not-so-continuous integration. Any opinion on that?
I'd vote to keep travis, since I also use it on my personal repo with Espresso.
I find it helpful to see travis results for stuff for which I don't
want to open a pull request.

**Comment by Marcello-Sega** [comment]
Dear all,

if I had to choose one, I would like to keep travis...but I also wonder
wether it's really that much work to keep both.

Cheers,

M



On Wed, Mar 2, 2016 at 3:40 PM, RudolfWeeber <notifications@github.com>
wrote:

> > I'm considering removing tavis again. We can get the same functionality
> with jenkins, and then we could not have to maintain two systems. Also the
> waiting times on travis have been so long lately that it would better be
> called not-so-continuous integration. Any opinion on that?
> I'd vote to keep travis, since I also use it on my personal repo with
> Espresso.
> I find it helpful to see travis results for stuff for which I don't
> want to open a pull request.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/521#issuecomment-191263344>
> .
>



-- 
University of Vienna, Institute of Computational Physics

**Comment by fweik** [comment]
We still need to keep jenkins, because self-hosting is the only way to test
GPU code. I'm not happy about that either. Travis has wired stuff going on
with their python environment, which I'm trying to figure out.
This came about because I had to change the platform from Ubuntu 12.04 to
14.04 to have a newer compiler available.

On Wed, Mar 2, 2016 at 3:49 PM, Marcello Sega <notifications@github.com>
wrote:

> Dear all,
>
> if I had to choose one, I would like to keep travis...but I also wonder
> wether it's really that much work to keep both.
>
> Cheers,
>
> M
>
>
>
> On Wed, Mar 2, 2016 at 3:40 PM, RudolfWeeber <notifications@github.com>
> wrote:
>
> > > I'm considering removing tavis again. We can get the same functionality
> > with jenkins, and then we could not have to maintain two systems. Also
> the
> > waiting times on travis have been so long lately that it would better be
> > called not-so-continuous integration. Any opinion on that?
> > I'd vote to keep travis, since I also use it on my personal repo with
> > Espresso.
> > I find it helpful to see travis results for stuff for which I don't
> > want to open a pull request.
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/espressomd/espresso/issues/521#issuecomment-191263344>
> > .
> >
>
>
>
> --
> University of Vienna, Institute of Computational Physics
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/521#issuecomment-191267704>
> .
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by mkuron** [comment]
drone.io works and is very fast. https://drone.io/github.com/mkuron/espresso/
Unfortunately, it seems like it doesn't have the build matrix functionality that Travis offers. So you can only specify one script that is to be run, not an entire `.travis.yml`-like file. That functionality only exists in the self-hosted version of Drone.

**Comment by RudolfWeeber** [comment]
s this resolved?
