### ISSUE TITLE
Cmake: Auto-detection of some libs doesn't work

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#540]
CUDA:
On a system without cuda:
$ cmake ~/espresso
-- Config file: /home/rudolf/espresso/src/core/myconfig-default.hpp
CMake Error at /usr/share/cmake-3.2/Modules/FindCUDA.cmake:586 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
  Call Stack (most recent call first):
    CMakeLists.txt:60 (find_package)

    -- Configuring incomplete, errors occurred!
    See also "/home/rudolf/es-build/CMakeFiles/CMakeOutput.log".

TCLTK: Apparently, find_package(TCL) only succeeds if tk is also there
$ cmake -D WITH_CUDA=0 ~/espresso
-- Config file: /home/rudolf/espresso/src/core/myconfig-default.hpp
-- Found PythonInterp: /usr/bin/python (found version "2.7.10")
-- Found Cython: /usr/local/bin/cython
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.10")
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found version "1.8.2")
-- NumPy ver. 1.8.2 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Could NOT find FFTW3 (missing:  FFTW3_LIBRARIES FFTW3_INCLUDE_DIR)
-- FFTW3 not found, diabling it.
-- Found Tclsh: /usr/bin/tclsh (found version "8.6")
-- Found TCL: /usr/lib/x86_64-linux-gnu/libtcl8.6.so
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find TCLTK (missing: TK_INCLUDE_PATH)
  Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindTCL.cmake:225 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:85 (find_package)

  -- Configuring incomplete, errors occurred!
  See also "/home/rudolf/es-build/CMakeFiles/CMakeOutput.log".

**Comment by RudolfWeeber** [comment]
And mpi (when not present, mpi_fake should be selected)

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake/Modules/FindMPI.cmake:587 (find_package_handle_standard_args)
CMakeLists.txt:135 (find_package)

**Comment by fweik** [comment]
@RudolfWeeber  can you please check if this problem still exists.
