### ISSUE TITLE
Add check for Cython version to build system

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#555]
The compiler throws multiple errors compiling cython files while building espresso with the autotools. 

electrostatics.pxd:183:12: Expected an identifier, found 'DECORATOR'
cellsystem.pyx:69:41: Cannot convert 'void' to Python object
utils.pyx:81:5: closures inside cdef functions not yet supported
...

The cython version that is installed on my institute work machine is Cython version 0.19.2

**Comment by jonaslandsgesell** [comment]
The  problem is fixed when installing a new cython version via 'pip install --user --upgrade cython' and putting the path /$HOME/.local/bin/cython into the PATH variable (Thanks Georg).

**Comment by fweik** [comment]
The python interface needs at least cython 0.22, there should be a check in the build system, but isnt.

**Comment by RudolfWeeber** [comment]
I googled: python -c "from Cython.Compiler.Version import version; print version"
I'm not experienced in putting this into cmake, though

**Comment by fweik** [comment]
Fixed with fe777b4c1aca05b624cbe6db937e53e7834898c2
