### ISSUE TITLE
Checkpointing of the RNG is gone

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#577]
Commit 9ccafbbd9308c1e8732a30af9225078083deb3f4 completely broke the blockfile mechanism of ESPResSo!  `t_random stat` is called from within the [`blockfile_support.tcl`](https://github.com/espressomd/espresso/blob/master/scripts/blockfile_support.tcl#L413) script.

**Comment by jonaslandsgesell** [comment]
The bitrandom generator (and its checkpointing) have already gone before this commit.

Maybe we should think about the necessity to checkpoint the random number generator. For physically relevant observables the seed and the current state of the random number generator before checkpointing should not matter statistically (also since checkpointing is a rare event).
Checkpointing of the RNG is however relevant if there is a need to produce bit-identical simulations where checkpointing occurs. See also http://www.gromacs.org/Documentation/How-tos/Extending_Simulations#Exact_vs_binary_identical_continuation in the exact vs binary section.

However we can use the standard Cpp11 methods to obtain the internal state of the RNG.

**Comment by hmenke** [comment]
I am not referring to `bit_random` but rather to `t_random`.  The relevant change is [this](https://github.com/espressomd/espresso/commit/9ccafbbd9308c1e8732a30af9225078083deb3f4#diff-c61b75d62735b82fb66f0891144e810fL129).

Also, if you remove any features, make sure they are purged completely from all helper scripts.  That is to say, please have a look at [`blockfile_support.tcl`](https://github.com/espressomd/espresso/blob/master/scripts/blockfile_support.tcl).  There are still some references to `bit_random` (and the offending `t_random stat`).

**Comment by hmenke** [comment]
Here is also a simple script to reproduce the issue
````
set f [open "test.blk" "w"]
blockfile $f write random
````
One then receives
````
Unknown argument 'stat' requested!
Usage: 't_random [{ int <n> | seed [<seed(0)> ... <seed(0)>] }]'
````

**Comment by fweik** [comment]
This is just an interface bug. The method you quote only deals with the bitrandom PRNG that was not used and is now removed. The obvious solution is to purge "t_random state" everywhere. If somebody needs checkpointing for the RNG that would not be hard to implement, but I don't think that came up yet.

**Comment by tigoesnumb3rs** [comment]
This also affects the lennard jones tutorial..

**Comment by fweik** [comment]
Ok, I somewhat misread that. Henri is right, we need to add the t_random stat mechanism again.

**Comment by hmenke** [comment]
This is still not fine.  Run the following script twice using the latest master.

````Tcl
set fname "test.blk"
if { [file exists $fname] } {
    set f [open $fname "r"]
    blockfile $f read auto
} else {
    set f [open $fname "w"]
    blockfile $f write random
}
````
This produces the following error
````
Wrong # of args: Usage: 't_random stat "<state(1)> ... <state(n_nodes*625)>"'
    while executing
"t_random stat 1 1812433254 3713160357 3109174145 64984499 3392658084 446538473 2629760756 2453345558 1394803949 1021787430 2063496713 1304877364 17136..."
    ("eval" body line 1)
    invoked from within
"eval t_random stat [eval concat $data]"
    (procedure "blockfile" line 3)
    invoked from within
"blockfile $f read auto"
    invoked from within
"if { [file exists $fname] } {
    set f [open $fname "r"]
    blockfile $f read auto
} else {
    set f [open $fname "w"]
    blockfile $f write rando..."
    (file "test.tcl" line 2)
````
Looking at the [parser of "stat"](https://github.com/espressomd/espresso/blob/master/src/tcl/random_tcl.cpp#L75) revealed, that there are only two arguments expected, namely the `stat` keyword and a string of seeds.  This conflicts with the documented behaviour which is `t_random stat <seed1> ... <seedN>`, i.e., a variadic number of seeds *not* one delimited string.  Furthermore, as shown in the example, this conflicts with the blockfile reader, which stores N seeds instead of one string of N seeds.

A quick fix, I could think of would perhaps be replacing `if(argc != 2)` [here](https://github.com/espressomd/espresso/blob/master/src/tcl/random_tcl.cpp#L85) by something like `if(argc < 2 || argc > n_nodes*625)`.

Please reopen this issue.

**N.B.:** Please also want to factor out the [Magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) of 625.

**Comment by jonaslandsgesell** [comment]
I think for the mersenne twister you can ask for this number by:

std::size_t seeds[ std::mt19937::state_size ] ;

**Comment by RudolfWeeber** [comment]
Is this resolved?

**Comment by jonaslandsgesell** [comment]
For me the test runs without the above problem. This seems to be fixed. 
I also changed the documentation with regard to the fact that "t_random stat" takes a string which is composed of seeds separated by spaces.

However a new problem has shown up:
Running the following script fails to set the seed in the core to 3, instead the seed 1 is reported from the core.
> t_random seed 3
>puts [t_random seed]

**Comment by RudolfWeeber** [comment]
Can this be closed?

**Comment by jonaslandsgesell** [comment]
Yes, I open a new issue for the seed in tcl

**Comment by RudolfWeeber** [comment]
Tcl. Won't fix
