### ISSUE TITLE
Build with scafacos ignores custom include dir supplied by pkg-config

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#581]
Maybe, becasue pkg-configu supplieds cflags but not c++-flags?
The build can still be done by manually adding -I... to the cxx flags

**Comment by fweik** [comment]
I think the PREFIX_CFLAGS have to be added explicitly to the compile flags. Could you try if that fixes the issue (Just add SCAFACOS_CFLAGS to the CMAKE_C_FLAGS).

**Comment by RudolfWeeber** [comment]
I tried adding  this, if scafacos is found
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SCAFACOS_CFLAGS}")
but it didnt' change anything.
Also in ccmake in the advanced mode, I don't se anything scafacos-related )like SCAFACOS_CFLAGS( except WITH_SCAFACOS

**Comment by fweik** [comment]
Bump
