### ISSUE TITLE
Langevin friction term calculated although thermostat langevin off

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#586]
If you switch of one component of the langevin thermostat by e.g.
`thermostat langevin $T $G off on`,
the tcl interface just sets 
`langevin_trans = false`.
In thermostat.hpp, this results in
`switch_trans = 0.0`
which appears as a factor in the force calculation, **but only in the noise term**.
If there is no special reason for this, this is a Bug. 
Same thing happens in both translational and rotational thermalization.

**Comment by fweik** [comment]
Looks like a bug to me

**Comment by KonradBreitsprecher** [comment]
So I should have read the ug...this is intended.

"Finally, the two options [on/off] allow one to switch the translational and
rotational thermalization on or off separately, **maintaining the frictional behavior**. This
can be useful, for instance, in high Peclet number active matter systems, where one
only wants to thermalize the rotational degrees of freedom and translational motion is
effected by the self-propulsion."
