### ISSUE TITLE
runtimeErrorMsg() doesn't work with boost test

### ISSUE THREAD

**Issue by rbardak** [espressomd/espresso#598]
When testing functions which use runtimeErrorMsg(), the I/O buffer doesn't survive testing and when the time comes to flush it --> segfault.

**Comment by fweik** [comment]
I don't understand you bug report.

**Comment by rbardak** [comment]
In my particular case, I am using the unit test framework to test a sanity check which uses an ostream to print out error messages. If I use std::cout for that, I do not encounter any trouble. However if I use runtimeErrorMsg() which is implemented in Espresso, my tests fail. Please note that I do not parse the printed out message so it doesn't matter if the print is sucessful.

Running the tests causes a failure and prints out that an invalid memory access has occured. The program doesn't actually segfault (which is to be expected because the boost test framework should catch that). Running it in gdb reveals the segfault.

After a quick search I found that calling a function with BOOST_CHECK_XXX( "functioncall", "assertvalue") makes sure that nothing in the scope of the function call survives, including iobuffers.

Looking at the code that is executed, runtimeErrorMsg() returns a runtimeErrorStream object, on which the operator "<<" is subsequently applied by me. This in itself shouldn't be a problem. When the object gets out of scope, rc.error(...) is called. I suppose this is when the iobuffer is flushed.

I suspect this is an issue with the destructor of runtimeErrorStream, although I'm not sure how to fix it.

**Comment by fweik** [comment]
I think I have a vague idea what is causing this, I'll have a look.

**Comment by fweik** [comment]
Can you post an minimal example (testcast) where this does not work?

**Comment by rbardak** [comment]
Example in the commits above. The first commit (minimal example for #598) is how I did it before. The second commit (modification of #598...)are modifications that I hacked together from looking at your unit tests.
