### ISSUE TITLE
coulomb_cloud_wall test fails with default config

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#610]
It says:

Testing SCAFACOS_ewald...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Dipolar extension not compiled in. Switch on via SCAFACOS_DIPOLES in myconfig.hpp
[2]    2130 segmentation fault (core dumped)  ../../Espresso coulomb_cloud_wall.tcl

Looks like an ifdef issue to me, it should not try to run the dipolar code.

**Comment by RudolfWeeber** [comment]
Fixed via 0bc54...
