### ISSUE TITLE
samples/python not up-to-date

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#611]
Maybe some of the guys familiar with the python interface can have a look into that folder. It looks like a lot of the files in there are not up-to-date or can be deleted (e.g. samples/python/not-working).
@RudolfWeeber  @fweik

**Comment by KaiSzuttor** [comment]
closed by #621

**Comment by fweik** [comment]
Closed iff #621. Github automatically closes the issue if you mention the issue in the pull request as "Closes #number" (as you did)

**Comment by KaiSzuttor** [comment]
Oh thats nice, didn't know that.
