### ISSUE TITLE
Cmake: paralell build immediately after cmake fails

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#614]
running 
cmake ~/espresso
make -j8

fails. However, building the first few items with a single build process, interrupting with control-c and then running make -j8 works fine.

**Comment by fweik** [comment]
I thought this would be fixed by 608ef089b353166f1a3a2ddb03b150ea4f2dabf5 .
Are you sure? :-)

**Comment by fweik** [comment]
Should be fixed by d88481fd941c597dcf0dd89e517fc3e2fb302475 @RudolfWeeber please check
