### ISSUE TITLE
P3M check for periodicity before tuning

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#617]
P3m requires 111 preiodicity. This is not denoted in the userguide and probably would be good.
When trying to tune p3m e.g. with periodicity 110 (setmd periodicity 1 1 0)  espresso should throw an error. Instead espresso does not terminate.

**Comment by fweik** [comment]
This is a bug. (See line 318 in p3m.cpp). The sanity check is not run on the master, this is also why it hangs.
