### ISSUE TITLE
engine_lb.py fails

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#644]
Python test case fails because the reference data is missing. Forgot to check in?
@hmenke

**Comment by hmenke** [comment]
That is correct.  Actually, I would rather have a symlink (or something similar) to the reference data (in the tcl testsuite) to not have it twice.  Any suggestions?

**Comment by fweik** [comment]
Cmake does not support symlinks because they are not portable. I think we can live with a copy, especially because it is only created if the testsuite is run.
