### ISSUE TITLE
Py docs: Templates for the correct use of pysyntax in the user guide

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#653]
For cases such as

Particle iteration
for p in system.part:

Number of particles
len(system.part)

Method calls:
system.part.clear()

**Comment by hmenke** [comment]
# Method calls

If you want to list available methods for calling, such as `clear()`, I suggest using the `\attributes` macro in the following way.

````latex
\begin{pysyntax}
  \attributes{
    system
  }{
    part
  }{
    clear()
  }
\end{pysyntax}
````

# Particle iteration and number of particles

I don't think that there should be separate formatting for particle iteration and number of particles.  These kinds of things should be shown in usage examples, but not in the reference overview.  If still urgently needed, I suggest showing this functionality be listing the Python attributes alongside the callable methods and member variables.

````latex
\begin{pysyntax}
  \attributes{
    system
  }{
    part
  }{
    __len__,
    __iter__,
    clear()
  }
\end{pysyntax}
````

It is quite hard to have unspecific documentation macros for such heterogeneous interfaces.  If there is actually a demand and a compelling use-case for syntax as shown in the question, I can come up with something.

**Comment by hmenke** [comment]
# Code examples

To typeset code examples, I could add the `listings` package to the user guide an implement a style to pretty-print pypresso code, as shown below:

````latex
\begin{lstlisting}[language=pypresso]
import espressomd
S = espressomd.System()
S.part.add(pos=[0,1,2])
S.part.add(pos=[0,2,1])
for p in S.part:
    print(p.pos)
\end{lstlisting}
````

**Comment by hmenke** [comment]
Attached is a visual mockup of what I think pretty-printed pypresso code could look like.  The code is from the sample `minimal-polymer.py`.
![test](https://cloud.githubusercontent.com/assets/1903556/16194785/a96a285e-36f6-11e6-880f-6b281dd13253.png)

**Comment by RudolfWeeber** [comment]
825ghi close
