### ISSUE TITLE
writevcf in tcl writes down unwanted zero

### ISSUE THREAD

**Issue by MartinFischerICP** [espressomd/espresso#659]
This script gives me an unwanted zero at the end of my first particle coordinates.... annoying when using small z coordinates because 1e-6 becomes 1e-60 

set N_0 20
set box_l 10
setmd box_l $box_l $box_l $box_l
setmd periodicity 1 1 1
for {set i 0} {$i < $N_0} {incr i} {
   set pid [setmd n_part]
   set posx [expr [t_random]*$box_l]
   set posy [expr [t_random]*$box_l]
   set posz [expr 1e-6*[t_random]*$box_l]
   part $pid pos $posx $posy $posz type 1 q 0
   puts "$posx $posy $posz"
}

set vtf_file [open "./test.vtf" "w"]

writevsf $vtf_file
writevcf $vtf_file
close $vtf_file
exit

**Comment by rbardak** [comment]
well, this script doesn't execute because you're not giving `expr` an operator to work with.

**Comment by MartinFischerICP** [comment]
sorry that was my first report so i didnt know how to insert code nicely.. but when u insert like
set posx [expr [t_random]*$box_l]
set posy [expr [t_random]*$box_l]
set posz [expr 1e-6*[t_random]*$box_l]

It should work properly and gives u at the first coordinate position an aditional zero. and ONLY at the first z coordinate.

**Comment by rbardak** [comment]
In this case it's a bug. I already found it too. writevcf always appends an additional zero after the output for the particle with pid = 0. This is caused by the default value for the "userdata" option.
