### ISSUE TITLE
Build problems with Cython 0.22: particle_data.pyx:1038:67

### ISSUE THREAD

**Issue by AlexanderWeyman** [espressomd/espresso#663]
During the make process on our institute cluster I noticed that it is not possible to build espresso with python/2.7.10 (and Cython version 0.22) module loaded. The problem is most likely caused by src/python/espressomd/particle_data.pyx:1038:67. Further details can be seen in the attached output of make. With python/2.7.11 (and Cython version 0.23.4) module loaded everything works fine.
[make_python_2.7.10_cython_0.22.txt](https://github.com/espressomd/espresso/files/300375/make_python_2.7.10_cython_0.22.txt)

**Comment by fweik** [comment]
Espresso required at least Cython 23.0

**Comment by AlexanderWeyman** [comment]
well, if that is the case we are off the hook and the issue can be closed.
