### ISSUE TITLE
Python: Random number generator and seed

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#674]
we need bindings for the Es random number generator state in py.
Also, I think, the System class should pickle the random number generator states rather than the seed which was set at the beginning of the simulation.
For deterministic tests, we also need an equivalent of the [t_ranomd] in tcl.

**Comment by jonaslandsgesell** [comment]
Some time ago I thought into the direction. The preliminary (?) agreement back then was to just use the numpy random number generator for random numbers in python. Then the user would need to care himself about seeding both (the Cpp and numpy) random number generator. If both seeds are set also deterministic tests are possible.

**Comment by jonaslandsgesell** [comment]
Ok Rudolf has deterministic checkpointing in mind. I'll look into making the random number checkpointing available in python.

**Comment by RudolfWeeber** [comment]
As far as I understand, this is done
