### ISSUE TITLE
Doc not build on Travis

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#715]

**Comment by pdebuyl** [comment]
Is this about the 404 not found for the pdfs linked from the "docs" pages of the website? If so, any idea of the reason?

**Comment by mkuron** [comment]
No, the documentation on the website is built on Jenkins, which has been broken for a few weeks/months now. We'll need to get that back up as the CUDA code is also not built on Travis, so it hasn't had its tests run in a long time now.

Travis by itself only supports uploading build artifacts to Amazon S3, so we don't use it. We could, however, try to have Travis post the documentation to espressomd.org via the Wordpress API. The authentication token could be stored safely in a [secret variable](https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings) in Travis.

**Comment by RudolfWeeber** [comment]
What do we do about this? Rely on Jenkins, only and close this issue?

**Comment by fweik** [comment]
I think we can rely on jenkins for the doc builds...
