### ISSUE TITLE
Query particles while integrating in a python thread causes segmentation fault

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#720]
In some cases (visualization etc) it might be useful to run the integration loop in a daemon thread.
However, this results in a seg fault after a few seconds, maybe due to simultaneous access to the (incomplete) particle data? Polling particle properties with slices works fine.

```
def main():
    while True:
        integrate.integrate(int_steps)

t = Thread(target=main)
t.daemon = True
t.start()

while True:
    print system.part #Seg fault
    print system.part[:].pos #Works!
```

```
Signal: Segmentation fault: 11 (11)
Signal code: Address not mapped (1)
Failing at address: 0x0
[ 0] 0   libsystem_platform.dylib            0x00007fff9966152a _sigtramp + 26
[ 1] 0   Python                              0x0000000104c3dfb5 PyEval_EvalFrameEx + 14850
[ 2] 0   libEspressoCore.dylib               0x00000001051754c3 _Z17get_particle_dataiP8Particle + 147
```

**Comment by KonradBreitsprecher** [comment]
Correction: Polling particle properties with slices **causes the same error**, just takes a little longer.

**Comment by fweik** [comment]
I think the reason for this is that the integrate function does not aquire
an interpreter lock. Maybe Michael Kuron can comment on that.

**Comment by RudolfWeeber** [comment]
I think, this occurs, because the espresso core itself is not thread safe.
Probably the only viable solution is the one Michael implemented for
mayavi: the thread handling espresso stuff copies the particle data
to a buffer from time to time, and the drawing function uses that
buffer.

**Comment by mkuron** [comment]
@fweik: `integrate.integrate` definitely does not need the interpreter lock as the core does not `#include <Python.h>` anywhere.

@RudolfWeeber: you are correct. The two threads compete for access to structures like the particle array. If one of them changes any memory allocations while the other reads, you get a segfault.

The only correct solution is what I did in the visualization demo. So your code should be either
`def main():
    while True:
        integrate.integrate(int_steps)
        print system.part
        print system.part[:].pos

t = Thread(target=main)
t.daemon = True
t.start()`
or
`p = None
def main():
    while True:
        integrate.integrate(int_steps)
        p = system.part[:]

t = Thread(target=main)
t.daemon = True
t.start()

while True:
    print p
    print p.pos`

This issue can be closed as invalid, unless somebody wants to add checks that `integrate` and `system.part` are being run in the same thread.
