### ISSUE TITLE
small typo in ug

### ISSUE THREAD

**Issue by Marcello-Sega** [espressomd/espresso#724]
In the ```part``` command description, the requirement for the exclude option is "EXCLUSION", but the correct one is "EXCLUSIONS". Just a little annoying, because one has to look into the code to find out the right define.

**Comment by jonaslandsgesell** [comment]
You can edit the userguide online on GitHub it s just a few clicks and you have a pull request.

**Comment by Marcello-Sega** [comment]
Wow, cool, it never came to my mind to make changes directly in the web interface :)
Cheers,
M
