### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by tigoesnumb3rs** [espressomd/espresso#726]
After the last coding day all of the tutorial links on the website are broken:

The tutorials generated by 'make doc' now generate the tutorials in a new location, since from now on there will be python tutorials as well:

```
tutorials
├── python
│   └── 02-charged_system
└── tcl
    ├── 00-building_espresso
    ├── 01-lennard_jones
    ├── 02-charged_system
    ├── 03-object_in_fluid
    ├── 04-lattice_boltzmann
    ├── 05-raspberry_electrophoresis
    ├── 06-active_matter
    ├── 07-electrokinetics
    └── 08-visualization
```

Also the links to `05-raspberry_electrophoresis` and `07-electrokinetics` are not linked to the latest jenkins build.

**Comment by fweik** [comment]
@KonradBreitsprecher  ?

**Comment by KonradBreitsprecher** [comment]
I added a static copy of the ug.pdf on espressomd.
Currently, [master-fetch-bootstrap fails on jenkins](http://espressomd.org/jenkins/job/master-fetch-bootstrap/), so do all downstream jobs..
The 'artifacts', the tutorial pdfs are included in the jenkins config and the website now links to TCL and python tutorials. So in principle, everything should work if master-doc is compiling again...

**Comment by KonradBreitsprecher** [comment]
Works now. Also the Chrome/Safari issue with displaying the .pdf files should be resolved.

**Comment by KonradBreitsprecher** [comment]
Ahh one thing is left: We don't want to add python tutorials in both build environments, so the python tutorials only work with cmake.
Related to that, Tilak creates cmake versions of the jenkins jobs. Once this is done, I can link the tutorials to the master-doc_cmake artefacts.
