### ISSUE TITLE
py: Complete integrators

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#739]
* Integrators (at this point velocity_verlet and minimize_energy) should have a common interface and common base class. 
* Instances should be available as attributes of the System class like
  system.velocity_verlet
  system.minimize_energy
  system.brownian_dynamics (no py interface yet)
* The integrate/run method should probably be called the same for all of them.
* Add, whatever is missing regarding npt
* Python docs for all available integrators

**Comment by tobiasrau** [comment]
I'm working on that.
