### ISSUE TITLE
py: Complete system class

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#742]
* Support non-periodic boundary conditions
* Move stuff out of the system class, which doesn't belong there (see below)
* (probably) change read-only properties into functions
* Document

The following attributes of the system class should go to other places
(The reason that they are in the system class now is just that they are accessed via setmd in tcl)

This should go to the thermostat class, probably as part of its get_state method:
gamma
temperature
nptiso_gamma0
nptiso_gammav
npt_p_ext
npt_p_inst
npt_p_inst_av
npt_piston
npt_p_diff
dpd_gamma
dpd_r_cut
dpd_tgamma
dpd_tr_cut
dpd_twf
dpd_wf
thermo_switch

This should go to the particleList class:
max_part (PArticleList.highest_particle_id())
n_part (Is already implemented as len(ParticleLIst))
n_part_types 
n_rigidbonds

The following should probably go to the CellSystem class, part of it into the get_state() method.

local_box_l
max_num_cells
min_num_cells
max_cut
max_range
max_skin
n_layers
node_grid
cell_grid
cell_size
n_nodes
max_cut_bonded
max_cut_nonbonded
skin
verlet_reuse

**Comment by tobiasrau** [comment]
I'm working on that.
