### ISSUE TITLE
Py: It should be testabel whether non-bonded interactions are active

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#744]
Espresso uses method specific ways such as: is lj_eps>=0.
There should be a NonBondedInteraction.is_acttive() method to check, whether an ia ias active.
Neede for picle support of NonBondedInteractions

**Comment by KaiSzuttor** [comment]
Ill have a look

**Comment by KaiSzuttor** [comment]
Thats in the code. :)
