### ISSUE TITLE
Cuda memory error on GTX 980

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#770]
There still seems to be a problem with the cuda code. Running this snipped yields an error:
``
setmd box_l 10.0 10.0 10.0
lbfluid gpu agrid 1.0 visc 1.0 dens 1.0 tau 0.01 friction 20.0
``

**Comment by rbardak** [comment]
what about time step and skin?

**Comment by fweik** [comment]
Are you sure that this is an Espresso issue?

**Comment by KaiSzuttor** [comment]
I just tried on another gtx 980 and it run well. So maybe my env or my card is broken.
