### ISSUE TITLE
Cannot build with autotools anymore (on OpenSuse leap 42.1 at icp)

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#776]
This was from a clean github master

# configure
[...]
****************************************************************
*                  Checking for programs                       *
****************************************************************
/home/weeber/es-tmp/configure: line 4745: syntax error near unexpected token `disable-static'
/home/weeber/es-tmp/configure: line 4745: `LT_INIT(disable-static)'

**Comment by KaiSzuttor** [comment]
this is because bootstrap.sh previously fails, we have to run libtoolize before running bootstrap.sh.

**Comment by fweik** [comment]
This seems to be an ICP issue. I can't reproduce this in a fresh opensuse container. This is odd.
@KaiSzuttor libtoolize should be run by autoreconf (call from bootstrap.sh), which should recognize
that libtool is used. This does not work on the ICP system.

**Comment by fweik** [comment]
Why was there an alocal in /usr/local/bin in the first place?!

**Comment by KaiSzuttor** [comment]
I dont know, maybe autotools package has been too old for us at some time? But the question is rather why does it corrupt the bootstrap.sh script?
