### ISSUE TITLE
Py: Electrostatics tutorial, elc stuff not yet in py tutorial

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#785]

**Comment by KonradBreitsprecher** [comment]
Going to add 2D electrostatics chapter

**Comment by fweik** [comment]
@KonradBreitsprecher  Is this done?

**Comment by KonradBreitsprecher** [comment]
Yes there is a section '2D Electrostatics and Constraints' in the 02 tutorial now.
