### ISSUE TITLE
Run travis build+checks in docker container

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#796]
I just accidentally (honestly!) merged a PR that moved the travis build and checks into a docker container,
with the obvious benefits. What do you think of this? If we decide not to do this am of course willing to roll it back. Observe how many python tests fail...
The container is a minimal ubuntu xenial with the packages required for espresso installed.

**Comment by fweik** [comment]
@tigoesnumb3rs @RudolfWeeber @rbardak

**Comment by RudolfWeeber** [comment]
If tcl and py tests work, I'm happy with it. CI checks on Python
will spare us a lot of trouble the next coding days.

I read trhough the travis.yml and the build scripts and it looks
nice. 

Can you put the dockerfile used to make the image in the maintainer
folder?

**Comment by fweik** [comment]
Looks good so far. I fixed the python-vtk thing, now only the coulomb_cloud_wall test fails, but this seems to be a legit error in the tests and not cause by the environment.
I'll put the Dockerfile into the repo.

**Comment by rbardak** [comment]
If I understand that correctly, we are building without cuda. Last time I tried I couldn't get espresso to build with cuda on xenial due to issues related to the compiler versions on xenial. So if building with cuda ever becomes an option, we might run into problems.

**Comment by fweik** [comment]
It's trivial to switch the distribution.

**Comment by mkuron** [comment]
If you put the Dockerfile into a separate Github repository, you can have the image automatically built on Docker Hub. You can also use that approach to build multiple images containing different operating systems (Debian, Ubuntu, OpenSuse, CentOS), multiple compilers (GCC, Clang) and multiple MPI implementations (MPICH, OpenMPI).

**Comment by fweik** [comment]
That was the plan :-)

**Comment by fweik** [comment]
So everything seems ok now.
