### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by jingjieyeo** [espressomd/espresso#800]
Hi everyone,

I encountered an error  when issuing `make`, I have attached the output logs after both `cmake` and `make`. Could you kindly advise how this can be resolved?

[make_output.txt](https://github.com/espressomd/espresso/files/439819/make_output.txt)
[cmake_output.txt](https://github.com/espressomd/espresso/files/439818/cmake_output.txt)

**Comment by RudolfWeeber** [comment]
See #801

**Comment by fweik** [comment]
Your issue has been fixed in the master branch. Thank you for reporting.
