### ISSUE TITLE
Current source implies higher boost version than required in cmake

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#801]
this is the cause for #800
Due to missing serialization support for boost::array
It doesn't work with the boost version installed in icp.
The "solution" is to make the MPiCallback class use vecotr rather than array for the 
requests:

diff --git a/src/core/MpiCallbacks.cpp b/src/core/MpiCallbacks.cpp
index abbd07a..057a57b 100644
--- a/src/core/MpiCallbacks.cpp
+++ b/src/core/MpiCallbacks.cpp
@@ -38,7 +38,7 @@ void MpiCallbacks::call(int id, int par1, int par2) const {
     throw std::out_of_range("Callback does not exists.");
   }
 
-  std::array<int, 3> request{id, par1, par2};
+  std::vector<int> request ={id, par1, par2};
 
   /** Send request to slaves */
   boost::mpi::broadcast(m_comm, request, 0);
@@ -81,7 +81,7 @@ void MpiCallbacks::abort_loop() const { call(LOOP_ABORT, 0, 0); }
 
 void MpiCallbacks::loop() const {
   for (;;) {
-    std::array<int, 3> request;
+    std::vector<int> request;
     /** Communicate callback id and parameters */
     boost::mpi::broadcast(m_comm, request, 0);
     /** id == 0 is loop_abort. */

It would be good, if we had a version that builds in icp for the coding day on Monday.

**Comment by fweik** [comment]
It would be great if jenkins was not broken and we would see such stuff...
