### ISSUE TITLE
cannot find -lpthreads

### ISSUE THREAD

**Issue by jingjieyeo** [espressomd/espresso#803]
Hi everyone,

Sorry for the trouble (again) but I encountered another problem (as attached), may I know how this can be resolved?

[CMakeError.txt](https://github.com/espressomd/espresso/files/440235/CMakeError.txt)

**Comment by fweik** [comment]
What system are you on?

**Comment by rbardak** [comment]
Chances are you only have a stub of libpthreads installed on your system and not the actual library

**Comment by jingjieyeo** [comment]
I'm using Linux Mint 17.3, I have:
libpthread-stubs0-dev
libpthread-workqueue-dev

How do I get pthreads to work?

**Comment by rbardak** [comment]
run
` for lib in $(locate libpthread | grep .so); do
  echo -e "\n$lib";
  nm $lib | grep pthread_create
done`
And post results.

You should find something like this:
`00000000000079d00000000000079d0 t __pthread_create_2_1
00000000000079d0 T pthread_create@@GLIBC_2.2.5`

If you do, then I guess something is wrong with cmake. If you don't then something is wrong with your libc. I will take a wild  guess and say try reinstalling the build-essentials for your system.

**Comment by jingjieyeo** [comment]
This is what I got:
```
/lib/i386-linux-gnu/libpthread-2.19.so
00007d90 t __pthread_create_2_0
000071b0 t __pthread_create_2_1
00007d90 T pthread_create@GLIBC_2.0
000071b0 T pthread_create@@GLIBC_2.1

/lib/i386-linux-gnu/libpthread.so.0
00007d90 t __pthread_create_2_0
000071b0 t __pthread_create_2_1
00007d90 T pthread_create@GLIBC_2.0
000071b0 T pthread_create@@GLIBC_2.1

/lib/x86_64-linux-gnu/libpthread-2.19.so
0000000000008430 t __pthread_create_2_1
0000000000008430 T pthread_create@@GLIBC_2.2.5

/lib/x86_64-linux-gnu/libpthread.so.0
0000000000008430 t __pthread_create_2_1
0000000000008430 T pthread_create@@GLIBC_2.2.5

/lib32/libpthread-2.19.so
00007d70 t __pthread_create_2_0
000071a0 t __pthread_create_2_1
00007d70 T pthread_create@GLIBC_2.0
000071a0 T pthread_create@@GLIBC_2.1

/lib32/libpthread.so.0
00007d70 t __pthread_create_2_0
000071a0 t __pthread_create_2_1
00007d70 T pthread_create@GLIBC_2.0
000071a0 T pthread_create@@GLIBC_2.1

/usr/lib/debug/lib/x86_64-linux-gnu/libpthread-2.19.so
0000000000008430 t __pthread_create_2_1
0000000000008430 T pthread_create@@GLIBC_2.2.5

/usr/lib/x86_64-linux-gnu/libpthread.so
nm: /usr/lib/x86_64-linux-gnu/libpthread.so: File format not recognized

```

**Comment by rbardak** [comment]
Okay, then as far as I understand, it should work... We should look into that. Maybe try and figure out if it is a known cmake issue on your system. I fleetingly remember that there was a related bug, however I don't know if that's relevant. You should also try building a different program which uses cmake as its build system and see if that works.

@fweik can you reproduce the problem on docker?

**Comment by jingjieyeo** [comment]
I've tried several versions of Gromacs before with cmake, those were fine. I'll try it again with the latest version and see how that goes. If you know of any other programs offhand which I can easily test cmake, please feel free to let me know as well.

**Comment by jingjieyeo** [comment]
I've recompiled GROMACS 5.1.2 with cmake, make, and make check. There doesn't seem to be any issues for that.

**Comment by jingjieyeo** [comment]
I reproduced the error on another workstation running Linux Mint (as attached). I'll try it on Ubuntu next to see what happens.


[CMakeError.txt](https://github.com/espressomd/espresso/files/443551/CMakeError.txt)

**Comment by hirschsn** [comment]
I'd say, the problem is quite obvious: The error says "/usr/bin/ld: cannot find -lpthreads". However, the library is called libpthread and not libpthreads.

**Comment by jingjieyeo** [comment]
What can I change to correct this issue?

**Comment by KaiSzuttor** [comment]
any update on that?

**Comment by fweik** [comment]
Iirc this was resolved on die mailinglist

**Comment by janlle** [comment]
I have the same problem `/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status`  I can't compile my hadoop3.2.x Please help me!

**Comment by jngrad** [comment]
This issue is quite old and our build system changed significantly since then. We only use `-lpthreads` for GPU-accelerated code now, where compilation is a different story compared to CPU code. You should look for an answer on the Apache Hadoop project and their [mailing list](https://hadoop.apache.org/mailing_lists.html).
