### ISSUE TITLE
Python interface for lbbdounaries

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#805]
Based on the cript_interface branch on fweik's github repo

-> script interface fuer LB bondaries
-> README.org lesen
-> script_interface/shapes/Wall.hpp und Wall.cpp lesen
-> script_interface/constraints/Constraint.hpp, Constraint.cpp und
Constraints.cpp lesen
-> Analoge Struktur fuer die LB boundaries bauen. Das benoetigt auch eine
Anpassung
   von code im core

**Comment by KaiSzuttor** [comment]
#479

**Comment by rempferg** [comment]
Current state: rempferg@8a33edf

Will stop for now.
