### ISSUE TITLE
Pickle support for Script_Interface based classes

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#806]
-> README.org lesen
-> script_interface/shapes/Wall.hpp und Wall.cpp lesen
-> script_interface/constraints/Constraint.hpp, Constraint.cpp und
Constraints.cpp lesen
Der interessante Punkt ist wie man beim Pickeln damit umgeht wenn sich
mehrere Python-
objecte ein C++ Objekt teilen. Das kann zubeispiel passieren wenn man ein
object als parameter
uebergibt und sich spaeter zurueck holt.

**Comment by tobiasrau** [comment]
I'm working in this.
