### ISSUE TITLE
CI testing with the correct boost version

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#808]
Right now, the version used in the CI testing docker container is newer than the one we require.

**Comment by fweik** [comment]
There are only packages for boost 1.58 in xenial. So we would either have to build it ourself or switch to different distro.

**Comment by mkuron** [comment]
We've also got a Debian 8 container now, which has Boost 1.55. Which version do we require?

**Comment by fweik** [comment]
At the ICP 1.54 is installed, but I think 1.55 is sufficient. Will close if you don't oppose.
