### ISSUE TITLE
analyze wallstuff is not documented

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#825]
The function `analyze wallstuff` is not documented in the user guide.  This issue was raised by a request on the `espressomd-devel@nongnu.org` mailing list.

https://lists.nongnu.org/archive/html/espressomd-devel/2016-08/msg00001.html

**Comment by RudolfWeeber** [comment]
As this is undocumented and has no test case, it will probably be removed,
unless someone commits to working on this code by 1st of June.

**Comment by RudolfWeeber** [comment]
Has been removed
