### ISSUE TITLE
Some python tests fail with python 3

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#826]
https://travis-ci.org/espressomd/espresso/jobs/156591475

**Comment by mkuron** [comment]
Will fix tomorrow. I thought I had all instances of that error fixed in 5b0909bcbcbd8cf5c4f7ca8ea0b30238c167287e and those tests definitely passed on my computer. I probably missed something.

**Comment by mkuron** [comment]
Ah, you overwrote some of my changes in this merge instead of resolving the merge conflicts: 6daf4e85da43c3891ec25f2e711799b975d23ae0
