### ISSUE TITLE
Intermittent test failure of mass-and-rinertia_per_particle.tcl

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#831]
`background_errors { ERROR: force on particle 174 was NAN.} { ERROR: force on particle 174 was NAN.} { ERROR: force on particle 174 was NAN.} 
    while executing
"integrate 100"
    (procedure "test_mass-and-rinertia_per_particle" line 132)
    invoked from within
"test_mass-and-rinertia_per_particle $i"
    ("for" body line 2)
    invoked from within
"for {set i 0} {$i < 4} {incr i} {
    test_mass-and-rinertia_per_particle $i
}"
    (file "mass-and-rinertia_per_particle.tcl" line 210)`

This test has failed in eddac1cfb21f3aca7ca6259afbf84519eec6829c for the first time and again in #817. Not sure what's causing it, but in both cases it only occured in one of the Travis jobs (once with the Debian image and once with Python3).

**Comment by KonradBreitsprecher** [comment]
Done some testing, and it fails quite often. I think it spans a too large parameter range and has a fixed timestep for variing masses and intertias:

-Random masses are [0:20[, which cause _Force was NaN_ for small values.
-Rotational inertia components are also [0:20[, the testcase fails in cases like 20 0.1 20

A testing range of [0.5:2[ is much more stable and reduces the failures to an acceptable amount
(1 occurred out of >200 tests). Do we lose possible error coverage with this approach?

Alternatively, we could calculate the appropriate timestep and number of samples for a given set of parameters to reduce the failure rate below a certain threshold.

Same applies for _mass-and-rinertia.tcl_

**Comment by mkuron** [comment]
@RudolfWeeber committed a few changes to that test case a couple weeks back to make it more robust, though it seems it has been failing more often since then. Perhaps he can chime in on this discussion.

**Comment by fweik** [comment]
I think the more important question is why it is not deterministic. Looks
like undefined behavior to me...

**Comment by KonradBreitsprecher** [comment]
The mass-and-rinertia_per_particle.tcl uses the `[pid] + Node_index` for setting the seed (mass-and-rinertia.tcl not). So I could reproduce failing tests..

**Comment by fweik** [comment]
It shouldn't, I must have missed that one.

**Comment by KonradBreitsprecher** [comment]
Not sure if #835 helps. I think there should be a random seed in the tests to cover not only a single set of gammas/masses/rinertias. Also it's quite clear that the test fails sometimes. Just think of a mass of 0.001, timestep 0.008 and 100 'noise kicks' in the same direction and you end up with forces around 10e8.
I would opt for [pid] seeds and reduced parameter range with a non-zero lower boundary for mass and rinertia.

**Comment by fweik** [comment]
I think deterministic tests are better. If corner cases can be identified they should be tested explicitly. As you can see from the current discussion which is completely about the test case non-deterministic tests are not helpful.

**Comment by KonradBreitsprecher** [comment]
But then there's no point in using t_random at all, this would just hide the actually tested parameters in an annoying way. So how about using a fixed set like [-1,0,1,100]?

**Comment by fweik** [comment]
I think the best way to identify cases where something is actually different, and explicitly test those What is the difference between 1 and 100? What kind of bug would you catch with 100 and not with 1?

**Comment by KonradBreitsprecher** [comment]
There are some, i.e. if you accidentally remove the mass from a=F/m in the integrator, mass=100 would fail but mass=1 would produce the correct temperature..I think

**Comment by psci2195** [comment]
I agree with @KonradBreitsprecher 's comment:

> Alternatively, we could calculate the appropriate timestep and number of samples for a given set of parameters to reduce the failure rate below a certain threshold.

Actually, even from a physical dimension side, a Langevin equation characteristic time is ```mass / gamma``` or ```rinertia / gamma_rot```. Hence, the timestep should be at least less than this value. Hence, when random ```mass``` or ```rinertia``` are very small then we need a very small timestep leading to a time-consuming auto-testing. Hence, if our tests are non-deterministic then, probably, we have no other choice than to introduce mass/rinertia lower limit as Konrad suggested above..

**Comment by psci2195** [comment]
just in case, I've opened such pull request: https://github.com/espressomd/espresso/pull/839.
Here,
```timestep << tau_langevin = mass/gamma```
<=>
```min(mass) > max(gamma) * timestep = 20 * 0.008=0.16```.
<=>
```0.20>0.16``` (with a buffer).

**Comment by fweik** [comment]
I merged #839, which seems to have a stable parameter set for the offending test. For the record: I still think that random tests only add FUD to the test suit.
