### ISSUE TITLE
Incomplete implementation of system.analysis.energy()

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#837]
Parameters `etype` and specific particle ids are not used in the method, 
so far it always calculates all energy contributions, which can be a massive overhead.

**Comment by RudolfWeeber** [comment]
On Thu, Sep 15, 2016 at 02:44:53AM -0700, KonradBreitsprecher wrote:
> Parameters `etype` and specific particle ids are not used in the method, 
> so far it always calculates all energy contributions, which can be a massive overhead.
This is also true for the tcl version, afaik. Changing this would require
reworking the core component.  It's probably a day of work.

The same is true for the pressure and stress tensor btw.

The resulting performance increase would probably be only relevant
for Monte Carlo simulations, were energy calculations are frequent.

If there is no urgend reason to do it fast (for instance a profiling of a simulatyion where energy caluclaiton takes mor than a few percent), I'd suggest we take this up again after th python transition is complete.

**Comment by jonaslandsgesell** [comment]
Yes this requires rewriting the energy routines in the core

**Comment by fweik** [comment]
I think the energy calculation should be treated like any other observable, and there should be a general mechanism in the core to limit the scope of observable to a subset of the particles. I think this is relatively easy to achieve...

**Comment by jngrad** [comment]
The `etype` parameter was removed in 4.0. The energy/pressure/stress tensor globals will be converted to observables in 4.2 (there is a dedicated ticket). Closing.
