### ISSUE TITLE
Constraints.hpp vs constraints.hpp bad idea for case insensitive filesystems MacOS e.g.

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#849]
branch: script_interface
file: src/core/constraints/contraints.hpp

File should be removed.

**Comment by mkuron** [comment]
#643 
As a side remark, that file is not even valid C++ as it contains a stray `'`.

**Comment by fweik** [comment]
Yeah I think that file is not supposed to be there ^^

**Comment by RudolfWeeber** [comment]
resolved?
