### ISSUE TITLE
ScriptInterface: call_method should be able to return a VariantMap

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#856]
Some core methods need to return more complex data structures than those supported by the variant used in the script interface.
E.g. prining resutls of correlators

This could be achieved
either by adding VariantMap to the supported parameter types (no idea, if this kind of cyiclical definition is possible)
or by adding a separate
variant_map_call_method()
to ScriptInterfaceBase.

**Comment by fweik** [comment]
The plan is to make Variant recursive (which boost::variant). Together with the base types the can represent arbitrary complex data.

**Comment by RudolfWeeber** [comment]
Resolved by implementation of recursive variants.
