### ISSUE TITLE
ScriptInterface: __get_item__ for system.constraints

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#857]
I want to implement the visualization for constraints, therefore I need access to all of them via espressomd.system(). @fweik , could you please make this happen?
Btw, love that set_params() for shapes works for already added constraints, enables easy realtime movement of shapes in espresso!

**Comment by fweik** [comment]
To move the constraint it should even be enough to change the parameters of the shape.

**Comment by fweik** [comment]
#885 implements access to the elements, if this is desired you can now implement __iter__ from cython...

**Comment by RudolfWeeber** [comment]
Can this be closed?

**Comment by fweik** [comment]
@KonradBreitsprecher do you remember if the python part of this is merged? I know that you have this in one of your branches...

**Comment by KonradBreitsprecher** [comment]
I can't remember that we had iter functionality for the container, only the 'get_elements' call method in the registry.
