### ISSUE TITLE
ScriptInterface: call_method methods not called on all nodes?

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#864]
Currently it seems that the methods defined in call_method are not called in parallel?

**Comment by rbardak** [comment]
could you be more specific? the ticket title says the calls are not made on
some nodes (meaning they are skipped), while your description implies they
are not made synchronously. In the latter case it could be that one node
was still busy with a previous call.

I suspect it isn't required that the calls are made synchronously, as long
as the order is the same on all nodes.

**Comment by KaiSzuttor** [comment]
What I mean is that if I place a debug print (see my branch h5mdcore) in the method that should be called by a mpi_callback, I see that those functions are only called on this_node=0 and the program hangs.

**Comment by fweik** [comment]
This is fixed in the script_interface branch
