### ISSUE TITLE
Shape::Rhomboid::calculate_distance broken

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#868]
It still compiles and runs, but produces incorrect distances and distance vectors. It most likely got broken when it was converted into a Shape.

**Comment by fweik** [comment]
I have written some basic general unit tests for the shape functions that I have not merged yet. My best idea was to get the normal and distance on a bunch of points, and then check if point - (dist*normal) is actually on the surface. I think this is similar to what you did manually to check the distance functions. Of course this is only a necessary and not a sufficient condition on the distance function, but I could not come up with something better yet. If you can think of sth, shoot..

**Comment by RudolfWeeber** [comment]
What do we do about this. There are some 500 lines of untested (and according to Georg's report) wrong code.
If there's no application in sight, we might remove the Rhomboid shape.

**Comment by fweik** [comment]
First of all check how much of it can be accomplished by library code? I think boost.geometry should be helpful here, but I have not checked.
