### ISSUE TITLE
Rigid body dynamics & virtual sites relative

### ISSUE THREAD

**Issue by Marcello-Sega** [espressomd/espresso#870]
In a simple test system, two oppositely charged molecules (cut-off electrostatics) repel each other (see script below). The molecules are built in the following way:
 
       R = V(+1)         R = V(-1)

Where V(x) is a virtual site with charge x, and R is a real, uncharged particle. Cut-off electrostatics is realized with debye-huckel and k=0. The inertia tensor should not matter, as there's no rotation involved. 

A control system of two real charged particles shows instead the expected behavior. 

    set tcl_precision 5
    set l 10
    setmd box_l $l $l $l
    setmd skin 0
    set cut 2.0
    setmd min_global_cut $cut
    setmd time_step 0.001
    
    set lb  [expr 0.555] ; #just to single out easily the force at distance 1.0
    inter coulomb [expr $lb ]   dh  0 $cut
    
    # total charge of this molecule: +1
    part 0  pos  0.0 0 0 q 1.0 
    part 1  pos  0.1 0 0 virtual 1 vs_auto_relate 0 q  1.0
    
    # total charge of this molecule: -1
    part 2  pos  1.0 0 0 q 1.0 
    part 3  pos  1.1 0 0 virtual 1 vs_auto_relate 2 q -1.0
    
    # 1) The distance between the two charges is 1.0, the force should be +/- 0.00555 at t=0
    # 2) The "molecules" are linear and aligned along their axis: no rotation => inertia tensor should not matter
    # 3) The charges are opposite, the "molecules" should attract each other  
    
    # let's add two other charged particles out of the cutoff of the previous ones, just to check.
    part 4 pos 5.0 0 0 q  1.0
    part 5 pos 6.0 0 0 q -1.0
    
    # Molecular pairs {0,1} + {2,3} and  {4}+{5} should behave identically (within numerical errors) 
    # Let's see...
    
    integrate 0
    puts "==="
    for {set t 0 } { $t < 2} {incr t } { 
    set totf 0
    for {set i 0 } { $i < [setmd n_part]} {incr i } {
 
      set p   [part $i print pos];   set v   [part $i print v] ;  set f   [part $i print f]
    
      set px  [format  {%0.4f} [lindex $p 0]] 
      set vx  [format  {%0.4f} [lindex $v 0]] 
      set fx  [format  {%0.4f} [lindex $f 0]] 
    
      puts "time [setmd time]  part $i pos: $px   vel:  $vx   force: $fx"
    }
    integrate 100
    puts "==="
    }
    
    puts "final charge distance virtual (should be smaller than 1.0) : [expr [lindex [part 3 print pos] 0]  - [lindex [part 1 print pos] 0 ]]"
    puts "final charge distance real   (should be smaller than 1.0): [expr [lindex [part 5 print pos] 0]  - [lindex [part 4 print pos] 0 ]]"
    
    # on 672c5d83a9b0bc97e1f98c06c4700112ff896372 I see the following problems:
    # 1) the force on the real particles seems not to be correct (neither in absolute  value, nor in sign)
    # 2) The problem is not just in the way forces are printed out, because at the end of the integration two oppositely charged molecules have repelled each other...
    # 3) two charged particles used as a control system give the expected results
    

The minimal configuration that generates this problem is

    #define LENNARD_JONES
    #define VIRTUAL_SITES_RELATIVE
    #define ELECTROSTATICS

**Comment by Marcello-Sega** [comment]
This is tested on 672c5d83a9b0bc97e1f98c06c4700112ff896372

**Comment by RudolfWeeber** [comment]
>     # total charge of this molecule: +1
>     part 0  pos  0.0 0 0 q 1.0 
>     part 1  pos  0.1 0 0 virtual 1 vs_auto_relate 0 q  1.0
I'm confused. Isn't it +2?

>     # total charge of this molecule: -1
>     part 2  pos  1.0 0 0 q 1.0 
>     part 3  pos  1.1 0 0 virtual 1 vs_auto_relate 2 q -1.0
I count total charge zero here. Also, the two charges on the two molecules do not co-incide, so they do not fully compensate.
So the positive charge on part 2 is closer to the two positive charges on part 0 and 1 than the negative charge on part 3. Shouldn't there be net repulsion?
Or did I misunderstand sth?

**Comment by Marcello-Sega** [comment]
yep, that's right, false alarm, sorry.
