### ISSUE TITLE
Not clear, what exactly polymer observables are doing

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#877]
@richter-t, could you please add equations in doc/ug/analysis-core.tex for the following observables:
spatial_polymer_property (is this the degree of ionization?)
persistence_length (there is more than one physical model. Please provide eqn)
polymer_pair_correlation (please provide eqn)

Thx

**Comment by richter-t** [comment]
If someone would review the changes in the documentation, this issues could probably be closed

**Comment by kosovan** [comment]
A few comments to these observables and to the docs:

1. spatial_polymer_property - this is a very generic name for an observable. Please give it a more direct name (degree of ionization or degree of charging?). In the updated docs you say that it calculates charges on "weak polyelectrolytes" but I doubt that the observable recognizes whether these particles belong to any polymer or take part in ionization reaction. Are the `ids` supposed to be consecutive particle ids along the polymer? If the observable is indeed degree of ionization, then it is unclear why Npoly is needed and how it is used by the observable. How does the function figure out the "monomer ranking number"? Is this the index in the `ids` list?

2. persistence_lentgh - the last sentence of the docs says: The observable will not calculate the actual persistence length but the correlation function of the bond angles. Then it should be called` bond_angle_correlation_function`, not `persistence_length`

3. polymer_pair_correlation - the textbook definition of pair correlation function g_ij is the distribution of particles of type j around particles of type i. It is unclear from the docs what is i and what is j. Please specify.

**Comment by richter-t** [comment]
After having a look into this again, my conclusion would be that it's not worth the time to port those observables into the new pythonesque/C++ style, since this stuff can be easily calculated with python alone. So I opt for dropping those obs from the code base. As far as I can see, those obs are already removed from the core (not_yet_implemented), thus I'll probably just delete the documentation for those.
