### ISSUE TITLE
Travis/GitLab CI Wishlist

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#883]
Stuff that could/should be checked in CI
- [ ] Clang sanitizer build (e.g. http://clang.llvm.org/docs/AddressSanitizer.html)
- [ ] Static analysis

**Comment by psci2195** [comment]
is adding of CUDA builds an option here :-) ?

**Comment by mkuron** [comment]
Travis is already building CUDA (though not testing, obviously), I added that quite recently. Jenkins has been building and testing CUDA for years.

**Comment by psci2195** [comment]
@mkuron , do you mean Jenkins on some specific machine or in some cloud?

**Comment by mkuron** [comment]
Jenkins runs on our internal machines, but the status hasn't been publicly accessible for the past few months. I believe @fweik would get notified if CUDA was failing on the master.

**Comment by fweik** [comment]
http://espressomd.org/jenkins/

**Comment by psci2195** [comment]
Wow, thanks!

**Comment by mkuron** [comment]
Static analysis is in #1683. Address sanitizer requires rebuilding Python.

**Comment by KaiSzuttor** [comment]
can we close this? @mkuron

**Comment by mkuron** [comment]
We don't have sanitizer builds yet. Easy to add though once we have our new build nodes running.

**Comment by mkuron** [comment]
@KaiSzuttor, We don't have sanitizer builds yet. Easy to add though once we have our new build nodes running.
