### ISSUE TITLE
Script interface: VariantMap in call_method

### ISSUE THREAD

**Issue by rbardak** [espressomd/espresso#889]
- c++:
  - The method `T& operator[]` of `std::map` is not a const method. Using `parameters["foo"]` in `call_method` will not compile, because the input argument 'parameters' of `call_method` is a `const VariantMap&`.
- python:
  - When setting `parameters[name] = kwargs[name]` in `call_method` of the class `PScriptInterface`, we need to wrap `kwargs[name]` with `self.make_variant` with the appropriate type, otherwise this will result in a bad `boost::get` at runtime. (same way it is done in `set_params`). As far as I understand it, the supported `**kwargs` for call_method should be arbitrary (?) so we can't rely on the list of valid params to derive the type.

**Comment by fweik** [comment]
You should use .at

**Comment by rbardak** [comment]
In the case of the all `call_method`s of the constraints, an instance derived from `PScriptInterface` is passed, which takes a different path in the if statement inside `call_method`. In this case, only the the object id is mapped.
Same goes for `observables`, their `call_method`s don't pass through the second branch either.

When I tried to pass a list (with the intention of having a Vector3d or at least sth similar), it was evaluated as bool. Passing c-objects directly through `call_method` is also not possible, since `**kwargs` are actual python dicts with python types.

One solution would be to pass an actual `VariantMap` to `call_method` instead of constructing it inside from the `**kwargs`. However this would limit the use of `call_method` to `cdef` classes and therefore limit the flexibility of the interface classes. Another idea was to pass an additional list containing information about the types, however this is an ugly solution. Using a complicated routine inside `call_method` to determine an appropriate type at each call would be horribly time consuming, especially if you want to do sth 10^5 times (loop over lattice cells for example).
Or provide an additional list on the c-level for valid call parameters and assign types the same way as in `set_params`.

**Comment by fweik** [comment]
I don't see a fundamental problem with inspecting the python type and then construct something accordingly.

**Comment by fweik** [comment]
Ok I'm working on new an cleaner functions for the variant conversion. That was messy anyway.

**Comment by fweik** [comment]
Please have a look at https://github.com/fweik/espresso/tree/python_to_variant
I think we should probably convert lists of e.g. only floats to a vector<double>, and
not to a vector<Variant>. The Variant version would allow for more generic code,
but this basically forces another copy of the values.

**Comment by rbardak** [comment]
I don't see the point in passing Vector3d anyway, you're only passing data in most cases and you can control the size of the list on the python side to assign to Vector3d via polymorphism. No need to check for that.

One issue with the `hasattr` part, in python3 it doesn't work as you expected. I dropped a comment there. We need to explicitly check for strings in that statement.

The recursivity might cause headaches if someone tries to pass a list of lists (i.e. `vector<vector<Variant>>`), but I don't think that'll ever happen. How come `vector<Variant>` is a valid Variant anyway?
