### ISSUE TITLE
Shared libraries not linked correctly with gcc/g++ (ubuntu)

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#894]
I attach the output of ldd build/src/core/libEspressoCore.so for gcc 4.8.5 and gcc 4.9.3
(build of my h5mdcore branch)
[output_gcc4.8.5.txt](https://github.com/espressomd/espresso/files/557693/output_gcc4.8.5.txt)
[output_gcc4.9.3.txt](https://github.com/espressomd/espresso/files/557696/output_gcc4.9.3.txt)

**Comment by KaiSzuttor** [comment]
I tested with docker ubuntu images and got correct linking with clang. See my dockerhub:
https://hub.docker.com/r/kaiszuttor/ubuntu/tags/

**Comment by fweik** [comment]
This seems to be a problem with your h5mdcore branch? Could not reproduce with the upstream branches...
