### ISSUE TITLE
OIF affinity does not work

### ISSUE THREAD

**Issue by icimrak** [espressomd/espresso#903]
Original location of add_affinity_pair_force was calc_non_bonded_pair_force_parts. A year ago or so this function has been moved to add_non_bonded_pair_force.

With this new scenario, the function add_affinity_pair_force is not
called at all, even if it should be.

**Comment by fweik** [comment]
I could not reproduce: With the following script

```tcl
setmd box_l 10. 10. 10.
setmd time_step 0.1
setmd skin 0.4

inter 0 0 affinity 1 1.0 1.0 1.0 1.0 2.0 2.1
part 0 pos 0. 0. 0. type 0
part 1 pos 1. 0. 0. type 0
integrate 0
```
add_affinity_pair_force is called with the current master. Please be aware of the fact that AFFINITY
is no longer active by default, and has to be activated via the myconfig.hpp

Can you please provide a minimal script that shows the undesired behaviour?

**Comment by icimrak** [comment]
Your script work well. I am aware of the necessity using AFFINITY in the  myconfig.hpp. 

When I want to use non-bonded affinity for the particle - wall interaction (which is the main use case), the function add_affinity_pair_force is however not called, see script below:

setmd box_l 10. 10. 10.
setmd time_step 0.1
setmd skin 0.4


constraint rhomboid corner 0 0 0 a 10 0 0 b 0 10 0 c 0 0 1 direction 1 type 3


part 0 pos 1. 1. 1.1 type 0

inter 0 3 affinity 1 1.0 1.0 1.0 1.0 2.0 2.1


for {set i 0} {$i < 100} {incr i} {
    integrate 1
    puts "[part 0 print pos]"
    puts "[part 0 print pos]"
}

**Comment by KaiSzuttor** [comment]
does this issue still exist, is there a python interface minimal example?

**Comment by icimrak** [comment]
The affinity for OIF has currently no interface for python. In coming months I plan to make one and go through the C-code to make it work properly. So for now, this issue may be closed.
