### ISSUE TITLE
buildenv-espresso-ubuntu-cuda docker image has no python tag

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#927]
@fweik

**Comment by fweik** [comment]
That's already fixed, but there seems to be another issue:
https://hub.docker.com/r/espressomd/buildenv-espresso-ubuntu-cuda/builds/baqwamcmww3cskmr6nz3lqr/

**Comment by mkuron** [comment]
Wrong libhdf5 package name?

**Comment by KaiSzuttor** [comment]
@mkuron see #921
