### ISSUE TITLE
LB particle coupling partially broken

### ISSUE THREAD

**Issue by rbardak** [espressomd/espresso#931]
If the feature `EXTERNAL_FORCES` is not activated, the (probably only cpu) LB does not transfer the particle momentum to the fluid. However, the correct forces are still exerted to the particle. Here is the offending script (txt file, because git doesn't support .py or .cpp file embedding for some reason):
[wtf.txt](https://github.com/espressomd/espresso/files/594842/wtf.txt)

This issue is independent from the interface and is present in all branches. As far as I can tell from git blame, the issue was present for 6 years. A quick fix would be to imply `EXTERNAL_FORCES` when activating `LB` in features.def.

**Comment by RudolfWeeber** [comment]
@rempferg is this still the case?
