### ISSUE TITLE
script interface python-level try/except casting to correct type

### ISSUE THREAD

**Issue by rbardak** [espressomd/espresso#935]
When the input at python level is an int, but the script interface expects a double, it throws. It performed the right (implicit?) casting before the recursive variant PR, therefore not throwing before. Throwing here is not only annoying (maybe even useless because it's implicitly done right?) but it probably broke half of our sample and tutorial scripts, which often pass ints to PscriptInterface classes when doubles are expected.

My suggestion would be a safe, explicit cast to the required type of the form

```python
try: val = int(val)
except ValueError:
    print("something informative")
    #exit/cleanup
# continue to pass val to its destination
```

This could be in the form of a function or somewhere internally. The interface is already aware of the required type so one could pass which type to cast as a callback.

Maybe there is a better solution at the cython level, but I wouldn't know.

**Comment by fweik** [comment]
It was my understanding that this is the desired behaviour. I agree that int -> double cast is probably safe. This can easily done in the interface if we want this.

**Comment by fweik** [comment]
See #936, iff we want this please approve the PR
