### ISSUE TITLE
Python support for rotate_system

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#947]

**Comment by fweik** [comment]
Also the current implementation works only on a single core.

**Comment by RudolfWeeber** [comment]
mpi reduction for center of mass is missing

**Comment by fweik** [comment]
This should probably be renamed to rotate particles, because this is what it does, other stuff is not affected.

**Comment by RudolfWeeber** [comment]
On Tue, Dec 12, 2017 at 03:25:56PM +0000, Florian Weik wrote:
> This should probably be renamed to rotate particles, because this is what it does, other stuff is not affected.
Rotating the particles (when they have rotational degrees of freedom) can be understood different as well...

**Comment by fweik** [comment]
Potentially the internal degrees of freedom should be rotated too.
