### ISSUE TITLE
Decide fate of non-bonded interactions without python support

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#951]
Please comment, if you are using one of the following non-bonded interactions
Smooth step
BMHTF
Morse
Buckingham
Soft Sphere
Membrane collision
Hat
Hertzian
Gaussian
Directional LJ
Gay Berne
Affinity

**Comment by rempferg** [comment]
Hat and Soft-Sphere are necessary for DPD. Flo Weik already took care of Hat.

**Comment by pkreissl** [comment]
I'll take care of the Soft-Sphere interface.

**Comment by pkreissl** [comment]
Also added smooth-step, Morse, Buckingham, Hertzian and Gaussian interaction.

**Comment by hmenke** [comment]
I'm not using it but Gay Berne has a Python interface.

https://github.com/espressomd/espresso/blob/0671bf5ad922c3136469851d3bb2119084054fe4/src/python/espressomd/interactions.pyx#L271-L346

**Comment by pkreissl** [comment]
So, with PR #1547 we will have the following non-bonded interactions interfaced:
 - Smooth step
 - Morse
 - Buckingham
 - Soft Sphere
 - Hertzian
 - Gaussian
 - Gay Berne (already there)
 - Hat (apparently already done by Flo Weik)
 - BMHTF

Still missing are:
 - Affinity (related to Shan-Chen)
 - ~BMHTF~
 - Directional LJ
 - ~Membrane collision (related to OIF)~ part of PR #1504

Should these also be interfaced?
