### ISSUE TITLE
Implement tests for constraints

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#966]
There is probably a more generic way to do this.

The tcl test coverage is limited to the main shapes
The following tcl test case exist
Stage 1

* constraints_reflecting.tcl
* constraints_rhomboid.tcl
* constraints.tcl (sphere,wall,cylinder)

**Comment by RudolfWeeber** [comment]
There are now tests for the basic interface, walls and homogeneous fiels.
Wich other ones do we want to hve coverage for in the near future?

What was the outcome of the issue with jumping force vectors in corners? @rempferg

**Comment by jonaslandsgesell** [comment]
There are now even more tests. Can this be closed?

**Comment by RudolfWeeber** [comment]
(lack of) coverage reported on the src/core/shapes/ folder says, this ticket should stay open.
