### ISSUE TITLE
Implement functional tests for electrokinetics in Python

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#967]
Based on the following tcl test cases

    Merge (shared code)
        ek_electrostatics_coupling_x.tcl
        ek_electrostatics_coupling_y.tcl
        ek_electrostatics_coupling_z.tcl
    Merge
        ek_eof_one_species_x_nonlinear.tcl
        ek_eof_one_species_x.tcl
        ek_eof_one_species_y_nonlinear.tcl
        ek_eof_one_species_y.tcl
        ek_eof_one_species_z_nonlinear.tcl
        ek_eof_one_species_z.tcl
    ek_reaction.tcl

**Comment by RudolfWeeber** [comment]
Do the existing tests provide sufficient coverage?

**Comment by rempferg** [comment]
I think so. They test everything I deem production ready. They don't test the particle coupling, yet, but the physics of that is still under development.
