### ISSUE TITLE
Vector3d parameter for shapes doesn't work

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#969]
```
from espressomd import *
from espressomd.shapes import *

system = espressomd.System()

shape_r = Rhomboid(
            pos = [25.0,25.0,25.0], 
            a = [10.0,0.0,0.0],
            b = [2.0,5.0,0.0],
            c = [-10.0,5.0,0.0],
            direction = 1)
```
throws

File "espressomd/script_interface.pyx", line 52, in espressomd.script_interface.PScriptInterface.set_params 
ValueError: Unknown parameter pos

**Comment by rbardak** [comment]
might be related to the introduction of recursive variant and the removal of vector3d support.

**Comment by fweik** [comment]
I think this is fixed. Please check.

**Comment by KonradBreitsprecher** [comment]
Nope. Same error..

**Comment by KonradBreitsprecher** [comment]
Ah wait, it's "corner" now.. Works!
