### ISSUE TITLE
Osascript invication by visualizationOpenGL.py

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#972]
This apple specific command is always called which throws an error. @KonradBreitsprecher

**Comment by mkuron** [comment]
Just submit a pull request removing that line. It's a terrible hack and I'm not sure how that slipped past me when I reviewed the code.

**Comment by KaiSzuttor** [comment]
Well, "terrible hack" is a bit harsh, but yes it should not be in there.

**Comment by KonradBreitsprecher** [comment]
Yes it's evil I agree, ment to bring the openGL window to the front during debugging on the mac.
Will be removed with the next commit...
