### ISSUE TITLE
OpenGL visualization: drag force

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#974]
In my experience and after talking with some guys at the summer school it does not seem to be intuitive that the user can apply a force on the particles just by clicking and moving in the visualization. I think this feature should be default not be switched on, just not to be too counter-intuitive.

**Comment by KaiSzuttor** [comment]
@KonradBreitsprecher is this resolved?

**Comment by KonradBreitsprecher** [comment]
Resolved

**Comment by KaiSzuttor** [comment]
#970
