### ISSUE TITLE
Circular dependency in _system.pyx, analysis.pyx and actors

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#999]
The _system module imports analysis since an instance of Analysis is a member of System,
on the other side the Analysis depends on System since it uses the System as an argument.
We should decide how we want to init those objects.

**Comment by RudolfWeeber** [comment]
> The _system module imports analysis since an instance of Analysis is a member of System,
> on the other side the Analysis depends on System since it uses the System as an argument.
> We should decide how we want to init those objects.
Is this a problem? The import happens at runtime only.
So, to my knowledge, it is legal in Py.

**Comment by rbardak** [comment]
It's legal, but it is considered bad practice. The garbage collector cannot handle circular referencing objects and leaks in these cases. However it doesn't matter for us because _there can only be one_.

We can always use weak references though, I think they are a built-in feature.

**Comment by KaiSzuttor** [comment]
Actually I stumbled over this while writing documentation with sphinx. But that's another topic...I'll close this issue for now.
